# -*- coding: utf-8 -*-
"""
Linux基础操作 - 学习路径
知识点: 文件系统、文件权限、文本处理、进程管理、网络命令、Shell脚本、环境变量、管道重定向、用户管理、软件包管理
题目数量: 90题 (选择题40 + 编程题20 + 简答题30)
难度分布: easy 30% + medium 50% + hard 20%
"""

EXERCISES = {
    "Linux基础命令": [
        # ==================== 选择题 (40题) ====================
        # --- 文件系统 (8题) ---
        {
            "title": "以下哪个命令用于显示当前工作目录的完整路径？",
            "description": "以下哪个命令用于显示当前工作目录的完整路径？\nA. ls\nB. cd\nC. pwd\nD. dir",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文件系统",
            "knowledge_point": "pwd命令",
            "solution": "C",
        },
        {
            "title": "使用 ls -l 命令查看文件时，第一列 '-rwxr-xr--' 表示什么？",
            "description": "使用 ls -l 命令查看文件时，第一列 '-rwxr-xr--' 表示什么？\nA. 文件大小\nB. 文件权限\nC. 文件所有者\nD. 文件修改时间",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文件系统",
            "knowledge_point": "ls命令",
            "solution": "B",
        },
        {
            "title": "以下哪个命令可以递归地创建多级目录？",
            "description": "以下哪个命令可以递归地创建多级目录？\nA. mkdir /a/b/c\nB. mkdir -p /a/b/c\nC. mkdir -r /a/b/c\nD. mkdir --recursive /a/b/c",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文件系统",
            "knowledge_point": "mkdir命令",
            "solution": "B",
        },
        {
            "title": "命令 'cp -r source_dir dest_dir' 中 -r 参数的作用是：",
            "description": "命令 'cp -r source_dir dest_dir' 中 -r 参数的作用是：\nA. 覆盖已存在的文件\nB. 递归复制目录及其内容\nC. 创建硬链接\nD. 显示复制进度",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文件系统",
            "knowledge_point": "cp命令",
            "solution": "B",
        },
        {
            "title": "要删除一个非空目录及其所有内容，应该使用哪个命令？",
            "description": "要删除一个非空目录及其所有内容，应该使用哪个命令？\nA. rmdir dirname\nB. rm dirname\nC. rm -r dirname\nD. rm -f dirname",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文件系统",
            "knowledge_point": "rm命令",
            "solution": "C",
        },
        {
            "title": "以下关于 'mv' 命令的说法，错误的是：",
            "description": "以下关于 'mv' 命令的说法，错误的是：\nA. 可以用于重命名文件\nB. 可以用于移动文件到另一个目录\nC. 移动文件时会自动保留源文件的副本\nD. 可以同时移动多个文件",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文件系统",
            "knowledge_point": "mv命令",
            "solution": "C",
        },
        {
            "title": "执行 'ls -a' 命令会显示以 '.' 开头的隐藏文件，'.' 和 '..' 分别代表什么？",
            "description": "执行 'ls -a' 命令会显示以 '.' 开头的隐藏文件，'.' 和 '..' 分别代表什么？\nA. 当前目录和根目录\nB. 当前目录和上级目录\nC. 上级目录和当前目录\nD. 主目录和当前目录",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文件系统",
            "knowledge_point": "特殊目录",
            "solution": "B",
        },
        {
            "title": "在Linux中，以下哪个命令组合可以用来查找文件系统中最近7天内修改过的所有 .log 文件？",
            "description": "在Linux中，以下哪个命令组合可以用来查找文件系统中最近7天内修改过的所有 .log 文件？\nA. find / -name '*.log' -mtime -7\nB. find / -name '*.log' -ctime 7\nC. locate '*.log' -mtime -7\nD. ls -l '*.log' --recent=7",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文件系统",
            "knowledge_point": "find命令",
            "solution": "A",
        },
        # --- 文件权限 (4题) ---
        {
            "title": "数字权限 755 对应的符号权限是什么？",
            "description": "数字权限 755 对应的符号权限是什么？\nA. rwxr-xr-x\nB. rwxrwxrwx\nC. rw-r--r--\nD. rwx------",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文件权限",
            "knowledge_point": "chmod数字权限",
            "solution": "A",
        },
        {
            "title": "命令 'chmod u+x script.sh' 的作用是：",
            "description": "命令 'chmod u+x script.sh' 的作用是：\nA. 给所有用户添加执行权限\nB. 给文件所有者添加执行权限\nC. 给同组用户添加执行权限\nD. 给其他用户添加执行权限",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文件权限",
            "knowledge_point": "chmod符号权限",
            "solution": "B",
        },
        {
            "title": "要将文件 file.txt 的所有者改为用户 testuser，同时将所属组改为 testgroup，应使用哪个命令？",
            "description": "要将文件 file.txt 的所有者改为用户 testuser，同时将所属组改为 testgroup，应使用哪个命令？\nA. chmod testuser:testgroup file.txt\nB. chown testuser:testgroup file.txt\nC. chgrp testuser:testgroup file.txt\nD. usermod testuser:testgroup file.txt",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文件权限",
            "knowledge_point": "chown命令",
            "solution": "B",
        },
        {
            "title": "权限 'rwxr-Sr-x' 中大写的 'S' 表示什么含义？",
            "description": "权限 'rwxr-Sr-x' 中大写的 'S' 表示什么含义？\nA. 普通的执行权限\nB. SetGID位已设置，但组执行权限未设置\nC. 粘滞位已设置\nD. 文件被锁定",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "文件权限",
            "knowledge_point": "特殊权限位",
            "solution": "B",
        },
        # --- 文本处理 (7题) ---
        {
            "title": "以下哪个命令可以用来查看文件的前10行内容？",
            "description": "以下哪个命令可以用来查看文件的前10行内容？\nA. tail\nB. head\nC. cat\nD. more",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文本处理",
            "knowledge_point": "head命令",
            "solution": "B",
        },
        {
            "title": "命令 'grep -i \"hello\" file.txt' 中 -i 参数的作用是：",
            "description": "命令 'grep -i \"hello\" file.txt' 中 -i 参数的作用是：\nA. 忽略大小写\nB. 显示行号\nC. 反向匹配\nD. 递归搜索",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文本处理",
            "knowledge_point": "grep命令",
            "solution": "A",
        },
        {
            "title": "以下哪个命令可以对文本文件按行排序并去除重复行？",
            "description": "以下哪个命令可以对文本文件按行排序并去除重复行？\nA. sort file.txt | uniq\nB. uniq file.txt | sort\nC. sort -u file.txt\nD. A和C都可以",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "sort和uniq命令",
            "solution": "D",
        },
        {
            "title": "在awk命令中，$0代表什么？",
            "description": "在awk命令中，$0代表什么？\nA. 第一个字段\nB. 最后一个字段\nC. 整行内容\nD. 行号",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "awk命令",
            "solution": "C",
        },
        {
            "title": "sed命令中，'s/old/new/g' 的作用是：",
            "description": "sed命令中，'s/old/new/g' 的作用是：\nA. 只替换每行第一个匹配\nB. 替换每行所有匹配\nC. 删除包含old的行\nD. 在old前面插入new",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "sed命令",
            "solution": "B",
        },
        {
            "title": "要统计文件 file.txt 的行数、单词数和字节数，应使用哪个命令？",
            "description": "要统计文件 file.txt 的行数、单词数和字节数，应使用哪个命令？\nA. count file.txt\nB. wc file.txt\nC. stat file.txt\nD. size file.txt",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文本处理",
            "knowledge_point": "wc命令",
            "solution": "B",
        },
        {
            "title": "命令 'awk -F: '{print $1, $3}' /etc/passwd' 的输出结果是什么格式？",
            "description": "命令 'awk -F: '{print $1, $3}' /etc/passwd' 的输出结果是什么格式？\nA. 用户名和用户ID，用冒号分隔\nB. 用户名和用户ID，用空格分隔\nC. 用户名和组ID，用空格分隔\nD. 用户名和主目录，用空格分隔",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "文本处理",
            "knowledge_point": "awk字段分割",
            "solution": "B",
        },
        # --- 进程管理 (4题) ---
        {
            "title": "以下哪个命令可以显示当前系统中运行的所有进程？",
            "description": "以下哪个命令可以显示当前系统中运行的所有进程？\nA. ps aux\nB. ls /proc\nC. jobs\nD. bg",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "进程管理",
            "knowledge_point": "ps命令",
            "solution": "A",
        },
        {
            "title": "要强制终止进程号为1234的进程，应使用哪个命令？",
            "description": "要强制终止进程号为1234的进程，应使用哪个命令？\nA. kill 1234\nB. kill -9 1234\nC. kill -15 1234\nD. stop 1234",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "进程管理",
            "knowledge_point": "kill命令",
            "solution": "B",
        },
        {
            "title": "top命令中，按哪个键可以按CPU使用率排序？",
            "description": "top命令中，按哪个键可以按CPU使用率排序？\nA. M\nB. P\nC. N\nD. T",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "进程管理",
            "knowledge_point": "top命令",
            "solution": "B",
        },
        {
            "title": "命令 'nohup ./script.sh &' 的作用是：",
            "description": "命令 'nohup ./script.sh &' 的作用是：\nA. 在后台运行脚本，终端关闭后脚本继续运行\nB. 在前台运行脚本\nC. 以root权限运行脚本\nD. 定时运行脚本",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "进程管理",
            "knowledge_point": "nohup和后台运行",
            "solution": "A",
        },
        # --- 网络命令 (4题) ---
        {
            "title": "以下哪个命令可以测试与远程主机的网络连通性？",
            "description": "以下哪个命令可以测试与远程主机的网络连通性？\nA. ping\nB. curl\nC. wget\nD. ssh",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "网络命令",
            "knowledge_point": "ping命令",
            "solution": "A",
        },
        {
            "title": "命令 'curl -o file.html http://example.com' 的作用是：",
            "description": "命令 'curl -o file.html http://example.com' 的作用是：\nA. 在终端显示网页内容\nB. 将网页内容保存到file.html\nC. 测试URL是否可达\nD. 下载文件并自动解压",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "网络命令",
            "knowledge_point": "curl命令",
            "solution": "B",
        },
        {
            "title": "netstat -tuln 命令中各个参数的含义，正确的是：",
            "description": "netstat -tuln 命令中各个参数的含义，正确的是：\nA. -t: TCP, -u: UDP, -l: 监听状态, -n: 以数字显示\nB. -t: 所有连接, -u: 用户连接, -l: 列出所有, -n: 以名称显示\nC. -t: TCP, -u: 用户, -l: 最近的, -n: 以数字显示\nD. -t: 路由表, -u: UDP, -l: 锁定, -n: 以数字显示",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "网络命令",
            "knowledge_point": "netstat命令",
            "solution": "A",
        },
        {
            "title": "wget与curl的主要区别是什么？",
            "description": "wget与curl的主要区别是什么？\nA. wget主要用于下载文件，curl还可以发送各种HTTP请求\nB. curl只能下载文件，wget还可以发送各种HTTP请求\nC. 两者功能完全相同\nD. wget只支持HTTP，curl支持所有协议",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "网络命令",
            "knowledge_point": "wget和curl对比",
            "solution": "A",
        },
        # --- Shell脚本基础 (4题) ---
        {
            "title": "Shell脚本的第一行通常是什么？",
            "description": "Shell脚本的第一行通常是什么？\nA. #!/bin/bash\nB. # shell script\nC. @echo off\nD. import shell",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Shell脚本",
            "knowledge_point": "Shebang",
            "solution": "A",
        },
        {
            "title": "在Shell脚本中，$? 代表什么？",
            "description": "在Shell脚本中，$? 代表什么？\nA. 当前进程的PID\nB. 上一个命令的退出状态码\nC. 脚本的参数个数\nD. 当前用户的UID",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Shell脚本",
            "knowledge_point": "特殊变量",
            "solution": "B",
        },
        {
            "title": "在Bash脚本中，$* 和 $@ 的区别是什么？",
            "description": "在Bash脚本中，$* 和 $@ 的区别是什么？\nA. 没有区别\nB. $* 将所有参数作为单个字符串，$@ 将每个参数作为独立字符串\nC. $@ 将所有参数作为单个字符串，$* 将每个参数作为独立字符串\nD. $* 只包含第一个参数，$@ 包含所有参数",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Shell脚本",
            "knowledge_point": "位置参数",
            "solution": "B",
        },
        {
            "title": "以下哪个是Shell脚本中正确的数组声明方式（Bash）？",
            "description": "以下哪个是Shell脚本中正确的数组声明方式（Bash）？\nA. arr=(1 2 3 4)\nB. arr=[1,2,3,4]\nC. arr={1 2 3 4}\nD. arr=(1,2,3,4)",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "Shell脚本",
            "knowledge_point": "Bash数组",
            "solution": "A",
        },
        # --- 环境变量 (3题) ---
        {
            "title": "以下哪个命令可以查看所有环境变量？",
            "description": "以下哪个命令可以查看所有环境变量？\nA. echo $PATH\nB. env\nC. set\nD. B和C都可以",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "环境变量",
            "knowledge_point": "查看环境变量",
            "solution": "D",
        },
        {
            "title": "要使环境变量在所有子进程中都可用，应该如何设置？",
            "description": "要使环境变量在所有子进程中都可用，应该如何设置？\nA. VAR=value\nB. export VAR=value\nC. set VAR=value\nD. env VAR=value",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "环境变量",
            "knowledge_point": "export命令",
            "solution": "B",
        },
        {
            "title": "以下哪个文件中的环境变量设置会对所有用户生效？",
            "description": "以下哪个文件中的环境变量设置会对所有用户生效？\nA. ~/.bashrc\nB. ~/.profile\nC. /etc/profile\nD. ~/.bash_profile",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "环境变量",
            "knowledge_point": "环境变量配置文件",
            "solution": "C",
        },
        # --- 管道和重定向 (3题) ---
        {
            "title": "命令 'ls > file.txt' 和 'ls >> file.txt' 的区别是什么？",
            "description": "命令 'ls > file.txt' 和 'ls >> file.txt' 的区别是什么？\nA. 没有区别\nB. > 覆盖写入，>> 追加写入\nC. > 追加写入，>> 覆盖写入\nD. > 写入文件，>> 写入屏幕",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "管道和重定向",
            "knowledge_point": "输出重定向",
            "solution": "B",
        },
        {
            "title": "管道符 '|' 的作用是什么？",
            "description": "管道符 '|' 的作用是什么？\nA. 将多个命令并行执行\nB. 将前一个命令的输出作为后一个命令的输入\nC. 同时执行两个命令\nD. 将命令输出保存到文件",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "管道和重定向",
            "knowledge_point": "管道",
            "solution": "B",
        },
        {
            "title": "命令 'command 2>&1' 的含义是什么？",
            "description": "命令 'command 2>&1' 的含义是什么？\nA. 将标准输出重定向到标准错误\nB. 将标准错误重定向到标准输出\nC. 将标准错误和标准输出都重定向到文件\nD. 忽略所有错误输出",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "管道和重定向",
            "knowledge_point": "文件描述符重定向",
            "solution": "B",
        },
        # --- 用户管理 (2题) ---
        {
            "title": "以下哪个命令可以创建一个新用户并同时创建其主目录？",
            "description": "以下哪个命令可以创建一个新用户并同时创建其主目录？\nA. useradd username\nB. useradd -m username\nC. adduser username\nD. B和C都可以",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "用户管理",
            "knowledge_point": "创建用户",
            "solution": "D",
        },
        {
            "title": "将用户添加到附加组应使用哪个命令？",
            "description": "将用户添加到附加组应使用哪个命令？\nA. usermod -aG groupname username\nB. useradd -G groupname username\nC. groupadd username groupname\nD. adduser groupname username",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "用户管理",
            "knowledge_point": "用户组管理",
            "solution": "A",
        },
        # --- 软件包管理 (1题) ---
        {
            "title": "在Debian/Ubuntu系统中，安装软件包的命令是什么？",
            "description": "在Debian/Ubuntu系统中，安装软件包的命令是什么？\nA. yum install package\nB. apt install package\nC. pacman -S package\nD. rpm -i package",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件包管理",
            "knowledge_point": "apt命令",
            "solution": "B",
        },

        # ==================== 编程题 (20题) ====================
        # --- 文件系统 (3题) ---
        {
            "title": "批量创建目录",
            "description": "编写一个Shell脚本，接收一个数字N作为参数，创建N个目录，目录名格式为 dir_1, dir_2, ..., dir_N。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文件系统",
            "knowledge_point": "mkdir命令和循环",
            "code_template": "#!/bin/bash\n# 接收参数N，创建N个目录：dir_1, dir_2, ..., dir_N\nN=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nN=$1\nfor i in $(seq 1 $N); do\n    mkdir -p \"dir_$i\"\ndone",
            "hint": "使用for循环和seq命令生成序列，结合mkdir创建目录",
        },
        {
            "title": "查找并删除临时文件",
            "description": "编写一个Shell脚本，在当前目录及其子目录中查找所有以 '.tmp' 结尾的文件，并在用户确认后删除它们。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文件系统",
            "knowledge_point": "find命令和文件删除",
            "code_template": "#!/bin/bash\n# 查找并删除当前目录下所有 .tmp 文件\n# 需要用户确认后才删除\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\necho \"以下 .tmp 文件将被删除:\"\nfind . -name \"*.tmp\" -type f\nread -p \"确认删除这些文件吗？(y/n): \" confirm\nif [ \"$confirm\" = \"y\" ]; then\n    find . -name \"*.tmp\" -type f -delete\n    echo \"文件已删除\"\nelse\n    echo \"操作已取消\"\nfi",
            "hint": "使用find命令查找文件，read命令获取用户输入，-delete参数删除文件",
        },
        {
            "title": "文件备份脚本",
            "description": "编写一个Shell脚本，将指定目录下的所有文件备份到另一个目录，备份文件名添加时间戳后缀（格式：原文件名_20240101_120000.bak）。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "文件系统",
            "knowledge_point": "文件操作和日期命令",
            "code_template": "#!/bin/bash\n# 备份源目录的所有文件到目标目录\n# 备份文件名格式: 原文件名_时间戳.bak\nSRC_DIR=$1\nDEST_DIR=$2\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nSRC_DIR=$1\nDEST_DIR=$2\n\nmkdir -p \"$DEST_DIR\"\nTIMESTAMP=$(date +%Y%m%d_%H%M%S)\n\nfor file in \"$SRC_DIR\"/*; do\n    if [ -f \"$file\" ]; then\n        filename=$(basename \"$file\")\n        cp \"$file\" \"${DEST_DIR}/${filename}_${TIMESTAMP}.bak\"\n    fi\ndone\necho \"备份完成\"",
            "hint": "使用date命令获取时间戳，basename获取文件名，for循环遍历文件",
        },
        # --- 文件权限 (2题) ---
        {
            "title": "批量修改文件权限",
            "description": "编写一个Shell脚本，将指定目录下所有 .sh 文件设置为可执行权限（755），将所有 .conf 文件设置为只读权限（644）。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文件权限",
            "knowledge_point": "chmod命令和find命令",
            "code_template": "#!/bin/bash\n# 批量修改指定目录下文件的权限\nDIR=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nDIR=$1\n# 设置 .sh 文件为可执行\nfind \"$DIR\" -name \"*.sh\" -type f -exec chmod 755 {} \\;\n# 设置 .conf 文件为只读\nfind \"$DIR\" -name \"*.conf\" -type f -exec chmod 644 {} \\;\necho \"权限修改完成\"",
            "hint": "使用find命令的-exec参数结合chmod命令批量修改权限",
        },
        {
            "title": "权限检查脚本",
            "description": "编写一个Shell脚本，检查指定文件是否对当前用户可读、可写、可执行，并输出检查结果。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文件权限",
            "knowledge_point": "文件测试操作符",
            "code_template": "#!/bin/bash\n# 检查文件权限\nFILE=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nFILE=$1\n\nif [ ! -e \"$FILE\" ]; then\n    echo \"文件不存在\"\n    exit 1\nfi\n\necho \"文件: $FILE\"\nif [ -r \"$FILE\" ]; then echo \"可读: 是\"; else echo \"可读: 否\"; fi\nif [ -w \"$FILE\" ]; then echo \"可写: 是\"; else echo \"可写: 否\"; fi\nif [ -x \"$FILE\" ]; then echo \"可执行: 是\"; else echo \"可执行: 否\"; fi",
            "hint": "使用 -r, -w, -x 文件测试操作符检查权限",
        },
        # --- 文本处理 (4题) ---
        {
            "title": "统计文件中单词出现次数",
            "description": "编写一个Shell脚本，统计指定文件中每个单词出现的次数，并按出现次数从高到低排序输出前10个。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "文本处理命令组合",
            "code_template": "#!/bin/bash\n# 统计文件中单词出现频率\nFILE=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nFILE=$1\ntr -s '[:space:]' '\\n' < \"$FILE\" | \\\n    tr '[:upper:]' '[:lower:]' | \\\n    sort | uniq -c | sort -rn | head -10",
            "hint": "使用tr将空格转换为换行，sort排序，uniq -c统计，sort -rn数字排序",
        },
        {
            "title": "提取日志中的错误信息",
            "description": "编写一个Shell脚本，从日志文件中提取所有包含 'ERROR' 或 'FATAL' 的行，并输出到错误日志文件中，同时统计错误总数。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "grep命令",
            "code_template": "#!/bin/bash\n# 从日志文件提取错误信息\nLOG_FILE=$1\nERROR_FILE=\"errors.log\"\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nLOG_FILE=$1\nERROR_FILE=\"errors.log\"\n\ngrep -E '(ERROR|FATAL)' \"$LOG_FILE\" > \"$ERROR_FILE\"\nERROR_COUNT=$(wc -l < \"$ERROR_FILE\")\necho \"共找到 $ERROR_COUNT 条错误信息\"\necho \"错误信息已保存到 $ERROR_FILE\"",
            "hint": "使用grep -E支持扩展正则表达式，匹配多个模式",
        },
        {
            "title": "文本替换脚本",
            "description": "编写一个Shell脚本，接收三个参数：文件名、要替换的字符串、替换后的字符串。脚本应备份原文件（添加.bak后缀），然后执行替换。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "sed命令",
            "code_template": "#!/bin/bash\n# 文本替换脚本\nFILE=$1\nOLD=$2\nNEW=$3\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nFILE=$1\nOLD=$2\nNEW=$3\n\nif [ ! -f \"$FILE\" ]; then\n    echo \"文件不存在\"\n    exit 1\nfi\n\ncp \"$FILE\" \"${FILE}.bak\"\nsed -i \"s/${OLD}/${NEW}/g\" \"$FILE\"\necho \"替换完成，原文件已备份为 ${FILE}.bak\"",
            "hint": "使用cp备份文件，sed -i进行原地替换，s/old/new/g替换所有匹配",
        },
        {
            "title": "CSV文件处理",
            "description": "编写一个Shell脚本，处理CSV文件（逗号分隔），提取第2列和第4列的数据，并计算第2列数值的总和。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "文本处理",
            "knowledge_point": "awk命令高级用法",
            "code_template": "#!/bin/bash\n# 处理CSV文件\nCSV_FILE=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nCSV_FILE=$1\n\necho \"第2列和第4列数据:\"\nawk -F',' '{print $2, $4}' \"$CSV_FILE\"\n\necho \"第2列数值总和:\"\nawk -F',' '{sum+=$2} END {print sum}' \"$CSV_FILE\"",
            "hint": "使用awk的-F参数指定分隔符，使用END块输出汇总结果",
        },
        # --- 进程管理 (2题) ---
        {
            "title": "进程监控脚本",
            "description": "编写一个Shell脚本，监控指定进程是否在运行。如果进程不存在，则输出警告信息并记录到日志文件。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "进程管理",
            "knowledge_point": "ps命令和条件判断",
            "code_template": "#!/bin/bash\n# 监控指定进程\nPROCESS_NAME=$1\nLOG_FILE=\"process_monitor.log\"\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nPROCESS_NAME=$1\nLOG_FILE=\"process_monitor.log\"\n\nif pgrep -x \"$PROCESS_NAME\" > /dev/null; then\n    echo \"进程 $PROCESS_NAME 正在运行\"\nelse\n    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')\n    echo \"警告: 进程 $PROCESS_NAME 未运行\"\n    echo \"[$TIMESTAMP] 进程 $PROCESS_NAME 未运行\" >> \"$LOG_FILE\"\nfi",
            "hint": "使用pgrep检查进程是否存在，date命令获取时间戳",
        },
        {
            "title": "批量终止进程",
            "description": "编写一个Shell脚本，接收进程名作为参数，先列出匹配的进程信息，然后询问用户是否终止这些进程。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "进程管理",
            "knowledge_point": "ps和kill命令",
            "code_template": "#!/bin/bash\n# 批量终止进程\nPROCESS_NAME=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nPROCESS_NAME=$1\n\necho \"匹配的进程:\"\nps aux | grep \"$PROCESS_NAME\" | grep -v grep\n\nPIDS=$(pgrep -f \"$PROCESS_NAME\")\nif [ -z \"$PIDS\" ]; then\n    echo \"没有找到匹配的进程\"\n    exit 0\nfi\n\nread -p \"是否终止这些进程？(y/n): \" confirm\nif [ \"$confirm\" = \"y\" ]; then\n    pkill -f \"$PROCESS_NAME\"\n    echo \"进程已终止\"\nelse\n    echo \"操作已取消\"\nfi",
            "hint": "使用pgrep -f匹配进程名，pkill -f终止匹配的进程",
        },
        # --- 网络命令 (2题) ---
        {
            "title": "批量检测主机连通性",
            "description": "编写一个Shell脚本，从文件中读取IP地址列表（每行一个），逐一ping测试连通性，输出结果并统计可达主机数量。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "网络命令",
            "knowledge_point": "ping命令和循环",
            "code_template": "#!/bin/bash\n# 批量检测主机连通性\nIP_FILE=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nIP_FILE=$1\nSUCCESS=0\nFAIL=0\n\nwhile IFS= read -r ip; do\n    if ping -c 1 -W 2 \"$ip\" > /dev/null 2>&1; then\n        echo \"$ip - 可达\"\n        ((SUCCESS++))\n    else\n        echo \"$ip - 不可达\"\n        ((FAIL++))\n    fi\ndone < \"$IP_FILE\"\n\necho \"\\n统计: 可达 $SUCCESS 台, 不可达 $FAIL 台\"",
            "hint": "使用while read循环读取文件，ping -c 1发送一个包，-W设置超时",
        },
        {
            "title": "网页状态检测",
            "description": "编写一个Shell脚本，接收URL列表作为参数，检测每个URL的HTTP状态码，输出状态码不是200的URL。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "网络命令",
            "knowledge_point": "curl命令高级用法",
            "code_template": "#!/bin/bash\n# 检测URL的HTTP状态码\n# URL列表作为参数传入\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\necho \"检测URL状态:\"\nfor url in \"$@\"; do\n    STATUS=$(curl -s -o /dev/null -w \"%{http_code}\" \"$url\")\n    if [ \"$STATUS\" != \"200\" ]; then\n        echo \"警告: $url 状态码 $STATUS\"\n    else\n        echo \"正常: $url\"\n    fi\ndone",
            "hint": "使用curl -s -o /dev/null -w \"%{http_code}\"获取HTTP状态码",
        },
        # --- Shell脚本基础 (3题) ---
        {
            "title": "菜单脚本",
            "description": "编写一个Shell脚本，显示一个交互式菜单（查看系统信息/查看磁盘使用/查看内存使用/退出），根据用户选择执行相应操作。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Shell脚本",
            "knowledge_point": "case语句和菜单",
            "code_template": "#!/bin/bash\n# 交互式菜单脚本\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nwhile true; do\n    echo \"\\n===== 系统管理菜单 =====\"\n    echo \"1. 查看系统信息\"\n    echo \"2. 查看磁盘使用\"\n    echo \"3. 查看内存使用\"\n    echo \"4. 退出\"\n    read -p \"请选择 [1-4]: \" choice\n    \n    case $choice in\n        1) uname -a ;;\n        2) df -h ;;\n        3) free -h ;;\n        4) echo \"退出\"; exit 0 ;;\n        *) echo \"无效选择\" ;;\n    esac\ndone",
            "hint": "使用while循环显示菜单，case语句处理用户选择",
        },
        {
            "title": "函数练习 - 计算器",
            "description": "编写一个Shell脚本，定义四个函数（add, subtract, multiply, divide），实现简单的计算器功能。脚本接收三个参数：数字1、运算符、数字2。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Shell脚本",
            "knowledge_point": "Shell函数",
            "code_template": "#!/bin/bash\n# 简单计算器\nNUM1=$1\nOP=$2\nNUM2=$3\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nadd() { echo $(($1 + $2)); }\nsubtract() { echo $(($1 - $2)); }\nmultiply() { echo $(($1 * $2)); }\ndivide() {\n    if [ $2 -eq 0 ]; then\n        echo \"错误: 除数不能为0\"\n        return 1\n    fi\n    echo $(($1 / $2))\n}\n\nNUM1=$1\nOP=$2\nNUM2=$3\n\ncase $OP in\n    +) add $NUM1 $NUM2 ;;\n    -) subtract $NUM1 $NUM2 ;;\n    x|\\*) multiply $NUM1 $NUM2 ;;\n    /) divide $NUM1 $NUM2 ;;\n    *) echo \"无效运算符\" ;;\nesac",
            "hint": "使用function关键字或直接定义函数，case语句匹配运算符",
        },
        {
            "title": "错误处理脚本",
            "description": "编写一个Shell脚本，实现一个安全的文件复制函数，包含参数检查、源文件存在性检查、目标目录存在性检查，并使用trap命令捕获错误信号。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "Shell脚本",
            "knowledge_point": "错误处理和trap",
            "code_template": "#!/bin/bash\n# 安全的文件复制脚本\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nerror_handler() {\n    echo \"错误: 脚本在第 $1 行退出\"\n    exit 1\n}\ntrap 'error_handler $LINENO' ERR\n\nsafe_copy() {\n    local src=$1\n    local dest=$2\n    \n    if [ $# -ne 2 ]; then\n        echo \"用法: safe_copy <源文件> <目标>\"\n        return 1\n    fi\n    \n    if [ ! -f \"$src\" ]; then\n        echo \"错误: 源文件 $src 不存在\"\n        return 1\n    fi\n    \n    local dest_dir=$(dirname \"$dest\")\n    if [ ! -d \"$dest_dir\" ]; then\n        mkdir -p \"$dest_dir\"\n    fi\n    \n    cp \"$src\" \"$dest\"\n    echo \"复制成功: $src -> $dest\"\n}\n\n# 示例调用\nsafe_copy \"$1\" \"$2\"",
            "hint": "使用trap捕获ERR信号，local定义局部变量，$LINENO获取行号",
        },
        # --- 用户管理 (1题) ---
        {
            "title": "用户信息查询脚本",
            "description": "编写一个Shell脚本，接收用户名作为参数，查询并显示该用户的详细信息（UID、GID、主目录、Shell、所属组等）。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "用户管理",
            "knowledge_point": "用户信息查询",
            "code_template": "#!/bin/bash\n# 查询用户信息\nUSERNAME=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nUSERNAME=$1\n\nif [ -z \"$USERNAME\" ]; then\n    echo \"用法: $0 <用户名>\"\n    exit 1\nfi\n\nif ! id \"$USERNAME\" > /dev/null 2>&1; then\n    echo \"用户 $USERNAME 不存在\"\n    exit 1\nfi\n\necho \"=== 用户信息: $USERNAME ===\"\necho \"UID: $(id -u $USERNAME)\"\necho \"GID: $(id -g $USERNAME)\"\necho \"主组: $(id -gn $USERNAME)\"\necho \"所属组: $(id -Gn $USERNAME)\"\necho \"主目录: $(eval echo ~$USERNAME)\"\necho \"Shell: $(grep \"^$USERNAME:\" /etc/passwd | cut -d: -f7)\"",
            "hint": "使用id命令获取用户信息，grep和cut提取/etc/passwd中的字段",
        },
        # --- 环境变量 (1题) ---
        {
            "title": "环境变量管理脚本",
            "description": "编写一个Shell脚本，可以添加、删除和列出自定义环境变量。脚本将环境变量存储在配置文件中。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "环境变量",
            "knowledge_point": "环境变量管理",
            "code_template": "#!/bin/bash\n# 环境变量管理脚本\nCONFIG_FILE=\".env_vars.conf\"\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nCONFIG_FILE=\".env_vars.conf\"\ntouch \"$CONFIG_FILE\"\n\ncase $1 in\n    add)\n        if [ -z \"$2\" ] || [ -z \"$3\" ]; then\n            echo \"用法: $0 add VAR_NAME VALUE\"\n            exit 1\n        fi\n        # 删除已有同名变量\n        grep -v \"^$2=\" \"$CONFIG_FILE\" > \"${CONFIG_FILE}.tmp\"\n        echo \"$2=$3\" >> \"${CONFIG_FILE}.tmp\"\n        mv \"${CONFIG_FILE}.tmp\" \"$CONFIG_FILE\"\n        export \"$2=$3\"\n        echo \"已添加: $2=$3\"\n        ;;\n    remove)\n        if [ -z \"$2\" ]; then\n            echo \"用法: $0 remove VAR_NAME\"\n            exit 1\n        fi\n        grep -v \"^$2=\" \"$CONFIG_FILE\" > \"${CONFIG_FILE}.tmp\"\n        mv \"${CONFIG_FILE}.tmp\" \"$CONFIG_FILE\"\n        unset \"$2\"\n        echo \"已删除: $2\"\n        ;;\n    list)\n        echo \"自定义环境变量:\"\n        cat \"$CONFIG_FILE\"\n        ;;\n    *)\n        echo \"用法: $0 {add|remove|list} [VAR_NAME] [VALUE]\"\n        ;;\nesac",
            "hint": "使用case语句实现菜单，grep -v删除匹配行，配置文件存储变量",
        },
        # --- 管道和重定向 (3题) ---
        {
            "title": "重定向日志收集",
            "description": "编写一个Shell脚本，同时运行多个命令，将标准输出和错误输出分别重定向到不同的日志文件，并在最后汇总输出执行结果。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "管道和重定向",
            "knowledge_point": "高级重定向",
            "code_template": "#!/bin/bash\n# 执行多个命令，分别记录输出和错误\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nSTDOUT_LOG=\"stdout.log\"\nSTDERR_LOG=\"stderr.log\"\nRESULT_LOG=\"result.log\"\n\n# 清空日志文件\n> \"$STDOUT_LOG\"\n> \"$STDERR_LOG\"\n> \"$RESULT_LOG\"\n\nCOMMANDS=(\"ls /tmp\" \"ls /nonexistent\" \"date\" \"uname -a\")\n\nfor cmd in \"${COMMANDS[@]}\"; do\n    echo \"执行: $cmd\" >> \"$RESULT_LOG\"\n    eval \"$cmd\" >> \"$STDOUT_LOG\" 2>> \"$STDERR_LOG\"\n    echo \"退出码: $?\" >> \"$RESULT_LOG\"\n    echo \"---\" >> \"$RESULT_LOG\"\ndone\n\necho \"标准输出行数: $(wc -l < $STDOUT_LOG)\"\necho \"错误输出行数: $(wc -l < $STDERR_LOG)\"",
            "hint": "使用>>追加重定向，2>>重定向错误输出，eval执行字符串命令",
        },
        {
            "title": "日志分析管道",
            "description": "编写一个Shell脚本，使用管道组合多个命令，分析Web服务器访问日志：统计访问次数最多的前5个IP地址。",
            "instructions": "请编写Shell脚本完成任务",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "管道和重定向",
            "knowledge_point": "管道组合",
            "code_template": "#!/bin/bash\n# 分析Web日志，找出访问最多的IP\nLOG_FILE=$1\n\n# 请在此处编写脚本\n",
            "solution": "#!/bin/bash\nLOG_FILE=$1\n\necho \"访问次数最多的前5个IP:\"\nawk '{print $1}' \"$LOG_FILE\" | \\\n    sort | uniq -c | \\\n    sort -rn | \\\n    head -5",
            "hint": "使用awk提取IP列，sort排序，uniq -c统计，sort -rn数字逆序排序",
        },

        # ==================== 简答题 (30题) ====================
        # --- 文件系统 (4题) ---
        {
            "title": "绝对路径和相对路径的区别",
            "description": "请解释Linux中绝对路径和相对路径的区别，并各举一个例子。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "文件系统",
            "knowledge_point": "路径概念",
            "solution": "绝对路径是从根目录(/)开始的完整路径，如 /home/user/documents/file.txt。相对路径是相对于当前工作目录的路径，如 ./documents/file.txt 或 ../other/file.txt。绝对路径在任何位置都指向同一个文件，而相对路径的含义取决于当前所在目录。",
        },
        {
            "title": "Linux目录结构说明",
            "description": "请说明Linux系统中以下主要目录的用途：/bin, /etc, /home, /var, /tmp, /usr, /dev, /proc",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文件系统",
            "knowledge_point": "FHS目录结构",
            "solution": "/bin: 存放系统基本命令（如ls, cp, mv等）\n/etc: 存放系统配置文件\n/home: 普通用户的主目录\n/var: 存放可变数据，如日志、缓存等\n/tmp: 临时文件目录，系统重启后可能清空\n/usr: 存放用户级程序和数据\n/dev: 设备文件目录\n/proc: 虚拟文件系统，提供进程和系统信息",
        },
        {
            "title": "硬链接和软链接的区别",
            "description": "请详细解释Linux中硬链接（hard link）和软链接（symbolic link）的区别，包括创建方式、特点和使用场景。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "文件系统",
            "knowledge_point": "链接类型",
            "solution": "硬链接：\n- 创建：ln source hardlink\n- 与原文件共享同一个inode\n- 不能跨文件系统\n- 不能链接目录\n- 删除原文件不影响硬链接\n\n软链接：\n- 创建：ln -s source symlink\n- 有独立的inode，指向原文件路径\n- 可以跨文件系统\n- 可以链接目录\n- 删除原文件会导致软链接失效（悬空链接）\n\n使用场景：硬链接用于重要文件的备份，软链接用于创建快捷方式或版本管理。",
        },
        {
            "title": "find命令的常用选项",
            "description": "请列举find命令至少5个常用的查找条件选项，并说明每个选项的用途。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文件系统",
            "knowledge_point": "find命令选项",
            "solution": "1. -name: 按文件名查找（支持通配符）\n2. -type: 按文件类型查找（f:文件, d:目录, l:链接）\n3. -size: 按文件大小查找（+100M:大于100M）\n4. -mtime: 按修改时间查找（-7:7天内修改）\n5. -user: 按文件所有者查找\n6. -perm: 按权限查找（如 -perm 755）\n7. -exec: 对找到的文件执行命令\n8. -maxdepth: 限制搜索深度",
        },
        # --- 文件权限 (3题) ---
        {
            "title": "Linux文件权限机制",
            "description": "请详细解释Linux文件权限系统，包括：三组权限（所有者、组、其他）、读写执行权限的含义、数字表示法和符号表示法。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文件权限",
            "knowledge_point": "权限系统",
            "solution": "Linux文件权限分为三组：\n1. 所有者(owner)：文件的创建者\n2. 组(group)：文件所属用户组的成员\n3. 其他(other)：其他所有用户\n\n三种权限：\n- 读(r/4)：查看文件内容/列出目录内容\n- 写(w/2)：修改文件/在目录中创建删除文件\n- 执行(x/1)：执行文件/进入目录\n\n数字表示法：每组权限用一个数字表示（r=4,w=2,x=1），如755=rwxr-xr-x\n符号表示法：u(所有者),g(组),o(其他),a(所有)，+添加,-删除,=设置",
        },
        {
            "title": "特殊权限位详解",
            "description": "请解释Linux中的三种特殊权限位：SetUID、SetGID和Sticky Bit，包括它们的作用和使用场景。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "文件权限",
            "knowledge_point": "特殊权限",
            "solution": "1. SetUID (SUID, 4xxx):\n- 设置在可执行文件上\n- 执行时以文件所有者身份运行\n- 典型例子：/usr/bin/passwd\n- 数字表示：chmod 4755 file\n\n2. SetGID (SGID, 2xxx):\n- 设置在目录上时，新创建的文件继承目录的组\n- 设置在可执行文件上时，以文件所属组身份运行\n- 数字表示：chmod 2755 dir\n\n3. Sticky Bit (1xxx):\n- 设置在目录上\n- 目录中的文件只有所有者才能删除\n- 典型例子：/tmp目录\n- 数字表示：chmod 1755 dir",
        },
        {
            "title": "umask的作用",
            "description": "请解释umask的作用，以及默认umask值0022对新创建文件和目录权限的影响。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文件权限",
            "knowledge_point": "umask",
            "solution": "umask（用户文件创建掩码）用于控制新创建文件和目录的默认权限。它定义了要从最大权限中去除的权限位。\n\n默认权限计算：\n- 文件最大权限：666（rw-rw-rw-）\n- 目录最大权限：777（rwxrwxrwx）\n\numask 0022的影响：\n- 新文件权限：666 - 022 = 644 (rw-r--r--)\n- 新目录权限：777 - 022 = 755 (rwxr-xr-x)\n\numask值通常在~/.bashrc或/etc/profile中设置，可以用umask命令查看和修改。",
        },
        # --- 文本处理 (4题) ---
        {
            "title": "grep命令常用选项",
            "description": "请列举grep命令至少6个常用选项，并说明每个选项的作用和使用场景。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "grep选项",
            "solution": "1. -i: 忽略大小写\n2. -v: 反向匹配（显示不匹配的行）\n3. -n: 显示行号\n4. -c: 统计匹配行数\n5. -r/-R: 递归搜索目录\n6. -l: 只显示包含匹配的文件名\n7. -w: 全词匹配\n8. -A n: 显示匹配行后n行\n9. -B n: 显示匹配行前n行\n10. -E: 使用扩展正则表达式\n11. -o: 只输出匹配的部分\n12. --color: 高亮显示匹配内容",
        },
        {
            "title": "awk的工作原理",
            "description": "请解释awk命令的工作原理，包括：基本语法结构、字段分割、内置变量（NR, NF, FS, OFS）和模式匹配。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "文本处理",
            "knowledge_point": "awk详解",
            "solution": "awk基本语法：awk 'pattern {action}' file\n\n工作原理：\n1. 逐行读取输入\n2. 按分隔符（默认空格）将每行分割成字段\n3. 匹配模式，执行对应动作\n\n内置变量：\n- NR: 当前行号\n- NF: 当前行的字段数\n- FS: 输入字段分隔符\n- OFS: 输出字段分隔符\n- $0: 整行内容\n- $1,$2...: 第1,2...个字段\n\n模式匹配：\n- 正则：/pattern/\n- 比较：$1 > 100\n- 范围：NR>=1 && NR<=5",
        },
        {
            "title": "sed命令详解",
            "description": "请解释sed命令的工作模式，包括：地址定位、常用命令（s替换、d删除、i插入、a追加）、以及-i选项的作用。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文本处理",
            "knowledge_point": "sed详解",
            "solution": "sed（流编辑器）工作模式：逐行读取输入，根据地址和命令处理，输出结果。\n\n地址定位：\n- 行号：3d（删除第3行）\n- 范围：3,7d（删除3-7行）\n- 正则：/pattern/d（删除匹配行）\n- $：最后一行\n\n常用命令：\n- s/old/new/g：替换（g表示全局）\n- d：删除\n- i\\text：在指定行前插入\n- a\\text：在指定行后追加\n- p：打印\n\n选项：\n-i：直接修改文件（原地编辑）\n-n：静默模式，配合p使用\n-e：执行多个命令",
        },
        {
            "title": "sort和uniq的配合使用",
            "description": "请解释sort和uniq命令如何配合使用，以及各自的常用选项。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "文本处理",
            "knowledge_point": "sort和uniq",
            "solution": "sort命令常用选项：\n-n: 按数字排序\n-r: 逆序排序\n-k: 按指定列排序\n-t: 指定分隔符\n-u: 去重（排序后）\n\nuniq命令常用选项：\n-c: 统计重复次数\n-d: 只显示重复行\n-u: 只显示唯一行\n-i: 忽略大小写\n\n配合使用：\n由于uniq只能去除相邻的重复行，所以通常需要先sort排序：\nsort file | uniq -c | sort -rn\n\n典型应用：统计日志中IP出现次数、分析词频等。",
        },
        # --- 进程管理 (3题) ---
        {
            "title": "进程状态说明",
            "description": "请解释Linux进程的几种基本状态（R运行、S睡眠、D不可中断、Z僵尸、T停止），以及如何查看进程状态。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "进程管理",
            "knowledge_point": "进程状态",
            "solution": "Linux进程基本状态：\n- R (Running/Runnable): 正在运行或在运行队列中等待\n- S (Sleeping): 可中断睡眠，等待事件完成\n- D (Disk Sleep): 不可中断睡眠，通常等待I/O\n- Z (Zombie): 僵尸进程，已终止但父进程未回收\n- T (Stopped): 被信号停止\n\n查看方式：\n- ps aux: 查看所有进程状态（STAT列）\n- top: 实时查看进程状态\n- cat /proc/[PID]/status: 查看详细状态\n\n僵尸进程处理：需要终止其父进程或修复父进程代码。",
        },
        {
            "title": "前台和后台进程管理",
            "description": "请解释Linux中前台进程和后台进程的概念，以及相关命令：&, jobs, fg, bg, Ctrl+Z的用法。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "进程管理",
            "knowledge_point": "前后台进程",
            "solution": "前台进程：占用当前终端，用户可以与之交互。\n后台进程：在后台运行，不占用终端。\n\n相关命令：\n- &: 命令末尾加&使其在后台运行（如 command &）\n- jobs: 列出当前终端的后台任务\n- fg %n: 将第n个后台任务调到前台\n- bg %n: 使第n个停止的任务在后台继续运行\n- Ctrl+Z: 暂停当前前台任务\n\n典型场景：\n1. 长时间运行的脚本：./long_script.sh &\n2. 暂停后转后台：Ctrl+Z, then bg\n3. 查看后台任务：jobs\n4. 需要交互时转前台：fg %1",
        },
        {
            "title": "kill信号类型",
            "description": "请解释常用kill信号的含义：SIGHUP(1), SIGINT(2), SIGKILL(9), SIGTERM(15), SIGSTOP(19), SIGCONT(18)。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "进程管理",
            "knowledge_point": "信号机制",
            "solution": "常用信号：\n- SIGHUP (1): 挂起信号，常用于让守护进程重新读取配置\n- SIGINT (2): 中断信号，等同于Ctrl+C\n- SIGKILL (9): 强制终止，进程无法捕获或忽略\n- SIGTERM (15): 默认终止信号，进程可以捕获并优雅退出\n- SIGSTOP (19): 暂停进程，无法捕获\n- SIGCONT (18): 继续运行被暂停的进程\n\n最佳实践：\n1. 首先尝试SIGTERM (kill PID)\n2. 等待进程优雅退出\n3. 如仍不退出，使用SIGKILL (kill -9 PID)\n4. 避免直接使用SIGKILL，可能导致资源未释放",
        },
        # --- 网络命令 (3题) ---
        {
            "title": "网络诊断工具",
            "description": "请介绍ping、traceroute、netstat/ss、nmap这几个网络诊断工具的用途和基本用法。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "网络命令",
            "knowledge_point": "网络诊断",
            "solution": "1. ping: 测试网络连通性\n   用法: ping [-c count] host\n   示例: ping -c 4 google.com\n\n2. traceroute: 显示数据包到达目标的路径\n   用法: traceroute host\n   示例: traceroute google.com\n\n3. netstat/ss: 查看网络连接和端口\n   用法: netstat -tuln (显示监听的TCP/UDP端口)\n   ss是netstat的替代品，性能更好\n\n4. nmap: 网络扫描和安全审计\n   用法: nmap [选项] target\n   示例: nmap -sV 192.168.1.1 (扫描开放端口和服务)",
        },
        {
            "title": "curl的高级用法",
            "description": "请介绍curl命令的高级用法，包括：发送POST请求、设置请求头、上传文件、跟随重定向、设置超时等。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "网络命令",
            "knowledge_point": "curl高级用法",
            "solution": "curl高级用法：\n\n1. POST请求: curl -X POST -d 'data' url\n2. JSON数据: curl -H 'Content-Type: application/json' -d '{\"key\":\"value\"}' url\n3. 设置请求头: curl -H 'Header: value' url\n4. 上传文件: curl -F 'file=@/path/to/file' url\n5. 跟随重定向: curl -L url\n6. 设置超时: curl --connect-timeout 5 --max-time 30 url\n7. 保存响应头: curl -D headers.txt url\n8. 使用代理: curl -x http://proxy:8080 url\n9. 认证: curl -u user:password url\n10. 下载文件: curl -O url 或 curl -o filename url",
        },
        {
            "title": "SSH相关命令",
            "description": "请介绍SSH的基本用法，包括：远程登录、远程执行命令、文件传输（scp和rsync）、SSH密钥配置。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "网络命令",
            "knowledge_point": "SSH用法",
            "solution": "SSH基本用法：\n\n1. 远程登录: ssh user@host\n   指定端口: ssh -p 2222 user@host\n\n2. 远程执行命令: ssh user@host 'command'\n   示例: ssh user@host 'ls -la /var/log'\n\n3. 文件传输:\n   scp: scp file user@host:/path\n   scp -r: 传输目录\n   rsync: rsync -avz src user@host:/dest\n\n4. SSH密钥配置:\n   生成密钥: ssh-keygen -t rsa\n   复制公钥: ssh-copy-id user@host\n   配置文件: ~/.ssh/config\n\n5. 安全建议:\n   - 禁用密码登录\n   - 使用非标准端口\n   - 定期更换密钥",
        },
        # --- Shell脚本 (4题) ---
        {
            "title": "Shell脚本中的条件测试",
            "description": "请解释Shell脚本中条件测试的三种形式：test命令、[]和[[]]，以及常用的文件测试、字符串测试和数值测试操作符。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "Shell脚本",
            "knowledge_point": "条件测试",
            "solution": "三种条件测试形式：\n1. test expression\n2. [ expression ] (注意空格)\n3. [[ expression ]] (Bash扩展，支持正则)\n\n文件测试：\n-e: 存在  -f: 普通文件  -d: 目录\n-r: 可读  -w: 可写  -x: 可执行\n-s: 非空  -L: 符号链接\n\n字符串测试：\n=, ==: 相等  !=: 不等\n-z: 为空  -n: 非空\n<, >: 字典序比较\n\n数值测试：\n-eq: 等于  -ne: 不等于\n-gt: 大于  -lt: 小于\n-ge: 大于等于  -le: 小于等于\n\n逻辑运算：\n-a/&&: 与  -o/||: 或  !: 非",
        },
        {
            "title": "Shell脚本的调试方法",
            "description": "请介绍Shell脚本调试的常用方法，包括：set -x、set -e、set -u、trap命令以及shellcheck工具。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "Shell脚本",
            "knowledge_point": "脚本调试",
            "solution": "Shell脚本调试方法：\n\n1. set -x: 执行跟踪，显示每条命令及其展开后的值\n2. set -e: 遇到错误立即退出\n3. set -u: 使用未定义变量时报错\n4. set -o pipefail: 管道中任意命令失败则整体失败\n\n组合使用: set -euo pipefail\n\n5. trap命令:\n   trap 'echo \"Error at line $LINENO\"' ERR\n   捕获错误信号并执行清理操作\n\n6. shellcheck工具:\n   静态分析脚本，发现潜在问题\n   使用: shellcheck script.sh\n\n7. 调试技巧：\n   - 在脚本开头加 set -x\n   - 使用 echo 调试变量值\n   - 分段测试脚本\n   - 检查退出码 echo $?",
        },
        {
            "title": "Shell脚本最佳实践",
            "description": "请列举至少8条编写高质量Shell脚本的最佳实践。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "Shell脚本",
            "knowledge_point": "脚本规范",
            "solution": "Shell脚本最佳实践：\n\n1. 添加shebang行: #!/bin/bash\n2. 使用set -euo pipefail严格模式\n3. 变量使用双引号: \"$VAR\"\n4. 使用local声明函数变量\n5. 添加注释说明脚本用途\n6. 使用有意义的变量名\n7. 错误处理: 检查命令返回值\n8. 日志记录: 使用logger或自定义日志函数\n9. 使用函数封装重复代码\n10. 代码缩进保持一致\n11. 使用shellcheck检查脚本\n12. 避免使用eval（安全风险）\n13. 使用$(command)代替反引号\n14. 临时文件使用mktemp并清理",
        },
        {
            "title": "Shell脚本中的循环结构",
            "description": "请介绍Shell脚本中的各种循环结构：for循环、while循环、until循环，以及break和continue的用法。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "Shell脚本",
            "knowledge_point": "循环结构",
            "solution": "Shell脚本循环结构：\n\n1. for循环：\n   for i in list; do commands; done\n   for ((i=0; i<10; i++)); do commands; done\n   for file in *.txt; do commands; done\n\n2. while循环：\n   while condition; do commands; done\n   while read line; do commands; done < file\n   while true; do commands; done (无限循环)\n\n3. until循环（条件为假时执行）：\n   until condition; do commands; done\n\n4. 控制语句：\n   break: 跳出循环\n   continue: 跳过本次循环\n\n示例：\nfor i in 1 2 3 4 5; do\n    if [ $i -eq 3 ]; then continue; fi\n    if [ $i -eq 5 ]; then break; fi\n    echo $i\ndone",
        },
        # --- 环境变量 (3题) ---
        {
            "title": "PATH环境变量",
            "description": "请解释PATH环境变量的作用，如何查看和修改PATH，以及添加新路径的几种方法。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "环境变量",
            "knowledge_point": "PATH变量",
            "solution": "PATH环境变量定义了Shell查找可执行文件的目录列表，用冒号分隔。\n\n查看PATH: echo $PATH\n\n修改方法：\n1. 临时添加（当前会话有效）:\n   export PATH=$PATH:/new/path\n\n2. 永久添加（用户级别）:\n   在 ~/.bashrc 或 ~/.profile 中添加:\n   export PATH=$PATH:/new/path\n   然后执行 source ~/.bashrc\n\n3. 永久添加（系统级别）:\n   在 /etc/environment 或 /etc/profile.d/ 下创建脚本\n\n注意事项：\n- 路径顺序很重要，先找到的命令先执行\n- 不要添加不可信的目录到PATH\n- 使用完整路径可以避免PATH相关问题",
        },
        {
            "title": "Shell配置文件加载顺序",
            "description": "请解释Bash Shell配置文件的加载顺序，包括/etc/profile、~/.bash_profile、~/.bashrc、~/.profile等文件的区别和作用。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "环境变量",
            "knowledge_point": "配置文件",
            "solution": "Bash配置文件加载顺序：\n\n登录Shell（login shell）：\n1. /etc/profile (系统级)\n2. ~/.bash_profile (用户级，按顺序查找第一个)\n   或 ~/.bash_login\n   或 ~/.profile\n3. ~/.bash_logout (退出时)\n\n非登录Shell（如脚本执行）：\n1. ~/.bashrc\n\n交互式非登录Shell（如打开新终端）：\n1. ~/.bashrc\n\n常见实践：\n- ~/.bash_profile 中 source ~/.bashrc\n- 环境变量放在 ~/.profile 或 ~/.bashrc\n- 别名和函数放在 ~/.bashrc\n- 系统级配置放在 /etc/profile.d/ 目录\n\n重新加载: source ~/.bashrc 或 . ~/.bashrc",
        },
        {
            "title": "常用环境变量说明",
            "description": "请解释以下环境变量的含义和用途：HOME, USER, SHELL, PATH, PS1, LANG, TERM, LD_LIBRARY_PATH",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "环境变量",
            "knowledge_point": "常用环境变量",
            "solution": "常用环境变量：\n\n- HOME: 当前用户的主目录路径\n  示例: /home/username\n\n- USER: 当前登录的用户名\n  示例: john\n\n- SHELL: 当前使用的Shell路径\n  示例: /bin/bash\n\n- PATH: 可执行文件搜索路径\n  示例: /usr/local/bin:/usr/bin:/bin\n\n- PS1: 命令行提示符格式\n  示例: \\u@\\h:\\w\\$\n\n- LANG: 系统语言和区域设置\n  示例: en_US.UTF-8\n\n- TERM: 终端类型\n  示例: xterm-256color\n\n- LD_LIBRARY_PATH: 动态链接库搜索路径\n  示例: /usr/local/lib",
        },
        # --- 管道和重定向 (2题) ---
        {
            "title": "输入输出重定向详解",
            "description": "请详细解释Linux中的输入输出重定向，包括：标准输入(0)、标准输出(1)、标准错误(2)、以及各种重定向操作符。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "管道和重定向",
            "knowledge_point": "重定向详解",
            "solution": "文件描述符：\n- 0: 标准输入(stdin)\n- 1: 标准输出(stdout)\n- 2: 标准错误(stderr)\n\n输出重定向：\n- >: 覆盖写入文件\n- >>: 追加写入文件\n- 2>: 重定向错误输出\n- 2>>: 追加重定向错误\n- &>: 重定向所有输出\n- 2>&1: 将错误合并到标准输出\n\n输入重定向：\n- <: 从文件读取输入\n- <<EOF: Here Document\n- <<<string: Here String\n\n示例：\ncommand > out.txt 2>&1 (所有输出到文件)\ncommand < in.txt (从文件读取)\ncat <<EOF > file (多行写入文件)",
        },
        {
            "title": "tee命令的用途",
            "description": "请解释tee命令的作用和使用场景，以及它在管道中的应用。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "管道和重定向",
            "knowledge_point": "tee命令",
            "solution": "tee命令作用：从标准输入读取数据，同时输出到标准输出和文件。\n\n基本语法: command | tee [options] file\n\n选项：\n-a: 追加模式\n-i: 忽略中断信号\n\n使用场景：\n1. 同时查看和保存输出：\n   ls -la | tee file_list.txt\n\n2. 记录命令执行日志：\n   ./script.sh 2>&1 | tee script.log\n\n3. 管道中间保存数据：\n   cat data.txt | sort | tee sorted.txt | uniq\n\n4. 调试管道命令：\n   在管道中间插入tee查看中间结果\n\n5. 多重定向：\n   command | tee file1 file2 (同时写入多个文件)",
        },
        {
            "title": "Here Document用法",
            "description": "请解释Here Document（<<）的语法和使用场景。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "管道和重定向",
            "knowledge_point": "Here Document",
            "solution": "Here Document语法：\ncommand <<DELIMITER\n内容\nDELIMITER\n\n特点：\n- DELIMITER通常是EOF，可以是任意标识符\n- 内容中的变量会被展开\n- 使用<<-可以忽略前导制表符\n- 使用引号包裹DELIMITER可禁止变量展开\n\n使用场景：\n\n1. 多行文本输入：\ncat <<EOF > file.txt\nline 1\nline 2\nEOF\n\n2. SQL查询：\nmysql -u root <<EOF\nSELECT * FROM users;\nEOF\n\n3. 配置文件生成：\ncat > /etc/config <<'EOF'  # 引号禁止变量展开\nVAR=$HOME\nEOF\n\n4. 脚本中发送邮件：\nmail -s \"Subject\" user@example.com <<EOF\n邮件内容\nEOF",
        },
        # --- 用户管理 (2题) ---
        {
            "title": "用户和组管理",
            "description": "请介绍Linux用户和组管理的相关命令：useradd, usermod, userdel, groupadd, groupdel, 以及/etc/passwd和/etc/shadow文件的格式。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "用户管理",
            "knowledge_point": "用户组管理",
            "solution": "用户管理命令：\n- useradd: 创建用户\n  useradd -m -s /bin/bash -G groupname username\n- usermod: 修改用户\n  usermod -aG groupname username (添加到附加组)\n  usermod -s /bin/zsh username (修改Shell)\n- userdel: 删除用户\n  userdel -r username (同时删除主目录)\n\n组管理命令：\n- groupadd: 创建组\n- groupdel: 删除组\n- gpasswd: 管理组成员\n\n/etc/passwd格式（每行7个字段）：\nusername:x:UID:GID:描述:主目录:Shell\n\n/etc/shadow格式：\nusername:加密密码:最后修改:最小期限:最大期限:警告:失效:标志\n\n常用查看命令：\nid username (查看用户信息)\ngroups username (查看所属组)\nwhoami (当前用户)",
        },
        {
            "title": "sudo机制说明",
            "description": "请解释sudo的工作原理、/etc/sudoers文件的配置方法以及安全使用建议。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "用户管理",
            "knowledge_point": "sudo机制",
            "solution": "sudo工作原理：\n1. 用户执行 sudo command\n2. 系统检查 /etc/sudoers 是否授权\n3. 输入当前用户密码（非root密码）\n4. 以目标用户（默认root）执行命令\n\n/etc/sudoers配置：\n使用visudo命令安全编辑\n格式: user host=(runas) commands\n\n示例：\n- john ALL=(ALL) ALL (完全权限)\n- john ALL=(ALL) NOPASSWD: ALL (免密)\n- %admin ALL=(ALL) ALL (组权限)\n- john ALL=(root) /usr/bin/systemctl (特定命令)\n\n安全建议：\n1. 使用visudo编辑，避免语法错误\n2. 最小权限原则\n3. 避免NOPASSWD\n4. 定期审计sudo日志 (/var/log/auth.log)\n5. 使用sudo -l 查看当前权限",
        },
        # --- 软件包管理 (1题) ---
        {
            "title": "apt和yum对比",
            "description": "请对比Debian/Ubuntu的apt和CentOS/RHEL的yum包管理器，包括：常用命令对照、配置文件位置、软件源管理。",
            "instructions": "请详细回答",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件包管理",
            "knowledge_point": "包管理器对比",
            "solution": "apt vs yum 命令对照：\n\n| 操作 | apt | yum |\n|------|-----|-----|\n| 更新源 | apt update | yum makecache |\n| 安装 | apt install pkg | yum install pkg |\n| 卸载 | apt remove pkg | yum remove pkg |\n| 更新所有 | apt upgrade | yum update |\n| 搜索 | apt search keyword | yum search keyword |\n| 信息 | apt show pkg | yum info pkg |\n| 列出已安装 | apt list --installed | yum list installed |\n| 清理缓存 | apt clean | yum clean all |\n\n配置文件：\napt: /etc/apt/sources.list, /etc/apt/sources.list.d/\nyum: /etc/yum.repos.d/*.repo\n\n软件源格式：\ndeb http://archive.ubuntu.com/ubuntu focal main (apt)\n[base]\nname=CentOS-$releasever - Base\nbaseurl=http://mirror.centos.org/... (yum)",
        },
    ],
}
