# -*- coding: utf-8 -*-
"""
Python编程基础 - 学习路径
知识点: 基本语法、流程控制、数据结构、函数、面向对象、异常处理、文件操作、模块和包、列表推导式、装饰器、生成器
题目数量: 90题 (选择题40 + 编程题20 + 简答题30)
难度分布: easy 30% (27题) + medium 50% (45题) + hard 20% (18题)
"""

EXERCISES = {
    "Python编程基础": [
        # ==================== 选择题 (40题) ====================
        # --- 基本语法 (easy) ---
        {
            "title": "Python中以下哪个是合法的变量名？",
            "description": "Python中以下哪个是合法的变量名？\nA. 2name\nB. my-var\nC. _count\nD. class",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "变量命名规则",
            "solution": "C",
        },
        {
            "title": "以下哪个不是Python的基本数据类型？",
            "description": "以下哪个不是Python的基本数据类型？\nA. int\nB. float\nC. char\nD. bool",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "数据类型",
            "solution": "C",
        },
        {
            "title": "表达式 10 / 3 的结果类型是？",
            "description": "表达式 10 / 3 的结果类型是？\nA. int\nB. float\nC. str\nD. 取决于Python版本",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "运算符与类型转换",
            "solution": "B",
        },
        {
            "title": "以下哪个表达式的结果为True？",
            "description": "以下哪个表达式的结果为True？\nA. bool(0)\nB. bool('')\nC. bool([])\nD. bool(1)",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "布尔值与真值判断",
            "solution": "D",
        },
        {
            "title": "以下哪个是Python中的不可变数据类型？",
            "description": "以下哪个是Python中的不可变数据类型？\nA. list\nB. dict\nC. set\nD. tuple",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "可变与不可变类型",
            "solution": "D",
        },
        # --- 流程控制 (easy/medium) ---
        {
            "title": "以下代码的输出是什么？\nx = 10\nif x > 5:\n    print('A')\nelif x > 3:\n    print('B')\nelse:\n    print('C')",
            "description": "以下代码的输出是什么？\nx = 10\nif x > 5:\n    print('A')\nelif x > 3:\n    print('B')\nelse:\n    print('C')\n\nA. A\nB. B\nC. C\nD. A B",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "流程控制",
            "knowledge_point": "if/elif/else",
            "solution": "A",
        },
        {
            "title": "以下代码的输出是什么？\nfor i in range(5):\n    if i == 3:\n        break\n    print(i)",
            "description": "以下代码的输出是什么？\nfor i in range(5):\n    if i == 3:\n        break\n    print(i)\n\nA. 0 1 2\nB. 0 1 2 3\nC. 0 1 2 4\nD. 0 1 2 3 4",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "流程控制",
            "knowledge_point": "break语句",
            "solution": "A",
        },
        {
            "title": "以下代码的输出是什么？\nfor i in range(5):\n    if i == 3:\n        continue\n    print(i)",
            "description": "以下代码的输出是什么？\nfor i in range(5):\n    if i == 3:\n        continue\n    print(i)\n\nA. 0 1 2\nB. 0 1 2 3\nC. 0 1 2 4\nD. 0 1 2 3 4",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "流程控制",
            "knowledge_point": "continue语句",
            "solution": "C",
        },
        {
            "title": "while循环与for循环的主要区别是什么？",
            "description": "while循环与for循环的主要区别是什么？\nA. while循环更高效\nB. for循环只能遍历序列\nC. while循环基于条件，for循环基于迭代\nD. 没有区别",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "流程控制",
            "knowledge_point": "循环类型比较",
            "solution": "C",
        },
        {
            "title": "以下代码中else子句何时执行？\nfor i in range(3):\n    print(i)\nelse:\n    print('done')",
            "description": "以下代码中else子句何时执行？\nfor i in range(3):\n    print(i)\nelse:\n    print('done')\n\nA. 循环正常结束时\nB. 循环被break中断时\nC. 循环出错时\nD. 永远不执行",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "流程控制",
            "knowledge_point": "for-else语句",
            "solution": "A",
        },
        {
            "title": "range(1, 10, 2) 生成的序列是什么？",
            "description": "range(1, 10, 2) 生成的序列是什么？\nA. [1, 2, 3, 4, 5, 6, 7, 8, 9]\nB. [1, 3, 5, 7, 9]\nC. [2, 4, 6, 8]\nD. [1, 3, 5, 7, 9, 11]",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "流程控制",
            "knowledge_point": "range函数",
            "solution": "B",
        },
        {
            "title": "以下代码的输出是什么？\nresult = [x**2 for x in range(5) if x % 2 == 0]",
            "description": "以下代码的输出是什么？\nresult = [x**2 for x in range(5) if x % 2 == 0]\n\nA. [0, 4, 16]\nB. [0, 1, 4, 9, 16]\nC. [1, 9]\nD. [0, 2, 4]",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "流程控制",
            "knowledge_point": "列表推导式基础",
            "solution": "A",
        },
        # --- 数据结构 (easy/medium/hard) ---
        {
            "title": "以下代码的输出是什么？\ns = {1, 2, 3, 2, 1}\nprint(len(s))",
            "description": "以下代码的输出是什么？\ns = {1, 2, 3, 2, 1}\nprint(len(s))\n\nA. 5\nB. 3\nC. 4\nD. 报错",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "数据结构",
            "knowledge_point": "集合去重特性",
            "solution": "B",
        },
        {
            "title": "以下代码的输出是什么？\nd = {'a': 1, 'b': 2}\nprint(d.get('c', 3))",
            "description": "以下代码的输出是什么？\nd = {'a': 1, 'b': 2}\nprint(d.get('c', 3))\n\nA. None\nB. 报错\nC. 3\nD. 'c'",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "数据结构",
            "knowledge_point": "字典get方法",
            "solution": "C",
        },
        {
            "title": "元组和列表的核心区别是什么？",
            "description": "元组和列表的核心区别是什么？\nA. 元组可以存储不同类型数据\nB. 元组是不可变的\nC. 元组访问速度慢\nD. 元组不支持索引",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "数据结构",
            "knowledge_point": "元组与列表区别",
            "solution": "B",
        },
        {
            "title": "以下哪个操作的时间复杂度是O(1)？",
            "description": "对于列表lst，以下哪个操作的时间复杂度是O(1)？\nA. lst.append(x)\nB. lst.insert(0, x)\nC. lst.remove(x)\nD. x in lst",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "列表操作复杂度",
            "solution": "A",
        },
        {
            "title": "字典的键必须满足什么条件？",
            "description": "字典的键必须满足什么条件？\nA. 必须是字符串\nB. 必须是可哈希的\nC. 必须是整数\nD. 必须是可变类型",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "字典键的特性",
            "solution": "B",
        },
        {
            "title": "以下哪个方法会修改原列表？",
            "description": "以下哪个方法会修改原列表？\nA. sorted(lst)\nB. lst.sort()\nC. lst[::-1]\nD. list(map(str, lst))",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "列表方法",
            "solution": "B",
        },
        {
            "title": "以下代码的输出是什么？\ns1 = {1, 2, 3}\ns2 = {2, 3, 4}\nprint(s1 & s2)",
            "description": "以下代码的输出是什么？\ns1 = {1, 2, 3}\ns2 = {2, 3, 4}\nprint(s1 & s2)\n\nA. {1, 2, 3, 4}\nB. {2, 3}\nC. {1}\nD. {4}",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "集合运算",
            "solution": "B",
        },
        # --- 函数 (medium/hard) ---
        {
            "title": "*args和**kwargs分别接收什么类型的参数？",
            "description": "*args和**kwargs分别接收什么类型的参数？\nA. 都是列表\nB. 元组和字典\nC. 都是字典\nD. 列表和元组",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "函数",
            "knowledge_point": "可变参数",
            "solution": "B",
        },
        {
            "title": "以下代码的输出是什么？\nx = 10\ndef foo():\n    global x\n    x = 20\n\nfoo()\nprint(x)",
            "description": "以下代码的输出是什么？\nx = 10\ndef foo():\n    global x\n    x = 20\n\nfoo()\nprint(x)\n\nA. 10\nB. 20\nC. 报错\nD. None",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "函数",
            "knowledge_point": "global关键字与作用域",
            "solution": "B",
        },
        {
            "title": "lambda函数的特点是什么？",
            "description": "lambda函数的特点是什么？\nA. 可以包含多条语句\nB. 只能包含一个表达式\nC. 必须有名字\nD. 不能作为参数传递",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "函数",
            "knowledge_point": "lambda函数",
            "solution": "B",
        },
        {
            "title": "以下代码的输出是什么？\ndef outer():\n    x = 10\n    def inner():\n        return x\n    return inner\n\nf = outer()\nprint(f())",
            "description": "以下代码的输出是什么？\ndef outer():\n    x = 10\n    def inner():\n        return x\n    return inner\n\nf = outer()\nprint(f())\n\nA. 10\nB. None\nC. 报错\nD. <function>",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "函数",
            "knowledge_point": "闭包",
            "solution": "A",
        },
        {
            "title": "以下代码的输出是什么？\ndef func(a, b=[]):\n    b.append(a)\n    return b\n\nprint(func(1))\nprint(func(2))",
            "description": "以下代码的输出是什么？\ndef func(a, b=[]):\n    b.append(a)\n    return b\n\nprint(func(1))\nprint(func(2))\n\nA. [1] [2]\nB. [1] [1, 2]\nC. [1, 2] [1, 2]\nD. 报错",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "函数",
            "knowledge_point": "可变默认参数陷阱",
            "solution": "B",
        },
        # --- 面向对象 (easy/medium/hard) ---
        {
            "title": "__init__方法的作用是什么？",
            "description": "__init__方法的作用是什么？\nA. 定义类\nB. 初始化实例\nC. 销毁实例\nD. 复制实例",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "面向对象",
            "knowledge_point": "__init__方法",
            "solution": "B",
        },
        {
            "title": "以下代码中super()的作用是什么？\nclass Child(Parent):\n    def __init__(self):\n        super().__init__()",
            "description": "以下代码中super()的作用是什么？\nclass Child(Parent):\n    def __init__(self):\n        super().__init__()\n\nA. 创建父类实例\nB. 调用父类的方法\nC. 删除父类\nD. 替换父类",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "面向对象",
            "knowledge_point": "super()函数",
            "solution": "B",
        },
        {
            "title": "以下哪个是类方法的装饰器？",
            "description": "以下哪个是类方法的装饰器？\nA. @staticmethod\nB. @classmethod\nC. @property\nD. @abstractmethod",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "面向对象",
            "knowledge_point": "类方法与静态方法",
            "solution": "B",
        },
        {
            "title": "多态的含义是什么？",
            "description": "多态的含义是什么？\nA. 一个类有多个父类\nB. 同一接口可以有不同的实现\nC. 一个对象有多种状态\nD. 类可以动态创建",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "面向对象",
            "knowledge_point": "多态",
            "solution": "B",
        },
        {
            "title": "以下代码的输出是什么？\nclass A:\n    x = 1\n\na = A()\nb = A()\na.x = 2\nprint(b.x)",
            "description": "以下代码的输出是什么？\nclass A:\n    x = 1\n\na = A()\nb = A()\na.x = 2\nprint(b.x)\n\nA. 1\nB. 2\nC. None\nD. 报错",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "面向对象",
            "knowledge_point": "类属性与实例属性",
            "solution": "A",
        },
        # --- 异常处理 (easy/medium) ---
        {
            "title": "以下代码中finally块何时执行？",
            "description": "try/except/finally中finally块何时执行？\nA. 只在没有异常时\nB. 只在有异常时\nC. 无论是否有异常都会执行\nD. 永远不执行",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "异常处理",
            "knowledge_point": "finally语句",
            "solution": "C",
        },
        {
            "title": "如何捕获所有普通异常？",
            "description": "如何捕获所有普通异常？\nA. except:\nB. except Exception:\nC. except All:\nD. except BaseException:",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "异常处理",
            "knowledge_point": "异常捕获",
            "solution": "B",
        },
        # --- 文件操作 (easy) ---
        {
            "title": "以下哪个模式用于写入文件并覆盖原内容？",
            "description": "以下哪个模式用于写入文件并覆盖原内容？\nA. 'r'\nB. 'w'\nC. 'a'\nD. 'rb'",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "文件操作",
            "knowledge_point": "文件打开模式",
            "solution": "B",
        },
        # --- 模块和包 (medium) ---
        {
            "title": "__init__.py文件的作用是什么？",
            "description": "__init__.py文件的作用是什么？\nA. 定义主函数\nB. 标识目录为Python包\nC. 存储配置信息\nD. 初始化数据库",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "模块和包",
            "knowledge_point": "__init__.py",
            "solution": "B",
        },
        # --- 装饰器与生成器 (hard) ---
        {
            "title": "装饰器的本质是什么？",
            "description": "装饰器的本质是什么？\nA. 一个类\nB. 一个接收函数作为参数并返回新函数的函数\nC. 一个特殊的注释\nD. 一个语法糖，没有实际作用",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "装饰器",
            "knowledge_point": "装饰器本质",
            "solution": "B",
        },
        {
            "title": "yield关键字的作用是什么？",
            "description": "yield关键字的作用是什么？\nA. 终止函数\nB. 返回值并暂停函数执行\nC. 抛出异常\nD. 定义变量",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "生成器",
            "knowledge_point": "yield关键字",
            "solution": "B",
        },
        {
            "title": "生成器表达式和列表推导式的区别是什么？",
            "description": "生成器表达式和列表推导式的区别是什么？\nA. 语法完全不同\nB. 生成器惰性求值，列表推导式立即求值\nC. 列表推导式更省内存\nD. 生成器不能迭代",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "生成器",
            "knowledge_point": "生成器与列表推导式",
            "solution": "B",
        },
        {
            "title": "以下代码的输出是什么？\nresult = [i+j for i in range(3) for j in range(3)\n         if i == j]",
            "description": "以下代码的输出是什么？\nresult = [i+j for i in range(3) for j in range(3) if i == j]\n\nA. [0, 2, 4]\nB. [0, 1, 2, 1, 2, 3, 2, 3, 4]\nC. [0, 2]\nD. [0, 1, 2]",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "列表推导式",
            "knowledge_point": "嵌套列表推导式",
            "solution": "A",
        },
        {
            "title": "以下代码的输出是什么？\nlst = [1, 2, 3]\nlst2 = lst\nlst2.append(4)\nprint(len(lst))",
            "description": "以下代码的输出是什么？\nlst = [1, 2, 3]\nlst2 = lst\nlst2.append(4)\nprint(len(lst))\n\nA. 3\nB. 4\nC. 报错\nD. None",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "数据结构",
            "knowledge_point": "引用与赋值",
            "solution": "B",
        },
        {
            "title": "@property装饰器的作用是什么？",
            "description": "@property装饰器的作用是什么？\nA. 定义类方法\nB. 将方法转换为属性访问\nC. 定义静态方法\nD. 定义抽象方法",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "面向对象",
            "knowledge_point": "@property装饰器",
            "solution": "B",
        },
        {
            "title": "Python中is和==的区别是什么？",
            "description": "Python中is和==的区别是什么？\nA. is比较值，==比较类型\nB. is比较对象身份（内存地址），==比较值\nC. 没有区别\nD. is只能用于None",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "基本语法",
            "knowledge_point": "is与==的区别",
            "solution": "B",
        },

        # ==================== 编程题 (20题) ====================
        # --- 基本语法 (easy) ---
        {
            "title": "编写函数计算圆的面积",
            "description": "编写Python函数circle_area(radius)，计算圆的面积。\n\n参数：radius (float) - 圆的半径\n返回值：圆的面积 (float)，保留2位小数\n\n注意：如果半径为负数，抛出ValueError",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "函数定义与数学运算",
            "code_template": "import math\n\ndef circle_area(radius):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "5", "expected": "78.54"}, {"input": "1", "expected": "3.14"}, {"input": "-1", "expected": "ValueError"}]',
            "solution": "import math\n\ndef circle_area(radius):\n    if radius < 0:\n        raise ValueError('半径不能为负数')\n    return round(math.pi * radius ** 2, 2)",
            "hint": "使用math.pi获取圆周率，注意处理负数情况",
        },
        {
            "title": "编写函数实现温度转换",
            "description": "编写Python函数celsius_to_fahrenheit(celsius)，将摄氏度转换为华氏度。\n\n公式：F = C * 9/5 + 32\n返回值：华氏温度 (float)，保留1位小数",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "算术运算与类型转换",
            "code_template": "def celsius_to_fahrenheit(celsius):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "0", "expected": "32.0"}, {"input": "100", "expected": "212.0"}, {"input": "37", "expected": "98.6"}]',
            "solution": "def celsius_to_fahrenheit(celsius):\n    return round(celsius * 9 / 5 + 32, 1)",
            "hint": "直接套用公式，注意使用round保留小数",
        },
        # --- 流程控制 (easy/medium) ---
        {
            "title": "编写函数判断闰年",
            "description": "编写Python函数is_leap_year(year)，判断是否为闰年。\n\n闰年规则：\n- 能被4整除但不能被100整除\n- 或者能被400整除\n\n返回值：True或False",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "流程控制",
            "knowledge_point": "条件判断",
            "code_template": "def is_leap_year(year):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "2000", "expected": "True"}, {"input": "1900", "expected": "False"}, {"input": "2024", "expected": "True"}]',
            "solution": "def is_leap_year(year):\n    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)",
            "hint": "使用逻辑运算符组合条件",
        },
        {
            "title": "编写函数交换两个变量的值",
            "description": "编写Python函数swap(a, b)，交换两个变量的值并返回。\n\n返回值：元组 (b, a)",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "变量与元组解包",
            "code_template": "def swap(a, b):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": "[{\"input\": \"1, 2\", \"expected\": \"(2, 1)\"}, {\"input\": \"'hello', 'world'\", \"expected\": \"('world', 'hello')\"}]",
            "solution": "def swap(a, b):\n    return (b, a)",
            "hint": "使用元组解包",
        },
        {
            "title": "编写函数求列表平均值",
            "description": "编写Python函数average(numbers)，计算数字列表的平均值。\n\n参数：numbers - 非空数字列表\n返回值：平均值 (float)，保留2位小数\n\n如果列表为空，抛出ValueError",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "列表操作与数学运算",
            "code_template": "def average(numbers):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "[1, 2, 3, 4, 5]", "expected": "3.0"}, {"input": "[10, 20]", "expected": "15.0"}, {"input": "[]", "expected": "ValueError"}]',
            "solution": "def average(numbers):\n    if not numbers:\n        raise ValueError('列表不能为空')\n    return round(sum(numbers) / len(numbers), 2)",
            "hint": "使用sum()和len()函数",
        },
        {
            "title": "编写函数判断质数",
            "description": "编写Python函数is_prime(n)，判断一个正整数是否为质数。\n\n质数：大于1且只能被1和自身整除的数\n如果n小于1，抛出ValueError",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "流程控制",
            "knowledge_point": "循环与条件判断",
            "code_template": "def is_prime(n):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "2", "expected": "True"}, {"input": "4", "expected": "False"}, {"input": "17", "expected": "True"}, {"input": "1", "expected": "ValueError"}]',
            "solution": "def is_prime(n):\n    if n < 1:\n        raise ValueError('n必须为正整数')\n    if n < 2:\n        return False\n    if n == 2:\n        return True\n    if n % 2 == 0:\n        return False\n    for i in range(3, int(n**0.5) + 1, 2):\n        if n % i == 0:\n            return False\n    return True",
            "hint": "只需要检查到sqrt(n)即可",
        },
        {
            "title": "编写函数计算阶乘",
            "description": "编写Python函数factorial(n)，计算n的阶乘。\n\nn! = n * (n-1) * ... * 1\n0! = 1\n\n如果n为负数，抛出ValueError",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "流程控制",
            "knowledge_point": "循环与递归",
            "code_template": "def factorial(n):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "5", "expected": "120"}, {"input": "0", "expected": "1"}, {"input": "-1", "expected": "ValueError"}]',
            "solution": "def factorial(n):\n    if n < 0:\n        raise ValueError('n不能为负数')\n    if n <= 1:\n        return 1\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result",
            "hint": "可以使用循环或递归实现，注意边界条件",
        },
        # --- 数据结构 (medium) ---
        {
            "title": "编写函数统计字符出现次数",
            "description": "编写Python函数char_count(s)，统计字符串中每个字符出现的次数。\n\n返回值：字典，键为字符，值为出现次数\n忽略空格",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "字典操作",
            "code_template": "def char_count(s):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "\\"hello\\"", "expected": "{\\"h\\":1,\\"e\\":1,\\"l\\":2,\\"o\\":1}"}]',
            "solution": "def char_count(s):\n    result = {}\n    for char in s:\n        if char != ' ':\n            result[char] = result.get(char, 0) + 1\n    return result",
            "hint": "使用字典的get方法设置默认值",
        },
        {
            "title": "编写函数合并两个字典",
            "description": "编写Python函数merge_dicts(d1, d2)，合并两个字典。\n\n如果键重复，d2的值覆盖d1的值\n返回合并后的新字典，不修改原字典",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "字典合并",
            "code_template": "def merge_dicts(d1, d2):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "{\\"a\\":1,\\"b\\":2}, {\\"b\\":3,\\"c\\":4}", "expected": "{\\"a\\":1,\\"b\\":3,\\"c\\":4}"}]',
            "solution": "def merge_dicts(d1, d2):\n    result = d1.copy()\n    result.update(d2)\n    return result",
            "hint": "使用字典的copy和update方法，或使用解包运算符 **",
        },
        # --- 函数 (medium/hard) ---
        {
            "title": "编写函数实现斐波那契数列",
            "description": "编写Python函数fibonacci(n)，返回斐波那契数列的第n项。\n\n斐波那契数列：0, 1, 1, 2, 3, 5, 8, 13, ...\nF(0) = 0, F(1) = 1, F(n) = F(n-1) + F(n-2)\n\n如果n为负数，抛出ValueError",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "函数",
            "knowledge_point": "递归与动态规划",
            "code_template": "def fibonacci(n):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "0", "expected": "0"}, {"input": "1", "expected": "1"}, {"input": "10", "expected": "55"}]',
            "solution": "def fibonacci(n):\n    if n < 0:\n        raise ValueError('n不能为负数')\n    if n <= 1:\n        return n\n    a, b = 0, 1\n    for _ in range(2, n + 1):\n        a, b = b, a + b\n    return b",
            "hint": "使用迭代方式避免递归的性能问题，用两个变量交替更新",
        },
        {
            "title": "编写函数实现简单柯里化",
            "description": "编写Python函数simple_curry(func)，实现两参数函数的柯里化。\n\n示例：\ndef add(a, b): return a + b\ncurried_add = simple_curry(add)\ncurried_add(1)(2) 应返回 3",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "函数",
            "knowledge_point": "高阶函数与闭包",
            "code_template": "def simple_curry(func):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "simple_curry(lambda a,b: a+b)(1)(2)", "expected": "3"}]',
            "solution": "def simple_curry(func):\n    def inner(a):\n        def inner2(b):\n            return func(a, b)\n        return inner2\n    return inner",
            "hint": "返回嵌套函数，每层接收一个参数",
        },
        # --- 面向对象 (medium/hard) ---
        {
            "title": "编写栈类",
            "description": "编写Python类Stack，实现栈数据结构。\n\n方法：\n- push(item): 压入元素\n- pop(): 弹出元素，栈空抛出IndexError\n- peek(): 查看栈顶元素，不弹出\n- is_empty(): 判断是否为空\n- size(): 返回元素数量",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "面向对象",
            "knowledge_point": "类的定义与实现",
            "code_template": "class Stack:\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "s=Stack(); s.push(1); s.push(2); s.pop()", "expected": "2"}, {"input": "s=Stack(); s.push(1); s.is_empty()", "expected": "False"}]',
            "solution": "class Stack:\n    def __init__(self):\n        self._items = []\n    \n    def push(self, item):\n        self._items.append(item)\n    \n    def pop(self):\n        if self.is_empty():\n            raise IndexError('栈为空')\n        return self._items.pop()\n    \n    def peek(self):\n        if self.is_empty():\n            raise IndexError('栈为空')\n        return self._items[-1]\n    \n    def is_empty(self):\n        return len(self._items) == 0\n    \n    def size(self):\n        return len(self._items)",
            "hint": "使用列表作为底层存储，append和pop模拟栈操作",
        },
        {
            "title": "编写动物类继承体系",
            "description": "编写Python类Animal、Dog、Cat，实现继承体系。\n\nAnimal基类：\n- 属性：name, age\n- 方法：speak() 返回 '...'，info() 返回信息字符串\n\nDog(Animal)：\n- 重写speak() 返回 'Woof!'\n\nCat(Animal)：\n- 重写speak() 返回 'Meow!'",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "面向对象",
            "knowledge_point": "继承与多态",
            "code_template": "class Animal:\n    # 请在此处编写代码\n    pass\n\nclass Dog(Animal):\n    # 请在此处编写代码\n    pass\n\nclass Cat(Animal):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "Dog(\\"Rex\\", 3).speak()", "expected": "Woof!"}, {"input": "Cat(\\"Kitty\\", 2).speak()", "expected": "Meow!"}]',
            "solution": "class Animal:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    \n    def speak(self):\n        return '...'\n    \n    def info(self):\n        return f'{self.name}, {self.age}岁'\n\nclass Dog(Animal):\n    def speak(self):\n        return 'Woof!'\n\nclass Cat(Animal):\n    def speak(self):\n        return 'Meow!'",
            "hint": "子类继承父类，重写speak方法实现多态",
        },
        {
            "title": "编写单例模式装饰器",
            "description": "编写Python装饰器singleton，实现单例模式。\n\n单例模式：一个类只能创建一个实例\n\n示例：\n@singleton\nclass MyClass:\n    pass\n\na = MyClass()\nb = MyClass()\na is b 应返回 True",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "面向对象",
            "knowledge_point": "设计模式与装饰器",
            "code_template": "def singleton(cls):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "MyClass() is MyClass()", "expected": "True"}]',
            "solution": "def singleton(cls):\n    instances = {}\n    def get_instance(*args, **kwargs):\n        if cls not in instances:\n            instances[cls] = cls(*args, **kwargs)\n        return instances[cls]\n    return get_instance",
            "hint": "使用字典缓存已创建的实例",
        },
        # --- 异常处理 (medium/hard) ---
        {
            "title": "编写安全的除法函数",
            "description": "编写Python函数safe_divide(a, b)，实现安全的除法。\n\n处理以下异常：\n- ZeroDivisionError: 返回 'Error: Division by zero'\n- TypeError: 返回 'Error: Invalid input type'\n\n正常情况返回除法结果（float）",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "异常处理",
            "knowledge_point": "异常捕获与处理",
            "code_template": "def safe_divide(a, b):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "10, 2", "expected": "5.0"}, {"input": "10, 0", "expected": "Error: Division by zero"}, {"input": "10, \\"a\\"", "expected": "Error: Invalid input type"}]',
            "solution": "def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return 'Error: Division by zero'\n    except TypeError:\n        return 'Error: Invalid input type'",
            "hint": "使用try/except捕获特定异常，分别处理",
        },
        {
            "title": "编写函数实现重试机制",
            "description": "编写Python函数retry(func, max_attempts=3)，实现重试机制。\n\n参数：\n- func: 要执行的无参函数\n- max_attempts: 最大重试次数，默认3\n\n如果func执行成功，返回结果\n如果func抛出异常，重试直到成功或达到最大次数\n达到最大次数仍失败，抛出最后一次的异常",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "异常处理",
            "knowledge_point": "重试机制与异常处理",
            "code_template": "def retry(func, max_attempts=3):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "lambda: 1/1, max_attempts=3", "expected": "1"}, {"input": "lambda: 1/0, max_attempts=3", "expected": "ZeroDivisionError"}]',
            "solution": "def retry(func, max_attempts=3):\n    last_exception = None\n    for _ in range(max_attempts):\n        try:\n            return func()\n        except Exception as e:\n            last_exception = e\n    raise last_exception",
            "hint": "使用for循环和try/except，用变量记录最后一次异常",
        },
        # --- 文件操作 (medium) ---
        {
            "title": "编写函数读取文本文件行数",
            "description": "编写Python函数count_lines(filepath)，统计文本文件的行数。\n\n如果文件不存在，抛出FileNotFoundError\n返回文件的行数（int）",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文件操作",
            "knowledge_point": "文件读取",
            "code_template": "def count_lines(filepath):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "\\"test.txt\\"", "expected": "文件行数（int）"}]',
            "solution": "def count_lines(filepath):\n    with open(filepath, 'r', encoding='utf-8') as f:\n        return sum(1 for _ in f)",
            "hint": "使用with语句打开文件，逐行遍历计数",
        },
        {
            "title": "编写函数写入JSON文件",
            "description": "编写Python函数write_json(filepath, data)，将数据写入JSON文件。\n\n参数：\n- filepath: 文件路径\n- data: 要写入的数据（字典或列表）\n\n要求：\n- 缩进为2个空格\n- 支持中文（ensure_ascii=False）\n- 如果文件已存在，覆盖",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "文件操作",
            "knowledge_point": "JSON文件写入",
            "code_template": "import json\n\ndef write_json(filepath, data):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "\\"test.json\\", {\\"name\\": \\"test\\"}", "expected": "写入成功，文件内容包含中文"}]',
            "solution": "import json\n\ndef write_json(filepath, data):\n    with open(filepath, 'w', encoding='utf-8') as f:\n        json.dump(data, f, ensure_ascii=False, indent=2)",
            "hint": "使用json.dump的ensure_ascii和indent参数",
        },
        # --- 列表推导式 (medium) ---
        {
            "title": "编写函数使用推导式处理数据",
            "description": "编写Python函数filter_and_square(items, threshold)，使用列表推导式。\n\n参数：\n- items: 数字列表\n- threshold: 阈值\n\n功能：\n1. 筛选出大于threshold的数\n2. 将这些数平方\n3. 返回排序后的结果",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "列表推导式",
            "knowledge_point": "列表推导式应用",
            "code_template": "def filter_and_square(items, threshold):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "[1, 5, 3, 8, 2, 7], 4", "expected": "[25, 49, 64]"}]',
            "solution": "def filter_and_square(items, threshold):\n    return sorted([x**2 for x in items if x > threshold])",
            "hint": "在一个列表推导式中同时完成筛选和转换",
        },
        # --- 生成器 (hard) ---
        {
            "title": "编写生成器实现无限序列",
            "description": "编写Python生成器函数infinite_sequence(start=0, step=1)，生成无限整数序列。\n\n参数：\n- start: 起始值\n- step: 步长\n\n每次next()返回序列中的下一个数",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "生成器",
            "knowledge_point": "生成器函数",
            "code_template": "def infinite_sequence(start=0, step=1):\n    # 请在此处编写代码\n    pass\n",
            "test_cases": '[{"input": "start=1, step=2, 取前3个", "expected": "[1, 3, 5]"}]',
            "solution": "def infinite_sequence(start=0, step=1):\n    current = start\n    while True:\n        yield current\n        current += step",
            "hint": "使用while True循环配合yield，每次yield后更新current",
        },

        # ==================== 简答题 (30题) ====================
        # --- 基本语法 (easy) ---
        {
            "title": "请解释Python中的变量命名规则",
            "description": "请详细解释：\n1. Python变量命名的基本规则是什么？\n2. 有哪些命名约定（如蛇形命名法）？\n3. 为什么不能使用保留字作为变量名？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "变量命名规则",
            "solution": "1. Python变量命名规则：\n- 必须以字母或下划线开头\n- 只能包含字母、数字和下划线\n- 区分大小写\n- 不能使用Python保留字（如if、for、class等）\n\n2. 命名约定：\n- 变量和函数：蛇形命名法（snake_case），如my_variable\n- 类名：驼峰命名法（PascalCase），如MyClass\n- 常量：全大写，如MAX_VALUE\n- 私有属性：单下划线前缀，如_private\n\n3. 保留字有特殊语法含义，使用会导致语法错误。",
        },
        {
            "title": "请解释Python中的数据类型",
            "description": "请详细解释Python中的主要数据类型：\n1. 数值类型（int、float、complex）\n2. 序列类型（str、list、tuple）\n3. 映射类型（dict）\n4. 集合类型（set、frozenset）\n5. 布尔类型（bool）\n6. None类型",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "数据类型",
            "solution": "1. 数值类型：int（整数）、float（浮点数）、complex（复数）\n\n2. 序列类型：\n- str：字符串，不可变\n- list：列表，可变\n- tuple：元组，不可变\n\n3. 映射类型：dict字典，键值对结构，键必须可哈希\n\n4. 集合类型：set（可变）、frozenset（不可变），元素唯一\n\n5. 布尔类型：bool，True或False\n\n6. NoneType：只有None一个值，表示空值",
        },
        {
            "title": "请解释Python中的运算符",
            "description": "请详细解释Python中的运算符类型：\n1. 算术运算符\n2. 比较运算符\n3. 逻辑运算符\n4. 赋值运算符\n5. 成员运算符\n6. 身份运算符",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "运算符",
            "solution": "1. 算术运算符：+、-、*、/、//（整除）、%（取模）、**（幂）\n2. 比较运算符：==、!=、>、<、>=、<=\n3. 逻辑运算符：and、or、not\n4. 赋值运算符：=、+=、-=、*=、/=等\n5. 成员运算符：in、not in\n6. 身份运算符：is、is not\n\n注意：/返回浮点数，//返回整数；is比较对象身份，==比较值。",
        },
        # --- 流程控制 (easy/medium) ---
        {
            "title": "请解释Python中的条件语句",
            "description": "请详细解释：\n1. if/elif/else的语法和用法\n2. 三元表达式\n3. 条件表达式的真值判断\n4. 常见的条件判断陷阱",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "流程控制",
            "knowledge_point": "条件语句",
            "solution": "1. if/elif/else语法：按顺序检查条件，执行第一个满足条件的代码块\n\n2. 三元表达式：x = 值1 if 条件 else 值2\n\n3. 真值判断：False值包括None、False、0、0.0、''、[]、{}、set()，其他值都为True\n\n4. 常见陷阱：\n- =（赋值）和==（比较）混淆\n- 多条件时注意逻辑运算符优先级\n- 浮点数比较应使用math.isclose()\n- 链式比较如 1 < x < 10",
        },
        {
            "title": "请解释Python中的循环语句",
            "description": "请详细解释：\n1. for循环的语法和用法\n2. while循环的语法和用法\n3. range()函数\n4. break、continue、else的用法\n5. 循环中的常见模式",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "流程控制",
            "knowledge_point": "循环语句",
            "solution": "1. for循环：遍历可迭代对象中的每个元素\n2. while循环：当条件为True时持续执行\n3. range()：生成整数序列，支持start/stop/step参数\n4. 控制语句：\n- break：跳出整个循环\n- continue：跳过本次迭代\n- else：循环正常结束时执行（未被break中断）\n5. 常见模式：\n- enumerate()：同时获取索引和值\n- zip()：并行遍历多个序列\n- for-else：搜索模式",
        },
        {
            "title": "请解释列表推导式和生成器表达式",
            "description": "请详细解释：\n1. 列表推导式的语法\n2. 带条件的列表推导式\n3. 嵌套列表推导式\n4. 字典推导式和集合推导式\n5. 生成器表达式",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "列表推导式",
            "knowledge_point": "推导式",
            "solution": "1. 列表推导式：[表达式 for 变量 in 可迭代对象]\n2. 带条件：[表达式 for 变量 in 可迭代对象 if 条件]\n3. 嵌套：[表达式 for x in 序列1 for y in 序列2]\n4. 字典推导式：{键: 值 for 变量 in 可迭代对象}\n   集合推导式：{表达式 for 变量 in 可迭代对象}\n5. 生成器表达式：(表达式 for 变量 in 可迭代对象)，惰性求值\n\n优点：简洁、可读性好、性能通常优于等价的for循环",
        },
        # --- 数据结构 (medium/hard) ---
        {
            "title": "请比较Python中的四种数据结构",
            "description": "请比较列表、元组、字典、集合的特点：\n1. 可变性\n2. 有序性\n3. 元素要求\n4. 访问方式\n5. 使用场景",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "数据结构比较",
            "solution": "1. 列表(list)：可变、有序、任意类型元素、索引访问、适合频繁修改的有序集合\n2. 元组(tuple)：不可变、有序、任意类型元素、索引访问、适合不可变数据和函数返回值\n3. 字典(dict)：可变、有序(Python3.7+)、键必须可哈希、键访问、适合键值对映射\n4. 集合(set)：可变、无序、元素可哈希且唯一、成员运算、适合去重和集合运算",
        },
        {
            "title": "请解释深拷贝和浅拷贝",
            "description": "请详细解释：\n1. 什么是浅拷贝？\n2. 什么是深拷贝？\n3. 它们的区别是什么？\n4. 如何实现？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "深拷贝与浅拷贝",
            "solution": "1. 浅拷贝：创建新对象，但内部元素仍引用原对象中的可变元素\n2. 深拷贝：递归复制所有层级的对象，完全独立\n3. 区别：对于不可变元素效果相同；对于嵌套的可变元素，深拷贝更安全\n4. 实现：\n- 浅拷贝：copy()、list()、切片[:]、copy.copy()\n- 深拷贝：copy.deepcopy()",
        },
        {
            "title": "请解释Python中字符串的常用操作",
            "description": "请详细解释：\n1. 字符串是可变还是不可变的？\n2. 常用方法（split、join、strip、replace等）\n3. 格式化方式（f-string、format、%）\n4. 切片操作",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "数据结构",
            "knowledge_point": "字符串操作",
            "solution": "1. 字符串是不可变的，修改会创建新字符串\n2. 常用方法：\n- split(sep)：按分隔符分割\n- join(iterable)：连接序列\n- strip()：去除首尾空白\n- replace(old, new)：替换\n- find/index：查找子串\n3. 格式化：f-string（推荐）、str.format()、%运算符\n4. 切片：s[start:stop:step]，支持负索引",
        },
        # --- 函数 (medium/hard) ---
        {
            "title": "请解释Python中的作用域",
            "description": "请详细解释：\n1. LEGB规则\n2. 局部作用域\n3. 闭包（嵌套）作用域\n4. 全局作用域\n5. 内置作用域\n6. global和nonlocal关键字",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "函数",
            "knowledge_point": "作用域",
            "solution": "LEGB规则（查找顺序）：\n1. Local（局部）：函数内部定义的变量\n2. Enclosing（闭包）：外层函数中的变量\n3. Global（全局）：模块级别定义的变量\n4. Built-in（内置）：Python内置的名称\n\nglobal关键字：在函数内声明使用全局变量\nnonlocal关键字：在嵌套函数内声明使用外层函数变量",
        },
        {
            "title": "请解释装饰器",
            "description": "请详细解释：\n1. 什么是装饰器？\n2. 装饰器的语法\n3. 如何编写简单装饰器？\n4. 带参数的装饰器\n5. functools.wraps的作用",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "装饰器",
            "knowledge_point": "装饰器",
            "solution": "1. 装饰器：接收函数作为参数，返回新函数的高阶函数，本质是闭包的应用\n2. 语法：@decorator 等价于 func = decorator(func)\n3. 编写：def decorator(func): def wrapper(*args, **kwargs): ... return wrapper\n4. 带参数：三层嵌套，外层接收参数，中层接收函数，内层是wrapper\n5. functools.wraps：保留原函数的元信息（__name__、__doc__等）",
        },
        {
            "title": "请解释闭包",
            "description": "请详细解释：\n1. 什么是闭包？\n2. 闭包的条件\n3. 闭包的应用场景\n4. 闭包的注意事项",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "函数",
            "knowledge_point": "闭包",
            "solution": "1. 闭包：内层函数引用了外层函数的变量，即使外层函数执行完毕，内层函数仍能访问这些变量\n2. 条件：有嵌套函数、内层引用外层变量、外层返回内层函数\n3. 应用：装饰器、回调函数、数据封装、函数工厂\n4. 注意：循环中的闭包陷阱（变量引用而非值拷贝）、可能导致内存泄漏",
        },
        # --- 面向对象 (medium/hard) ---
        {
            "title": "请解释面向对象的三大特性",
            "description": "请详细解释面向对象编程的三大特性：\n1. 封装\n2. 继承\n3. 多态\n\n并举例说明在Python中的实现。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "面向对象",
            "knowledge_point": "面向对象特性",
            "solution": "1. 封装：将数据和方法绑定，隐藏实现细节。Python通过_前缀和@property实现\n2. 继承：子类继承父类属性和方法，实现代码复用。支持单继承和多继承\n3. 多态：同一接口不同实现。Python通过鸭子类型和方法重写实现，不需要显式接口",
        },
        {
            "title": "请解释魔术方法（dunder methods）",
            "description": "请解释Python中常用的魔术方法：\n1. __init__和__new__\n2. __str__和__repr__\n3. __len__\n4. __getitem__和__setitem__\n5. __eq__、__lt__等比较方法",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "面向对象",
            "knowledge_point": "魔术方法",
            "solution": "1. __new__创建实例，__init__初始化实例\n2. __str__用户友好（print），__repr__开发者友好（交互环境）\n3. __len__实现len()函数\n4. __getitem__/__setitem__实现索引操作obj[key]\n5. 比较方法：__eq__(==)、__lt__(<)、__gt__(>)等，可用@functools.total_ordering简化",
        },
        {
            "title": "请解释Python中的属性访问控制",
            "description": "请详细解释：\n1. 公有属性\n2. 受保护属性（单下划线）\n3. 私有属性（双下划线）\n4. @property装饰器\n5. 描述符协议",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "面向对象",
            "knowledge_point": "属性访问控制",
            "solution": "1. 公有属性：无前缀，任何地方可访问\n2. 受保护属性（_var）：约定不外部访问，但无强制限制\n3. 私有属性（__var）：名称改写为_ClassName__var，外部不能直接访问\n4. @property：将方法伪装为属性，实现getter/setter\n5. 描述符：实现__get__/__set__/__delete__的类，是property的底层机制",
        },
        # --- 异常处理 (medium/hard) ---
        {
            "title": "请解释异常处理机制",
            "description": "请详细解释：\n1. try/except/else/finally的用法\n2. 异常的层次结构\n3. 自定义异常\n4. 异常链\n5. 最佳实践",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "异常处理",
            "knowledge_point": "异常处理",
            "solution": "1. try：可能出错的代码；except：捕获异常；else：无异常时执行；finally：总执行\n2. 层次：BaseException > Exception > ValueError/TypeError等\n3. 自定义：class MyError(Exception): pass\n4. 异常链：raise NewError() from original_error\n5. 实践：捕获具体异常、避免裸except、用finally释放资源、记录异常信息",
        },
        {
            "title": "请解释上下文管理器",
            "description": "请详细解释：\n1. 什么是上下文管理器？\n2. with语句的工作原理\n3. __enter__和__exit__方法\n4. contextlib.contextmanager装饰器\n5. 应用场景",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "异常处理",
            "knowledge_point": "上下文管理器",
            "solution": "1. 上下文管理器：实现__enter__和__exit__的对象，用于资源管理\n2. with语句：调用__enter__获取资源 -> 执行代码块 -> 调用__exit__释放资源\n3. __enter__返回值赋给as变量；__exit__处理异常，返回True则抑制异常\n4. @contextmanager：用yield简化，yield前是__enter__，yield后是__exit__\n5. 应用：文件、数据库连接、线程锁、临时修改环境",
        },
        # --- 文件操作 (medium) ---
        {
            "title": "请解释文件操作",
            "description": "请详细解释：\n1. 文件打开模式（r、w、a、rb、wb等）\n2. with语句的优势\n3. 文件读取方法（read、readline、readlines）\n4. 文件写入方法（write、writelines）\n5. 文件指针操作（seek、tell）",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文件操作",
            "knowledge_point": "文件操作",
            "solution": "1. 模式：r（只读）、w（写入覆盖）、a（追加）、r+（读写）、rb/wb（二进制）\n2. with语句：自动关闭文件，即使发生异常也能正确释放资源\n3. 读取：read()全部、readline()一行、readlines()所有行列表\n4. 写入：write(string)、writelines(lines)\n5. 指针：seek(offset)移动、tell()获取当前位置",
        },
        {
            "title": "请解释Python中处理CSV和JSON文件",
            "description": "请详细解释：\n1. csv模块的使用（reader、writer、DictReader、DictWriter）\n2. json模块的使用（dump、load、dumps、loads）\n3. 两者的区别和适用场景",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "文件操作",
            "knowledge_point": "CSV与JSON处理",
            "solution": "1. csv模块：\n- reader：按行读取为列表\n- DictReader：按行读取为字典\n- writer/DictWriter：写入CSV\n\n2. json模块：\n- dump/load：文件对象\n- dumps/loads：字符串\n- indent格式化、ensure_ascii中文支持\n\n3. 区别：CSV适合表格数据、简单；JSON适合嵌套结构、支持更多数据类型",
        },
        # --- 模块和包 (medium) ---
        {
            "title": "请解释模块和包",
            "description": "请详细解释：\n1. 什么是模块？\n2. 什么是包？\n3. __init__.py的作用\n4. 导入方式\n5. __name__和__main__\n6. 模块搜索路径",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "模块和包",
            "knowledge_point": "模块和包",
            "solution": "1. 模块：一个.py文件就是一个模块\n2. 包：包含__init__.py的目录，可含子包和模块\n3. __init__.py：标识为包，可含初始化代码（Python3.3+可选）\n4. 导入：import module、from module import name、from package import module\n5. __name__：直接运行为'__main__'，被导入时为模块名\n6. 搜索路径：sys.path（当前目录、PYTHONPATH、标准库、第三方包）",
        },
        {
            "title": "请解释Python的包管理工具pip",
            "description": "请详细解释：\n1. pip的基本命令（install、uninstall、list、freeze）\n2. requirements.txt的作用\n3. 虚拟环境（venv）的概念和用途\n4. 包的版本管理",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "模块和包",
            "knowledge_point": "包管理",
            "solution": "1. pip命令：install安装、uninstall卸载、list列出、freeze导出依赖\n2. requirements.txt：记录项目依赖，pip install -r requirements.txt批量安装\n3. 虚拟环境：\n- 隔离项目依赖\n- python -m venv myenv 创建\n- source myenv/bin/activate 激活（Windows: myenv\\Scripts\\activate）\n4. 版本管理：==固定版本、>=最低版本、~=兼容版本",
        },
        # --- 生成器 (hard) ---
        {
            "title": "请解释生成器",
            "description": "请详细解释：\n1. 什么是生成器？\n2. 生成器函数和生成器表达式\n3. yield关键字的工作原理\n4. 生成器的优势\n5. 生成器的应用场景",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "生成器",
            "knowledge_point": "生成器",
            "solution": "1. 生成器：特殊的迭代器，惰性求值，按需生成数据\n2. 两种形式：生成器函数（含yield）、生成器表达式（()语法）\n3. yield原理：遇到yield暂停并返回值，再次调用时从暂停处继续\n4. 优势：内存高效（不一次生成全部）、支持无限序列\n5. 应用：大数据处理、无限序列、管道式数据处理、协程",
        },
        {
            "title": "请解释迭代器协议",
            "description": "请详细解释：\n1. 什么是迭代器？\n2. 可迭代对象和迭代器的区别\n3. __iter__和__next__方法\n4. for循环的工作原理\n5. StopIteration异常",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "生成器",
            "knowledge_point": "迭代器协议",
            "solution": "1. 迭代器：实现__iter__和__next__的对象，记住遍历位置\n2. 区别：可迭代对象有__iter__返回迭代器；迭代器有__next__返回下一值\n3. __iter__()返回自身；__next__()返回下一值或抛出StopIteration\n4. for循环原理：调用iter()获取迭代器，循环调用next()，捕获StopIteration结束\n5. StopIteration：迭代结束信号，for循环自动处理",
        },
        # --- 综合 (hard) ---
        {
            "title": "请解释Python的内存管理和垃圾回收",
            "description": "请详细解释：\n1. Python的内存管理机制\n2. 引用计数\n3. 垃圾回收（循环引用）\n4. 内存池\n5. 常见的内存泄漏场景",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "基本语法",
            "knowledge_point": "内存管理",
            "solution": "1. 内存管理：私有堆空间，Python内存管理器自动管理\n2. 引用计数：对象引用数为0时销毁，sys.getrefcount()查看\n3. 垃圾回收：分代回收处理循环引用，gc模块控制\n4. 内存池：小对象使用pymalloc，避免频繁系统调用\n5. 泄漏场景：循环引用、全局变量持有大对象、未关闭资源、缓存未清理",
        },
        {
            "title": "请解释GIL（全局解释器锁）",
            "description": "请详细解释：\n1. 什么是GIL？\n2. GIL的作用\n3. GIL对多线程的影响\n4. 如何规避GIL的限制\n5. 多线程vs多进程",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "模块和包",
            "knowledge_point": "GIL",
            "solution": "1. GIL：CPython的全局解释器锁，同一时刻只有一个线程执行字节码\n2. 作用：保护Python对象，简化内存管理\n3. 影响：CPU密集型无法利用多核，I/O密集型影响较小\n4. 规避：多进程、C扩展（NumPy）、其他实现（PyPy）\n5. 对比：多线程适合I/O密集型，多进程适合CPU密集型",
        },
        # --- 编码规范 (easy/medium) ---
        {
            "title": "请解释Python的编码规范PEP 8",
            "description": "请详细解释PEP 8编码规范的主要内容：\n1. 缩进和行长\n2. 命名约定\n3. 空行和空格\n4. 注释规范",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "编码规范",
            "knowledge_point": "PEP 8",
            "solution": "1. 缩进和行长：\n- 使用4个空格缩进，不用Tab\n- 每行最多79字符\n- 换行时使用反斜杠或括号\n\n2. 命名约定：\n- 变量/函数：snake_case\n- 类：CamelCase\n- 常量：UPPER_CASE\n- 私有：_前缀\n\n3. 空行和空格：\n- 顶级定义间空2行\n- 方法定义间空1行\n- 运算符两侧加空格\n\n4. 注释：\n- 行内注释前2个空格\n- 文档字符串用三引号",
        },
        {
            "title": "请解释Python中的常用内置函数",
            "description": "请详细解释Python中的常用内置函数：\n1. 数学相关（abs、round、min、max、sum）\n2. 类型转换（int、float、str、list、dict）\n3. 序列相关（len、range、enumerate、zip、map、filter）\n4. 其他（print、input、type、isinstance）",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "基本语法",
            "knowledge_point": "内置函数",
            "solution": "1. 数学相关：\n- abs(x)：绝对值\n- round(x, n)：四舍五入\n- min/max：最小/最大值\n- sum(iterable)：求和\n\n2. 类型转换：\n- int()、float()、str()、list()、dict()、set()、bool()\n\n3. 序列相关：\n- len()：长度\n- range()：整数序列\n- enumerate()：带索引遍历\n- zip()：并行遍历\n- map(func, iterable)：映射\n- filter(func, iterable)：过滤\n\n4. 其他：\n- print()：输出\n- input()：输入\n- type()：返回类型\n- isinstance()：判断类型",
        },
        {
            "title": "请解释Python中的正则表达式",
            "description": "请详细解释：\n1. re模块的基本使用\n2. 常用正则语法（.、*、+、?、[]、\\d、\\w等）\n3. 常用函数（match、search、findall、sub）\n4. 分组和捕获\n5. 贪婪与非贪婪匹配",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "高级特性",
            "knowledge_point": "正则表达式",
            "solution": "1. re模块：import re\n\n2. 常用语法：\n- .：任意字符\n- *：0次或多次\n- +：1次或多次\n- ?：0次或1次\n- []：字符集\n- \\d：数字[0-9]\n- \\w：字母数字下划线\n- \\s：空白字符\n- ^：开头\n- $：结尾\n\n3. 常用函数：\n- re.match()：从开头匹配\n- re.search()：搜索第一个匹配\n- re.findall()：查找所有匹配\n- re.sub()：替换\n- re.split()：分割\n\n4. 分组：用()分组，group(1)获取\n\n5. 贪婪/非贪婪：*?、+?、??表示非贪婪",
        },
        {
            "title": "请解释Python中的类型注解",
            "description": "请详细解释：\n1. 什么是类型注解？\n2. 函数参数和返回值的类型注解\n3. 变量的类型注解\n4. typing模块的常用类型（List、Dict、Optional、Union等）\n5. 类型检查工具（mypy）",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "高级特性",
            "knowledge_point": "类型注解",
            "solution": "1. 类型注解：Python 3.5+引入，为变量和函数添加类型提示\n\n2. 函数注解：\ndef func(a: int, b: str) -> bool:\n    ...\n\n3. 变量注解：\nx: int = 10\nname: str = 'hello'\n\n4. typing模块：\n- List[int]：整数列表\n- Dict[str, int]：字符串到整数的字典\n- Optional[int]：int或None\n- Union[int, str]：int或str\n- Tuple[int, ...]：元组\n- Callable[[int], str]：函数类型\n\n5. mypy：静态类型检查工具，pip install mypy",
        },
        {
            "title": "请解释Python中的异步编程",
            "description": "请详细解释：\n1. 同步和异步的区别\n2. async/await语法\n3. asyncio模块的基本使用\n4. 协程的概念\n5. 异步编程的适用场景",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "高级特性",
            "knowledge_point": "异步编程",
            "solution": "1. 同步vs异步：\n- 同步：顺序执行，阻塞等待\n- 异步：非阻塞，遇到等待时切换执行其他任务\n\n2. async/await：\nasync def func():\n    await asyncio.sleep(1)\n    return 'done'\n\n3. asyncio使用：\n- asyncio.run(func())：运行协程\n- asyncio.gather(*tasks)：并发运行\n- asyncio.create_task()：创建任务\n\n4. 协程：\n- 使用async def定义\n- await暂停执行等待结果\n- 事件循环调度\n\n5. 适用场景：\n- I/O密集型任务\n- 网络请求\n- 高并发Web服务\n- 不适合CPU密集型",
        },
    ]
}
