# -*- coding: utf-8 -*-
"""
软件测试基础 - 学习路径 ID=1
知识点: 测试定义、测试原则、测试级别、测试类型、SDLC/STLC、黑盒白盒测试
题目数量: 90题 (选择题40 + 编程题20 + 简答题30)
难度分布: easy 30% + medium 50% + hard 20%
"""

EXERCISES = {
    "软件测试基础理论": [
        # ==================== 选择题 (40题) ====================
        # --- 测试定义与概念 (easy) ---
        {
            "title": "以下关于软件测试的定义，正确的是：",
            "description": "以下关于软件测试的定义，正确的是：\nA. 软件测试是为了证明软件没有缺陷\nB. 软件测试是为了发现软件中的缺陷而执行程序的过程\nC. 软件测试只能在开发完成后进行\nD. 软件测试等同于调试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试定义与概念",
            "knowledge_point": "软件测试的定义",
            "solution": "B",
        },
        {
            "title": "软件测试的根本目的是：",
            "description": "软件测试的根本目的是：\nA. 发现尽可能多的缺陷\nB. 证明软件满足需求\nC. 提高软件质量，降低风险\nD. 完成测试任务",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试定义与概念",
            "knowledge_point": "软件测试的目的",
            "solution": "C",
        },
        {
            "title": "以下哪项不属于软件测试的基本原则？",
            "description": "以下哪项不属于软件测试的基本原则？\nA. 测试显示缺陷的存在\nB. 穷尽测试是不可能的\nC. 缺陷集群效应\nD. 测试可以证明软件没有缺陷",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试原则",
            "knowledge_point": "软件测试原则",
            "solution": "D",
        },
        {
            "title": "关于测试原则，以下说法错误的是：",
            "description": "关于测试原则，以下说法错误的是：\nA. 测试应尽早介入\nB. 杀虫剂悖论意味着需要定期更新测试用例\nC. 测试活动应依赖于软件开发模型\nD. 不存在缺陷就说明软件是可用的",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试原则",
            "knowledge_point": "测试原则",
            "solution": "D",
        },
        {
            "title": "缺陷集群效应（Pareto原则）是指：",
            "description": "缺陷集群效应（Pareto原则）是指：\nA. 所有模块的缺陷数量相同\nB. 80%的缺陷集中在20%的模块中\nC. 缺陷是随机分布的\nD. 缺陷只出现在新开发的模块中",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试原则",
            "knowledge_point": "缺陷集群效应",
            "solution": "B",
        },
        # --- 测试级别 (medium) ---
        {
            "title": "以下哪个测试级别主要关注模块之间的接口？",
            "description": "以下哪个测试级别主要关注模块之间的接口？\nA. 单元测试\nB. 集成测试\nC. 系统测试\nD. 验收测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试级别",
            "knowledge_point": "集成测试",
            "solution": "B",
        },
        {
            "title": "单元测试的主要执行者是：",
            "description": "单元测试的主要执行者是：\nA. 测试工程师\nB. 开发工程师\nC. 产品经理\nD. 项目经理",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试级别",
            "knowledge_point": "单元测试",
            "solution": "B",
        },
        {
            "title": "系统测试的依据是：",
            "description": "系统测试的依据是：\nA. 详细设计文档\nB. 概要设计文档\nC. 需求规格说明书\nD. 用户手册",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试级别",
            "knowledge_point": "系统测试",
            "solution": "C",
        },
        {
            "title": "验收测试通常由谁来执行？",
            "description": "验收测试通常由谁来执行？\nA. 开发团队\nB. 测试团队\nC. 用户或客户\nD. 项目经理",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试级别",
            "knowledge_point": "验收测试",
            "solution": "C",
        },
        {
            "title": "自顶向下的集成测试需要使用什么来替代未开发完成的底层模块？",
            "description": "自顶向下的集成测试需要使用什么来替代未开发完成的底层模块？\nA. 驱动模块\nB. 桩模块\nC. 测试代理\nD. 模拟器",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试级别",
            "knowledge_point": "集成测试策略",
            "solution": "B",
        },
        {
            "title": "自底向上的集成测试需要使用什么来替代未开发完成的顶层模块？",
            "description": "自底向上的集成测试需要使用什么来替代未开发完成的顶层模块？\nA. 驱动模块\nB. 桩模块\nC. 测试代理\nD. 模拟器",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试级别",
            "knowledge_point": "集成测试策略",
            "solution": "A",
        },
        # --- 测试类型 (medium) ---
        {
            "title": "以下哪种测试属于非功能测试？",
            "description": "以下哪种测试属于非功能测试？\nA. 功能测试\nB. 性能测试\nC. 回归测试\nD. 冒烟测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试类型",
            "knowledge_point": "功能测试与非功能测试",
            "solution": "B",
        },
        {
            "title": "回归测试的目的是：",
            "description": "回归测试的目的是：\nA. 测试新开发的功能\nB. 验证修改后软件仍然正常工作\nC. 测试系统性能\nD. 测试用户界面",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试类型",
            "knowledge_point": "回归测试",
            "solution": "B",
        },
        {
            "title": "冒烟测试（Smoke Testing）通常在什么时候执行？",
            "description": "冒烟测试（Smoke Testing）通常在什么时候执行？\nA. 每次代码提交后\nB. 版本发布前的最后阶段\nC. 接收新版本时首先执行\nD. 只在第一次发布时执行",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试类型",
            "knowledge_point": "冒烟测试",
            "solution": "C",
        },
        {
            "title": "以下关于Alpha测试和Beta测试的说法，正确的是：",
            "description": "以下关于Alpha测试和Beta测试的说法，正确的是：\nA. Alpha测试在用户现场进行\nB. Beta测试在开发方现场进行\nC. Alpha测试在开发方现场进行，Beta测试在用户现场进行\nD. Alpha测试和Beta测试没有区别",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试类型",
            "knowledge_point": "Alpha和Beta测试",
            "solution": "C",
        },
        {
            "title": "负载测试和压力测试的主要区别是：",
            "description": "负载测试和压力测试的主要区别是：\nA. 没有区别\nB. 负载测试关注正常负载下的性能，压力测试关注超出极限的情况\nC. 负载测试更复杂\nD. 压力测试不需要工具",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试类型",
            "knowledge_point": "性能测试类型",
            "solution": "B",
        },
        # --- 黑盒测试 (medium) ---
        {
            "title": "黑盒测试又称为：",
            "description": "黑盒测试又称为：\nA. 结构测试\nB. 功能测试\nC. 代码测试\nD. 单元测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "黑盒测试",
            "knowledge_point": "黑盒测试定义",
            "solution": "B",
        },
        {
            "title": "以下哪种测试方法属于黑盒测试？",
            "description": "以下哪种测试方法属于黑盒测试？\nA. 语句覆盖\nB. 判定覆盖\nC. 等价类划分\nD. 路径覆盖",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "黑盒测试",
            "knowledge_point": "黑盒测试方法",
            "solution": "C",
        },
        {
            "title": "等价类划分方法的核心思想是：",
            "description": "等价类划分方法的核心思想是：\nA. 测试所有可能的输入\nB. 将输入划分为若干等价类，从每个类中选取代表性数据测试\nC. 只测试边界值\nD. 只测试有效输入",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "黑盒测试",
            "knowledge_point": "等价类划分",
            "solution": "B",
        },
        {
            "title": "边界值分析法通常与哪种方法配合使用？",
            "description": "边界值分析法通常与哪种方法配合使用？\nA. 判定表\nB. 等价类划分\nC. 因果图\nD. 状态转换",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "黑盒测试",
            "knowledge_point": "边界值分析",
            "solution": "B",
        },
        {
            "title": "判定表方法适用于什么场景？",
            "description": "判定表方法适用于什么场景？\nA. 单一条件的测试\nB. 多个条件组合的测试\nC. 界面测试\nD. 性能测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "黑盒测试",
            "knowledge_point": "判定表",
            "solution": "B",
        },
        # --- 白盒测试 (hard) ---
        {
            "title": "白盒测试又称为：",
            "description": "白盒测试又称为：\nA. 功能测试\nB. 结构测试\nC. 界面测试\nD. 系统测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "白盒测试",
            "knowledge_point": "白盒测试定义",
            "solution": "B",
        },
        {
            "title": "以下哪种覆盖方法的覆盖程度最高？",
            "description": "以下哪种覆盖方法的覆盖程度最高？\nA. 语句覆盖\nB. 判定覆盖\nC. 条件覆盖\nD. 路径覆盖",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "白盒测试",
            "knowledge_point": "覆盖方法",
            "solution": "D",
        },
        {
            "title": "语句覆盖要求：",
            "description": "语句覆盖要求：\nA. 每条语句至少执行一次\nB. 每个判定的真假分支至少执行一次\nC. 每个条件的真假值至少出现一次\nD. 每条路径至少执行一次",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "白盒测试",
            "knowledge_point": "语句覆盖",
            "solution": "A",
        },
        {
            "title": "判定覆盖要求：",
            "description": "判定覆盖要求：\nA. 每条语句至少执行一次\nB. 每个判定的真假分支至少执行一次\nC. 每个条件的真假值至少出现一次\nD. 每条路径至少执行一次",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "白盒测试",
            "knowledge_point": "判定覆盖",
            "solution": "B",
        },
        {
            "title": "条件覆盖和判定覆盖的关系是：",
            "description": "条件覆盖和判定覆盖的关系是：\nA. 条件覆盖一定满足判定覆盖\nB. 判定覆盖一定满足条件覆盖\nC. 两者相互独立\nD. 两者完全相同",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "白盒测试",
            "knowledge_point": "覆盖方法关系",
            "solution": "C",
        },
        # --- SDLC/STLC (medium) ---
        {
            "title": "STLC是指：",
            "description": "STLC是指：\nA. 软件开发生命周期\nB. 软件测试生命周期\nC. 系统测试生命周期\nD. 安全测试生命周期",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "SDLC/STLC",
            "knowledge_point": "STLC定义",
            "solution": "B",
        },
        {
            "title": "在V模型中，单元测试对应的开发阶段是：",
            "description": "在V模型中，单元测试对应的开发阶段是：\nA. 需求分析\nB. 概要设计\nC. 详细设计\nD. 编码",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "V模型",
            "solution": "D",
        },
        {
            "title": "在V模型中，系统测试对应的开发阶段是：",
            "description": "在V模型中，系统测试对应的开发阶段是：\nA. 需求分析\nB. 概要设计\nC. 详细设计\nD. 编码",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "V模型",
            "solution": "A",
        },
        {
            "title": "敏捷开发中的测试特点是：",
            "description": "敏捷开发中的测试特点是：\nA. 测试在开发完成后进行\nB. 测试与开发并行，持续集成\nC. 只进行单元测试\nD. 不需要测试计划",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "敏捷测试",
            "solution": "B",
        },
        {
            "title": "STLC中，测试计划制定发生在哪个阶段？",
            "description": "STLC中，测试计划制定发生在哪个阶段？\nA. 需求分析\nB. 测试计划\nC. 测试设计\nD. 测试执行",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "SDLC/STLC",
            "knowledge_point": "STLC阶段",
            "solution": "B",
        },
        {
            "title": "W模型相对于V模型的优势是：",
            "description": "W模型相对于V模型的优势是：\nA. 更简单\nB. 测试与开发同步进行\nC. 不需要文档\nD. 成本更低",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "W模型",
            "solution": "B",
        },
        {
            "title": "测试用例设计通常在STLC的哪个阶段完成？",
            "description": "测试用例设计通常在STLC的哪个阶段完成？\nA. 测试计划阶段\nB. 测试设计阶段\nC. 测试执行阶段\nD. 测试总结阶段",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "SDLC/STLC",
            "knowledge_point": "STLC阶段",
            "solution": "B",
        },
        {
            "title": "以下哪个不属于STLC的阶段？",
            "description": "以下哪个不属于STLC的阶段？\nA. 需求分析\nB. 测试设计\nC. 代码开发\nD. 测试执行",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "SDLC/STLC",
            "knowledge_point": "STLC阶段",
            "solution": "C",
        },
        {
            "title": "测试环境搭建通常在哪个阶段进行？",
            "description": "测试环境搭建通常在哪个阶段进行？\nA. 测试计划阶段\nB. 测试准备阶段\nC. 测试执行阶段\nD. 测试总结阶段",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "SDLC/STLC",
            "knowledge_point": "测试环境",
            "solution": "B",
        },
        {
            "title": "敏捷测试中，测试人员的主要职责是：",
            "description": "敏捷测试中，测试人员的主要职责是：\nA. 只执行测试\nB. 编写测试报告\nC. 参与需求评审、编写自动化测试、持续反馈\nD. 管理项目进度",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "敏捷测试职责",
            "solution": "C",
        },
        {
            "title": "持续集成(CI)的核心思想是：",
            "description": "持续集成(CI)的核心思想是：\nA. 每月集成一次\nB. 开发人员频繁地将代码集成到主干\nC. 只在发布时集成\nD. 不需要自动化测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "持续集成",
            "solution": "B",
        },
        {
            "title": "测试准入标准通常包括：",
            "description": "测试准入标准通常包括：\nA. 代码全部完成\nB. 需求文档评审通过、测试环境就绪、测试用例评审通过\nC. 所有缺陷已修复\nD. 项目即将上线",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "测试准入标准",
            "solution": "B",
        },
        {
            "title": "测试准出标准通常包括：",
            "description": "测试准出标准通常包括：\nA. 所有测试用例执行完毕\nB. 严重缺陷已修复、测试用例执行率达到要求、遗留缺陷有明确处理方案\nC. 没有任何遗留缺陷\nD. 客户满意",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "测试准出标准",
            "solution": "B",
        },
        {
            "title": "在瀑布模型中，测试活动的特点是：",
            "description": "在瀑布模型中，测试活动的特点是：\nA. 与开发并行进行\nB. 在开发完成后进行\nC. 不需要测试计划\nD. 只进行单元测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "瀑布模型测试",
            "solution": "B",
        },
        # ==================== 编程题 (20题) ====================
        {
            "title": "编写函数判断是否为闰年",
            "description": "编写一个Python函数is_leap_year(year)，判断给定年份是否为闰年。\n\n闰年规则：\n1. 能被4整除但不能被100整除\n2. 或者能被400整除\n\n示例：\n- is_leap_year(2024) -> True\n- is_leap_year(1900) -> False\n- is_leap_year(2000) -> True",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试编程基础",
            "knowledge_point": "边界值测试编程",
            "code_template": "def is_leap_year(year):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "2024", "expected": "True"}, {"input": "1900", "expected": "False"}, {"input": "2000", "expected": "True"}, {"input": "2023", "expected": "False"}]',
            "solution": "def is_leap_year(year):\n    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)",
            "hint": "注意闰年的两个条件，使用逻辑运算符组合",
        },
        {
            "title": "编写函数验证密码强度",
            "description": "编写Python函数check_password_strength(password)，检查密码强度。\n\n规则：\n- 长度>=8位\n- 包含大写字母\n- 包含小写字母\n- 包含数字\n- 包含特殊字符(!@#$%^&*)\n\n返回值：\n- 满足5条: \"strong\"\n- 满足3-4条: \"medium\"\n- 满足1-2条: \"weak\"",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试编程基础",
            "knowledge_point": "等价类测试编程",
            "code_template": "def check_password_strength(password):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"Abc12345!\"", "expected": "\"strong\""}, {"input": "\"abcdefgh\"", "expected": "\"weak\""}, {"input": "\"Abc12345\"", "expected": "\"medium\""}]',
            "solution": "def check_password_strength(password):\n    score = 0\n    if len(password) >= 8: score += 1\n    if any(c.isupper() for c in password): score += 1\n    if any(c.islower() for c in password): score += 1\n    if any(c.isdigit() for c in password): score += 1\n    if any(c in '!@#$%^&*' for c in password): score += 1\n    if score >= 5: return 'strong'\n    elif score >= 3: return 'medium'\n    return 'weak'",
            "hint": "使用any()函数和字符串方法检查各类字符",
        },
        {
            "title": "编写函数计算等价类测试数据",
            "description": "编写Python函数generate_equivalence_classes(min_val, max_val, invalid_count=2)，\n生成等价类测试数据。\n\n返回字典：\n- valid: 有效等价类的代表值（范围内3个值）\n- invalid: 无效等价类的代表值（范围外的值）\n- boundary: 边界值（最小值和最大值）",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计编程",
            "knowledge_point": "等价类划分编程",
            "code_template": "def generate_equivalence_classes(min_val, max_val, invalid_count=2):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "1, 100", "expected": "valid中包含范围内值，boundary包含1和100"}]',
            "solution": "def generate_equivalence_classes(min_val, max_val, invalid_count=2):\n    valid = [min_val + (max_val - min_val) // 4, (min_val + max_val) // 2, max_val - (max_val - min_val) // 4]\n    invalid = [min_val - 1, max_val + 1][:invalid_count]\n    boundary = [min_val, max_val]\n    return {'valid': valid, 'invalid': invalid, 'boundary': boundary}",
            "hint": "计算有效范围内的代表值，以及边界和范围外的值",
        },
        {
            "title": "编写函数实现简单的判定表",
            "description": "编写Python函数evaluate_decision_table(conditions, rules)，\n根据判定表规则评估结果。\n\nconditions: dict，条件名->值\nrules: list of dict，每条规则包含conditions和result\n\n返回匹配规则的result列表",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "测试设计编程",
            "knowledge_point": "判定表编程",
            "code_template": "def evaluate_decision_table(conditions, rules):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "conditions={\'age>18\': True, \'has_id\': True}, rules=[{\'conditions\': {\'age>18\': True, \'has_id\': True}, \'result\': \'pass\'}]", "expected": "[\'pass\']"}]',
            "solution": "def evaluate_decision_table(conditions, rules):\n    results = []\n    for rule in rules:\n        match = all(conditions.get(k) == v for k, v in rule['conditions'].items())\n        if match:\n            results.append(rule['result'])\n    return results",
            "hint": "遍历规则，检查所有条件是否匹配",
        },
        {
            "title": "编写函数验证邮箱格式",
            "description": "编写Python函数validate_email(email)，验证邮箱格式是否正确。\n\n规则：\n- 包含且仅包含一个@\n- @前后都有字符\n- @后包含至少一个.\n- .前后都有字符\n\n返回True或False",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试编程基础",
            "knowledge_point": "输入验证测试",
            "code_template": "def validate_email(email):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"test@example.com\"", "expected": "True"}, {"input": "\"invalid\"", "expected": "False"}, {"input": "\"@example.com\"", "expected": "False"}]',
            "solution": "def validate_email(email):\n    if email.count('@') != 1:\n        return False\n    local, domain = email.split('@')\n    if not local or not domain:\n        return False\n    if '.' not in domain:\n        return False\n    parts = domain.split('.')\n    return all(parts)",
            "hint": "使用count()检查@数量，split()分割后验证各部分",
        },
        {
            "title": "编写函数实现测试覆盖率计算",
            "description": "编写Python函数calculate_coverage(total_cases, executed_cases, passed_cases)，\n计算测试覆盖率指标。\n\n返回字典：\n- execution_rate: 执行率 = executed/total\n- pass_rate: 通过率 = passed/executed\n- coverage: 综合覆盖率",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试度量编程",
            "knowledge_point": "测试覆盖率",
            "code_template": "def calculate_coverage(total_cases, executed_cases, passed_cases):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "100, 80, 70", "expected": "execution_rate=0.8, pass_rate=0.875"}]',
            "solution": "def calculate_coverage(total_cases, executed_cases, passed_cases):\n    execution_rate = executed_cases / total_cases if total_cases > 0 else 0\n    pass_rate = passed_cases / executed_cases if executed_cases > 0 else 0\n    coverage = execution_rate * pass_rate\n    return {'execution_rate': round(execution_rate, 2), 'pass_rate': round(pass_rate, 2), 'coverage': round(coverage, 2)}",
            "hint": "注意除零检查",
        },
        {
            "title": "编写函数生成边界值测试数据",
            "description": "编写Python函数generate_boundary_values(min_val, max_val)，\n生成边界值测试数据集合。\n\n返回列表，包含：\n- 最小值-1, 最小值, 最小值+1\n- 最大值-1, 最大值, 最大值+1\n- 中间值",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计编程",
            "knowledge_point": "边界值分析编程",
            "code_template": "def generate_boundary_values(min_val, max_val):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "1, 100", "expected": "[0, 1, 2, 99, 100, 101, 50]"}]',
            "solution": "def generate_boundary_values(min_val, max_val):\n    mid = (min_val + max_val) // 2\n    return [min_val - 1, min_val, min_val + 1, max_val - 1, max_val, max_val + 1, mid]",
            "hint": "直接计算边界附近的值和中间值",
        },
        {
            "title": "编写函数检查测试用例完整性",
            "description": "编写Python函数validate_test_case(test_case)，检查测试用例是否完整。\n\ntest_case是字典，必须包含以下字段：\n- id: 非空字符串\n- title: 非空字符串\n- steps: 非空列表\n- expected: 非空字符串\n\n返回 (is_valid, missing_fields) 元组",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理编程",
            "knowledge_point": "测试用例验证",
            "code_template": "def validate_test_case(test_case):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"id\": \"TC001\", \"title\": \"Test\", \"steps\": [\"step1\"], \"expected\": \"ok\"}", "expected": "(True, [])"}]',
            "solution": "def validate_test_case(test_case):\n    required = ['id', 'title', 'steps', 'expected']\n    missing = [f for f in required if not test_case.get(f)]\n    return (len(missing) == 0, missing)",
            "hint": "使用列表推导式检查缺失字段",
        },
        {
            "title": "编写函数实现简单缺陷分类",
            "description": "编写Python函数classify_severity(description)，根据描述判断缺陷严重程度。\n\n关键词匹配规则：\n- 包含'崩溃''死机''数据丢失': critical\n- 包含'功能失效''无法使用': major\n- 包含'显示错误''界面问题': minor\n- 其他: trivial",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "缺陷管理编程",
            "knowledge_point": "缺陷分类",
            "code_template": "def classify_severity(description):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"程序崩溃\"", "expected": "\"critical\""}, {"input": "\"按钮显示错误\"", "expected": "\"minor\""}]',
            "solution": "def classify_severity(description):\n    critical = ['崩溃', '死机', '数据丢失']\n    major = ['功能失效', '无法使用']\n    minor = ['显示错误', '界面问题']\n    for kw in critical:\n        if kw in description: return 'critical'\n    for kw in major:\n        if kw in description: return 'major'\n    for kw in minor:\n        if kw in description: return 'minor'\n    return 'trivial'",
            "hint": "按优先级检查关键词",
        },
        {
            "title": "编写函数计算测试执行进度",
            "description": "编写Python函数calculate_progress(test_results)，计算测试执行进度。\n\ntest_results: list of dict，每个包含 'status' 字段（passed/failed/blocked/not_run）\n\n返回字典：\n- total: 总数\n- passed: 通过数\n- failed: 失败数\n- blocked: 阻塞数\n- not_run: 未执行数\n- progress: 执行进度百分比",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理编程",
            "knowledge_point": "测试进度统计",
            "code_template": "def calculate_progress(test_results):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"status\":\"passed\"},{\"status\":\"failed\"},{\"status\":\"not_run\"}]", "expected": "total=3, passed=1, failed=1, not_run=1, progress=66.67"}]',
            "solution": "def calculate_progress(test_results):\n    total = len(test_results)\n    stats = {'passed': 0, 'failed': 0, 'blocked': 0, 'not_run': 0}\n    for r in test_results:\n        stats[r['status']] = stats.get(r['status'], 0) + 1\n    executed = total - stats['not_run']\n    progress = round(executed / total * 100, 2) if total > 0 else 0\n    return {'total': total, **stats, 'progress': progress}",
            "hint": "使用字典统计各状态数量",
        },
        {
            "title": "编写函数验证手机号格式",
            "description": "编写Python函数validate_phone(phone)，验证中国大陆手机号格式。\n\n规则：\n- 11位数字\n- 以1开头\n- 第二位是3-9\n\n返回True或False",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试编程基础",
            "knowledge_point": "输入验证测试",
            "code_template": "def validate_phone(phone):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"13812345678\"", "expected": "True"}, {"input": "\"12345678901\"", "expected": "False"}, {"input": "\"1381234567\"", "expected": "False"}]',
            "solution": "def validate_phone(phone):\n    if len(phone) != 11:\n        return False\n    if not phone.isdigit():\n        return False\n    if phone[0] != '1':\n        return False\n    if phone[1] not in '3456789':\n        return False\n    return True",
            "hint": "逐个检查条件",
        },
        {
            "title": "编写函数实现测试数据工厂",
            "description": "编写Python函数create_test_data(data_type, count=5)，\n生成指定类型的测试数据。\n\ndata_type支持：\n- 'email': 生成测试邮箱\n- 'phone': 生成测试手机号\n- 'name': 生成测试用户名\n\n返回数据列表",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试编程基础",
            "knowledge_point": "测试数据生成",
            "code_template": "def create_test_data(data_type, count=5):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"email\", 3", "expected": "返回3个邮箱格式的字符串列表"}]',
            "solution": "def create_test_data(data_type, count=5):\n    if data_type == 'email':\n        return [f'test{i}@example.com' for i in range(count)]\n    elif data_type == 'phone':\n        return [f'1380000000{i:01d}' for i in range(count)]\n    elif data_type == 'name':\n        return [f'user_{i:03d}' for i in range(count)]\n    return []",
            "hint": "使用列表推导式生成数据",
        },
        {
            "title": "编写函数检查URL格式",
            "description": "编写Python函数validate_url(url)，验证URL格式。\n\n规则：\n- 以http://或https://开头\n- 包含域名（至少一个.）\n- 域名前后有字符\n\n返回True或False",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试编程基础",
            "knowledge_point": "输入验证测试",
            "code_template": "def validate_url(url):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"https://www.example.com\"", "expected": "True"}, {"input": "\"ftp://example.com\"", "expected": "False"}, {"input": "\"http://\"", "expected": "False"}]',
            "solution": "def validate_url(url):\n    if not url.startswith(('http://', 'https://')):\n        return False\n    domain = url.split('://')[1] if '://' in url else ''\n    if not domain or '.' not in domain:\n        return False\n    parts = domain.split('.')\n    return all(parts)",
            "hint": "先检查协议，再检查域名",
        },
        {
            "title": "编写函数实现冒烟测试检查",
            "description": "编写Python函数smoke_test_check(system_status)，\n执行冒烟测试检查。\n\nsystem_status: dict，包含各模块状态\n- database: True/False\n- api: True/False\n- frontend: True/False\n- auth: True/False\n\n返回 (passed, failed_modules) 元组",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试编程基础",
            "knowledge_point": "冒烟测试",
            "code_template": "def smoke_test_check(system_status):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"database\": true, \"api\": true, \"frontend\": true, \"auth\": true}", "expected": "(True, [])"}]',
            "solution": "def smoke_test_check(system_status):\n    required = ['database', 'api', 'frontend', 'auth']\n    failed = [m for m in required if not system_status.get(m)]\n    return (len(failed) == 0, failed)",
            "hint": "检查所有必需模块的状态",
        },
        {
            "title": "编写函数解析测试报告",
            "description": "编写Python函数parse_test_report(report_text)，解析测试报告文本。\n\nreport_text格式示例：\n'Total:100 Passed:80 Failed:15 Blocked:5'\n\n返回字典包含total, passed, failed, blocked, pass_rate",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理编程",
            "knowledge_point": "测试报告解析",
            "code_template": "def parse_test_report(report_text):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"Total:100 Passed:80 Failed:15 Blocked:5\"", "expected": "{total:100, passed:80, failed:15, blocked:5, pass_rate:80.0}"}]',
            "solution": "def parse_test_report(report_text):\n    result = {}\n    for part in report_text.split():\n        if ':' in part:\n            key, val = part.split(':')\n            result[key.lower()] = int(val)\n    result['pass_rate'] = round(result.get('passed', 0) / result.get('total', 1) * 100, 1)\n    return result",
            "hint": "使用split()分割文本，提取键值对",
        },
        {
            "title": "编写函数实现缺陷优先级排序",
            "description": "编写Python函数sort_defects(defects)，按优先级排序缺陷。\n\ndefects: list of dict，每个包含 severity 和 created_at\n\n优先级：critical > major > minor > trivial\n同级别按创建时间升序\n\n返回排序后的列表",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "缺陷管理编程",
            "knowledge_point": "缺陷优先级排序",
            "code_template": "def sort_defects(defects):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"severity\":\"minor\",\"created_at\":\"2024-01-01\"},{\"severity\":\"critical\",\"created_at\":\"2024-01-02\"}]", "expected": "critical排在minor前面"}]',
            "solution": "def sort_defects(defects):\n    priority = {'critical': 0, 'major': 1, 'minor': 2, 'trivial': 3}\n    return sorted(defects, key=lambda x: (priority.get(x['severity'], 99), x['created_at']))",
            "hint": "使用优先级映射字典配合sorted()",
        },
        {
            "title": "编写函数检查测试环境配置",
            "description": "编写Python函数check_environment(config)，检查测试环境配置。\n\nconfig: dict，包含\n- host: 非空字符串\n- port: 1-65535整数\n- database_url: 非空字符串\n- timeout: 正整数\n\n返回 (is_valid, errors) 元组",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试编程基础",
            "knowledge_point": "环境配置检查",
            "code_template": "def check_environment(config):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"host\":\"localhost\",\"port\":8080,\"database_url\":\"sqlite:///test.db\",\"timeout\":30}", "expected": "(True, [])"}]',
            "solution": "def check_environment(config):\n    errors = []\n    if not config.get('host'):\n        errors.append('host is required')\n    port = config.get('port', 0)\n    if not (1 <= port <= 65535):\n        errors.append('port must be 1-65535')\n    if not config.get('database_url'):\n        errors.append('database_url is required')\n    if config.get('timeout', 0) <= 0:\n        errors.append('timeout must be positive')\n    return (len(errors) == 0, errors)",
            "hint": "逐项检查配置参数",
        },
        {
            "title": "编写函数实现测试用例去重",
            "description": "编写Python函数deduplicate_cases(test_cases)，对测试用例去重。\n\ntest_cases: list of dict，每个包含 title 和 steps\n\n根据title去重，保留第一个出现的\n返回去重后的列表",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理编程",
            "knowledge_point": "测试用例管理",
            "code_template": "def deduplicate_cases(test_cases):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"title\":\"Test1\"},{\"title\":\"Test2\"},{\"title\":\"Test1\"}]", "expected": "[{\"title\":\"Test1\"},{\"title\":\"Test2\"}]"}]',
            "solution": "def deduplicate_cases(test_cases):\n    seen = set()\n    result = []\n    for case in test_cases:\n        if case['title'] not in seen:\n            seen.add(case['title'])\n            result.append(case)\n    return result",
            "hint": "使用集合记录已出现的title",
        },
        {
            "title": "编写函数统计缺陷趋势",
            "description": "编写Python函数defect_trend(defects_by_date)，统计缺陷趋势。\n\ndefects_by_date: dict，日期->新增缺陷数\n\n返回字典：\n- total: 总缺陷数\n- peak_date: 缺陷最多的日期\n- average: 平均每日缺陷数",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "缺陷管理编程",
            "knowledge_point": "缺陷趋势分析",
            "code_template": "def defect_trend(defects_by_date):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"2024-01-01\":5,\"2024-01-02\":10,\"2024-01-03\":3}", "expected": "total=18, peak_date=2024-01-02, average=6.0"}]',
            "solution": "def defect_trend(defects_by_date):\n    total = sum(defects_by_date.values())\n    peak_date = max(defects_by_date, key=defects_by_date.get)\n    average = round(total / len(defects_by_date), 1) if defects_by_date else 0\n    return {'total': total, 'peak_date': peak_date, 'average': average}",
            "hint": "使用max()和sum()函数",
        },
        # ==================== 简答题 (30题) ====================
        {
            "title": "请解释软件测试的定义和目的",
            "description": "请详细解释：\n1. 什么是软件测试？\n2. 软件测试的目的是什么？\n3. 测试能证明软件没有缺陷吗？为什么？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试定义与概念",
            "knowledge_point": "软件测试定义",
            "solution": "1. 软件测试是使用人工或自动手段来运行或测试某个系统的过程，目的是检验它是否满足规定的需求或弄清预期结果与实际结果之间的差别。\n\n2. 软件测试的目的包括：\n- 发现软件中的缺陷\n- 验证软件是否满足需求\n- 评估软件质量\n- 降低软件发布后的风险\n\n3. 测试不能证明软件没有缺陷，只能证明缺陷的存在。因为穷尽测试是不可能的，无法测试所有可能的输入和场景。",
        },
        {
            "title": "请解释软件测试的7个基本原则",
            "description": "请详细解释ISTQB定义的软件测试7个基本原则，并举例说明。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试原则",
            "knowledge_point": "测试原则",
            "solution": "1. 测试显示缺陷的存在：测试只能发现缺陷，不能证明没有缺陷\n2. 穷尽测试不可能：无法测试所有组合，需要风险分析和优先级\n3. 测试尽早介入：越早发现缺陷，修复成本越低\n4. 缺陷集群效应：少数模块包含大多数缺陷（80/20原则）\n5. 杀虫剂悖论：重复相同测试会降低发现新缺陷的能力\n6. 测试依赖于上下文：不同项目需要不同测试方法\n7. 无错误谬论：没有发现缺陷不代表软件可用",
        },
        {
            "title": "请比较V模型和W模型",
            "description": "请比较V模型和W模型的特点、优缺点和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "V模型和W模型",
            "solution": "V模型：\n- 特点：测试阶段与开发阶段一一对应\n- 优点：清晰简单，易于管理\n- 缺点：测试介入晚，线性模型不适应需求变化\n- 适用：需求稳定的项目\n\nW模型：\n- 特点：测试与开发同步进行\n- 优点：测试尽早介入，更早发现问题\n- 缺点：管理复杂度高\n- 适用：需要早期测试的项目",
        },
        {
            "title": "请解释黑盒测试和白盒测试的区别",
            "description": "请详细解释黑盒测试和白盒测试的定义、方法、优缺点和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试方法",
            "knowledge_point": "黑盒白盒对比",
            "solution": "黑盒测试（功能测试）：\n- 定义：不关注内部结构，只关注输入输出\n- 方法：等价类划分、边界值分析、判定表、因果图\n- 优点：从用户角度测试，不需要代码知识\n- 缺点：覆盖率难以衡量\n\n白盒测试（结构测试）：\n- 定义：关注内部代码结构\n- 方法：语句覆盖、判定覆盖、条件覆盖、路径覆盖\n- 优点：覆盖率高，能发现深层缺陷\n- 缺点：需要代码知识，工作量大",
        },
        {
            "title": "请解释单元测试、集成测试、系统测试、验收测试的区别",
            "description": "请解释四个测试级别的定义、测试对象、执行者和测试依据。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试级别",
            "knowledge_point": "测试级别",
            "solution": "单元测试：\n- 对象：最小可测试单元（函数、类）\n- 执行者：开发人员\n- 依据：详细设计文档\n\n集成测试：\n- 对象：模块间接口\n- 执行者：开发或测试人员\n- 依据：概要设计文档\n\n系统测试：\n- 对象：完整系统\n- 执行者：测试团队\n- 依据：需求规格说明书\n\n验收测试：\n- 对象：完整系统\n- 执行者：用户/客户\n- 依据：用户需求",
        },
        {
            "title": "请解释等价类划分方法",
            "description": "请解释等价类划分方法的原理、步骤和注意事项，并举例说明。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "原理：将输入数据划分为若干等价类，从每个类中选取代表性数据进行测试。\n\n步骤：\n1. 分析输入条件\n2. 划分有效等价类和无效等价类\n3. 从每个等价类中选取测试数据\n\n注意事项：\n- 等价类内的数据应具有相同测试效果\n- 有效和无效等价类都需要测试\n- 边界值需要单独考虑\n\n示例：年龄输入（1-150）\n- 有效等价类：1-150之间的任意值\n- 无效等价类：<1的值、>150的值",
        },
        {
            "title": "请解释边界值分析方法",
            "description": "请解释边界值分析方法的原理、与等价类划分的关系和测试用例设计方法。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "原理：缺陷常出现在边界，因此重点测试边界值。\n\n与等价类的关系：边界值分析是等价类划分的补充。\n\n测试用例设计：\n- 边界上的值\n- 边界两边的值\n- 最大值、最小值\n- 刚好超过/低于边界的值\n\n示例：输入范围1-100\n测试数据：0, 1, 2, 99, 100, 101",
        },
        {
            "title": "请解释判定表方法",
            "description": "请解释判定表方法的组成、适用场景和设计步骤。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "组成：\n- 条件桩：所有输入条件\n- 动作桩：所有可能的操作\n- 条件项：条件的取值组合\n- 动作项：对应的执行动作\n\n适用场景：\n- 多个条件组合\n- 条件之间有逻辑关系\n\n设计步骤：\n1. 识别条件和动作\n2. 构建判定表\n3. 简化规则\n4. 生成测试用例",
        },
        {
            "title": "请解释软件测试生命周期(STLC)的各个阶段",
            "description": "请详细解释STLC的每个阶段及其主要活动。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "STLC阶段",
            "solution": "STLC阶段：\n1. 需求分析：分析测试需求，确定测试范围\n2. 测试计划：制定测试策略、资源、进度\n3. 测试设计：设计测试用例、准备测试数据\n4. 测试环境搭建：配置硬件、软件、网络环境\n5. 测试执行：执行测试用例，记录结果\n6. 测试报告：总结测试结果，评估质量\n7. 测试结束：归档文档，总结经验教训",
        },
        {
            "title": "请解释什么是回归测试",
            "description": "请解释回归测试的定义、目的、策略和注意事项。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试类型",
            "knowledge_point": "回归测试",
            "solution": "定义：修改代码后重新测试，确保修改没有引入新的缺陷。\n\n目的：\n- 验证修改的正确性\n- 确保未修改的功能正常\n\n策略：\n- 完全回归：重新执行所有测试用例\n- 选择性回归：只执行受影响的测试用例\n\n注意事项：\n- 自动化回归测试效率更高\n- 需要维护回归测试用例集\n- 关注修改影响范围",
        },
        {
            "title": "请解释冒烟测试和回归测试的区别",
            "description": "请比较冒烟测试和回归测试的定义、目的、执行时机和测试范围。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试类型",
            "knowledge_point": "冒烟测试vs回归测试",
            "solution": "冒烟测试：\n- 定义：验证系统基本功能是否正常\n- 目的：决定是否继续深入测试\n- 时机：接收新版本时\n- 范围：核心功能\n\n回归测试：\n- 定义：验证修改后系统仍正常\n- 目的：确保修改没有引入缺陷\n- 时机：代码修改后\n- 范围：受影响的功能",
        },
        {
            "title": "请解释Alpha测试和Beta测试",
            "description": "请解释Alpha测试和Beta测试的定义、区别和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试类型",
            "knowledge_point": "Alpha和Beta测试",
            "solution": "Alpha测试：\n- 地点：开发方现场\n- 执行者：用户或测试人员\n- 环境：受控环境\n- 时机：发布前\n\nBeta测试：\n- 地点：用户现场\n- 执行者：最终用户\n- 环境：真实环境\n- 时机：发布后、正式前\n\n区别：Alpha在受控环境，Beta在真实环境",
        },
        {
            "title": "请解释性能测试的类型",
            "description": "请解释负载测试、压力测试、稳定性测试的区别和目的。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试类型",
            "knowledge_point": "性能测试类型",
            "solution": "负载测试：\n- 目的：验证系统在预期负载下的性能\n- 方法：逐步增加负载\n- 关注：响应时间、吞吐量\n\n压力测试：\n- 目的：找出系统极限\n- 方法：超出正常负载\n- 关注：系统崩溃点、恢复能力\n\n稳定性测试：\n- 目的：验证系统长期运行的稳定性\n- 方法：持续运行较长时间\n- 关注：内存泄漏、资源耗尽",
        },
        {
            "title": "请解释测试用例的要素",
            "description": "请解释一个完整的测试用例应该包含哪些要素。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "测试用例要素",
            "solution": "测试用例要素：\n1. 用例ID：唯一标识\n2. 用例标题：简短描述测试目的\n3. 前置条件：执行前需要满足的条件\n4. 测试步骤：详细的操作步骤\n5. 测试数据：需要的输入数据\n6. 预期结果：正确的输出或行为\n7. 优先级：重要程度\n8. 执行状态：通过/失败/阻塞",
        },
        {
            "title": "请解释缺陷报告的要素",
            "description": "请解释一个完整的缺陷报告应该包含哪些要素。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "缺陷管理",
            "knowledge_point": "缺陷报告要素",
            "solution": "缺陷报告要素：\n1. 缺陷ID：唯一标识\n2. 标题：简短描述缺陷\n3. 严重程度：critical/major/minor/trivial\n4. 优先级：high/medium/low\n5. 复现步骤：详细的操作步骤\n6. 预期结果：应该是什么\n7. 实际结果：实际是什么\n8. 测试环境：系统、浏览器等\n9. 截图/日志：证据\n10. 报告人和日期",
        },
        {
            "title": "请解释什么是测试驱动开发(TDD)",
            "description": "请解释TDD的定义、流程和优点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试方法",
            "knowledge_point": "TDD",
            "solution": "定义：先写测试，再写代码，最后重构。\n\n流程（红-绿-重构）：\n1. 红：编写失败的测试\n2. 绿：编写最少代码让测试通过\n3. 重构：优化代码\n\n优点：\n- 代码质量高\n- 测试覆盖率高\n- 设计更好\n- 重构有信心\n\n缺点：\n- 学习曲线陡\n- 初期开发速度慢",
        },
        {
            "title": "请解释什么是持续集成(CI)",
            "description": "请解释CI的定义、原则和实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "持续集成",
            "solution": "定义：频繁地将代码集成到主干，每次集成都通过自动化测试验证。\n\n原则：\n- 频繁提交代码\n- 每次提交都触发构建和测试\n- 构建失败后优先修复\n\n实践：\n- 版本控制\n- 自动化构建\n- 自动化测试\n- 快速反馈\n\n工具：Jenkins, GitLab CI, GitHub Actions",
        },
        {
            "title": "请解释什么是敏捷测试",
            "description": "请解释敏捷测试的特点、与传统测试的区别。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "SDLC/STLC",
            "knowledge_point": "敏捷测试",
            "solution": "特点：\n- 测试与开发并行\n- 持续测试\n- 自动化程度高\n- 重视协作\n\n与传统测试区别：\n- 传统：测试在开发后\n- 敏捷：测试贯穿整个迭代\n- 传统：详细的测试计划\n- 敏捷：灵活调整\n- 传统：独立的测试团队\n- 敏捷：跨功能团队",
        },
        {
            "title": "请解释测试金字塔",
            "description": "请解释测试金字塔的概念、各层测试的占比和作用。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试策略",
            "knowledge_point": "测试金字塔",
            "solution": "测试金字塔：\n\n底层：单元测试（70%）\n- 数量最多，执行最快\n- 测试最小单元\n\n中层：集成测试（20%）\n- 测试模块间交互\n- 数量适中\n\n顶层：端到端测试（10%）\n- 数量最少，执行最慢\n- 测试完整流程\n\n原则：\n- 越底层越多\n- 越底层越快\n- 越底层越稳定",
        },
        {
            "title": "请解释测试左移和测试右移",
            "description": "请解释测试左移和测试右移的概念和实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试策略",
            "knowledge_point": "测试左右移",
            "solution": "测试左移：\n- 概念：测试尽早介入开发过程\n- 实践：需求评审、设计评审、代码审查\n- 优点：早期发现缺陷，降低修复成本\n\n测试右移：\n- 概念：测试延伸到生产环境\n- 实践：监控、日志分析、用户反馈\n- 优点：发现真实环境问题\n\n总结：左移预防，右移检测",
        },
        {
            "title": "请解释什么是探索性测试",
            "description": "请解释探索性测试的定义、特点和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试方法",
            "knowledge_point": "探索性测试",
            "solution": "定义：同时学习、设计和执行测试的方法。\n\n特点：\n- 不依赖预先编写的测试用例\n- 强调测试人员的创造力和经验\n- 边测试边设计\n\n适用场景：\n- 需求不明确\n- 时间紧迫\n- 补充自动化测试\n- 发现边缘缺陷\n\n与脚本测试对比：\n- 脚本测试：可重复，适合回归\n- 探索性测试：灵活，适合发现新缺陷",
        },
        {
            "title": "请解释测试覆盖率的类型",
            "description": "请解释代码覆盖率、需求覆盖率、用例覆盖率的区别和计算方法。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试度量",
            "knowledge_point": "测试覆盖率",
            "solution": "代码覆盖率：\n- 定义：被测试代码占总代码的比例\n- 类型：语句覆盖、分支覆盖、路径覆盖\n- 工具：coverage.py, JaCoCo\n\n需求覆盖率：\n- 定义：被测试需求占总需求的比例\n- 计算：已测需求数/总需求数\n\n用例覆盖率：\n- 定义：已执行用例占总用例的比例\n- 计算：已执行数/总数",
        },
        {
            "title": "请解释什么是测试自动化",
            "description": "请解释测试自动化的定义、优缺点和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "自动化测试",
            "knowledge_point": "测试自动化概念",
            "solution": "定义：使用工具自动执行测试脚本。\n\n优点：\n- 提高效率\n- 可重复执行\n- 减少人为错误\n- 支持持续集成\n\n缺点：\n- 初期投入大\n- 维护成本高\n- 不能替代探索性测试\n\n适用场景：\n- 回归测试\n- 性能测试\n- 数据驱动测试\n- 重复性高的测试",
        },
        {
            "title": "请解释Page Object模式",
            "description": "请解释Page Object模式的定义、结构和优点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "自动化测试",
            "knowledge_point": "Page Object模式",
            "solution": "定义：将页面封装为对象，分离页面操作和测试逻辑。\n\n结构：\n- Page类：封装页面元素和操作\n- Test类：编写测试逻辑\n\n优点：\n- 代码可维护性高\n- 减少代码重复\n- 可读性好\n\n示例：\nclass LoginPage:\n    username = (By.ID, 'username')\n    password = (By.ID, 'password')\n    \n    def login(self, user, pwd):\n        self.driver.find_element(*self.username).send_keys(user)",
        },
        {
            "title": "请解释数据驱动测试",
            "description": "请解释数据驱动测试的定义、实现方式和优点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "自动化测试",
            "knowledge_point": "数据驱动测试",
            "solution": "定义：测试逻辑和测试数据分离，使用不同数据执行相同测试。\n\n实现方式：\n- 参数化（pytest.mark.parametrize）\n- 外部文件（CSV, Excel, JSON）\n- 数据库\n\n优点：\n- 减少代码重复\n- 易于添加新测试数据\n- 覆盖更多场景\n\n示例：\n@pytest.mark.parametrize('input,expected', [(1,2), (2,3)])\ndef test_add(input, expected):\n    assert add(input, 1) == expected",
        },
        {
            "title": "请解释接口测试的必要性",
            "description": "请解释为什么需要接口测试，以及接口测试的优势。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "接口测试",
            "knowledge_point": "接口测试概念",
            "solution": "必要性：\n- UI不稳定，接口相对稳定\n- 可以在UI完成前开始测试\n- 发现更深层的缺陷\n\n优势：\n- 执行速度快\n- 维护成本低\n- 覆盖面广\n- 适合自动化\n\n测试内容：\n- 参数验证\n- 业务逻辑\n- 异常处理\n- 性能",
        },
        {
            "title": "请解释什么是Mock和Stub",
            "description": "请解释Mock和Stub的定义、区别和使用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试方法",
            "knowledge_point": "Mock和Stub",
            "solution": "Stub（桩）：\n- 定义：提供预设响应的替代品\n- 用途：隔离被测系统\n- 特点：简单的返回值\n\nMock（模拟）：\n- 定义：可以验证交互行为的替代品\n- 用途：验证方法调用\n- 特点：可以断言调用次数、参数\n\n区别：\n- Stub关注状态\n- Mock关注行为\n\n工具：unittest.mock, Mockito",
        },
        {
            "title": "请解释测试环境管理的重要性",
            "description": "请解释测试环境管理的重要性、挑战和最佳实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试环境管理",
            "solution": "重要性：\n- 确保测试结果可靠\n- 提高测试效率\n- 减少环境问题导致的缺陷遗漏\n\n挑战：\n- 环境配置复杂\n- 多环境维护困难\n- 环境不一致\n\n最佳实践：\n- 环境配置自动化（Docker）\n- 环境隔离\n- 定期维护和更新\n- 文档化环境配置",
        },
        {
            "title": "请解释风险驱动测试",
            "description": "请解释风险驱动测试的定义、风险评估方法和测试策略。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试策略",
            "knowledge_point": "风险驱动测试",
            "solution": "定义：根据风险优先级分配测试资源。\n\n风险评估：\n- 发生概率\n- 影响程度\n- 风险值 = 概率 × 影响\n\n测试策略：\n- 高风险：详细测试\n- 中风险：标准测试\n- 低风险：简单测试\n\n优点：\n- 资源利用最大化\n- 关注重要功能\n- 提高测试效率",
        },
        {
            "title": "请解释测试人员需要具备的技能",
            "description": "请从技术技能和软技能两方面说明测试人员的能力要求。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试职业",
            "knowledge_point": "测试人员技能",
            "solution": "技术技能：\n- 测试理论和方法\n- 编程能力（Python, Java）\n- 自动化测试工具\n- 数据库（SQL）\n- Linux操作\n- 网络协议\n- 性能/安全测试\n\n软技能：\n- 沟通能力\n- 细心和耐心\n- 逻辑思维\n- 学习能力\n- 团队协作\n- 问题分析能力",
        },
    ]
}
