# -*- coding: utf-8 -*-
"""
软件工程基础知识 - 学习路径 ID=5
知识点: 开发模型、需求分析、设计模式、配置管理、项目管理基础
题目数量: 90题 (选择题40 + 编程题20 + 简答题30)
难度分布: easy 30% + medium 50% + hard 20%
"""

EXERCISES = {
    "计算机基础与网络知识": [
        # ==================== 选择题 (40题) ====================
        # --- 软件开发模型 (easy/medium) ---
        {
            "title": "瀑布模型的特点是：",
            "description": "瀑布模型的特点是：\nA. 迭代开发\nB. 线性顺序执行\nC. 并行开发\nD. 增量交付",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件开发模型",
            "knowledge_point": "瀑布模型",
            "solution": "B",
        },
        {
            "title": "敏捷开发的核心价值观包括：",
            "description": "以下哪项不属于敏捷宣言的核心价值观？\nA. 个体和互动高于流程和工具\nB. 可工作的软件高于详尽的文档\nC. 合同谈判高于客户合作\nD. 响应变化高于遵循计划",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件开发模型",
            "knowledge_point": "敏捷开发",
            "solution": "C",
        },
        {
            "title": "Scrum中Sprint的典型周期是：",
            "description": "Scrum中Sprint的典型周期是：\nA. 1周\nB. 2-4周\nC. 2个月\nD. 6个月",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件开发模型",
            "knowledge_point": "Scrum框架",
            "solution": "B",
        },
        {
            "title": "增量模型的特点是：",
            "description": "增量模型的特点是：\nA. 一次性交付完整系统\nB. 分批次交付系统功能\nC. 不需要需求分析\nD. 只适用于小项目",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "增量模型",
            "solution": "B",
        },
        {
            "title": "螺旋模型特别适用于：",
            "description": "螺旋模型特别适用于：\nA. 小型项目\nB. 需求明确的项目\nC. 高风险大型项目\nD. 维护项目",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "螺旋模型",
            "solution": "C",
        },
        {
            "title": "以下哪个不是Scrum的角色？",
            "description": "以下哪个不是Scrum的角色？\nA. Product Owner\nB. Scrum Master\nC. Project Manager\nD. Development Team",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件开发模型",
            "knowledge_point": "Scrum角色",
            "solution": "C",
        },
        {
            "title": "看板方法的核心原则是：",
            "description": "看板方法的核心原则是：\nA. 固定迭代周期\nB. 限制在制品数量\nC. 强制角色分工\nD. 详细的需求文档",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "看板方法",
            "solution": "B",
        },
        {
            "title": "DevOps的核心思想是：",
            "description": "DevOps的核心思想是：\nA. 开发和运维分离\nB. 开发和运维协作\nC. 只关注开发\nD. 只关注运维",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件开发模型",
            "knowledge_point": "DevOps",
            "solution": "B",
        },
        # --- 需求分析 (medium) ---
        {
            "title": "功能需求描述的是：",
            "description": "功能需求描述的是：\nA. 系统应该做什么\nB. 系统应该怎么做\nC. 系统的性能指标\nD. 系统的约束条件",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "需求分析",
            "knowledge_point": "功能需求",
            "solution": "A",
        },
        {
            "title": "以下哪项属于非功能需求？",
            "description": "以下哪项属于非功能需求？\nA. 用户登录功能\nB. 系统响应时间小于3秒\nC. 数据查询功能\nD. 报表生成功能",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "需求分析",
            "knowledge_point": "非功能需求",
            "solution": "B",
        },
        {
            "title": "用户故事的标准格式是：",
            "description": "用户故事的标准格式是：\nA. 作为<角色>，我希望<功能>，以便<价值>\nB. 系统应该实现<功能>\nC. 开发<功能>需要<时间>\nD. 测试<功能>需要<资源>",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "需求分析",
            "knowledge_point": "用户故事",
            "solution": "A",
        },
        {
            "title": "需求变更管理的目的是：",
            "description": "需求变更管理的目的是：\nA. 阻止所有变更\nB. 控制变更的影响\nC. 增加项目范围\nD. 减少测试工作",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "需求分析",
            "knowledge_point": "需求变更",
            "solution": "B",
        },
        {
            "title": "需求追踪矩阵的作用是：",
            "description": "需求追踪矩阵的作用是：\nA. 记录项目进度\nB. 追踪需求到设计、代码、测试的映射\nC. 管理项目预算\nD. 分配团队任务",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "需求分析",
            "knowledge_point": "需求追踪",
            "solution": "B",
        },
        {
            "title": "验收标准(Acceptance Criteria)的作用是：",
            "description": "验收标准的作用是：\nA. 定义代码规范\nB. 定义用户故事完成的条件\nC. 定义项目里程碑\nD. 定义团队KPI",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "需求分析",
            "knowledge_point": "验收标准",
            "solution": "B",
        },
        # --- 设计模式 (hard) ---
        {
            "title": "单例模式的目的是：",
            "description": "单例模式的目的是：\nA. 创建多个实例\nB. 确保一个类只有一个实例\nC. 提高代码可读性\nD. 减少内存使用",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "设计模式",
            "knowledge_point": "单例模式",
            "solution": "B",
        },
        {
            "title": "工厂模式的主要优点是：",
            "description": "工厂模式的主要优点是：\nA. 提高程序性能\nB. 解耦对象创建和使用\nC. 减少代码行数\nD. 简化类结构",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "设计模式",
            "knowledge_point": "工厂模式",
            "solution": "B",
        },
        {
            "title": "观察者模式适用于：",
            "description": "观察者模式适用于：\nA. 对象间一对多依赖关系\nB. 单一对象的创建\nC. 算法的封装\nD. 接口的适配",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "设计模式",
            "knowledge_point": "观察者模式",
            "solution": "A",
        },
        {
            "title": "MVC模式中，M代表：",
            "description": "MVC模式中，M代表：\nA. Module\nB. Model\nC. Manager\nD. Method",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "设计模式",
            "knowledge_point": "MVC模式",
            "solution": "B",
        },
        {
            "title": "以下哪个不是创建型设计模式？",
            "description": "以下哪个不是创建型设计模式？\nA. 单例模式\nB. 工厂模式\nC. 观察者模式\nD. 建造者模式",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "设计模式",
            "knowledge_point": "设计模式分类",
            "solution": "C",
        },
        {
            "title": "策略模式的目的是：",
            "description": "策略模式的目的是：\nA. 定义算法族，使它们可以互相替换\nB. 创建对象的复杂过程\nC. 建立对象间的通知机制\nD. 适配不兼容的接口",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "设计模式",
            "knowledge_point": "策略模式",
            "solution": "A",
        },
        # --- 配置管理 (medium) ---
        {
            "title": "版本控制的主要目的是：",
            "description": "版本控制的主要目的是：\nA. 备份代码\nB. 追踪代码变更历史\nC. 提高代码性能\nD. 减少代码行数",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "版本控制",
            "solution": "B",
        },
        {
            "title": "Git中，git commit的作用是：",
            "description": "Git中，git commit的作用是：\nA. 创建新分支\nB. 提交暂存区的更改到本地仓库\nC. 推送到远程仓库\nD. 合并分支",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "Git命令",
            "solution": "B",
        },
        {
            "title": "Git分支策略中，feature分支用于：",
            "description": "Git分支策略中，feature分支用于：\nA. 生产环境部署\nB. 开发新功能\nC. 修复紧急bug\nD. 版本发布",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "Git分支",
            "solution": "B",
        },
        {
            "title": "代码审查(Code Review)的主要目的是：",
            "description": "代码审查的主要目的是：\nA. 检查代码行数\nB. 提高代码质量\nC. 评估开发速度\nD. 分配任务",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "代码审查",
            "solution": "B",
        },
        {
            "title": "持续集成(CI)的核心实践是：",
            "description": "持续集成的核心实践是：\nA. 每月集成一次\nB. 频繁集成并自动测试\nC. 只在发布时集成\nD. 手动集成",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "配置管理",
            "knowledge_point": "持续集成",
            "solution": "B",
        },
        {
            "title": "制品库(Artifact Repository)的作用是：",
            "description": "制品库的作用是：\nA. 存储源代码\nB. 存储构建产物\nC. 存储文档\nD. 存储测试用例",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "配置管理",
            "knowledge_point": "制品管理",
            "solution": "B",
        },
        # --- 项目管理 (medium) ---
        {
            "title": "项目管理三角形包括：",
            "description": "项目管理三角形包括：\nA. 时间、成本、范围\nB. 时间、人员、设备\nC. 需求、设计、测试\nD. 计划、执行、监控",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "项目管理",
            "knowledge_point": "项目管理三角形",
            "solution": "A",
        },
        {
            "title": "甘特图主要用于：",
            "description": "甘特图主要用于：\nA. 代码审查\nB. 项目进度管理\nC. 需求分析\nD. 风险评估",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "项目管理",
            "knowledge_point": "甘特图",
            "solution": "B",
        },
        {
            "title": "风险管理的第一步是：",
            "description": "风险管理的第一步是：\nA. 风险应对\nB. 风险识别\nC. 风险监控\nD. 风险评估",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "风险管理",
            "solution": "B",
        },
        {
            "title": "里程碑(Milestone)的定义是：",
            "description": "里程碑的定义是：\nA. 项目开始日期\nB. 项目中的重要节点或事件\nC. 项目结束日期\nD. 每周的会议",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "项目管理",
            "knowledge_point": "里程碑",
            "solution": "B",
        },
        {
            "title": "WBS(工作分解结构)的目的是：",
            "description": "WBS的目的是：\nA. 分解项目为可管理的工作包\nB. 记录项目进度\nC. 分配团队成员\nD. 评估项目成本",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "WBS",
            "solution": "A",
        },
        {
            "title": "站会(Stand-up Meeting)的典型时长是：",
            "description": "站会的典型时长是：\nA. 1小时\nB. 15分钟\nC. 30分钟\nD. 2小时",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "项目管理",
            "knowledge_point": "站会",
            "solution": "B",
        },
        {
            "title": "回顾会议(Retrospective)的目的是：",
            "description": "回顾会议的目的是：\nA. 分配任务\nB. 总结经验教训，持续改进\nC. 演示产品\nD. 制定计划",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "回顾会议",
            "solution": "B",
        },
        {
            "title": "关键路径法(CPM)用于：",
            "description": "关键路径法用于：\nA. 代码优化\nB. 识别项目中最长的任务路径\nC. 需求分析\nD. 风险评估",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "项目管理",
            "knowledge_point": "关键路径",
            "solution": "B",
        },
        {
            "title": "以下哪个不是敏捷估算方法？",
            "description": "以下哪个不是敏捷估算方法？\nA. 计划扑克\nB. T-shirt sizing\nC. 甘特图\nD. 宽带德尔菲",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "敏捷估算",
            "solution": "C",
        },
        {
            "title": "Velocity(速率)在Scrum中用于：",
            "description": "Velocity在Scrum中用于：\nA. 测量代码质量\nB. 测量团队每Sprint完成的工作量\nC. 测量bug数量\nD. 测量客户满意度",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "Velocity",
            "solution": "B",
        },
        {
            "title": "技术债务(Technical Debt)是指：",
            "description": "技术债务是指：\nA. 项目超支\nB. 为了短期目标而牺牲代码质量\nC. 人员流失\nD. 需求变更",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "技术债务",
            "solution": "B",
        },
        {
            "title": "重构(Refactoring)的目的是：",
            "description": "重构的目的是：\nA. 添加新功能\nB. 改善代码结构而不改变行为\nC. 修复bug\nD. 优化性能",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "重构",
            "solution": "B",
        },
        {
            "title": "SOLID原则中，S代表：",
            "description": "SOLID原则中，S代表：\nA. Simple\nB. Single Responsibility\nC. Standard\nD. Secure",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "SOLID原则",
            "solution": "B",
        },
        {
            "title": "DRY原则的含义是：",
            "description": "DRY原则的含义是：\nA. 快速开发\nB. Don't Repeat Yourself\nC. 设计先行\nD. 文档优先",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件工程",
            "knowledge_point": "DRY原则",
            "solution": "B",
        },
        {
            "title": "KISS原则的含义是：",
            "description": "KISS原则的含义是：\nA. 保持简单\nB. Keep It Simple, Stupid\nC. 快速迭代\nD. 持续集成",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "软件工程",
            "knowledge_point": "KISS原则",
            "solution": "B",
        },
        # ==================== 编程题 (20题) ====================
        {
            "title": "实现简单的单例模式",
            "description": "使用Python实现一个单例模式的类Singleton。\n\n要求：\n- 无论创建多少次实例，都返回同一个对象\n- 使用__new__方法实现\n\n示例：\ns1 = Singleton()\ns2 = Singleton()\nassert s1 is s2  # True",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "设计模式",
            "knowledge_point": "单例模式",
            "code_template": "class Singleton:\n    _instance = None\n    \n    def __new__(cls, *args, **kwargs):\n        # 请在此处编写代码\n        pass",
            "test_cases": "[{\"input\": \"s1=Singleton(); s2=Singleton(); s1 is s2\", \"expected\": \"True\"}]",
            "solution": "class Singleton:\n    _instance = None\n    \n    def __new__(cls, *args, **kwargs):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance",
            "hint": "使用类变量存储实例，__new__中检查是否已存在",
        },
        {
            "title": "实现简单的工厂模式",
            "description": "实现一个简单的工厂模式，根据类型创建不同的形状对象。\n\n要求：\n- ShapeFactory类有create_shape方法\n- 支持创建circle和rectangle\n- 返回对应的Shape对象\n\nShape类有area()方法计算面积",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "设计模式",
            "knowledge_point": "工厂模式",
            "code_template": "class Shape:\n    def area(self):\n        pass\n\nclass Circle(Shape):\n    def __init__(self, radius):\n        self.radius = radius\n    \n    def area(self):\n        # 请实现\n        pass\n\nclass Rectangle(Shape):\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n    \n    def area(self):\n        # 请实现\n        pass\n\nclass ShapeFactory:\n    def create_shape(self, shape_type, *args):\n        # 请实现工厂方法\n        pass",
            "test_cases": "[]",
            "solution": "import math\n\nclass Shape:\n    def area(self):\n        pass\n\nclass Circle(Shape):\n    def __init__(self, radius):\n        self.radius = radius\n    \n    def area(self):\n        return round(math.pi * self.radius ** 2, 2)\n\nclass Rectangle(Shape):\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n    \n    def area(self):\n        return self.width * self.height\n\nclass ShapeFactory:\n    def create_shape(self, shape_type, *args):\n        if shape_type == 'circle':\n            return Circle(*args)\n        elif shape_type == 'rectangle':\n            return Rectangle(*args)\n        raise ValueError(f'Unknown shape: {shape_type}')",
            "hint": "使用if/elif根据类型创建不同对象",
        },
        {
            "title": "实现观察者模式",
            "description": "实现一个简单的观察者模式。\n\n要求：\n- Subject类：支持attach、detach、notify方法\n- Observer类：有update方法\n- 当Subject状态改变时，通知所有观察者",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "设计模式",
            "knowledge_point": "观察者模式",
            "code_template": "class Subject:\n    def __init__(self):\n        self._observers = []\n        self._state = None\n    \n    def attach(self, observer):\n        # 请实现\n        pass\n    \n    def detach(self, observer):\n        # 请实现\n        pass\n    \n    def notify(self):\n        # 请实现\n        pass\n    \n    @property\n    def state(self):\n        return self._state\n    \n    @state.setter\n    def state(self, value):\n        self._state = value\n        self.notify()\n\nclass Observer:\n    def __init__(self, name):\n        self.name = name\n        self.received = None\n    \n    def update(self, state):\n        # 请实现\n        pass",
            "test_cases": "[]",
            "solution": "class Subject:\n    def __init__(self):\n        self._observers = []\n        self._state = None\n    \n    def attach(self, observer):\n        self._observers.append(observer)\n    \n    def detach(self, observer):\n        self._observers.remove(observer)\n    \n    def notify(self):\n        for observer in self._observers:\n            observer.update(self._state)\n    \n    @property\n    def state(self):\n        return self._state\n    \n    @state.setter\n    def state(self, value):\n        self._state = value\n        self.notify()\n\nclass Observer:\n    def __init__(self, name):\n        self.name = name\n        self.received = None\n    \n    def update(self, state):\n        self.received = state",
            "hint": "Subject维护观察者列表，状态改变时遍历通知",
        },
        {
            "title": "实现简单的用户故事解析器",
            "description": "编写函数parse_user_story(story_text)，解析用户故事文本。\n\n用户故事格式：\n'As a <role>, I want <feature>, so that <benefit>'\n\n返回字典：{role, feature, benefit}\n\n如果格式不正确，返回None",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "需求分析",
            "knowledge_point": "用户故事",
            "code_template": "def parse_user_story(story_text):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[]",
            "solution": "def parse_user_story(story_text):\n    import re\n    pattern = r'As an? (.*?), I want (.*?), so that (.*)'\n    match = re.match(pattern, story_text, re.IGNORECASE)\n    if match:\n        return {\n            'role': match.group(1).strip(),\n            'feature': match.group(2).strip(),\n            'benefit': match.group(3).strip()\n        }\n    return None",
            "hint": "使用正则表达式匹配各部分",
        },
        {
            "title": "实现简单的任务看板",
            "description": "实现一个简单的任务看板类KanbanBoard。\n\n功能：\n- add_task(task, status='todo'): 添加任务\n- move_task(task, new_status): 移动任务状态\n- get_tasks(status): 获取指定状态的任务列表\n- get_stats(): 获取各状态任务数量统计\n\n状态：todo, in_progress, done",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "看板",
            "code_template": "class KanbanBoard:\n    def __init__(self):\n        # 请初始化\n        pass\n    \n    def add_task(self, task, status='todo'):\n        # 请实现\n        pass\n    \n    def move_task(self, task, new_status):\n        # 请实现\n        pass\n    \n    def get_tasks(self, status):\n        # 请实现\n        pass\n    \n    def get_stats(self):\n        # 请实现\n        pass",
            "test_cases": "[]",
            "solution": "class KanbanBoard:\n    def __init__(self):\n        self.board = {'todo': [], 'in_progress': [], 'done': []}\n    \n    def add_task(self, task, status='todo'):\n        if status in self.board:\n            self.board[status].append(task)\n    \n    def move_task(self, task, new_status):\n        for status in self.board:\n            if task in self.board[status]:\n                self.board[status].remove(task)\n                self.board[new_status].append(task)\n                return True\n        return False\n    \n    def get_tasks(self, status):\n        return self.board.get(status, [])\n    \n    def get_stats(self):\n        return {s: len(tasks) for s, tasks in self.board.items()}",
            "hint": "使用字典存储各状态的任务列表",
        },
        {
            "title": "实现Git提交信息生成器",
            "description": "编写函数generate_commit_message(type, scope, message)，\n生成符合Conventional Commits规范的提交信息。\n\n格式：type(scope): message\n\ntype类型：feat, fix, docs, style, refactor, test, chore\n\n返回格式化的提交信息字符串",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "Git提交规范",
            "code_template": "def generate_commit_message(type, scope, message):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"feat, auth, add login feature\", \"expected\": \"feat(auth): add login feature\"}]",
            "solution": "def generate_commit_message(type, scope, message):\n    valid_types = ['feat', 'fix', 'docs', 'style', 'refactor', 'test', 'chore']\n    if type not in valid_types:\n        raise ValueError(f'Invalid type: {type}')\n    return f'{type}({scope}): {message}'",
            "hint": "验证type是否有效，然后格式化字符串",
        },
        {
            "title": "实现简单的需求追踪矩阵",
            "description": "实现RequirementMatrix类，管理需求到测试用例的映射。\n\n功能：\n- add_requirement(req_id, description): 添加需求\n- add_test_case(req_id, case_id): 关联测试用例\n- get_coverage(): 返回需求覆盖率\n- get_uncovered(): 返回未覆盖的需求列表",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "需求分析",
            "knowledge_point": "需求追踪",
            "code_template": "class RequirementMatrix:\n    def __init__(self):\n        # 请初始化\n        pass\n    \n    def add_requirement(self, req_id, description):\n        # 请实现\n        pass\n    \n    def add_test_case(self, req_id, case_id):\n        # 请实现\n        pass\n    \n    def get_coverage(self):\n        # 请实现\n        pass\n    \n    def get_uncovered(self):\n        # 请实现\n        pass",
            "test_cases": "[]",
            "solution": "class RequirementMatrix:\n    def __init__(self):\n        self.requirements = {}\n        self.mappings = {}\n    \n    def add_requirement(self, req_id, description):\n        self.requirements[req_id] = description\n        self.mappings[req_id] = []\n    \n    def add_test_case(self, req_id, case_id):\n        if req_id in self.mappings:\n            self.mappings[req_id].append(case_id)\n    \n    def get_coverage(self):\n        if not self.requirements:\n            return 0.0\n        covered = sum(1 for cases in self.mappings.values() if cases)\n        return round(covered / len(self.requirements), 2)\n    \n    def get_uncovered(self):\n        return [req_id for req_id, cases in self.mappings.items() if not cases]",
            "hint": "使用字典存储需求和映射关系",
        },
        {
            "title": "实现迭代速度计算器",
            "description": "编写类VelocityTracker，追踪团队迭代速度。\n\n功能：\n- add_sprint(completed_points): 添加Sprint完成的故事点\n- get_average(): 返回平均速度\n- get_trend(): 返回速度趋势（increasing/decreasing/stable）\n- predict_next(): 预测下一Sprint完成的点数",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "Velocity",
            "code_template": "class VelocityTracker:\n    def __init__(self):\n        # 请初始化\n        pass\n    \n    def add_sprint(self, completed_points):\n        # 请实现\n        pass\n    \n    def get_average(self):\n        # 请实现\n        pass\n    \n    def get_trend(self):\n        # 请实现\n        pass\n    \n    def predict_next(self):\n        # 请实现\n        pass",
            "test_cases": "[{\"input\": \"t=VelocityTracker(); t.add_sprint(10); t.add_sprint(12); t.get_average()\", \"expected\": \"11\"}]",
            "solution": "class VelocityTracker:\n    def __init__(self):\n        self.sprints = []\n    \n    def add_sprint(self, completed_points):\n        self.sprints.append(completed_points)\n    \n    def get_average(self):\n        return sum(self.sprints) / len(self.sprints) if self.sprints else 0\n    \n    def get_trend(self):\n        if len(self.sprints) < 3:\n            return 'stable'\n        recent = self.sprints[-3:]\n        if recent[-1] > recent[0]:\n            return 'increasing'\n        elif recent[-1] < recent[0]:\n            return 'decreasing'\n        return 'stable'\n    \n    def predict_next(self):\n        return round(self.get_average())",
            "hint": "使用列表存储Sprint数据，计算平均值和趋势",
        },
        {
            "title": "实现简单的风险评估器",
            "description": "编写函数assess_risk(probability, impact)，评估风险等级。\n\nprobability: 1-5（概率）\nimpact: 1-5（影响）\n\n风险值 = probability * impact\n返回 (risk_level, risk_score)\n- 1-5: low\n- 6-12: medium\n- 13-19: high\n- 20-25: critical",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "项目管理",
            "knowledge_point": "风险管理",
            "code_template": "def assess_risk(probability, impact):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"3, 4\", \"expected\": \"(medium, 12)\"}]",
            "solution": "def assess_risk(probability, impact):\n    score = probability * impact\n    if score <= 5:\n        level = 'low'\n    elif score <= 12:\n        level = 'medium'\n    elif score <= 19:\n        level = 'high'\n    else:\n        level = 'critical'\n    return (level, score)",
            "hint": "计算风险值后判断等级",
        },
        {
            "title": "实现代码复杂度计算器",
            "description": "编写函数calculate_cyclomatic_complexity(code)，\n计算代码的圈复杂度（简化版）。\n\n统计代码中以下关键字的数量：\nif, elif, for, while, and, or, except\n\n返回复杂度 = 关键字数量 + 1",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "代码复杂度",
            "code_template": "def calculate_cyclomatic_complexity(code):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"if a and b: pass\", \"expected\": \"3\"}]",
            "solution": "def calculate_cyclomatic_complexity(code):\n    keywords = ['if', 'elif', 'for', 'while', 'and', 'or', 'except']\n    count = 0\n    for word in code.split():\n        if word in keywords:\n            count += 1\n    return count + 1",
            "hint": "使用split()分割代码，统计关键字出现次数",
        },
        {
            "title": "实现简单的版本号比较器",
            "description": "编写函数compare_versions(version1, version2)，比较两个版本号。\n\n版本号格式：major.minor.patch（如1.2.3）\n\n返回值：\n- 1: version1 > version2\n- -1: version1 < version2\n- 0: 相等",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "版本管理",
            "code_template": "def compare_versions(version1, version2):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"1.2.3, 1.2.4\", \"expected\": \"-1\"}]",
            "solution": "def compare_versions(version1, version2):\n    v1 = list(map(int, version1.split('.')))\n    v2 = list(map(int, version2.split('.')))\n    for a, b in zip(v1, v2):\n        if a > b: return 1\n        if a < b: return -1\n    return 0",
            "hint": "分割版本号后逐位比较",
        },
        {
            "title": "实现技术债务计算器",
            "description": "编写类TechnicalDebtTracker，追踪技术债务。\n\n功能：\n- add_debt(description, effort_hours, priority): 添加债务\n- get_total_effort(): 返回总工时\n- get_by_priority(priority): 返回指定优先级的债务列表\n- get_summary(): 返回统计摘要",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "技术债务",
            "code_template": "class TechnicalDebtTracker:\n    def __init__(self):\n        # 请初始化\n        pass\n    \n    def add_debt(self, description, effort_hours, priority):\n        # 请实现\n        pass\n    \n    def get_total_effort(self):\n        # 请实现\n        pass\n    \n    def get_by_priority(self, priority):\n        # 请实现\n        pass\n    \n    def get_summary(self):\n        # 请实现\n        pass",
            "test_cases": "[]",
            "solution": "class TechnicalDebtTracker:\n    def __init__(self):\n        self.debts = []\n    \n    def add_debt(self, description, effort_hours, priority):\n        self.debts.append({\n            'description': description,\n            'effort_hours': effort_hours,\n            'priority': priority\n        })\n    \n    def get_total_effort(self):\n        return sum(d['effort_hours'] for d in self.debts)\n    \n    def get_by_priority(self, priority):\n        return [d for d in self.debts if d['priority'] == priority]\n    \n    def get_summary(self):\n        by_priority = {}\n        for d in self.debts:\n            p = d['priority']\n            by_priority[p] = by_priority.get(p, 0) + d['effort_hours']\n        return {'total': self.get_total_effort(), 'by_priority': by_priority}",
            "hint": "使用列表存储债务，按优先级分类统计",
        },
        {
            "title": "实现简单的项目进度追踪器",
            "description": "编写类ProjectTracker，追踪项目进度。\n\n功能：\n- add_task(task_name, estimated_hours): 添加任务\n- update_progress(task_name, completed_hours): 更新进度\n- get_task_progress(task_name): 返回任务完成百分比\n- get_overall_progress(): 返回整体进度",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "项目进度",
            "code_template": "class ProjectTracker:\n    def __init__(self):\n        # 请初始化\n        pass\n    \n    def add_task(self, task_name, estimated_hours):\n        # 请实现\n        pass\n    \n    def update_progress(self, task_name, completed_hours):\n        # 请实现\n        pass\n    \n    def get_task_progress(self, task_name):\n        # 请实现\n        pass\n    \n    def get_overall_progress(self):\n        # 请实现\n        pass",
            "test_cases": "[]",
            "solution": "class ProjectTracker:\n    def __init__(self):\n        self.tasks = {}\n    \n    def add_task(self, task_name, estimated_hours):\n        self.tasks[task_name] = {'estimated': estimated_hours, 'completed': 0}\n    \n    def update_progress(self, task_name, completed_hours):\n        if task_name in self.tasks:\n            self.tasks[task_name]['completed'] = min(completed_hours, self.tasks[task_name]['estimated'])\n    \n    def get_task_progress(self, task_name):\n        task = self.tasks.get(task_name)\n        if task and task['estimated'] > 0:\n            return round(task['completed'] / task['estimated'] * 100, 1)\n        return 0.0\n    \n    def get_overall_progress(self):\n        if not self.tasks:\n            return 0.0\n        total_est = sum(t['estimated'] for t in self.tasks.values())\n        total_comp = sum(t['completed'] for t in self.tasks.values())\n        return round(total_comp / total_est * 100, 1) if total_est > 0 else 0.0",
            "hint": "使用字典存储任务信息，计算百分比",
        },
        {
            "title": "实现简单的代码行数统计",
            "description": "编写函数count_code_lines(code_text)，统计代码行数。\n\n返回字典：\n- total: 总行数\n- code: 有效代码行（非空、非注释）\n- comments: 注释行（以#开头）\n- blank: 空行",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "软件工程",
            "knowledge_point": "代码度量",
            "code_template": "def count_code_lines(code_text):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"# comment\\ncode\\n\\nmore code\", \"expected\": \"{total:4, code:2, comments:1, blank:1}\"}]",
            "solution": "def count_code_lines(code_text):\n    lines = code_text.split('\\n')\n    total = len(lines)\n    comments = sum(1 for l in lines if l.strip().startswith('#'))\n    blank = sum(1 for l in lines if not l.strip())\n    code = total - comments - blank\n    return {'total': total, 'code': code, 'comments': comments, 'blank': blank}",
            "hint": "分割行后分别统计各类行数",
        },
        {
            "title": "实现简单的依赖解析器",
            "description": "编写函数resolve_dependencies(deps)，解析依赖关系。\n\ndeps: dict，key为任务，value为依赖的任务列表\n\n返回拓扑排序后的执行顺序列表\n如果存在循环依赖，返回None",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "软件工程",
            "knowledge_point": "依赖管理",
            "code_template": "def resolve_dependencies(deps):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"{A: [], B: [A], C: [B]}\", \"expected\": \"[A, B, C]\"}]",
            "solution": "def resolve_dependencies(deps):\n    result = []\n    visited = set()\n    visiting = set()\n    \n    def visit(node):\n        if node in visiting:\n            return False\n        if node in visited:\n            return True\n        visiting.add(node)\n        for dep in deps.get(node, []):\n            if not visit(dep):\n                return False\n        visiting.remove(node)\n        visited.add(node)\n        result.append(node)\n        return True\n    \n    for node in deps:\n        if not visit(node):\n            return None\n    return result",
            "hint": "使用深度优先搜索实现拓扑排序",
        },
        {
            "title": "实现简单的会议时间安排器",
            "description": "编写函数find_meeting_slot(schedules, duration)，\n找到所有参与者都空闲的时间段。\n\nschedules: dict，人名->忙碌时间段列表 [(start, end), ...]\nduration: 会议时长（分钟）\n\n返回第一个可用的时间段 (start, end)，工作时间9:00-18:00",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "会议安排",
            "code_template": "def find_meeting_slot(schedules, duration):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"schedules={A:[(9,10)], B:[(10,11)]}, duration=60\", \"expected\": \"(11, 12)\"}]",
            "solution": "def find_meeting_slot(schedules, duration):\n    # 合并所有忙碌时间\n    busy = []\n    for person_slots in schedules.values():\n        busy.extend(person_slots)\n    busy.sort()\n    \n    # 寻找空闲时段\n    current = 9\n    for start, end in busy:\n        if start - current >= duration / 60:\n            return (current, current + duration / 60)\n        current = max(current, end)\n    \n    if 18 - current >= duration / 60:\n        return (current, current + duration / 60)\n    return None",
            "hint": "合并所有忙碌时间后寻找空闲时段",
        },
        {
            "title": "实现简单的Sprint燃尽图数据生成",
            "description": "编写函数generate_burndown(total_points, daily_completed)，\n生成燃尽图数据。\n\ntotal_points: 总故事点\ndaily_completed: 每天完成的点数列表\n\n返回字典：\n- ideal: 理想燃尽数据\n- actual: 实际燃尽数据",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "燃尽图",
            "code_template": "def generate_burndown(total_points, daily_completed):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"10, [2, 3, 2, 3]\", \"expected\": \"ideal和actual各5个点\"}]",
            "solution": "def generate_burndown(total_points, daily_completed):\n    days = len(daily_completed)\n    ideal = [total_points - (total_points / days) * i for i in range(days + 1)]\n    actual = [total_points]\n    remaining = total_points\n    for completed in daily_completed:\n        remaining -= completed\n        actual.append(max(0, remaining))\n    return {'ideal': ideal, 'actual': actual}",
            "hint": "理想燃尽是线性递减，实际燃尽根据完成数据计算",
        },
        {
            "title": "实现简单的代码审查评分",
            "description": "编写函数review_code(code)，对代码进行简单评分。\n\n评分规则（每项1分）：\n- 有函数定义\n- 有注释\n- 有异常处理\n- 变量命名规范（无单字符变量）\n- 代码行数<50\n\n返回 (score, details) 元组",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "代码审查",
            "code_template": "def review_code(code):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[]",
            "solution": "def review_code(code):\n    score = 0\n    details = []\n    if 'def ' in code:\n        score += 1\n        details.append('has_function')\n    if '#' in code:\n        score += 1\n        details.append('has_comment')\n    if 'try' in code or 'except' in code:\n        score += 1\n        details.append('has_error_handling')\n    import re\n    if not re.search(r'\\b[a-z]\\b', code):\n        score += 1\n        details.append('good_naming')\n    if len(code.split('\\n')) < 50:\n        score += 1\n        details.append('good_length')\n    return (score, details)",
            "hint": "使用字符串检查和正则表达式判断各项",
        },
        {
            "title": "实现简单的团队负载均衡器",
            "description": "编写函数balance_load(members, tasks)，分配任务给团队成员。\n\nmembers: 成员列表\ntasks: 任务列表，每个任务有name和estimated_hours\n\n返回分配方案：{member: [task_names]}\n尽量平均分配工作量",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "任务分配",
            "code_template": "def balance_load(members, tasks):\n    # 请在此处编写代码\n    pass",
            "test_cases": "[{\"input\": \"members=[A,B], tasks=[{name:T1,hours:4},{name:T2,hours:4},{name:T3,hours:4},{name:T4,hours:4}]\", \"expected\": \"每人2个任务\"}]",
            "solution": "def balance_load(members, tasks):\n    # 按工时排序，贪心分配\n    sorted_tasks = sorted(tasks, key=lambda t: t['estimated_hours'], reverse=True)\n    loads = {m: [] for m in members}\n    hours = {m: 0 for m in members}\n    \n    for task in sorted_tasks:\n        # 分配给当前负载最轻的成员\n        min_member = min(members, key=lambda m: hours[m])\n        loads[min_member].append(task['name'])\n        hours[min_member] += task['estimated_hours']\n    \n    return loads",
            "hint": "使用贪心算法，每次分配给负载最轻的成员",
        },
        # ==================== 简答题 (30题) ====================
        {
            "title": "请解释瀑布模型和敏捷开发的区别",
            "description": "请从开发流程、文档要求、需求变更、适用场景等方面比较瀑布模型和敏捷开发。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "软件开发模型",
            "knowledge_point": "瀑布vs敏捷",
            "solution": "瀑布模型：\n- 流程：线性顺序，需求→设计→开发→测试→部署\n- 文档：详细的文档\n- 变更：变更困难，成本高\n- 适用：需求明确、稳定的项目\n\n敏捷开发：\n- 流程：迭代增量，2-4周一个Sprint\n- 文档：够用即可\n- 变更：欢迎变更\n- 适用：需求不确定、快速变化的项目",
        },
        {
            "title": "请解释Scrum框架的核心要素",
            "description": "请解释Scrum的三个角色、五个事件和三个工件。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "Scrum框架",
            "solution": "三个角色：\n- Product Owner：产品负责人，管理Product Backlog\n- Scrum Master：确保Scrum流程\n- Development Team：开发团队\n\n五个事件：\n- Sprint：迭代周期\n- Sprint Planning：计划会\n- Daily Scrum：每日站会\n- Sprint Review：评审会\n- Sprint Retrospective：回顾会\n\n三个工件：\n- Product Backlog：产品待办列表\n- Sprint Backlog：Sprint待办列表\n- Increment：增量",
        },
        {
            "title": "请解释什么是用户故事",
            "description": "请解释用户故事的定义、格式、特点和验收标准。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "需求分析",
            "knowledge_point": "用户故事",
            "solution": "定义：从用户角度描述需求的简短描述\n\n格式：\nAs a <role>, I want <feature>, so that <benefit>\n\n特点（INVEST）：\n- Independent：独立的\n- Negotiable：可协商的\n- Valuable：有价值的\n- Estimable：可估算的\n- Small：小的\n- Testable：可测试的\n\n验收标准：定义故事完成的条件",
        },
        {
            "title": "请解释需求分析的主要活动",
            "description": "请解释需求分析包括哪些主要活动。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "需求分析",
            "knowledge_point": "需求分析",
            "solution": "主要活动：\n1. 需求获取：访谈、问卷、观察、原型\n2. 需求分析：整理、分类、建模\n3. 需求规格：编写SRS文档\n4. 需求验证：评审、确认\n5. 需求管理：变更控制、追踪\n\n关键输出：\n- 功能需求列表\n- 非功能需求\n- 用例图\n- 用户故事",
        },
        {
            "title": "请解释什么是设计模式",
            "description": "请解释设计模式的定义、分类和常见模式。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "设计模式",
            "knowledge_point": "设计模式",
            "solution": "定义：解决特定问题的可重用方案\n\n分类：\n- 创建型：单例、工厂、建造者\n- 结构型：适配器、装饰器、代理\n- 行为型：观察者、策略、命令\n\n常见模式：\n- 单例：确保一个实例\n- 工厂：解耦创建和使用\n- 观察者：一对多通知\n- 策略：算法可替换",
        },
        {
            "title": "请解释MVC模式",
            "description": "请解释MVC模式的定义、各层职责和优点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "设计模式",
            "knowledge_point": "MVC模式",
            "solution": "定义：Model-View-Controller模式\n\n各层职责：\n- Model：数据和业务逻辑\n- View：用户界面展示\n- Controller：处理用户输入，协调Model和View\n\n优点：\n- 分离关注点\n- 代码可维护性高\n- 可独立修改各层\n\n应用：\n- Web框架（Django, Rails）\n- 桌面应用\n- 移动应用",
        },
        {
            "title": "请解释版本控制的作用",
            "description": "请解释版本控制的定义、主要功能和常用工具。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "版本控制",
            "solution": "定义：记录文件变更历史的系统\n\n主要功能：\n- 追踪变更历史\n- 多人协作\n- 分支管理\n- 版本回退\n- 代码审查\n\n常用工具：\n- Git：分布式\n- SVN：集中式\n- Mercurial：分布式\n\nGit基本命令：\ngit clone, add, commit, push, pull, branch, merge",
        },
        {
            "title": "请解释Git分支策略",
            "description": "请解释常见的Git分支策略（Git Flow, GitHub Flow等）。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "配置管理",
            "knowledge_point": "Git分支策略",
            "solution": "Git Flow：\n- main：生产环境\n- develop：开发主线\n- feature/*：功能分支\n- release/*：发布分支\n- hotfix/*：热修复\n\nGitHub Flow：\n- main：主分支\n- feature branches：功能分支\n- Pull Request：合并请求\n\nTrunk Based：\n- 单一主干\n- 短生命周期分支\n- 频繁集成",
        },
        {
            "title": "请解释持续集成、持续交付、持续部署的区别",
            "description": "请解释CI/CD/CD的区别和联系。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "配置管理",
            "knowledge_point": "CI/CD",
            "solution": "持续集成(CI)：\n- 频繁集成代码\n- 自动化构建和测试\n- 快速发现问题\n\n持续交付(CD)：\n- CI基础上\n- 自动化部署到测试环境\n- 手动部署到生产\n\n持续部署(CD)：\n- 持续交付基础上\n- 自动部署到生产\n- 需要完善的自动化测试",
        },
        {
            "title": "请解释项目管理三角形",
            "description": "请解释项目管理三角形（范围、时间、成本）的关系。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "项目管理",
            "knowledge_point": "项目管理三角形",
            "solution": "三个约束：\n- 范围：项目要做什么\n- 时间：项目何时完成\n- 成本：项目花费多少\n\n关系：\n- 三者相互制约\n- 改变一个会影响其他\n- 质量是中心\n\n示例：\n- 增加范围→增加时间或成本\n- 缩短时间→增加成本或减少范围\n- 减少成本→增加时间或减少范围",
        },
        {
            "title": "请解释风险管理的流程",
            "description": "请解释风险管理的完整流程。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "风险管理",
            "solution": "流程：\n1. 风险识别：找出潜在风险\n2. 风险分析：评估概率和影响\n3. 风险优先级：确定处理顺序\n4. 风险应对：制定应对策略\n5. 风险监控：跟踪风险状态\n\n应对策略：\n- 规避：消除风险\n- 转移：转嫁给第三方\n- 减轻：降低概率或影响\n- 接受：准备应急计划",
        },
        {
            "title": "请解释什么是技术债务",
            "description": "请解释技术债务的定义、类型和管理方法。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "技术债务",
            "solution": "定义：为了短期目标而牺牲代码质量\n\n类型：\n- 故意债务：明知故犯\n- 无意债务：设计不足\n- 环境债务：技术过时\n\n管理方法：\n- 识别和记录\n- 评估影响\n- 制定还债计划\n- 定期重构\n- 建立编码规范",
        },
        {
            "title": "请解释SOLID原则",
            "description": "请解释SOLID五个原则的含义。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "软件工程",
            "knowledge_point": "SOLID原则",
            "solution": "S - 单一职责：一个类只做一件事\nO - 开闭原则：对扩展开放，对修改关闭\nL - 里氏替换：子类可替换父类\nI - 接口隔离：接口要小而专\nD - 依赖倒置：依赖抽象而非具体\n\n目的：\n- 提高代码可维护性\n- 降低耦合度\n- 增强可扩展性",
        },
        {
            "title": "请解释什么是重构",
            "description": "请解释重构的定义、时机和常见技巧。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "重构",
            "solution": "定义：改善代码结构而不改变行为\n\n时机：\n- 代码重复\n- 函数过长\n- 类职责过多\n- 耦合度过高\n\n常见技巧：\n- 提取函数\n- 提取类\n- 重命名\n- 移动方法\n- 简化条件\n\n工具：\n- IDE重构功能\n- 测试保障",
        },
        {
            "title": "请解释什么是代码审查",
            "description": "请解释代码审查的定义、目的和最佳实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "配置管理",
            "knowledge_point": "代码审查",
            "solution": "定义：团队成员互相检查代码\n\n目的：\n- 发现缺陷\n- 提高代码质量\n- 知识共享\n- 统一编码规范\n\n最佳实践：\n- 小批量审查\n- 及时反馈\n- 尊重作者\n- 关注代码而非个人\n- 使用工具辅助",
        },
        {
            "title": "请解释什么是DevOps",
            "description": "请解释DevOps的定义、核心原则和实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "DevOps",
            "solution": "定义：开发和运维协作的文化和实践\n\n核心原则：\n- 文化：协作、信任\n- 自动化：CI/CD\n- 精益：持续改进\n- 度量：监控反馈\n\n实践：\n- 持续集成\n- 持续交付\n- 基础设施即代码\n- 监控和日志\n- 微服务",
        },
        {
            "title": "请解释什么是微服务架构",
            "description": "请解释微服务的定义、特点和与单体架构的区别。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "软件工程",
            "knowledge_point": "微服务",
            "solution": "定义：将应用拆分为小型、独立的服务\n\n特点：\n- 独立部署\n- 技术多样性\n- 团队自治\n- 故障隔离\n\n与单体区别：\n- 单体：一个代码库，统一部署\n- 微服务：多个服务，独立部署\n\n优缺点：\n+ 灵活性高、可扩展\n- 复杂度高、运维成本",
        },
        {
            "title": "请解释什么是测试金字塔",
            "description": "请解释测试金字塔的概念和各层测试的占比。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试策略",
            "knowledge_point": "测试金字塔",
            "solution": "概念：描述自动化测试的理想分布\n\n各层：\n- 底层：单元测试（70%）\n  - 数量多、速度快、成本低\n- 中层：集成测试（20%）\n  - 测试接口和交互\n- 顶层：端到端测试（10%）\n  - 数量少、速度慢、成本高\n\n原则：\n- 越底层越多\n- 越底层越快\n- 越底层越稳定",
        },
        {
            "title": "请解释什么是TDD",
            "description": "请解释测试驱动开发的定义、流程和优缺点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试方法",
            "knowledge_point": "TDD",
            "solution": "定义：先写测试，再写代码\n\n流程（红-绿-重构）：\n1. 红：编写失败的测试\n2. 绿：编写最少代码让测试通过\n3. 重构：优化代码\n\n优点：\n- 代码质量高\n- 测试覆盖率高\n- 设计更好\n- 重构有信心\n\n缺点：\n- 学习曲线陡\n- 初期开发速度慢",
        },
        {
            "title": "请解释敏捷估算方法",
            "description": "请解释计划扑克、T-shirt sizing等敏捷估算方法。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "项目管理",
            "knowledge_point": "敏捷估算",
            "solution": "计划扑克：\n- 使用斐波那契数列卡片\n- 团队成员同时出牌\n- 讨论差异后重新估算\n- 达成共识\n\nT-shirt sizing：\n- 使用XS/S/M/L/XL\n- 快速粗略估算\n- 适合早期估算\n\n宽带德尔菲：\n- 专家独立估算\n- 匿名分享\n- 迭代直到收敛",
        },
        {
            "title": "请解释什么是看板方法",
            "description": "请解释看板的定义、核心原则和实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "看板方法",
            "solution": "定义：可视化工作流程的管理方法\n\n核心原则：\n- 可视化工作\n- 限制在制品(WIP)\n- 管理流动\n- 明确流程规则\n- 持续改进\n\n实践：\n- 看板板：可视化工作\n- WIP限制：控制并行工作\n- 每日站会：同步状态\n- 度量：前置时间、吞吐量",
        },
        {
            "title": "请解释什么是回顾会议",
            "description": "请解释回顾会议的目的、形式和最佳实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "项目管理",
            "knowledge_point": "回顾会议",
            "solution": "目的：总结经验教训，持续改进\n\n形式：\n- 定期举行（Sprint结束）\n- 全员参与\n- 安全的环境\n\n常见问题：\n- 什么做得好？\n- 什么可以改进？\n- 下一步行动？\n\n最佳实践：\n- 聚焦过程而非个人\n- 产生具体行动项\n- 跟踪改进效果",
        },
        {
            "title": "请解释什么是产品待办列表",
            "description": "请解释Product Backlog的定义、特点和管理方法。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "软件开发模型",
            "knowledge_point": "Product Backlog",
            "solution": "定义：产品需求的有序列表\n\n特点：\n- 动态的\n- 有序的\n- 详细的\n- 估算的\n\n管理方法：\n- Product Owner负责\n- 定期梳理(Refinement)\n- 优先级排序\n- 持续更新\n\n条目类型：\n- 用户故事\n- 技术任务\n- 缺陷\n- 知识获取",
        },
        {
            "title": "请解释什么是持续改进",
            "description": "请解释持续改进的概念和在软件开发中的应用。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "持续改进",
            "solution": "概念：不断优化流程和产品\n\n方法：\n- PDCA循环：计划-执行-检查-行动\n- Kaizen：小步改进\n- 回顾会议\n\n应用：\n- 代码重构\n- 流程优化\n- 工具改进\n- 技能提升\n\n度量：\n- 缺陷率\n- 交付周期\n- 代码质量",
        },
        {
            "title": "请解释什么是软件质量",
            "description": "请解释软件质量的定义、维度和度量方法。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件工程",
            "knowledge_point": "软件质量",
            "solution": "定义：软件满足需求的程度\n\n维度：\n- 功能性：满足需求\n- 可靠性：稳定运行\n- 易用性：用户友好\n- 效率：资源利用\n- 可维护性：易于修改\n- 可移植性：跨平台\n\n度量方法：\n- 缺陷密度\n- 代码覆盖率\n- 圈复杂度\n- 用户满意度",
        },
        {
            "title": "请解释什么是配置管理",
            "description": "请解释配置管理的定义、活动和重要性。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "配置管理",
            "knowledge_point": "配置管理",
            "solution": "定义：识别和管理软件配置项\n\n活动：\n- 配置项识别\n- 版本控制\n- 变更控制\n- 配置审计\n- 状态报告\n\n重要性：\n- 追踪变更\n- 保证一致性\n- 支持并行开发\n- 问题可回溯\n\n工具：\n- Git, SVN\n- Jenkins\n- Ansible",
        },
        {
            "title": "请解释什么是敏捷教练",
            "description": "请解释Scrum Master的角色和职责。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "Scrum Master",
            "solution": "定义：Scrum流程的守护者\n\n职责：\n- 教练：指导团队理解Scrum\n- 服务型领导：移除障碍\n- 引导者：促进会议\n- 变革代理人：推动改进\n\n不做：\n- 不是项目经理\n- 不分配任务\n- 不做技术决策\n\n技能：\n- 沟通能力\n- 引导技巧\n- 冲突解决",
        },
        {
            "title": "请解释什么是产品负责人",
            "description": "请解释Product Owner的角色和职责。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "软件开发模型",
            "knowledge_point": "Product Owner",
            "solution": "定义：产品价值的最大化者\n\n职责：\n- 管理Product Backlog\n- 定义用户故事\n- 确定优先级\n- 接受或拒绝工作\n- 与利益相关者沟通\n\n技能：\n- 产品愿景\n- 需求分析\n- 沟通协调\n- 决策能力\n\n挑战：\n- 平衡各方需求\n- 管理期望\n- 保持专注",
        },
    ]
}
