"""initial_schema

Revision ID: f95900275eee
Revises: 
Create Date: 2026-04-15 00:30:20.265998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95900275eee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_question_records')
    op.drop_table('audit_logs')
    op.drop_table('interview_question_collections')
    op.drop_table('auto_test_steps')
    with op.batch_alter_table('test_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_scenarios_webhook_token'))

    op.drop_table('test_scenarios')
    op.drop_table('admin_users')
    op.drop_table('auto_test_plans')
    op.drop_table('auto_test_cases')
    op.drop_table('auto_test_report_results')
    op.drop_table('scheduled_tasks')
    op.drop_table('auto_test_reports')
    with op.batch_alter_table('auto_test_groups', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_auto_test_groups_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)

    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_answers_id'), ['id'], unique=False)

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempts_id'), ['id'], unique=False)

    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_cases', sa.Text(), nullable=True, comment='测试用例JSON格式，代码题用'))
        batch_op.create_index(batch_op.f('ix_exam_questions_id'), ['id'], unique=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_id'), ['id'], unique=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_user_post_favorite'), type_='unique')
        batch_op.create_index(batch_op.f('ix_favorites_id'), ['id'], unique=False)

    with op.batch_alter_table('interface_test_cases', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_interface_test_cases_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('interface_test_environments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('base_url',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_interface_test_environments_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('interface_test_folders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_interface_test_folders_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('description')

    with op.batch_alter_table('interface_test_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interface_test_plans_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('interface_test_report_results', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('case_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_interface_test_report_results_id'), ['id'], unique=False)

    with op.batch_alter_table('interface_test_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interface_test_reports_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_interview_questions_id'), ['id'], unique=False)
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('interview_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_interview_sessions_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'submissions', ['latest_submission_id'], ['id'])
        batch_op.create_foreign_key(None, 'interview_questions', ['question_id'], ['id'])

    with op.batch_alter_table('interview_test_cases', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_interview_test_cases_id'), ['id'], unique=False)

    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_user_comment_like'), type_='unique')
        batch_op.drop_constraint(batch_op.f('unique_user_post_like'), type_='unique')
        batch_op.create_index(batch_op.f('ix_likes_id'), ['id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_id'), ['id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_submissions_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_id'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_id'))

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_id'))
        batch_op.create_unique_constraint(batch_op.f('unique_user_post_like'), ['user_id', 'post_id'])
        batch_op.create_unique_constraint(batch_op.f('unique_user_comment_like'), ['user_id', 'comment_id'])

    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin_users', ['admin_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_learning_paths_id'))

    with op.batch_alter_table('interview_test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_test_cases_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_interview_sessions_id'))
        batch_op.alter_column('interview_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_interview_questions_id'))
        batch_op.alter_column('tags',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('interface_test_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_interface_test_reports_id'))

    with op.batch_alter_table('interface_test_report_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interface_test_report_results_id'))
        batch_op.alter_column('url',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('case_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('interface_test_plans', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_interface_test_plans_id'))

    with op.batch_alter_table('interface_test_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'interface_test_folders', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_interface_test_folders_id'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('interface_test_environments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_interface_test_environments_id'))
        batch_op.alter_column('base_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('interface_test_cases', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_interface_test_cases_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_id'))
        batch_op.create_unique_constraint(batch_op.f('unique_user_post_favorite'), ['user_id', 'post_id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin_users', ['admin_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_exercises_id'))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_id'))

    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_id'))
        batch_op.drop_column('test_cases')

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempts_id'))

    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_answers_id'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_id'))

    with op.batch_alter_table('auto_test_groups', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_auto_test_groups_id'))
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('auto_test_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('plan_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('total_count', sa.INTEGER(), nullable=True),
    sa.Column('success_count', sa.INTEGER(), nullable=True),
    sa.Column('failed_count', sa.INTEGER(), nullable=True),
    sa.Column('total_time', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('executed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['auto_test_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('cron_expression', sa.VARCHAR(length=50), nullable=False),
    sa.Column('env_id', sa.INTEGER(), nullable=True),
    sa.Column('webhook_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_run_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['test_scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_test_report_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('case_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), nullable=True),
    sa.Column('url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('status_code', sa.INTEGER(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.Column('time_ms', sa.INTEGER(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('request_headers', sa.TEXT(), nullable=True),
    sa.Column('request_body', sa.TEXT(), nullable=True),
    sa.Column('response_body', sa.TEXT(), nullable=True),
    sa.Column('response_headers', sa.TEXT(), nullable=True),
    sa.Column('executed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['auto_test_cases.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['auto_test_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_test_cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('folder_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('url', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('headers', sa.TEXT(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('body_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('extractors', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('assertions', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['auto_test_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_test_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('environment_id', sa.INTEGER(), nullable=True),
    sa.Column('case_ids', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('data_matrix', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['interface_test_environments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=500), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login_ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('test_scenarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('environment_id', sa.INTEGER(), nullable=True),
    sa.Column('case_ids', sa.TEXT(), nullable=False),
    sa.Column('data_matrix', sa.TEXT(), nullable=True),
    sa.Column('cron_expression', sa.VARCHAR(length=50), nullable=True),
    sa.Column('webhook_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('webhook_token', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_scenarios_webhook_token'), ['webhook_token'], unique=1)

    op.create_table('auto_test_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), nullable=False),
    sa.Column('api_case_id', sa.INTEGER(), nullable=False),
    sa.Column('step_order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('variable_overrides', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('extractors', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['api_case_id'], ['auto_test_cases.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['auto_test_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_question_collections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name=op.f('unique_user_interview_question'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=200), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_question_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('user_answer', sa.TEXT(), nullable=True),
    sa.Column('ai_feedback', sa.TEXT(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('is_answered', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
