"""
测试用例设计 - 90题
知识点: 等价类划分、边界值分析、判定表、因果图、正交试验、场景法、错误推测法
"""

EXERCISES = {
    "测试用例设计方法": [
        # ==================== 选择题 (35题) ====================
        # --- 等价类划分 (6题) ---
        {
            "title": "等价类划分的基本概念",
            "description": "等价类划分法将输入数据划分为若干等价类，从每个等价类中选取什么作为测试用例？",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "B",
        },
        {
            "title": "有效等价类与无效等价类",
            "description": "某系统要求用户年龄在18-60之间，以下哪个属于无效等价类？\nA. 25\nB. 45\nC. 15\nD. 30",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "C",
        },
        {
            "title": "等价类划分的覆盖原则",
            "description": "使用等价类划分法设计测试用例时，应该至少覆盖多少个有效等价类和无效等价类？",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "A",
        },
        {
            "title": "等价类的划分粒度",
            "description": "以下关于等价类划分的说法，哪个是正确的？\nA. 等价类划分越细越好\nB. 每个等价类至少选取一个代表值\nC. 无效等价类不需要测试\nD. 等价类只能用于数值输入",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "B",
        },
        {
            "title": "多输入等价类组合",
            "description": "当系统有两个输入参数，每个参数各划分为3个等价类时，使用完全组合需要多少个测试用例？",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "C",
        },
        {
            "title": "等价类划分的局限性",
            "description": "等价类划分法不适用于以下哪种场景？\nA. 输入参数有明确取值范围\nB. 输入参数之间存在依赖关系\nC. 输入为枚举类型\nD. 输入为布尔类型",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "B",
        },
        # --- 边界值分析 (6题) ---
        {
            "title": "边界值分析的基本概念",
            "description": "边界值分析法主要关注什么位置的测试数据？\nA. 等价类内部\nB. 等价类边界\nC. 随机数据\nD. 默认值",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "B",
        },
        {
            "title": "边界值的取值方法",
            "description": "对于范围[1, 100]的输入，边界值分析法应选取哪些值？\nA. 0, 1, 100, 101\nB. 1, 50, 100\nC. 0, 100\nD. 1, 2, 99, 100",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "A",
        },
        {
            "title": "边界值与等价类的关系",
            "description": "边界值分析法通常与哪种方法结合使用？\nA. 等价类划分\nB. 场景法\nC. 错误推测法\nD. 因果图",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "A",
        },
        {
            "title": "边界值缺陷的统计规律",
            "description": "根据软件缺陷的统计规律，缺陷最常出现在什么位置？\nA. 输入范围的中间值\nB. 输入范围的边界\nC. 默认值\nD. 随机位置",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "B",
        },
        {
            "title": "健壮性测试的边界值",
            "description": "健壮性边界值测试在基本边界值基础上增加了什么？\nA. 最大值和最小值\nB. 略超过边界的值\nC. 中间值\nD. 特殊字符",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "B",
        },
        {
            "title": "多变量边界值分析",
            "description": "当有两个相互独立的输入变量，每个变量有3个边界值时，最简边界值分析需要多少用例？",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "C",
        },
        # --- 判定表 (5题) ---
        {
            "title": "判定表的基本结构",
            "description": "判定表由哪四个部分组成？\nA. 条件桩、动作桩、条件项、动作项\nB. 输入、输出、处理、反馈\nC. 前置条件、后置条件、触发器、结果\nD. 规则、条件、动作、结果",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "A",
        },
        {
            "title": "判定表的适用场景",
            "description": "判定表最适合用于什么类型的测试？\nA. 性能测试\nB. 多条件组合的逻辑测试\nC. 界面测试\nD. 兼容性测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "B",
        },
        {
            "title": "判定表规则数计算",
            "description": "如果判定表有4个条件，每个条件有2个取值(是/否)，最多有多少条规则？",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "D",
        },
        {
            "title": "判定表的简化",
            "description": "以下哪种情况可以合并判定表中的规则？\nA. 条件项相同，动作项不同\nB. 条件项不同，动作项相同\nC. 只有一个条件项不同，动作项相同\nD. 所有条件项都不同",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "C",
        },
        {
            "title": "判定表的局限性",
            "description": "判定表方法的主要局限性是什么？\nA. 不能处理多条件\nB. 条件过多时规则数爆炸\nC. 不能表示动作\nD. 只能用于数值输入",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "B",
        },
        # --- 因果图 (4题) ---
        {
            "title": "因果图的基本概念",
            "description": "因果图中，C表示原因，E表示效果，因果关系的基本符号包括哪些？\nA. 恒等、非、或、与\nB. 加、减、乘、除\nC. 输入、输出、处理、存储\nD. 以上都不对",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "因果图",
            "solution": "A",
        },
        {
            "title": "因果图与判定表的关系",
            "description": "因果图方法最终需要转换为什么来设计测试用例？\nA. 流程图\nB. 判定表\nC. 状态图\nD. 用例图",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "因果图",
            "solution": "B",
        },
        {
            "title": "因果图的约束关系",
            "description": "因果图中的E约束(exclusive)表示什么？\nA. 两个原因不能同时为真\nB. 两个原因必须同时为真\nC. 至少一个原因为真\nD. 原因和结果互斥",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "因果图",
            "solution": "A",
        },
        {
            "title": "因果图的适用场景",
            "description": "因果图方法最适合用于以下哪种场景？\nA. 界面布局测试\nB. 输入条件之间存在约束和依赖关系\nC. 性能压力测试\nD. 安装卸载测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "因果图",
            "solution": "B",
        },
        # --- 正交试验 (4题) ---
        {
            "title": "正交试验法的基本概念",
            "description": "正交试验法的核心思想是什么？\nA. 测试所有可能的组合\nB. 用最少的用例覆盖最多的因素组合\nC. 随机选择测试数据\nD. 只测试边界值",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "正交试验",
            "solution": "B",
        },
        {
            "title": "正交表的表示方法",
            "description": "正交表L9(3^4)表示什么含义？\nA. 9次试验，4个因素，每个因素3个水平\nB. 9个因素，4次试验\nC. 3次试验，9个因素\nD. 4次试验，3个因素",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "正交试验",
            "solution": "A",
        },
        {
            "title": "正交试验的特点",
            "description": "正交试验法的两个重要特点是什么？\nA. 均匀分散、整齐可比\nB. 完全随机、全面覆盖\nC. 逐步递增、逐步递减\nD. 以上都不对",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "正交试验",
            "solution": "A",
        },
        {
            "title": "正交表的选择",
            "description": "有3个因素，每个因素有3个水平，应该选择哪个正交表？\nA. L4(2^3)\nB. L9(3^4)\nC. L8(2^7)\nD. L16(4^5)",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "正交试验",
            "solution": "B",
        },
        # --- 场景法 (5题) ---
        {
            "title": "场景法的基本概念",
            "description": "场景法基于什么来设计测试用例？\nA. 代码结构\nB. 事件触发流程\nC. 数据库设计\nD. 界面设计",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "solution": "B",
        },
        {
            "title": "基本流与备选流",
            "description": "在场景法中，基本流是指什么？\nA. 错误的操作流程\nB. 从开始到结束的最短路径\nC. 用户最可能的操作流程\nD. 系统默认的处理流程",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "solution": "C",
        },
        {
            "title": "场景法的覆盖标准",
            "description": "场景法至少需要覆盖哪些场景？\nA. 只覆盖基本流\nB. 基本流和所有备选流\nC. 随机选择几个场景\nD. 只覆盖异常场景",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "solution": "B",
        },
        {
            "title": "场景法与用例的关系",
            "description": "场景法最适合用于测试什么？\nA. 单个函数\nB. 端到端的业务流程\nC. 数据库查询\nD. 接口参数",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "solution": "B",
        },
        {
            "title": "备选流的识别",
            "description": "以下哪个不属于备选流？\nA. 用户取消操作\nB. 系统超时\nC. 正常登录成功\nD. 输入验证失败",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "solution": "C",
        },
        # --- 错误推测法 (3题) ---
        {
            "title": "错误推测法的基本概念",
            "description": "错误推测法主要依赖什么来设计测试用例？\nA. 数学模型\nB. 测试人员的经验和直觉\nC. 自动化工具\nD. 需求文档",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "错误推测法",
            "solution": "B",
        },
        {
            "title": "常见的错误推测场景",
            "description": "以下哪个场景最适合使用错误推测法？\nA. 测试空值输入\nB. 测试正常业务流程\nC. 测试性能指标\nD. 测试界面美观度",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "错误推测法",
            "solution": "A",
        },
        {
            "title": "错误推测法的补充作用",
            "description": "错误推测法通常作为什么方法的补充？\nA. 系统化的测试设计方法\nB. 性能测试方法\nC. 自动化测试方法\nD. 回归测试方法",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "错误推测法",
            "solution": "A",
        },
        # --- 综合 (2题) ---
        {
            "title": "测试设计方法的选择",
            "description": "针对一个有复杂业务规则的系统，应该优先选择哪种测试设计方法？\nA. 等价类划分\nB. 边界值分析\nC. 判定表\nD. 随机测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试设计方法选择",
            "solution": "C",
        },
        {
            "title": "测试设计方法的组合使用",
            "description": "在实际项目中，最佳实践是怎样的？\nA. 只使用一种测试设计方法\nB. 根据不同场景组合使用多种方法\nC. 只使用自动化工具\nD. 只依赖经验测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "测试设计方法选择",
            "solution": "B",
        },

        # ==================== 编程题 (25题) ====================
        # --- 等价类划分实现 (5题) ---
        {
            "title": "实现等价类划分器",
            "description": "编写函数classify_age(age)，根据年龄范围划分等价类。\n\n规则:\n- 无效(负数): return invalid\n- 儿童(0-12): return child\n- 青少年(13-17): return teen\n- 成人(18-64): return adult\n- 老年(65+): return senior",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "code_template": "def classify_age(age):\n    pass",
            "test_cases": "[{\"input\": \"25\", \"expected\": \"adult\"}, {\"input\": \"10\", \"expected\": \"child\"}, {\"input\": \"-1\", \"expected\": \"invalid\"}]",
            "solution": "def classify_age(age):\n    if age < 0: return invalid\n    if age <= 12: return child\n    if age <= 17: return teen\n    if age <= 64: return adult\n    return senior",
            "hint": "使用if-elif-else链判断年龄范围",
        },
        {
            "title": "实现密码强度等价类判断",
            "description": "编写函数check_password_strength(password)，判断密码强度。\n\n规则:\n- 长度<6: weak\n- 长度6-11，只有字母或数字: medium\n- 长度6-11，包含字母和数字: strong\n- 长度>=12，包含字母数字特殊字符: very_strong",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "code_template": "def check_password_strength(password):\n    pass",
            "test_cases": "[{\"input\": \"abc\", \"expected\": \"weak\"}, {\"input\": \"abcdef\", \"expected\": \"medium\"}, {\"input\": \"abc123\", \"expected\": \"strong\"}]",
            "solution": "def check_password_strength(password):\n    length = len(password)\n    has_letter = any(c.isalpha() for c in password)\n    has_digit = any(c.isdigit() for c in password)\n    has_special = any(not c.isalnum() for c in password)\n    if length < 6: return weak\n    if length < 12:\n        if has_letter and has_digit: return strong\n        return medium\n    if has_letter and has_digit and has_special: return very_strong\n    return strong",
            "hint": "使用any()函数检查字符类型",
        },
        {
            "title": "实现成绩等级等价类",
            "description": "编写函数grade_score(score)，将分数转换为等级。\n\n0-59: F\n60-69: D\n70-79: C\n80-89: B\n90-100: A\n其他: invalid",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "code_template": "def grade_score(score):\n    pass",
            "test_cases": "[{\"input\": \"85\", \"expected\": \"B\"}, {\"input\": \"55\", \"expected\": \"F\"}, {\"input\": \"101\", \"expected\": \"invalid\"}]",
            "solution": "def grade_score(score):\n    if score < 0 or score > 100: return invalid\n    if score < 60: return F\n    if score < 70: return D\n    if score < 80: return C\n    if score < 90: return B\n    return A",
            "hint": "从低到高逐级判断",
        },
        {
            "title": "实现BMI等价类分类",
            "description": "编写函数classify_bmi(weight, height_m)，计算BMI并分类。\n\nBMI = weight / height_m^2\n<18.5: underweight\n18.5-24.9: normal\n25-29.9: overweight\n>=30: obese",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "code_template": "def classify_bmi(weight, height_m):\n    pass",
            "test_cases": "[{\"input\": \"70, 1.75\", \"expected\": \"normal\"}, {\"input\": \"45, 1.70\", \"expected\": \"underweight\"}]",
            "solution": "def classify_bmi(weight, height_m):\n    bmi = weight / (height_m ** 2)\n    if bmi < 18.5: return underweight\n    if bmi < 25: return normal\n    if bmi < 30: return overweight\n    return obese",
            "hint": "先计算BMI再判断范围",
        },
        {
            "title": "实现三角形类型等价类",
            "description": "编写函数classify_triangle(a, b, c)，判断三角形类型。\n\n不能构成三角形: invalid\n三边相等: equilateral\n两边相等: isosceles\n三边不等: scalene",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "code_template": "def classify_triangle(a, b, c):\n    pass",
            "test_cases": "[{\"input\": \"3, 3, 3\", \"expected\": \"equilateral\"}, {\"input\": \"3, 4, 5\", \"expected\": \"scalene\"}, {\"input\": \"1, 2, 10\", \"expected\": \"invalid\"}]",
            "solution": "def classify_triangle(a, b, c):\n    if a + b <= c or a + c <= b or b + c <= a: return invalid\n    if a == b == c: return equilateral\n    if a == b or b == c or a == c: return isosceles\n    return scalene",
            "hint": "先判断能否构成三角形",
        },
        # --- 边界值分析实现 (5题) ---
        {
            "title": "实现边界值测试数据生成器",
            "description": "编写函数generate_boundary_values(min_val, max_val)，生成边界值测试数据列表。\n\n返回: [min-1, min, min+1, max-1, max, max+1]",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "code_template": "def generate_boundary_values(min_val, max_val):\n    pass",
            "test_cases": "[{\"input\": \"1, 100\", \"expected\": \"[0, 1, 2, 99, 100, 101]\"}]",
            "solution": "def generate_boundary_values(min_val, max_val):\n    return [min_val-1, min_val, min_val+1, max_val-1, max_val, max_val+1]",
            "hint": "直接计算边界值及相邻值",
        },
        {
            "title": "实现范围验证器",
            "description": "编写函数validate_range(value, min_val, max_val)，验证值是否在范围内。\n\n在范围内: valid\n小于最小值: below_minimum\n大于最大值: above_maximum",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "code_template": "def validate_range(value, min_val, max_val):\n    pass",
            "test_cases": "[{\"input\": \"50, 1, 100\", \"expected\": \"valid\"}, {\"input\": \"0, 1, 100\", \"expected\": \"below_minimum\"}]",
            "solution": "def validate_range(value, min_val, max_val):\n    if value < min_val: return below_minimum\n    if value > max_val: return above_maximum\n    return valid",
            "hint": "用if判断上下界",
        },
        {
            "title": "实现字符串长度边界检查",
            "description": "编写函数check_string_length(s, min_len, max_len)，检查字符串长度。\n\n太短: too_short\n太长: too_long\n合法: valid\n为空: empty",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "code_template": "def check_string_length(s, min_len, max_len):\n    pass",
            "test_cases": "[{\"input\": \"hello, 3, 10\", \"expected\": \"valid\"}, {\"input\": \"ab, 3, 10\", \"expected\": \"too_short\"}]",
            "solution": "def check_string_length(s, min_len, max_len):\n    if not s: return empty\n    if len(s) < min_len: return too_short\n    if len(s) > max_len: return too_long\n    return valid",
            "hint": "先检查空字符串，再判断长度范围",
        },
        {
            "title": "实现数组边界访问器",
            "description": "编写函数safe_access(arr, index)，安全访问数组元素。\n\n越界: out_of_bounds\n成功: 返回对应元素",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "code_template": "def safe_access(arr, index):\n    pass",
            "test_cases": "[{\"input\": \"[1,2,3], 0\", \"expected\": \"1\"}, {\"input\": \"[1,2,3], 5\", \"expected\": \"out_of_bounds\"}]",
            "solution": "def safe_access(arr, index):\n    if index < 0 or index >= len(arr): return out_of_bounds\n    return arr[index]",
            "hint": "检查index是否在0到len(arr)-1范围内",
        },
        {
            "title": "实现日期边界验证",
            "description": "编写函数validate_date(year, month, day)，验证日期是否有效。\n\n月份1-12，日期根据月份天数判断，闰年2月29天",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "code_template": "def validate_date(year, month, day):\n    pass",
            "test_cases": "[{\"input\": \"2024, 2, 29\", \"expected\": \"valid\"}, {\"input\": \"2023, 2, 29\", \"expected\": \"invalid\"}]",
            "solution": "def validate_date(year, month, day):\n    if month < 1 or month > 12: return invalid\n    days = [31,29 if year%4==0 and (year%100!=0 or year%400==0) else 28,31,30,31,30,31,31,30,31,30,31]\n    if day < 1 or day > days[month-1]: return invalid\n    return valid",
            "hint": "注意闰年判断和每月天数",
        },
        # --- 判定表实现 (5题) ---
        {
            "title": "实现简单的判定表引擎",
            "description": "编写函数evaluate_rules(age, income, credit)，根据规则判断是否批准贷款。\n\n规则:\n- age>=18 AND income>=30000: approved\n- age>=18 AND income<30000 AND credit=good: review\n- 其他: denied",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "code_template": "def evaluate_rules(age, income, credit):\n    pass",
            "test_cases": "[{\"input\": \"25, 50000, good\", \"expected\": \"approved\"}, {\"input\": \"25, 20000, good\", \"expected\": \"review\"}, {\"input\": \"15, 50000, good\", \"expected\": \"denied\"}]",
            "solution": "def evaluate_rules(age, income, credit):\n    if age >= 18 and income >= 30000: return approved\n    if age >= 18 and income < 30000 and credit == good: return review\n    return denied",
            "hint": "按照规则优先级从高到低判断",
        },
        {
            "title": "实现折扣判定表",
            "description": "编写函数calculate_discount(is_member, purchase_amount, is_holiday)，计算折扣率。\n\n规则:\n- 会员且节日: 20%\n- 会员非节日且>100: 10%\n- 非会员节日且>200: 5%\n- 其他: 0%",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "code_template": "def calculate_discount(is_member, purchase_amount, is_holiday):\n    pass",
            "test_cases": "[{\"input\": \"True, 500, True\", \"expected\": \"20\"}, {\"input\": \"True, 500, False\", \"expected\": \"10\"}, {\"input\": \"False, 500, False\", \"expected\": \"0\"}]",
            "solution": "def calculate_discount(is_member, purchase_amount, is_holiday):\n    if is_member and is_holiday: return 20\n    if is_member and not is_holiday and purchase_amount > 100: return 10\n    if not is_member and is_holiday and purchase_amount > 200: return 5\n    return 0",
            "hint": "逐条判断规则条件",
        },
        {
            "title": "实现权限判定表",
            "description": "编写函数check_permission(role, resource, action)，检查权限。\n\n规则:\n- admin: 全部允许\n- editor + own_content: 允许edit/delete\n- viewer: 只允许read\n- 其他: denied",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "code_template": "def check_permission(role, resource, action):\n    pass",
            "test_cases": "[{\"input\": \"admin, post, delete\", \"expected\": \"allow\"}, {\"input\": \"viewer, post, edit\", \"expected\": \"denied\"}]",
            "solution": "def check_permission(role, resource, action):\n    if role == admin: return allow\n    if role == editor and resource == own_content and action in [edit, delete]: return allow\n    if role == viewer and action == read: return allow\n    return denied",
            "hint": "先判断最高权限角色",
        },
        {
            "title": "实现交通灯判定表",
            "description": "编写函数traffic_action(light, pedestrian, emergency)，判断交通灯动作。\n\n规则:\n- 红灯 + 行人: stop\n- 绿灯 + 紧急车辆: yield\n- 绿灯 + 无紧急: go\n- 黄灯: caution",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "code_template": "def traffic_action(light, pedestrian, emergency):\n    pass",
            "test_cases": "[{\"input\": \"red, True, False\", \"expected\": \"stop\"}, {\"input\": \"green, False, True\", \"expected\": \"yield\"}]",
            "solution": "def traffic_action(light, pedestrian, emergency):\n    if light == yellow: return caution\n    if light == red and pedestrian: return stop\n    if light == green and emergency: return yield\n    if light == green: return go\n    return stop",
            "hint": "先处理黄灯，再处理红绿灯组合",
        },
        {
            "title": "实现保险费率判定表",
            "description": "编写函数calculate_premium(age, has_accident, vehicle_type)，计算保险费率倍数。\n\n规则:\n- age<25 且有事故: 2.5\n- age<25 无事故: 1.8\n- age>=25 有事故: 1.5\n- age>=25 无事故: 1.0\n- 摩托车额外 +0.5",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "code_template": "def calculate_premium(age, has_accident, vehicle_type):\n    pass",
            "test_cases": "[{\"input\": \"20, True, car\", \"expected\": \"2.5\"}, {\"input\": \"30, False, car\", \"expected\": \"1.0\"}, {\"input\": \"30, False, motorcycle\", \"expected\": \"1.5\"}]",
            "solution": "def calculate_premium(age, has_accident, vehicle_type):\n    if age < 25 and has_accident: base = 2.5\n    elif age < 25: base = 1.8\n    elif has_accident: base = 1.5\n    else: base = 1.0\n    if vehicle_type == motorcycle: base += 0.5\n    return base",
            "hint": "先计算基础费率，再加车型附加",
        },
        # --- 场景法实现 (5题) ---
        {
            "title": "实现购物车场景测试",
            "description": "编写函数process_checkout(cart, coupon, payment_method)，处理结账流程。\n\n步骤: 计算小计 -> 应用优惠券 -> 计算税费(8%) -> 返回总金额",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "code_template": "def process_checkout(cart, coupon, payment_method):\n    pass",
            "test_cases": "[{\"input\": \"[100, 200], none, cash\", \"expected\": \"324.0\"}]",
            "solution": "def process_checkout(cart, coupon, payment_method):\n    subtotal = sum(cart)\n    if coupon == SAVE10: subtotal *= 0.9\n    elif coupon == SAVE20: subtotal *= 0.8\n    total = subtotal * 1.08\n    return round(total, 2)",
            "hint": "按步骤计算: 求和、优惠、税费",
        },
        {
            "title": "实现登录流程场景",
            "description": "编写函数login(username, password, captcha, max_attempts)，模拟登录。\n\n成功: success\n验证码错误: captcha_error\n密码错误: 返回剩余次数\n超过次数: locked",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "code_template": "def login(username, password, captcha, max_attempts):\n    pass",
            "test_cases": "[{\"input\": \"admin, admin123, valid, 3\", \"expected\": \"success\"}]",
            "solution": "def login(username, password, captcha, max_attempts):\n    if captcha != valid: return captcha_error\n    if username == admin and password == admin123: return success\n    if max_attempts <= 1: return locked\n    return f attempts remaining: {max_attempts - 1}",
            "hint": "先验证验证码，再验证账号密码",
        },
        {
            "title": "实现订单状态流转",
            "description": "编写函数update_order_status(current_status, action)，模拟订单状态流转。\n\ncreated + pay -> paid\npaid + ship -> shipped\nshipped + deliver -> delivered\n任何状态 + cancel -> cancelled(仅created/paid可取消)",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "code_template": "def update_order_status(current_status, action):\n    pass",
            "test_cases": "[{\"input\": \"created, pay\", \"expected\": \"paid\"}, {\"input\": \"shipped, cancel\", \"expected\": \"invalid_transition\"}]",
            "solution": "def update_order_status(current_status, action):\n    transitions = {created:{pay:paid, cancel:cancelled}, paid:{ship:shipped, cancel:cancelled}, shipped:{deliver:delivered}, delivered:{}}\n    if action in transitions.get(current_status, {}): return transitions[current_status][action]\n    return invalid_transition",
            "hint": "用字典定义状态转换表",
        },
        {
            "title": "实现文件上传场景",
            "description": "编写函数validate_upload(filename, size_mb, allowed_types)，验证文件上传。\n\n文件过大(>10MB): file_too_large\n类型不允许: invalid_type\n成功: valid",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "code_template": "def validate_upload(filename, size_mb, allowed_types):\n    pass",
            "test_cases": "[{\"input\": \"test.jpg, 5, [jpg,png]\", \"expected\": \"valid\"}, {\"input\": \"test.exe, 5, [jpg,png]\", \"expected\": \"invalid_type\"}]",
            "solution": "def validate_upload(filename, size_mb, allowed_types):\n    if size_mb > 10: return file_too_large\n    ext = filename.rsplit(dot, 1)[-1] if dot in filename else \n    if ext not in allowed_types: return invalid_type\n    return valid",
            "hint": "先检查大小，再检查文件扩展名",
        },
        {
            "title": "实现银行取款场景",
            "description": "编写函数withdraw(balance, amount, daily_limit, withdrawn_today)，处理取款。\n\n余额不足: insufficient_funds\n超过日限额: daily_limit_exceeded\n成功: 返回新余额",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "code_template": "def withdraw(balance, amount, daily_limit, withdrawn_today):\n    pass",
            "test_cases": "[{\"input\": \"10000, 5000, 20000, 0\", \"expected\": \"5000\"}, {\"input\": \"10000, 5000, 20000, 18000\", \"expected\": \"daily_limit_exceeded\"}]",
            "solution": "def withdraw(balance, amount, daily_limit, withdrawn_today):\n    if amount > balance: return insufficient_funds\n    if withdrawn_today + amount > daily_limit: return daily_limit_exceeded\n    return balance - amount",
            "hint": "先检查余额，再检查日限额",
        },
        # --- 因果图/正交/错误推测实现 (5题) ---
        {
            "title": "实现因果图逻辑求解器",
            "description": "编写函数evaluate_causal(cause_a, cause_b, relation)，求解因果关系。\n\nrelation=AND: A且B则True\nrelation=OR: A或B则True\nrelation=NOT_A: 非A则True\nrelation=XOR: A异或B则True",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "因果图",
            "code_template": "def evaluate_causal(cause_a, cause_b, relation):\n    pass",
            "test_cases": "[{\"input\": \"True, True, AND\", \"expected\": \"True\"}, {\"input\": \"True, False, XOR\", \"expected\": \"True\"}]",
            "solution": "def evaluate_causal(cause_a, cause_b, relation):\n    if relation == AND: return cause_a and cause_b\n    if relation == OR: return cause_a or cause_b\n    if relation == NOT_A: return not cause_a\n    if relation == XOR: return cause_a != cause_b",
            "hint": "根据relation类型选择逻辑运算",
        },
        {
            "title": "实现正交表生成器",
            "description": "编写函数generate_pairwise(factors)，生成两两组合测试用例。\n\nfactors: dict，key为因素名，value为水平列表\n返回: list of dict，每条用例是一个因素取值组合",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "正交试验",
            "code_template": "def generate_pairwise(factors):\n    pass",
            "test_cases": "[{\"input\": \"{A:[1,2], B:[x,y]}\", \"expected\": \"4 combinations\"}]",
            "solution": "def generate_pairwise(factors):\n    import itertools\n    keys = list(factors.keys())\n    values = [factors[k] for k in keys]\n    combos = list(itertools.product(*values))\n    return [dict(zip(keys, c)) for c in combos]",
            "hint": "使用itertools.product生成笛卡尔积",
        },
        {
            "title": "实现输入验证错误推测",
            "description": "编写函数test_input_edge_cases(value)，测试各种边界和异常输入。\n\nNone: null_input\n空字符串: empty_string\n纯空格: whitespace_only\n超长(>1000): too_long\n正常: valid",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "错误推测法",
            "code_template": "def test_input_edge_cases(value):\n    pass",
            "test_cases": "[{\"input\": \"None\", \"expected\": \"null_input\"}, {\"input\": \"hello\", \"expected\": \"valid\"}]",
            "solution": "def test_input_edge_cases(value):\n    if value is None: return null_input\n    if isinstance(value, str):\n        if not value: return empty_string\n        if not value.strip(): return whitespace_only\n        if len(value) > 1000: return too_long\n    return valid",
            "hint": "按优先级检查各种异常情况",
        },
        {
            "title": "实现SQL注入检测器",
            "description": "编写函数detect_sql_injection(input_str)，检测常见SQL注入模式。\n\n检测关键词: OR 1=1, DROP TABLE, --, ', UNION SELECT\n有风险: dangerous\n安全: safe",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "错误推测法",
            "code_template": "def detect_sql_injection(input_str):\n    pass",
            "test_cases": "[{\"input\": \"admin OR 1=1\", \"expected\": \"dangerous\"}, {\"input\": \"normaluser\", \"expected\": \"safe\"}]",
            "solution": "def detect_sql_injection(input_str):\n    dangerous_patterns = [OR 1=1, DROP TABLE, --, UNION SELECT, xp_]\n    upper = input_str.upper()\n    for pattern in dangerous_patterns:\n        if pattern in upper: return dangerous\n    return safe",
            "hint": "将输入转大写后匹配关键词",
        },
        {
            "title": "实现XSS检测器",
            "description": "编写函数detect_xss(input_str)，检测XSS攻击模式。\n\n检测: script标签、on事件、javascript:、iframe\n有风险: dangerous\n安全: safe",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "错误推测法",
            "code_template": "def detect_xss(input_str):\n    pass",
            "test_cases": "[{\"input\": \"<script>alert(1)</script>\", \"expected\": \"dangerous\"}, {\"input\": \"hello world\", \"expected\": \"safe\"}]",
            "solution": "def detect_xss(input_str):\n    lower = input_str.lower()\n    patterns = [script, onload, onerror, javascript:, iframe]\n    for p in patterns:\n        if p in lower: return dangerous\n    return safe",
            "hint": "检查常见的XSS攻击关键词",
        },

        # ==================== 简答题 (30题) ====================
        {
            "title": "解释等价类划分法",
            "description": "请详细解释什么是等价类划分法，以及如何划分有效等价类和无效等价类。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "等价类划分法将输入数据划分为若干个等价类，假定每个等价类中的代表值与其他值的测试效果相同。有效等价类是符合规格说明的合理输入数据集合，无效等价类是不符合规格说明的输入数据集合。划分时需考虑输入数据的类型、范围、取值集合等。每个等价类至少选取一个代表值作为测试用例。",
        },
        {
            "title": "等价类划分的实践步骤",
            "description": "描述使用等价类划分法设计测试用例的完整步骤。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "步骤: 1)分析输入条件和输出结果 2)为每个输入划分有效等价类和无效等价类 3)为每个等价类分配唯一编号 4)设计测试用例覆盖所有有效等价类 5)为每个无效等价类设计单独的测试用例 6)合并可以组合的测试用例以减少用例数 7)评审测试用例的完整性和准确性",
        },
        {
            "title": "边界值分析法原理",
            "description": "解释为什么边界值分析法能够有效发现软件缺陷，以及边界值的取值原则。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "根据缺陷聚集理论，大量缺陷发生在输入范围的边界处。原因包括: 开发人员容易在边界条件判断时犯错(如使用<而非<=)、循环的起止条件、数组索引边界等。边界值取值原则: 对于范围[a,b]，取a-1, a, a+1, b-1, b, b+1六个值。这比等价类划分更精确地定位边界附近的缺陷。",
        },
        {
            "title": "边界值分析与等价类划分的区别",
            "description": "比较边界值分析法和等价类划分法的异同点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "相同点: 都是黑盒测试方法，都基于输入数据的划分。不同点: 1)等价类关注等价类内部的代表性数据，边界值关注等价类边界 2)等价类选取每个等价类的一个值，边界值选取边界及相邻值 3)边界值分析是等价类划分的补充 4)边界值发现的缺陷更多集中在边界处理逻辑 5)实际项目中两者通常结合使用",
        },
        {
            "title": "判定表的构建过程",
            "description": "详细描述构建判定表的步骤和注意事项。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "构建步骤: 1)确定条件桩(所有输入条件)和动作桩(所有输出动作) 2)确定每个条件的取值 3)计算所有条件组合的规则数 4)填写条件项和动作项 5)合并相似规则(只有一个条件不同且动作相同) 6)为每条规则设计测试用例。注意事项: 条件过多时规则数会指数增长，需要使用简化技术或分层处理。",
        },
        {
            "title": "因果图方法详解",
            "description": "解释因果图方法的基本原理、符号含义和使用步骤。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "因果图",
            "solution": "因果图用图形表示输入条件(因)和输出结果(果)之间的逻辑关系。基本符号: 恒等(因果同真)、非(因果相反)、或(任一因真则果真)、与(所有因真则果真)。约束: E约束(互斥)、I约束(包含)、O约束(唯一)、R约束(要求)。步骤: 1)分析原因和结果 2)画因果图 3)标注约束 4)转换为判定表 5)设计测试用例。",
        },
        {
            "title": "正交试验法的数学基础",
            "description": "解释正交试验法的数学原理，为什么正交表能保证两两覆盖。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "正交试验",
            "solution": "正交表基于组合数学和数论原理构造。正交性体现在: 任意两列的水平组合出现次数相同(均衡分散)。这保证了任意两个因素的所有水平组合都能被覆盖到。正交表L_n(k^m)中n是试验次数，k是水平数，m是最大因素数。与全组合相比，正交表大幅减少用例数但保持了覆盖性。",
        },
        {
            "title": "场景法的应用场景",
            "description": "说明场景法的适用场景，以及如何识别基本流和备选流。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "solution": "场景法适用于有明确业务流程的系统测试。识别方法: 基本流是用户正常操作的完整流程，无异常无分支。备选流包括: 1)可选步骤 2)异常处理路径 3)错误恢复路径 4)取消操作 5)超时处理。从用例图或流程图中提取场景，每个场景是一条从起点到终点的路径。",
        },
        {
            "title": "错误推测法的常用策略",
            "description": "列举并解释错误推测法中常用的测试策略和关注点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "错误推测法",
            "solution": "常用策略: 1)空值和null输入 2)边界值和特殊值(0, -1, 最大值) 3)类型转换错误 4)字符串特殊字符(引号、转义符) 5)并发和竞态条件 6)资源不足(内存、磁盘) 7)国际化字符(中文、Emoji) 8)重复提交 9)幂等性检查 10)历史缺陷模式分析。依赖测试人员的经验和对系统的理解。",
        },
        {
            "title": "测试设计方法的选择策略",
            "description": "在实际项目中，如何根据不同的测试对象选择合适的测试设计方法？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试设计方法选择",
            "solution": "选择策略: 1)有明确数值范围 -> 等价类+边界值 2)多条件组合 -> 判定表/因果图 3)多因素多水平 -> 正交试验 4)有业务流程 -> 场景法 5)基于经验补充 -> 错误推测法。最佳实践是组合使用，先用系统化方法保证覆盖，再用经验方法补充边界和异常场景。",
        },
        {
            "title": "等价类划分的边界问题",
            "description": "等价类划分法在处理连续型数据时存在什么问题？如何解决？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "等价类划分",
            "solution": "问题: 连续型数据(如浮点数)的等价类边界不明确，一个等价类内部可能包含大量不同的值，无法保证所有值的行为一致。解决方案: 1)结合边界值分析法在边界处增加测试 2)将连续数据离散化为有限区间 3)使用分类树方法细化等价类 4)在等价类内部随机选取多个值进行测试。",
        },
        {
            "title": "边界值分析的扩展方法",
            "description": "除了基本边界值分析，还有哪些扩展方法？各自的适用场景是什么？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "边界值分析",
            "solution": "扩展方法: 1)健壮性测试: 在边界外增加测试点，检查系统对越界的处理 2)最坏情况测试: 对多个变量的边界值进行组合 3)随机测试: 在边界附近随机取值 4)特殊值测试: 针对0、空、null等特殊值。适用场景: 健壮性测试用于验证异常处理，最坏情况测试用于安全关键系统。",
        },
        {
            "title": "判定表的简化技术",
            "description": "当判定表的规则数过多时，有哪些简化技术？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "判定表",
            "solution": "简化技术: 1)规则合并: 只有一个条件不同且动作相同时合并 2)不关心项: 某些条件对结果无影响时标记为- 3)条件分解: 将大判定表拆分为多个小判定表 4)优先级排序: 先测试高风险规则 5)使用决策树替代: 条件有优先级时用决策树更直观。这些技术可以显著减少测试用例数。",
        },
        {
            "title": "因果图中的约束类型",
            "description": "详细解释因果图中的E、I、O、R四种约束及其含义。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "因果图",
            "solution": "E约束(Exclusive/互斥): C1和C2不能同时为真。I约束(Inclusive/包含): C1、C2、C3中至少有一个为真。O约束(One and only one/唯一): C1和C2中有且仅有一个为真。R约束(Requires/要求): 如果C1为真，则C2也必须为真。这些约束帮助准确建模输入条件之间的复杂关系。",
        },
        {
            "title": "正交表的选择方法",
            "description": "如何根据测试需求选择合适的正交表？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "正交试验",
            "solution": "选择步骤: 1)确定因素数(输入变量个数) 2)确定每个因素的水平数 3)选择满足条件的最小正交表: 因素数<=正交表列数，水平数=正交表水平数 4)如果水平数不同，使用混合水平正交表 5)将因素分配到正交表的列。常用正交表: L4(2^3)、L8(2^7)、L9(3^4)、L16(4^5)。",
        },
        {
            "title": "场景法与状态机的关系",
            "description": "场景法与有限状态机测试方法有什么关系和区别？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "场景法",
            "solution": "关系: 场景法中的备选流类似状态机中的状态转换。区别: 场景法关注端到端的业务流程，状态机关注状态之间的转换。场景法适合测试业务逻辑，状态机适合测试有状态的系统。两者可以结合: 用状态机建模系统状态，用场景法设计端到端测试。状态机测试更系统化，场景法更贴近用户视角。",
        },
        {
            "title": "测试设计的覆盖标准",
            "description": "解释测试设计中常用的覆盖标准及其含义。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试覆盖标准",
            "solution": "常用覆盖标准: 1)语句覆盖: 每条语句至少执行一次 2)分支覆盖: 每个判断的真假分支至少执行一次 3)条件覆盖: 每个条件的真假至少出现一次 4)路径覆盖: 每条独立路径至少执行一次 5)等价类覆盖: 每个等价类至少一个用例 6)边界覆盖: 所有边界值都被测试。覆盖标准从弱到强递增，成本也递增。",
        },
        {
            "title": "黑盒测试与白盒测试的设计方法对比",
            "description": "对比黑盒测试和白盒测试的设计方法，说明各自的优缺点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试设计方法对比",
            "solution": "黑盒方法(等价类、边界值、判定表等): 优点是不需要了解代码，从用户角度测试，能发现需求缺陷; 缺点是覆盖可能不全面。白盒方法(语句覆盖、分支覆盖等): 优点是覆盖系统化，能测试代码逻辑; 缺点是成本高，不能发现需求缺陷。实际项目中两者结合使用效果最佳。",
        },
        {
            "title": "测试用例设计规范",
            "description": "描述一个良好的测试用例应该包含哪些要素，以及编写规范。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试设计",
            "knowledge_point": "测试用例编写规范",
            "solution": "测试用例要素: 1)用例编号(唯一标识) 2)用例标题(简明描述测试目标) 3)前置条件 4)测试步骤(详细操作步骤) 5)测试数据 6)预期结果 7)实际结果 8)优先级 9)关联需求。编写规范: 标题简明、步骤可执行、预期结果明确可验证、一个用例验证一个测试点、避免冗余。",
        },
        {
            "title": "测试数据准备方法",
            "description": "描述测试数据准备的常用方法和最佳实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试数据准备",
            "solution": "方法: 1)手工构造: 适合小规模测试 2)脚本生成: 编写程序批量生成 3)从生产环境脱敏复制 4)使用数据生成工具(Faker等) 5)自动化测试框架的数据驱动。最佳实践: 数据与脚本分离、使用前置条件初始化、测试后清理数据、数据版本管理、敏感数据脱敏。",
        },
        {
            "title": "测试设计评审要点",
            "description": "描述测试设计评审应该关注哪些方面。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试设计评审",
            "solution": "评审要点: 1)覆盖率: 是否覆盖所有需求和等价类 2)方法选择: 测试设计方法是否合适 3)数据正确性: 测试数据和预期结果是否正确 4)完整性: 是否覆盖正常、异常、边界场景 5)可执行性: 测试步骤是否清晰可执行 6)优先级: 重要场景是否优先 7)冗余检查: 是否有重复用例。",
        },
        {
            "title": "基于需求的测试设计",
            "description": "如何从需求文档出发，系统地设计测试用例？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试设计流程",
            "solution": "流程: 1)分析需求文档，提取测试条件 2)为每个功能点创建测试大纲 3)使用等价类/边界值分析输入 4)使用判定表分析业务规则 5)使用场景法设计端到端测试 6)使用错误推测法补充异常场景 7)确定测试优先级 8)编写详细测试用例 9)评审和完善。需求追踪矩阵确保覆盖。",
        },
        {
            "title": "测试设计自动化",
            "description": "哪些测试设计工作可以自动化？如何实现？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "测试设计自动化",
            "solution": "可自动化的工作: 1)等价类和边界值的测试数据生成 2)正交表的自动生成 3)组合测试用例的生成 4)基于模型的测试用例生成 5)参数化测试数据的管理。实现方式: 使用Python脚本生成测试数据、使用PICT等组合测试工具、使用模型驱动测试框架、集成到CI/CD流水线。",
        },
        {
            "title": "探索性测试与脚本化测试",
            "description": "比较探索性测试和脚本化测试的优缺点及适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试方法对比",
            "solution": "脚本化测试: 优点是可重复、可审计、适合回归测试; 缺点是前期投入大、可能遗漏未预见的场景。探索性测试: 优点是灵活、能发现意外缺陷、适合新功能; 缺点是不可重复、依赖测试人员能力。适用场景: 脚本化用于回归测试和合规要求，探索性用于新功能测试和缺陷调查。两者互补。",
        },
        {
            "title": "测试设计的度量指标",
            "description": "描述评估测试设计质量的常用度量指标。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试度量",
            "solution": "常用度量: 1)需求覆盖率: 已测试需求数/总需求数 2)用例密度: 每个需求的平均用例数 3)缺陷发现率: 执行用例发现的缺陷数 4)等价类覆盖率: 已覆盖等价类/总等价类 5)边界覆盖率: 已测试边界/总边界 6)用例通过率 7)用例执行效率。这些指标帮助评估测试设计的充分性和有效性。",
        },
        {
            "title": "测试用例的维护策略",
            "description": "描述如何维护和管理测试用例库，确保其持续有效。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "测试用例管理",
            "solution": "维护策略: 1)定期评审和更新用例 2)需求变更时同步更新用例 3)删除过时和冗余的用例 4)标记高优先级用例用于冒烟测试 5)版本管理用例 6)用例执行结果分析，优化低效用例 7)缺陷修复后添加回归用例 8)使用测试管理工具(如TestRail)管理。",
        },
        {
            "title": "移动端测试设计的特殊考虑",
            "description": "移动端应用的测试设计需要考虑哪些特殊因素？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "移动端测试设计",
            "solution": "特殊考虑: 1)屏幕尺寸和分辨率适配 2)触摸手势(滑动、缩放、长按) 3)网络环境(WiFi/4G/弱网/断网) 4)设备方向(横屏/竖屏) 5)中断处理(来电、通知) 6)电池和性能 7)不同OS版本兼容性 8)权限管理 9)离线功能 10)推送通知。需要使用正交试验法管理设备和系统的组合。",
        },
        {
            "title": "API测试设计方法",
            "description": "API接口测试应该从哪些维度设计测试用例？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试设计",
            "knowledge_point": "API测试设计",
            "solution": "维度: 1)参数验证: 必填、类型、范围、边界 2)功能验证: 正常返回、业务逻辑 3)异常处理: 错误码、异常输入 4)安全性: 认证、授权、注入 5)性能: 响应时间、并发 6)幂等性: 重复请求结果一致 7)兼容性: 版本兼容 8)数据完整性: 返回数据格式和内容。每个维度使用对应的测试设计方法。",
        },
        {
            "title": "测试设计中的风险分析",
            "description": "如何在测试设计中进行风险分析，确定测试优先级？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试设计",
            "knowledge_point": "风险测试",
            "solution": "风险分析步骤: 1)识别风险项(功能复杂度、变更频率、历史缺陷、业务重要性) 2)评估风险概率和影响 3)计算风险优先级=概率x影响 4)高风险区域分配更多测试资源 5)使用风险矩阵指导测试优先级 6)动态调整: 根据测试结果重新评估风险。这确保有限资源集中在最重要的地方。",
        },
    ]
}
