# -*- coding: utf-8 -*-
"""
测试计划编写与项目管理 - 学习路径 ID=8
知识点: 测试计划编写(IEEE 829), 测试策略制定, 测试范围与风险评估, 资源估算与进度管理,
       测试入口出口准则, 测试报告编写, 测试项目管理方法论, 测试度量与质量评估
题目数量: 90题 (选择题35 + 编程题20 + 简答题35)
难度分布: easy 30% + medium 50% + hard 20%
"""

EXERCISES = {
    "测试计划编写与项目管理": [
        # ==================== 选择题 (35题) ====================
        # --- 测试计划编写 IEEE 829 (easy) ---
        {
            "title": "IEEE 829标准定义的是：",
            "description": "IEEE 829标准定义的是：\nA. 软件测试计划文档标准\nB. 软件需求规格说明标准\nC. 软件设计文档标准\nD. 软件配置管理标准",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "A",
        },
        {
            "title": "IEEE 829测试计划中不包含以下哪个部分？",
            "description": "IEEE 829测试计划中不包含以下哪个部分？\nA. 测试范围\nB. 测试策略\nC. 源代码清单\nD. 测试进度安排",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "C",
        },
        {
            "title": "测试计划的核心作用是：",
            "description": "测试计划的核心作用是：\nA. 记录所有缺陷\nB. 指导和管理测试活动的开展\nC. 替代测试用例\nD. 直接提高代码质量",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "B",
        },
        {
            "title": "IEEE 829标准中，测试计划的引言部分应包含：",
            "description": "IEEE 829标准中，测试计划的引言部分应包含：\nA. 测试用例详情\nB. 测试目的、范围和参考文档\nC. 缺陷跟踪记录\nD. 测试环境配置",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "B",
        },
        {
            "title": "关于测试计划的说法，错误的是：",
            "description": "关于测试计划的说法，错误的是：\nA. 测试计划应在测试活动开始前制定\nB. 测试计划是动态文档，可以随项目变化更新\nC. 测试计划一旦制定就不能修改\nD. 测试计划需要经过评审",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "C",
        },
        # --- 测试策略制定 (easy/medium) ---
        {
            "title": "测试策略的主要目的是：",
            "description": "测试策略的主要目的是：\nA. 详细描述每个测试步骤\nB. 确定测试范围、方法、资源和进度的总体方案\nC. 记录测试执行结果\nD. 管理测试人员考勤",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "B",
        },
        {
            "title": "以下哪种测试策略适用于需求不明确或频繁变更的项目？",
            "description": "以下哪种测试策略适用于需求不明确或频繁变更的项目？\nA. 瀑布式测试策略\nB. 基于风险的测试策略\nC. 探索性测试策略\nD. 全面回归测试策略",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "C",
        },
        {
            "title": "制定测试策略时不需要考虑的因素是：",
            "description": "制定测试策略时，以下哪项不是需要考虑的因素？\nA. 项目风险和优先级\nB. 可用资源和时间约束\nC. 开发人员的薪资水平\nD. 技术栈和系统架构",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "C",
        },
        {
            "title": "基于风险的测试策略的核心思想是：",
            "description": "基于风险的测试策略的核心思想是：\nA. 对所有功能进行同等程度的测试\nB. 优先测试风险最高的部分\nC. 只测试核心功能\nD. 不进行任何风险评估",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "B",
        },
        {
            "title": "回归测试策略应考虑：",
            "description": "在测试策略中，回归测试策略应考虑：\nA. 每次都执行全部测试用例\nB. 根据变更影响范围选择性回归\nC. 只在项目结束时回归\nD. 不需要回归测试",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "B",
        },
        # --- 测试范围与风险评估 (easy/medium/hard) ---
        {
            "title": "确定测试范围时不需要明确的内容是：",
            "description": "确定测试范围时，以下哪项不属于需要明确的内容？\nA. 需要测试的功能模块\nB. 不需要测试的功能及原因\nC. 开发团队的组织架构\nD. 测试的优先级",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "C",
        },
        {
            "title": "风险评估中，风险优先级等于：",
            "description": "风险评估中，风险优先级等于：\nA. 风险发生概率 + 风险影响程度\nB. 风险发生概率 * 风险影响程度\nC. 风险影响程度 - 风险发生概率\nD. 风险发生概率 / 风险影响程度",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "B",
        },
        {
            "title": "以下哪项属于项目风险而非产品风险？",
            "description": "以下哪项属于项目风险而非产品风险？\nA. 软件存在安全漏洞\nB. 关键开发人员离职\nC. 系统性能不达标\nD. 用户界面不友好",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "B",
        },
        {
            "title": "产品风险不包括以下哪项？",
            "description": "产品风险不包括以下哪项？\nA. 功能缺陷\nB. 性能瓶颈\nC. 项目进度延迟\nD. 安全漏洞",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "C",
        },
        {
            "title": "高概率高影响的风险应该：",
            "description": "在风险矩阵中，高概率高影响的风险应该：\nA. 忽略不计\nB. 优先分配资源进行应对\nC. 只做记录不做处理\nD. 转嫁给客户",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "B",
        },
        # --- 资源估算与进度管理 (easy/medium) ---
        {
            "title": "测试工作量估算的常用方法不包括：",
            "description": "测试工作量估算的常用方法不包括：\nA. 类比估算法\nB. 专家判断法\nC. 随机猜测法\nD. 功能点分析法",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "C",
        },
        {
            "title": "测试资源规划中不属于测试资源的是：",
            "description": "测试资源规划中，以下哪项不属于测试资源？\nA. 测试人员\nB. 测试工具\nC. 测试环境\nD. 需求文档版本",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "D",
        },
        {
            "title": "测试进度管理中，里程碑的作用是：",
            "description": "测试进度管理中，里程碑的作用是：\nA. 记录每个测试用例的执行时间\nB. 标记关键节点，监控项目进展\nC. 分配测试人员的任务\nD. 管理测试环境",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "B",
        },
        {
            "title": "最适合有历史数据参考项目的估算方法是：",
            "description": "以下哪种估算方法最适合有历史数据参考的项目？\nA. 德尔菲法\nB. 类比估算法\nC. 计划扑克法\nD. 头脑风暴法",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "B",
        },
        {
            "title": "敏捷项目中常用的测试工作量估算方法是：",
            "description": "敏捷项目中，测试工作量估算常用的方法是：\nA. 甘特图\nB. 计划扑克（Planning Poker）\nC. 关键路径法\nD. 瀑布模型法",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "B",
        },
        # --- 测试入口出口准则 (easy/medium) ---
        {
            "title": "测试入口准则（Entry Criteria）是指：",
            "description": "测试入口准则（Entry Criteria）是指：\nA. 测试结束的条件\nB. 开始测试活动必须满足的前提条件\nC. 编写测试用例的标准\nD. 提交缺陷的标准",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "B",
        },
        {
            "title": "通常不是系统测试入口准则的是：",
            "description": "以下哪项通常不是系统测试的入口准则？\nA. 需求文档已评审通过\nB. 所有代码已完成且通过单元测试\nC. 用户已签署验收报告\nD. 测试环境已搭建并验证",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "C",
        },
        {
            "title": "测试出口准则（Exit Criteria）的主要作用是：",
            "description": "测试出口准则（Exit Criteria）的主要作用是：\nA. 确定何时可以开始测试\nB. 确定何时可以结束测试\nC. 确定测试用例的优先级\nD. 确定缺陷的严重程度",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "B",
        },
        {
            "title": "通常作为测试出口准则的是：",
            "description": "以下哪项通常作为测试出口准则？\nA. 所有测试用例都已编写完成\nB. 严重以上缺陷修复率达100%，用例执行率达95%\nC. 所有开发人员完成编码\nD. 测试计划已获批准",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "B",
        },
        {
            "title": "关于入口准则和出口准则，正确的是：",
            "description": "关于入口准则和出口准则，以下说法正确的是：\nA. 入口准则和出口准则是固定不变的\nB. 可以根据项目实际情况进行裁剪和调整\nC. 出口准则必须要求零缺陷\nD. 入口准则不需要文档评审",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "B",
        },
        # --- 测试报告编写 (easy/medium) ---
        {
            "title": "测试报告的主要目的是：",
            "description": "测试报告的主要目的是：\nA. 记录所有测试用例的代码\nB. 向利益相关者传达测试结果和质量状态\nC. 分配测试任务\nD. 制定测试计划",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "solution": "B",
        },
        {
            "title": "测试报告中通常不包含以下哪项内容？",
            "description": "测试报告中通常不包含以下哪项内容？\nA. 测试执行概况\nB. 缺陷统计分析\nC. 开发人员的绩效考核\nD. 测试结论与建议",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "solution": "C",
        },
        {
            "title": "缺陷分布分析通常包括：",
            "description": "测试报告中的缺陷分布分析通常包括：\nA. 按模块、严重程度、状态分布\nB. 开发人员的代码行数\nC. 测试人员的加班时长\nD. 项目的商业利润",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "solution": "A",
        },
        # --- 测试项目管理方法论 (medium/hard) ---
        {
            "title": "敏捷测试管理中测试活动的主要载体是：",
            "description": "在敏捷测试管理中，测试活动的主要载体是：\nA. 测试计划文档\nB. 用户故事和Sprint\nC. 需求规格说明书\nD. 设计文档",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "B",
        },
        {
            "title": "WBS在测试项目管理中的作用是：",
            "description": "WBS（工作分解结构）在测试项目管理中的作用是：\nA. 记录缺陷信息\nB. 将测试工作逐层分解为可管理的任务\nC. 编写测试用例\nD. 搭建测试环境",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "B",
        },
        {
            "title": "最适合需求频繁变更项目的管理方法是：",
            "description": "以下哪种项目管理方法最适合需求频繁变更的测试项目？\nA. 瀑布模型\nB. V模型\nC. 敏捷方法\nD. 瀑布+V模型",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "C",
        },
        {
            "title": "测试项目中干系人管理的目的是：",
            "description": "在测试项目管理中，干系人管理的目的是：\nA. 减少测试工作量\nB. 识别、分析并管理影响项目的相关方期望\nC. 增加测试人员数量\nD. 缩短测试周期",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "B",
        },
        # --- 测试度量与质量评估 (medium/hard) ---
        {
            "title": "缺陷密度的计算公式是：",
            "description": "缺陷密度的计算公式是：\nA. 缺陷数 / 代码行数（或功能点数）\nB. 缺陷数 * 代码行数\nC. 代码行数 / 缺陷数\nD. 缺陷数 + 代码行数",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "A",
        },
        {
            "title": "最能反映测试执行效率的指标是：",
            "description": "以下哪项指标最能反映测试执行的效率？\nA. 缺陷密度\nB. 测试用例执行速率\nC. 需求覆盖率\nD. 代码覆盖率",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "B",
        },
        {
            "title": "缺陷移除效率(DRE)的计算公式是：",
            "description": "测试度量中，缺陷移除效率(DRE)的计算公式是：\nA. 测试发现缺陷数 / (测试发现缺陷数 + 客户发现缺陷数)\nB. 客户发现缺陷数 / 测试发现缺陷数\nC. 测试发现缺陷数 * 客户发现缺陷数\nD. 总缺陷数 / 测试周期",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "A",
        },

        # ==================== 编程题 (20题) ====================
        # --- 测试计划编写相关编程 (easy/medium) ---
        {
            "title": "编写函数解析测试计划章节标题",
            "description": "编写Python函数parse_test_plan_sections(plan_text)，解析测试计划文本中的章节标题。\n\nplan_text: 字符串，包含测试计划内容\n返回: 列表，包含所有以数字编号开头的章节标题\n\n示例：\n输入: \"1.引言\\n1.1目的\\n2.测试范围\\n3.测试策略\"\n输出: [\"1.引言\", \"1.1目的\", \"2.测试范围\", \"3.测试策略\"]",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "code_template": "def parse_test_plan_sections(plan_text):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"1.引言\\n1.1目的\\n2.测试范围\"", "expected": "[\"1.引言\", \"1.1目的\", \"2.测试范围\"]"}]',
            "solution": "def parse_test_plan_sections(plan_text):\n    import re\n    lines = plan_text.split('\\n')\n    sections = []\n    for line in lines:\n        line = line.strip()\n        if re.match(r'^\\d+\\.?\\d*\\.?\\s*\\S', line):\n            sections.append(line)\n    return sections",
            "hint": "使用正则表达式匹配以数字开头的行",
        },
        {
            "title": "编写函数验证测试计划完整性",
            "description": "编写Python函数validate_plan_completeness(plan_sections, required_sections)，\n检查测试计划是否包含所有必需章节。\n\nplan_sections: list，测试计划中实际的章节名\nrequired_sections: list，必须包含的章节名\n返回: 字典 {'complete': bool, 'missing': list}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "code_template": "def validate_plan_completeness(plan_sections, required_sections):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[\"引言\", \"测试范围\"], [\"引言\", \"测试范围\", \"测试策略\"]", "expected": "complete=False, missing=[\"测试策略\"]"}]',
            "solution": "def validate_plan_completeness(plan_sections, required_sections):\n    missing = [s for s in required_sections if s not in plan_sections]\n    return {'complete': len(missing) == 0, 'missing': missing}",
            "hint": "使用列表推导式找出缺失的章节",
        },
        # --- 测试策略相关编程 (medium) ---
        {
            "title": "编写函数计算基于风险的测试优先级",
            "description": "编写Python函数calculate_risk_priority(probability, impact)，\n计算风险优先级分数和等级。\n\nprobability: float，发生概率(0-1)\nimpact: float，影响程度(1-10)\n返回: 字典 {'priority_score': float, 'level': str}\n\nlevel规则：score>=7为high，>=4为medium，其余为low",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "code_template": "def calculate_risk_priority(probability, impact):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "0.8, 9", "expected": "priority_score=7.2, level=high"}, {"input": "0.3, 5", "expected": "priority_score=1.5, level=low"}]',
            "solution": "def calculate_risk_priority(probability, impact):\n    score = round(probability * impact, 1)\n    if score >= 7:\n        level = 'high'\n    elif score >= 4:\n        level = 'medium'\n    else:\n        level = 'low'\n    return {'priority_score': score, 'level': level}",
            "hint": "风险分数 = 概率 * 影响程度，然后按阈值分类",
        },
        {
            "title": "编写函数生成测试策略矩阵",
            "description": "编写Python函数generate_strategy_matrix(modules)，\n根据模块信息生成测试策略矩阵。\n\nmodules: list of dict，每个包含 name, risk_level, complexity\n返回: list of dict，每个包含 name 和 recommended_approach\n\n规则：\n- risk=high且complexity=high: 全面测试+自动化\n- risk=high或complexity=high: 重点测试\n- 其他: 基本测试",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "code_template": "def generate_strategy_matrix(modules):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"name\": \"支付\", \"risk_level\": \"high\", \"complexity\": \"high\"}]", "expected": "[{\"name\": \"支付\", \"recommended_approach\": \"全面测试+自动化\"}]"}]',
            "solution": "def generate_strategy_matrix(modules):\n    result = []\n    for m in modules:\n        if m['risk_level'] == 'high' and m['complexity'] == 'high':\n            approach = '全面测试+自动化'\n        elif m['risk_level'] == 'high' or m['complexity'] == 'high':\n            approach = '重点测试'\n        else:\n            approach = '基本测试'\n        result.append({'name': m['name'], 'recommended_approach': approach})\n    return result",
            "hint": "遍历模块列表，根据风险和复杂度组合确定策略",
        },
        # --- 风险评估相关编程 (medium/hard) ---
        {
            "title": "编写函数构建风险矩阵",
            "description": "编写Python函数build_risk_matrix(risks)，\n构建风险矩阵并按分数排序。\n\nrisks: list of dict，每个包含 name, probability(1-5), impact(1-5)\n返回: list of dict，每个包含 name, risk_score, priority\n\nrisk_score = probability * impact\npriority: score>=15为critical，>=10为high，>=5为medium，其余为low",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "code_template": "def build_risk_matrix(risks):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"name\": \"数据丢失\", \"probability\": 4, \"impact\": 5}]", "expected": "[{\"name\": \"数据丢失\", \"risk_score\": 20, \"priority\": \"critical\"}]"}]',
            "solution": "def build_risk_matrix(risks):\n    result = []\n    for r in risks:\n        score = r['probability'] * r['impact']\n        if score >= 15:\n            priority = 'critical'\n        elif score >= 10:\n            priority = 'high'\n        elif score >= 5:\n            priority = 'medium'\n        else:\n            priority = 'low'\n        result.append({'name': r['name'], 'risk_score': score, 'priority': priority})\n    return sorted(result, key=lambda x: x['risk_score'], reverse=True)",
            "hint": "计算分数后按阈值分类，最后按分数排序",
        },
        {
            "title": "编写函数对风险进行排序",
            "description": "编写Python函数rank_risks(risks)，对风险进行排序。\n\nrisks: list of dict，每个包含 name, probability, impact\n返回: list，按风险分数从高到低排列的风险名称列表",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "code_template": "def rank_risks(risks):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"name\": \"A\", \"probability\": 3, \"impact\": 4}, {\"name\": \"B\", \"probability\": 5, \"impact\": 5}]", "expected": "[\"B\", \"A\"]"}]',
            "solution": "def rank_risks(risks):\n    scored = [(r['name'], r['probability'] * r['impact']) for r in risks]\n    scored.sort(key=lambda x: x[1], reverse=True)\n    return [name for name, _ in scored]",
            "hint": "计算每个风险的分数，排序后提取名称",
        },
        # --- 资源估算与进度管理编程 (medium/hard) ---
        {
            "title": "编写函数估算测试总工作量",
            "description": "编写Python函数estimate_test_effort(num_cases, avg_time_per_case, complexity_factor=1.0)，\n估算测试总工作量。\n\nnum_cases: int，测试用例数\navg_time_per_case: float，每个用例平均执行时间（小时）\ncomplexity_factor: float，复杂度系数\n返回: 字典 {'total_hours': float, 'total_days': float}\n\n假设每人每天工作8小时",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "code_template": "def estimate_test_effort(num_cases, avg_time_per_case, complexity_factor=1.0):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "100, 0.5, 1.2", "expected": "total_hours=60.0, total_days=7.5"}]',
            "solution": "def estimate_test_effort(num_cases, avg_time_per_case, complexity_factor=1.0):\n    total_hours = num_cases * avg_time_per_case * complexity_factor\n    total_days = round(total_hours / 8, 1)\n    return {'total_hours': round(total_hours, 1), 'total_days': total_days}",
            "hint": "总工时 = 用例数 * 平均时间 * 复杂度系数",
        },
        {
            "title": "编写函数计算项目关键路径",
            "description": "编写Python函数calculate_critical_path(tasks)，\n计算测试项目的关键路径。\n\ntasks: list of dict，每个包含 name, duration(天), dependencies(前置任务名列表)\n返回: dict {'critical_path': list, 'total_duration': int}\n\n简化版：返回从每个任务出发的最长路径",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "code_template": "def calculate_critical_path(tasks):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"name\": \"A\", \"duration\": 3, \"dependencies\": []}, {\"name\": \"B\", \"duration\": 5, \"dependencies\": [\"A\"]}]", "expected": "critical_path=[\"A\", \"B\"], total_duration=8"}]',
            "solution": "def calculate_critical_path(tasks):\n    task_map = {t['name']: t for t in tasks}\n    def get_path_length(name, visited=None):\n        if visited is None:\n            visited = set()\n        if name in visited:\n            return 0, []\n        visited.add(name)\n        t = task_map[name]\n        if not t['dependencies']:\n            return t['duration'], [name]\n        max_len = 0\n        max_path = []\n        for dep in t['dependencies']:\n            dep_len, dep_path = get_path_length(dep, visited.copy())\n            if dep_len > max_len:\n                max_len = dep_len\n                max_path = dep_path\n        return max_len + t['duration'], max_path + [name]\n    best_len = 0\n    best_path = []\n    for t in tasks:\n        length, path = get_path_length(t['name'])\n        if length > best_len:\n            best_len = length\n            best_path = path\n    return {'critical_path': best_path, 'total_duration': best_len}",
            "hint": "使用递归计算从每个任务开始的最长路径",
        },
        # --- 入口出口准则编程 (easy/medium) ---
        {
            "title": "编写函数检查入口准则是否满足",
            "description": "编写Python函数check_entry_criteria(criteria_status)，\n检查测试入口准则是否满足。\n\ncriteria_status: dict，准则名 -> bool (True表示已满足)\n返回: dict {'ready': bool, 'unsatisfied': list}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "code_template": "def check_entry_criteria(criteria_status):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"需求评审通过\": true, \"环境就绪\": false, \"用例评审通过\": true}", "expected": "ready=False, unsatisfied=[\"环境就绪\"]"}]',
            "solution": "def check_entry_criteria(criteria_status):\n    unsatisfied = [name for name, status in criteria_status.items() if not status]\n    return {'ready': len(unsatisfied) == 0, 'unsatisfied': unsatisfied}",
            "hint": "遍历字典找出值为False的键",
        },
        {
            "title": "编写函数检查出口准则是否满足",
            "description": "编写Python函数check_exit_criteria(metrics, thresholds)，\n检查测试出口准则是否满足。\n\nmetrics: dict，指标名 -> 当前值\nthresholds: dict，指标名 -> 阈值\n返回: dict {'passed': bool, 'details': list of dict}\n\ndetails中每个dict包含 metric, current, threshold, met(bool)",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "code_template": "def check_exit_criteria(metrics, thresholds):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"执行率\": 95, \"通过率\": 90}, {\"执行率\": 90, \"通过率\": 95}", "expected": "passed=True, 所有指标均达标"}]',
            "solution": "def check_exit_criteria(metrics, thresholds):\n    details = []\n    all_met = True\n    for name, threshold in thresholds.items():\n        current = metrics.get(name, 0)\n        met = current >= threshold\n        if not met:\n            all_met = False\n        details.append({'metric': name, 'current': current, 'threshold': threshold, 'met': met})\n    return {'passed': all_met, 'details': details}",
            "hint": "遍历阈值字典，比较当前值是否达到阈值",
        },
        # --- 测试报告编写编程 (medium) ---
        {
            "title": "编写函数计算测试执行燃尽数据",
            "description": "编写Python函数calculate_burndown(total_cases, daily_executed)，\n计算测试执行燃尽数据。\n\ntotal_cases: int，总用例数\ndaily_executed: list of int，每天执行的用例数\n返回: list of int，每天剩余的用例数（含初始值）",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "code_template": "def calculate_burndown(total_cases, daily_executed):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "100, [20, 30, 25, 15]", "expected": "[100, 80, 50, 25, 10]"}]',
            "solution": "def calculate_burndown(total_cases, daily_executed):\n    remaining = [total_cases]\n    current = total_cases\n    for count in daily_executed:\n        current = max(0, current - count)\n        remaining.append(current)\n    return remaining",
            "hint": "从总数开始，每天减去执行数，记录剩余量",
        },
        {
            "title": "编写函数生成缺陷统计摘要",
            "description": "编写Python函数generate_defect_summary(defects)，\n生成缺陷统计摘要。\n\ndefects: list of dict，每个包含 severity(critical/major/minor/trivial), status(open/resolved/closed)\n返回: dict，包含按严重程度和状态的统计",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "code_template": "def generate_defect_summary(defects):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"severity\": \"critical\", \"status\": \"open\"}, {\"severity\": \"major\", \"status\": \"resolved\"}]", "expected": "包含severity和status的统计"}]',
            "solution": "def generate_defect_summary(defects):\n    by_severity = {}\n    by_status = {}\n    for d in defects:\n        sev = d['severity']\n        status = d['status']\n        by_severity[sev] = by_severity.get(sev, 0) + 1\n        by_status[status] = by_status.get(status, 0) + 1\n    return {'total': len(defects), 'by_severity': by_severity, 'by_status': by_status}",
            "hint": "使用字典统计各分类的数量",
        },
        {
            "title": "编写函数生成测试报告文本",
            "description": "编写Python函数generate_test_report(summary)，\n根据摘要数据生成测试报告文本。\n\nsummary: dict，包含 total_cases, executed, passed, failed, blocked\n返回: 字符串，格式化的测试报告",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "code_template": "def generate_test_report(summary):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"total_cases\": 100, \"executed\": 90, \"passed\": 80, \"failed\": 8, \"blocked\": 2}", "expected": "包含执行率、通过率等信息的报告文本"}]',
            "solution": "def generate_test_report(summary):\n    total = summary['total_cases']\n    executed = summary['executed']\n    passed = summary['passed']\n    exec_rate = round(executed / total * 100, 1) if total > 0 else 0\n    pass_rate = round(passed / executed * 100, 1) if executed > 0 else 0\n    report = f\"测试执行报告\\n\"\n    report += f\"总用例数: {total}\\n\"\n    report += f\"已执行: {executed} (执行率: {exec_rate}%)\\n\"\n    report += f\"通过: {passed} (通过率: {pass_rate}%)\\n\"\n    report += f\"失败: {summary['failed']}\\n\"\n    report += f\"阻塞: {summary['blocked']}\"\n    return report",
            "hint": "计算各项比率，使用f-string格式化报告",
        },
        # --- 测试项目管理编程 (medium) ---
        {
            "title": "编写函数生成WBS分解结构",
            "description": "编写Python函数generate_wbs(project_name, phases)，\n生成测试项目的工作分解结构。\n\nproject_name: str，项目名\nphases: list of dict，每个包含 phase_name 和 task_count\n返回: dict，树形结构的WBS",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "code_template": "def generate_wbs(project_name, phases):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"项目A\", [{\"phase_name\": \"计划\", \"task_count\": 3}, {\"phase_name\": \"执行\", \"task_count\": 5}]", "expected": "包含项目名和各阶段任务的树形结构"}]',
            "solution": "def generate_wbs(project_name, phases):\n    wbs = {'project': project_name, 'phases': []}\n    for i, phase in enumerate(phases, 1):\n        tasks = [f\"{i}.{j} {phase['phase_name']}-任务{j}\" for j in range(1, phase['task_count'] + 1)]\n        wbs['phases'].append({'id': i, 'name': phase['phase_name'], 'tasks': tasks})\n    return wbs",
            "hint": "遍历阶段列表，为每个阶段生成编号任务",
        },
        {
            "title": "编写函数计算Sprint测试容量",
            "description": "编写Python函数calculate_sprint_capacity(team_size, sprint_days, avg_velocity, leave_days=0)，\n计算Sprint的测试容量。\n\nteam_size: int，团队人数\nsprint_days: int，Sprint天数\navg_velocity: float，平均速率（每天每人完成的故事点）\nleave_days: int，请假人天数\n返回: dict {'available_days': int, 'capacity': float, 'suggested_points': int}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "code_template": "def calculate_sprint_capacity(team_size, sprint_days, avg_velocity, leave_days=0):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "5, 10, 2.0, 5", "expected": "available_days=45, capacity=90.0, suggested_points=90"}]',
            "solution": "def calculate_sprint_capacity(team_size, sprint_days, avg_velocity, leave_days=0):\n    available_days = team_size * sprint_days - leave_days\n    capacity = available_days * avg_velocity\n    suggested_points = int(capacity * 0.85)\n    return {'available_days': available_days, 'capacity': round(capacity, 1), 'suggested_points': suggested_points}",
            "hint": "可用天数 = 团队人数 * Sprint天数 - 请假人天数",
        },
        # --- 测试度量编程 (medium/hard) ---
        {
            "title": "编写函数计算测试投入产出比",
            "description": "编写Python函数calculate_test_roi(defects_prevented, cost_per_defect, test_cost)，\n计算测试投入产出比(ROI)。\n\ndefects_prevented: int，预防的缺陷数\ncost_per_defect: float，每个缺陷的修复成本\ntest_cost: float，测试总成本\n返回: dict {'roi': float, 'benefit': float, 'cost': float}\n\nROI = (benefit - cost) / cost * 100",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "code_template": "def calculate_test_roi(defects_prevented, cost_per_defect, test_cost):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "50, 1000, 20000", "expected": "roi=150.0, benefit=50000, cost=20000"}]',
            "solution": "def calculate_test_roi(defects_prevented, cost_per_defect, test_cost):\n    benefit = defects_prevented * cost_per_defect\n    roi = round((benefit - test_cost) / test_cost * 100, 1) if test_cost > 0 else 0\n    return {'roi': roi, 'benefit': benefit, 'cost': test_cost}",
            "hint": "收益 = 预防缺陷数 * 每个缺陷成本，ROI = (收益-成本)/成本*100",
        },
        {
            "title": "编写函数计算测试用例设计效率",
            "description": "编写Python函数calculate_design_efficiency(test_cases, design_hours)，\n计算测试用例设计效率。\n\ntest_cases: int，设计的测试用例数\ndesign_hours: float，设计花费的工时\n返回: dict {'cases_per_hour': float, 'efficiency_level': str}\n\nefficiency_level: cases_per_hour>=5为high，>=2为medium，其余为low",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "code_template": "def calculate_design_efficiency(test_cases, design_hours):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "30, 5", "expected": "cases_per_hour=6.0, efficiency_level=high"}]',
            "solution": "def calculate_design_efficiency(test_cases, design_hours):\n    cph = round(test_cases / design_hours, 1) if design_hours > 0 else 0\n    if cph >= 5:\n        level = 'high'\n    elif cph >= 2:\n        level = 'medium'\n    else:\n        level = 'low'\n    return {'cases_per_hour': cph, 'efficiency_level': level}",
            "hint": "效率 = 用例数 / 设计工时，再按阈值分类",
        },
        {
            "title": "编写函数计算缺陷密度",
            "description": "编写Python函数calculate_defect_density(defect_count, size_metric)，\n计算缺陷密度。\n\ndefect_count: int，缺陷数量\nsize_metric: float，规模度量（千行代码KLOC或功能点FP）\n返回: dict {'density': float, 'unit': str}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "code_template": "def calculate_defect_density(defect_count, size_metric):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "25, 10.5", "expected": "density=2.38"}]',
            "solution": "def calculate_defect_density(defect_count, size_metric):\n    density = round(defect_count / size_metric, 2) if size_metric > 0 else 0\n    return {'density': density, 'unit': 'defects/KLOC'}",
            "hint": "缺陷密度 = 缺陷数 / 规模度量",
        },
        {
            "title": "编写函数计算缺陷移除效率",
            "description": "编写Python函数calculate_dre(found_by_test, found_by_customer)，\n计算缺陷移除效率(DRE)。\n\nfound_by_test: int，测试阶段发现的缺陷数\nfound_by_customer: int，客户发现的缺陷数\n返回: dict {'dre': float, 'percentage': str}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "code_template": "def calculate_dre(found_by_test, found_by_customer):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "90, 10", "expected": "dre=0.9, percentage=90.0%"}]',
            "solution": "def calculate_dre(found_by_test, found_by_customer):\n    total = found_by_test + found_by_customer\n    dre = round(found_by_test / total, 2) if total > 0 else 0\n    percentage = f\"{round(dre * 100, 1)}%\"\n    return {'dre': dre, 'percentage': percentage}",
            "hint": "DRE = 测试发现 / (测试发现 + 客户发现)",
        },
        {
            "title": "编写函数分析质量趋势",
            "description": "编写Python函数quality_trend(weekly_defects)，\n分析缺陷趋势。\n\nweekly_defects: list of int，每周发现的缺陷数\n返回: dict {'trend': str, 'peak_week': int, 'avg_per_week': float}\n\ntrend: 如果最后3周平均 < 整体平均则为improving，否则为stable或declining",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "code_template": "def quality_trend(weekly_defects):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[10, 15, 20, 12, 8, 5]", "expected": "trend=improving, peak_week=3"}]',
            "solution": "def quality_trend(weekly_defects):\n    if not weekly_defects:\n        return {'trend': 'stable', 'peak_week': 0, 'avg_per_week': 0}\n    avg = sum(weekly_defects) / len(weekly_defects)\n    peak_week = weekly_defects.index(max(weekly_defects)) + 1\n    if len(weekly_defects) >= 3:\n        recent_avg = sum(weekly_defects[-3:]) / 3\n        if recent_avg < avg * 0.8:\n            trend = 'improving'\n        elif recent_avg > avg * 1.2:\n            trend = 'declining'\n        else:\n            trend = 'stable'\n    else:\n        trend = 'stable'\n    return {'trend': trend, 'peak_week': peak_week, 'avg_per_week': round(avg, 1)}",
            "hint": "比较最近3周平均值与整体平均值的关系",
        },

        # ==================== 简答题 (35题) ====================
        # --- 测试计划编写 IEEE 829 (easy/medium) ---
        {
            "title": "请解释IEEE 829测试计划标准的主要组成部分",
            "description": "请详细说明IEEE 829标准中测试计划应包含哪些主要部分，以及各部分的作用。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "IEEE 829测试计划标准的主要组成部分：\n\n1. 引言：说明测试目的、范围和参考文档\n2. 测试项：列出需要测试的功能和特性\n3. 被测试的特性：详细描述被测系统的功能\n4. 不被测试的特性：明确排除的功能及原因\n5. 测试方法：描述测试策略和方法\n6. 测试项通过/失败准则：定义判定标准\n7. 测试暂停/恢复准则：定义中断条件\n8. 测试交付物：列出测试产出文档\n9. 测试任务：定义具体的测试活动\n10. 环境需求：描述硬件、软件环境\n11. 职责：明确各角色的责任\n12. 人员配备与培训：人员需求\n13. 进度安排：时间节点\n14. 风险与应急措施：风险分析\n15. 审批：签字确认",
        },
        {
            "title": "请说明测试计划与测试策略的区别",
            "description": "请比较测试计划和测试策略的定义、内容、侧重点和使用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "测试计划与测试策略的区别：\n\n测试计划：\n- 定义：描述特定项目的测试活动安排\n- 内容：范围、进度、资源、风险、交付物\n- 侧重：做什么、谁来做、何时做\n- 使用：项目级别，针对具体项目\n\n测试策略：\n- 定义：描述组织级的测试方法和原则\n- 内容：测试类型、方法、工具选择标准\n- 侧重：怎么做、用什么方法\n- 使用：组织级别，可跨项目复用\n\n关系：测试策略是测试计划的输入，测试计划引用并细化策略中的方法。",
        },
        {
            "title": "请描述制定测试计划的步骤",
            "description": "请详细描述从项目启动到测试计划定稿的完整步骤。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "制定测试计划的步骤：\n\n1. 分析需求：理解项目需求和业务目标\n2. 确定测试范围：明确测试和不测试的内容\n3. 风险评估：识别项目和产品风险\n4. 确定测试策略：选择测试方法和类型\n5. 估算工作量：评估测试所需时间和资源\n6. 制定进度安排：规划里程碑和时间节点\n7. 分配资源：确定人员、工具、环境需求\n8. 定义准入准出标准：设定开始和结束条件\n9. 编写计划文档：按IEEE 829格式撰写\n10. 评审计划：组织相关人员评审\n11. 修订定稿：根据评审意见修改\n12. 获得批准：获得项目管理层审批",
        },
        {
            "title": "请说明测试计划中测试范围的确定方法",
            "description": "请说明如何确定测试范围，包括输入依据和考虑因素。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "确定测试范围的方法：\n\n输入依据：\n- 需求规格说明书\n- 业务流程文档\n- 用户故事和验收标准\n- 历史缺陷数据\n\n考虑因素：\n1. 功能重要性：核心功能优先覆盖\n2. 用户使用频率：高频功能重点测试\n3. 技术复杂度：复杂模块需要更多测试\n4. 历史缺陷率：缺陷多的模块重点测试\n5. 变更范围：新修改的功能需要测试\n6. 合规要求：法规要求必须测试的内容\n\n确定步骤：\n1. 列出所有功能模块\n2. 评估各模块的测试优先级\n3. 标记不测试的内容及原因\n4. 获得利益相关者确认",
        },
        {
            "title": "请说明敏捷模式下测试计划的特点",
            "description": "请说明敏捷开发模式下测试计划与传统测试计划的主要区别。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "敏捷模式下测试计划的特点：\n\n1. 轻量化：不追求大而全的文档，注重实用性\n2. 迭代式：每个Sprint都有测试计划，持续更新\n3. 持续更新：随需求变化快速调整\n4. 团队协作：全团队参与计划制定\n5. 价值驱动：优先测试高价值功能\n6. 即时反馈：快速执行和反馈循环\n\n与传统模式的区别：\n- 传统：一次性的详细计划\n- 敏捷：持续演进的轻量计划\n- 传统：计划驱动\n- 敏捷：价值驱动",
        },
        # --- 测试策略制定 (medium/hard) ---
        {
            "title": "请解释常见的测试策略类型及其适用场景",
            "description": "请列举并解释至少4种常见的测试策略类型，说明各自的适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "常见测试策略类型：\n\n1. 基于需求的测试策略\n- 适用：需求明确、稳定的项目\n- 特点：直接从需求推导测试用例\n\n2. 基于风险的测试策略\n- 适用：资源有限、需要优先级排序\n- 特点：优先测试高风险区域\n\n3. 基于经验的测试策略\n- 适用：需求不明确或快速迭代\n- 特点：依赖测试人员经验，探索性测试\n\n4. 回归测试策略\n- 适用：频繁变更的系统\n- 特点：关注变更影响范围\n\n5. 自动化测试策略\n- 适用：重复性高、稳定性好的测试\n- 特点：提高效率，降低人工成本\n\n6. 混合测试策略\n- 适用：大型复杂项目\n- 特点：结合多种策略优势",
        },
        {
            "title": "请说明如何制定自动化测试策略",
            "description": "请详细说明自动化测试策略的制定过程，包括评估标准和实施步骤。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "自动化测试策略制定：\n\n评估标准（适合自动化的场景）：\n- 需要频繁执行的回归测试\n- 手工测试容易出错的场景\n- 需要大量数据的测试\n- 性能测试和压力测试\n- 跨浏览器/跨平台测试\n\n不适合自动化的场景：\n- 需求频繁变更的功能\n- 一次性测试\n- 探索性测试\n- 用户体验测试\n\n实施步骤：\n1. 评估自动化ROI\n2. 选择合适的工具和框架\n3. 确定自动化范围和优先级\n4. 建立自动化测试架构\n5. 编写和维护测试脚本\n6. 集成到CI/CD流程\n7. 持续优化和维护",
        },
        {
            "title": "请解释测试分层策略（测试金字塔）",
            "description": "请解释测试金字塔的概念、各层的占比建议和实际应用。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "测试金字塔：\n\n概念：Martin Fowler提出的测试分层模型，从底层到顶层：\n\n1. 单元测试（底层，占比70%）\n- 数量最多，执行最快\n- 覆盖函数、类级别\n- 开发人员负责\n\n2. 集成测试（中层，占比20%）\n- 验证模块间交互\n- 包含API测试、服务测试\n- 执行速度适中\n\n3. UI测试（顶层，占比10%）\n- 数量最少，执行最慢\n- 验证端到端流程\n- 测试人员负责\n\n实际应用：\n- 理想比例为7:2:1\n- 根据项目特点调整\n- 自动化优先从底层开始\n- 顶层测试应精简高效",
        },
        {
            "title": "请说明如何制定性能测试策略",
            "description": "请说明性能测试策略的制定方法，包括测试类型、指标和工具选择。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试策略制定",
            "solution": "性能测试策略制定：\n\n测试类型：\n1. 负载测试：验证预期负载下的性能\n2. 压力测试：找出系统极限\n3. 稳定性测试：长期运行验证\n4. 并发测试：多用户同时访问\n5. 容量测试：大数据量测试\n\n关键指标：\n- 响应时间（RT）\n- 吞吐量（TPS/QPS）\n- 并发用户数\n- 资源利用率（CPU/内存/IO）\n- 错误率\n\n工具选择：\n- JMeter：开源，支持多协议\n- LoadRunner：企业级，功能全面\n- Locust：Python编写，灵活\n- Gatling：高性能，代码驱动\n\n实施步骤：\n1. 确定性能需求和目标\n2. 设计测试场景\n3. 准备测试环境和数据\n4. 执行测试并监控\n5. 分析结果和调优建议",
        },
        # --- 测试范围与风险评估 (medium/hard) ---
        {
            "title": "请解释产品风险和项目风险的区别",
            "description": "请分别说明产品风险和项目风险的定义、来源和应对策略。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "产品风险与项目风险的区别：\n\n产品风险：\n- 定义：产品质量相关的风险\n- 来源：功能缺陷、性能问题、安全漏洞、兼容性问题\n- 影响：用户体验差、数据丢失、系统崩溃\n- 应对：加强测试覆盖、自动化回归、性能测试\n\n项目风险：\n- 定义：项目管理相关的风险\n- 来源：人员流失、进度延迟、资源不足、需求变更\n- 影响：项目延期、成本超支、质量下降\n- 应对：风险预案、资源备份、敏捷迭代、沟通管理\n\n共同点：\n- 都需要识别和评估\n- 都需要制定应对计划\n- 都需要持续监控",
        },
        {
            "title": "请说明风险评估的步骤和方法",
            "description": "请详细说明测试中风险评估的完整步骤和常用方法。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "风险评估步骤：\n\n1. 风险识别\n- 头脑风暴\n- 检查清单\n- 专家访谈\n- 历史数据分析\n\n2. 风险分析\n- 定性分析：概率和影响评级\n- 定量分析：数值计算\n- 风险矩阵：可视化优先级\n\n3. 风险优先级排序\n- 计算风险分数 = 概率 * 影响\n- 按分数高低排序\n- 确定重点关注的风险\n\n4. 风险应对计划\n- 规避：消除风险源\n- 转移：将风险转移给第三方\n- 减轻：降低概率或影响\n- 接受：制定应急预案\n\n5. 风险监控\n- 定期评审风险状态\n- 更新风险登记表\n- 调整应对策略",
        },
        {
            "title": "请说明如何根据风险评估结果调整测试范围",
            "description": "请说明风险评估结果如何影响测试范围的确定和测试资源的分配。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试范围与风险评估",
            "solution": "根据风险调整测试范围的方法：\n\n1. 高风险区域\n- 扩大测试范围\n- 增加测试深度和广度\n- 分配最优秀的测试人员\n- 使用多种测试方法\n- 增加自动化覆盖\n\n2. 中风险区域\n- 标准测试覆盖\n- 常规测试方法\n- 正常资源分配\n\n3. 低风险区域\n- 缩减测试范围\n- 基本功能验证\n- 可以减少测试轮次\n- 考虑抽样测试\n\n资源分配原则：\n- 高风险占测试资源的50-60%\n- 中风险占30-40%\n- 低风险占10-20%\n\n动态调整：\n- 随项目进展重新评估\n- 根据新发现的风险调整\n- 考虑已修复缺陷的影响",
        },
        # --- 资源估算与进度管理 (medium/hard) ---
        {
            "title": "请介绍常用的测试工作量估算方法",
            "description": "请介绍至少3种测试工作量估算方法，说明其原理、优缺点和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "常用测试工作量估算方法：\n\n1. 类比估算法\n- 原理：参考类似历史项目数据\n- 优点：简单快速\n- 缺点：依赖历史数据质量\n- 适用：有丰富历史数据的组织\n\n2. 专家判断法（德尔菲法）\n- 原理：多位专家独立估算后汇总\n- 优点：利用专家经验\n- 缺点：主观性强\n- 适用：新型项目或缺乏历史数据\n\n3. 功能点分析法\n- 原理：基于功能点数量估算\n- 优点：与技术无关，可早期使用\n- 缺点：需要专业培训\n- 适用：需求明确的项目\n\n4. 计划扑克法\n- 原理：团队协作估算（敏捷常用）\n- 优点：团队共识，考虑全面\n- 缺点：需要团队参与\n- 适用：敏捷开发项目\n\n5. 三点估算法\n- 原理：(乐观+4*最可能+悲观)/6\n- 优点：考虑不确定性\n- 缺点：需要多次估算\n- 适用：不确定性高的项目",
        },
        {
            "title": "请说明测试进度管理的关键活动",
            "description": "请说明测试进度管理中需要关注的关键活动和监控指标。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "测试进度管理的关键活动：\n\n1. 制定进度计划\n- 定义里程碑\n- 分解测试任务\n- 确定任务依赖关系\n- 分配资源\n\n2. 进度监控\n- 每日站会同步进展\n- 跟踪测试执行进度\n- 监控缺陷发现和修复速率\n- 识别进度偏差\n\n3. 关键监控指标\n- 用例执行进度（计划vs实际）\n- 缺陷发现速率趋势\n- 缺陷修复速率\n- 测试覆盖率\n- 阻塞问题数量\n\n4. 进度调整\n- 增加资源（人力或工具）\n- 调整测试优先级\n- 优化测试流程\n- 必要时调整里程碑\n\n5. 沟通汇报\n- 定期进度报告\n- 风险预警\n- 干系人沟通",
        },
        {
            "title": "请解释甘特图和关键路径法在测试项目中的应用",
            "description": "请说明甘特图和关键路径法的原理，以及如何在测试项目管理中应用。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "资源估算与进度管理",
            "solution": "甘特图：\n- 原理：条形图显示任务的时间安排\n- 应用：\n  1. 可视化测试任务时间线\n  2. 显示任务并行和依赖关系\n  3. 标记里程碑节点\n  4. 跟踪实际进度vs计划\n- 优点：直观易懂\n- 缺点：不直接显示关键路径\n\n关键路径法（CPM）：\n- 原理：找出决定项目最短工期的任务链\n- 应用：\n  1. 识别测试项目的关键路径\n  2. 确定哪些任务不能延迟\n  3. 优化关键路径上的资源分配\n  4. 评估进度变更的影响\n- 优点：突出重点任务\n- 缺点：需要详细的任务分解\n\n实际应用：\n- 结合两者优势\n- 用甘特图展示整体进度\n- 用CPM识别关键任务\n- 优先保障关键路径资源",
        },
        # --- 测试入口出口准则 (medium) ---
        {
            "title": "请详细说明系统测试的入口准则和出口准则",
            "description": "请分别列出系统测试阶段的入口准则和出口准则，并解释每条准则的意义。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "系统测试入口准则：\n1. 需求文档已评审通过并基线化\n2. 测试计划已获批准\n3. 测试用例已评审通过\n4. 测试环境已搭建并验证\n5. 开发团队提交系统测试申请\n6. 冒烟测试通过\n7. 测试数据已准备\n\n系统测试出口准则：\n1. 所有高优先级测试用例已执行\n2. 用例执行率达到95%以上\n3. 用例通过率达到90%以上\n4. 严重以上缺陷全部修复\n5. 一般缺陷修复率达到95%\n6. 遗留缺陷有明确处理方案\n7. 测试报告已编写完成\n8. 回归测试通过",
        },
        {
            "title": "请说明如何制定合理的入口出口准则",
            "description": "请说明制定入口出口准则的原则、考虑因素和常见问题。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "制定入口出口准则的原则：\n\n1. 可衡量性\n- 使用具体数值而非模糊描述\n- 例如：执行率>=95%，而非大部分执行\n\n2. 可达成性\n- 标准不能过高或过低\n- 要考虑项目实际情况\n\n3. 项目适配性\n- 根据项目规模和重要性调整\n- 关键系统标准更高\n\n考虑因素：\n- 项目风险等级\n- 质量要求\n- 时间和资源约束\n- 历史项目经验\n- 行业标准和规范\n\n常见问题：\n1. 标准过高导致无法退出\n2. 标准过低导致质量不足\n3. 缺乏明确的数值指标\n4. 准则未获得各方认可\n5. 执行时缺乏严格把关\n\n最佳实践：\n- 多方参与制定\n- 定期评审和调整\n- 记录例外情况和审批流程",
        },
        {
            "title": "请解释测试暂停准则和恢复准则",
            "description": "请说明在什么情况下应该暂停测试，以及恢复测试需要满足什么条件。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试入口出口准则",
            "solution": "测试暂停准则（何时暂停）：\n1. 发现阻塞性缺陷，无法继续测试\n2. 测试环境严重不稳定\n3. 需求发生重大变更\n4. 关键资源不可用（人员、工具）\n5. 版本构建失败\n6. 缺陷修复引入新的严重问题\n7. 安全漏洞需要紧急处理\n\n测试恢复准则（何时恢复）：\n1. 阻塞性缺陷已修复并验证\n2. 测试环境恢复稳定\n3. 需求变更已评审并更新用例\n4. 关键资源已到位\n5. 新版本构建成功\n6. 新引入的问题已解决\n7. 安全问题已修复\n\n管理要点：\n- 明确定义暂停/恢复条件\n- 建立沟通和升级机制\n- 记录暂停原因和影响\n- 评估暂停对进度的影响",
        },
        # --- 测试报告编写 (easy/medium/hard) ---
        {
            "title": "请说明测试报告应包含的核心内容",
            "description": "请详细说明一份完整的测试报告应包含哪些核心内容。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "solution": "测试报告核心内容：\n\n1. 报告概述\n- 项目名称和版本\n- 测试周期\n- 报告编写人\n\n2. 测试执行概况\n- 计划用例数vs执行数\n- 通过/失败/阻塞统计\n- 执行率和通过率\n\n3. 缺陷分析\n- 缺陷总数和分布\n- 按严重程度分类\n- 按模块分类\n- 缺陷趋势图\n\n4. 测试环境\n- 硬件配置\n- 软件版本\n- 测试工具\n\n5. 遗留问题\n- 未修复的缺陷\n- 风险评估\n- 处理建议\n\n6. 测试结论\n- 质量评估\n- 发布建议\n- 后续计划\n\n7. 附录\n- 详细数据表\n- 参考文档",
        },
        {
            "title": "请说明如何编写有效的缺陷分析报告",
            "description": "请说明缺陷分析报告应包含哪些维度的分析，以及如何从数据中得出有价值的结论。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "solution": "缺陷分析报告的维度：\n\n1. 数量维度\n- 缺陷总数统计\n- 新增vs修复vs遗留趋势\n- 每日/每周缺陷曲线\n\n2. 严重程度维度\n- 按critical/major/minor/trivial分类\n- 各级别占比分析\n- 严重缺陷趋势\n\n3. 模块分布维度\n- 各模块缺陷数量\n- 缺陷密度对比\n- 识别高风险模块\n\n4. 状态维度\n- open/resolved/closed统计\n- 缺陷生命周期分析\n- 平均修复时间\n\n5. 根因分析\n- 缺陷类型分布（功能/性能/界面等）\n- 引入阶段分析\n- 根本原因分类\n\n有价值的结论：\n- 质量趋势判断\n- 风险预警\n- 改进建议\n- 资源优化建议",
        },
        {
            "title": "请说明测试报告中如何进行质量评估",
            "description": "请说明如何基于测试数据对产品质量进行综合评估。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试报告编写",
            "solution": "质量评估方法：\n\n1. 缺陷指标评估\n- 缺陷密度：与行业基准对比\n- 缺陷移除效率：测试发现率\n- 遗留缺陷风险：未修复缺陷影响\n\n2. 测试覆盖评估\n- 需求覆盖率：已测需求/总需求\n- 代码覆盖率：语句/分支覆盖\n- 用例覆盖率：已执行/总用例\n\n3. 过程质量评估\n- 缺陷发现速率趋势\n- 缺陷修复速率\n- 回归测试通过率\n\n4. 综合评估模型\n- 建立质量评分卡\n- 设置各项指标权重\n- 计算综合质量分数\n\n5. 发布建议\n- 基于评估结果给出建议\n- 明确遗留风险\n- 提出后续改进措施\n\n注意事项：\n- 结合定量和定性分析\n- 考虑业务影响\n- 与历史数据对比",
        },
        # --- 测试项目管理方法论 (medium/hard) ---
        {
            "title": "请说明敏捷测试管理与传统测试管理的区别",
            "description": "请从测试计划、测试执行、团队协作等方面比较敏捷测试和传统测试管理的差异。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "敏捷测试与传统测试管理的区别：\n\n1. 测试计划\n- 传统：详细的前期计划，相对固定\n- 敏捷：轻量级计划，随迭代调整\n\n2. 测试时机\n- 传统：开发完成后集中测试\n- 敏捷：与开发并行，持续测试\n\n3. 文档管理\n- 传统：大量正式文档\n- 敏捷：精简文档，注重沟通\n\n4. 团队协作\n- 传统：测试团队独立运作\n- 敏捷：跨职能团队紧密协作\n\n5. 需求变更\n- 传统：变更成本高，流程复杂\n- 敏捷：拥抱变更，快速响应\n\n6. 反馈周期\n- 传统：反馈周期长\n- 敏捷：快速反馈，持续改进\n\n7. 自动化程度\n- 传统：自动化程度较低\n- 敏捷：高度依赖自动化\n\n8. 质量责任\n- 传统：测试团队对质量负责\n- 敏捷：全团队对质量负责",
        },
        {
            "title": "请说明如何进行测试团队的组建和管理",
            "description": "请说明测试团队的组织结构、人员配置、能力建设和绩效管理。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "测试团队组建和管理：\n\n1. 组织结构\n- 独立测试部门\n- 嵌入式测试团队\n- 矩阵式管理\n\n2. 人员配置\n- 测试经理：整体管理\n- 测试架构师：技术方案\n- 测试工程师：用例设计和执行\n- 自动化工程师：工具和脚本\n- 性能测试工程师：专项测试\n\n3. 能力建设\n- 技术能力：工具、编程、数据库\n- 业务能力：行业知识、用户思维\n- 软技能：沟通、分析、学习能力\n- 培训计划：内部培训、外部认证\n\n4. 绩效管理\n- 量化指标：缺陷发现数、用例设计数\n- 质量指标：漏测率、回归通过率\n- 效率指标：执行速率、自动化率\n- 360度评估\n\n5. 团队文化\n- 质量意识\n- 持续学习\n- 知识共享\n- 协作精神",
        },
        {
            "title": "请说明测试配置管理的重要性和实施方法",
            "description": "请说明测试配置管理的概念、管理对象和实施流程。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "测试配置管理：\n\n重要性：\n- 确保测试环境一致性\n- 追溯测试基线\n- 管理测试版本\n- 控制变更影响\n\n管理对象：\n1. 测试文档：计划、用例、报告\n2. 测试脚本：自动化脚本\n3. 测试数据：测试输入和预期结果\n4. 测试环境：配置信息\n5. 被测软件：版本和构建\n\n实施流程：\n1. 配置识别\n- 确定配置项\n- 建立配置库\n- 制定命名规范\n\n2. 配置控制\n- 变更申请流程\n- 变更评审\n- 版本管理\n\n3. 配置状态报告\n- 记录配置项状态\n- 生成状态报告\n- 变更历史追溯\n\n4. 配置审计\n- 功能配置审计\n- 物理配置审计\n- 定期检查",
        },
        {
            "title": "请说明如何管理测试中的变更",
            "description": "请说明需求变更对测试的影响，以及如何有效管理测试变更。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "测试变更管理：\n\n需求变更对测试的影响：\n- 测试用例需要更新\n- 测试范围可能扩大\n- 测试进度可能延迟\n- 测试资源需要增加\n- 回归测试范围扩大\n\n变更管理流程：\n1. 变更识别\n- 监控需求变更通知\n- 评估变更影响范围\n\n2. 变更评估\n- 分析对测试用例的影响\n- 估算额外工作量\n- 评估风险\n\n3. 变更审批\n- 提交变更影响报告\n- 获得管理层审批\n\n4. 变更实施\n- 更新测试用例\n- 调整测试计划\n- 重新分配资源\n\n5. 变更验证\n- 执行变更相关测试\n- 回归测试\n\n最佳实践：\n- 建立变更控制委员会\n- 使用需求追溯矩阵\n- 自动化回归测试\n- 预留缓冲时间",
        },
        # --- 测试度量与质量评估 (medium/hard) ---
        {
            "title": "请介绍常用的测试度量指标",
            "description": "请分类介绍测试过程中常用的度量指标，说明其计算方法和应用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "常用测试度量指标：\n\n1. 进度指标\n- 用例执行率 = 已执行/总用例\n- 用例通过率 = 通过数/已执行数\n- 计划vs实际进度偏差\n\n2. 质量指标\n- 缺陷密度 = 缺陷数/规模（KLOC或FP）\n- 缺陷移除效率 = 测试发现/(测试发现+客户发现)\n- 缺陷逃逸率 = 客户发现/总缺陷\n\n3. 效率指标\n- 用例设计效率 = 用例数/人天\n- 缺陷发现效率 = 缺陷数/测试人天\n- 自动化覆盖率 = 自动化用例/总用例\n\n4. 覆盖指标\n- 需求覆盖率 = 已测需求/总需求\n- 代码覆盖率 = 已覆盖代码/总代码\n- 风险覆盖率 = 已覆盖风险/总风险\n\n5. 成本指标\n- 测试成本 = 测试投入/总项目成本\n- 缺陷修复成本 = 修复总工时/缺陷数\n\n应用场景：\n- 项目监控和决策\n- 质量趋势分析\n- 过程改进依据",
        },
        {
            "title": "请说明如何建立测试度量体系",
            "description": "请说明建立测试度量体系的步骤、选择指标的原则和实施注意事项。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "建立测试度量体系：\n\n步骤：\n1. 明确度量目标\n- 支持决策\n- 监控质量\n- 改进过程\n\n2. 选择度量指标\n- 与目标对齐\n- 可采集可计算\n- 数量适中（5-10个核心指标）\n\n3. 建立数据采集机制\n- 工具自动化采集\n- 明确采集责任人\n- 确保数据准确性\n\n4. 设定基线和目标\n- 历史数据作为基线\n- 行业标准作为参考\n- 设定合理目标值\n\n5. 建立报告机制\n- 定期生成报告\n- 可视化展示\n- 异常预警\n\n选择指标的原则：\n- SMART原则（具体、可衡量、可达、相关、有时限）\n- 成本效益原则\n- 行动导向原则\n\n注意事项：\n- 避免度量过多\n- 防止指标被操纵\n- 结合定性和定量\n- 持续优化指标体系",
        },
        {
            "title": "请说明如何利用测试度量进行过程改进",
            "description": "请说明如何通过分析测试度量数据发现问题，并推动测试过程的持续改进。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "利用测试度量进行过程改进：\n\n1. 数据分析发现问题\n- 缺陷密度高的模块 -> 测试覆盖不足或开发质量差\n- 缺陷逃逸率高 -> 测试策略需要优化\n- 回归失败率高 -> 自动化覆盖不足\n- 用例设计效率低 -> 需要改进设计方法\n\n2. 根因分析\n- 使用鱼骨图分析原因\n- 5Why分析法追溯根本原因\n- 区分人员、流程、工具问题\n\n3. 制定改进措施\n- 针对根因制定具体措施\n- 设定改进目标和时间表\n- 分配责任人\n\n4. 实施改进\n- 小步快跑，逐步改进\n- 培训和知识传递\n- 工具和流程优化\n\n5. 验证效果\n- 对比改进前后的度量数据\n- 评估改进效果\n- 总结经验教训\n\n6. 持续循环\n- 建立PDCA循环\n- 定期回顾和调整\n- 形成持续改进文化",
        },
        {
            "title": "请解释测试估算中的不确定性管理",
            "description": "请说明测试估算中不确定性的来源，以及如何使用三点估算法等方法管理不确定性。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "测试估算中的不确定性管理：\n\n不确定性来源：\n1. 需求不确定性：需求不明确或频繁变更\n2. 技术不确定性：新技术、复杂架构\n3. 人员不确定性：团队能力、人员变动\n4. 环境不确定性：环境搭建、工具限制\n5. 历史数据不足：缺乏参考基准\n\n管理方法：\n\n1. 三点估算法\n- 乐观估算(O)：最理想情况\n- 最可能估算(M)：正常情况\n- 悲观估算(P)：最差情况\n- 期望值 = (O + 4M + P) / 6\n- 标准差 = (P - O) / 6\n\n2. 预留缓冲\n- 根据不确定性程度预留10-30%缓冲\n- 高不确定性项目预留更多\n\n3. 渐进式估算\n- 随项目进展细化估算\n- 定期重新评估\n\n4. 范围估算\n- 给出估算范围而非单一值\n- 例如：20-30人天\n\n5. 风险调整\n- 识别估算风险\n- 量化风险影响\n- 调整估算值",
        },
        {
            "title": "请说明如何管理测试项目的沟通",
            "description": "请说明测试项目中沟通管理的要点，包括沟通对象、频率和方式。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "测试项目沟通管理：\n\n沟通对象：\n1. 项目经理：进度和风险汇报\n2. 开发团队：缺陷和变更沟通\n3. 产品团队：需求和验收标准\n4. 管理层：质量状态和决策支持\n5. 客户：验收和发布沟通\n\n沟通频率：\n- 每日：团队站会，同步进展\n- 每周：进度报告，风险更新\n- 里程碑：阶段总结，质量评估\n- 紧急：阻塞问题，重大风险\n\n沟通方式：\n- 会议：评审会、回顾会\n- 报告：日报、周报、测试报告\n- 工具：项目管理平台、即时通讯\n- 文档：共享文档、知识库\n\n最佳实践：\n- 建立标准化沟通模板\n- 明确信息升级机制\n- 保持透明和及时\n- 记录重要决策和结论",
        },
        {
            "title": "请说明如何编写测试项目的总结报告",
            "description": "请说明测试项目总结报告的目的、内容和编写要点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "测试项目总结报告：\n\n目的：\n- 记录项目经验教训\n- 为后续项目提供参考\n- 评估测试过程有效性\n- 促进团队能力提升\n\n内容：\n1. 项目概述\n- 项目背景和目标\n- 测试范围和周期\n- 团队组成\n\n2. 测试执行总结\n- 计划vs实际情况对比\n- 关键指标达成情况\n- 里程碑完成情况\n\n3. 质量评估\n- 缺陷统计和分析\n- 质量指标评估\n- 遗留风险分析\n\n4. 问题和挑战\n- 遇到的主要问题\n- 采取的应对措施\n- 未解决的问题\n\n5. 经验教训\n- 做得好的方面\n- 需要改进的方面\n- 具体改进建议\n\n6. 数据附录\n- 详细的度量数据\n- 参考文档列表\n\n编写要点：\n- 客观真实\n- 数据支撑\n- 可操作的建议\n- 知识沉淀",
        },
        {
            "title": "请说明测试环境管理的最佳实践",
            "description": "请说明如何有效管理测试环境，包括环境规划、配置管理和常见问题处理。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "测试环境管理最佳实践：\n\n1. 环境规划\n- 定义环境层次：开发、测试、预生产、生产\n- 明确各环境用途和访问权限\n- 规划环境数量和配置\n\n2. 配置管理\n- 环境配置文档化\n- 使用配置管理工具（Ansible、Terraform）\n- 版本控制环境配置\n- 环境快照和恢复机制\n\n3. 数据管理\n- 测试数据独立管理\n- 敏感数据脱敏处理\n- 数据重置和恢复流程\n- 数据版本控制\n\n4. 常见问题及处理\n- 环境不稳定：建立健康检查机制\n- 环境冲突：实施环境预约和排队\n- 配置不一致：自动化环境搭建\n- 数据污染：测试前数据清理\n\n5. 工具支持\n- 容器化（Docker/K8s）快速搭建\n- 环境监控和告警\n- 自动化部署和配置",
        },
        {
            "title": "请说明测试计划评审的流程和要点",
            "description": "请说明测试计划评审的完整流程、参与人员和评审要点。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试管理",
            "knowledge_point": "测试计划编写(IEEE 829)",
            "solution": "测试计划评审：\n\n评审流程：\n1. 准备阶段\n- 编写完成测试计划初稿\n- 提前发送给评审人员\n- 安排评审会议时间\n\n2. 评审会议\n- 作者介绍计划内容\n- 逐章节讨论和质询\n- 记录问题和建议\n- 达成共识\n\n3. 修订阶段\n- 整理评审意见\n- 修改测试计划\n- 确认修改结果\n\n4. 审批阶段\n- 最终版本审批\n- 归档保存\n\n参与人员：\n- 测试经理/测试负责人\n- 项目经理\n- 开发负责人\n- 产品负责人\n- 质量保证人员\n\n评审要点：\n1. 范围是否完整覆盖需求\n2. 策略是否适合项目特点\n3. 资源估算是否合理\n4. 进度是否可行\n5. 风险是否充分识别\n6. 入口出口准则是否明确\n7. 环境和工具是否就绪\n8. 沟通计划是否完善",
        },
        {
            "title": "请说明测试中的度量陷阱和注意事项",
            "description": "请说明使用测试度量指标时的常见陷阱，以及如何避免这些问题。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试度量与质量评估",
            "solution": "测试度量陷阱和注意事项：\n\n常见陷阱：\n1. 过度依赖单一指标\n- 只看缺陷数量忽略质量\n- 只看覆盖率忽略有效性\n\n2. 指标被操纵\n- 为了达标而拆分用例\n- 降低标准以提高通过率\n- 选择性报告数据\n\n3. 忽略上下文\n- 不同项目直接对比指标\n- 忽略项目规模和复杂度差异\n- 不考虑团队经验和能力\n\n4. 度量成本过高\n- 数据采集消耗大量时间\n- 度量工作影响测试执行\n- 报告编写过于繁琐\n\n5. 目标设定不合理\n- 追求100%覆盖率\n- 设定不可能达到的标准\n- 忽略项目约束条件\n\n避免方法：\n1. 综合使用多个指标\n2. 结合业务上下文分析\n3. 用度量驱动改进而非考核\n4. 定期审视和调整指标\n5. 自动化数据采集\n6. 关注趋势而非绝对值",
        },
        {
            "title": "请说明如何在测试项目中应用持续改进",
            "description": "请说明如何在测试项目中建立持续改进机制，包括度量、分析和改进的闭环。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试管理",
            "knowledge_point": "测试项目管理方法论",
            "solution": "测试项目持续改进：\n\n1. 建立度量基线\n- 收集当前过程数据\n- 建立关键指标基线\n- 设定改进目标\n\n2. 数据收集与分析\n- 每个迭代/Sprint收集数据\n- 分析趋势和异常\n- 识别改进机会\n\n3. 回顾会议\n- 定期举行Sprint回顾\n- 讨论做得好的和需改进的\n- 制定具体改进措施\n\n4. 改进实施\n- 将改进措施纳入下个迭代\n- 分配责任人\n- 设定完成标准\n\n5. 效果验证\n- 对比改进前后数据\n- 评估改进效果\n- 总结经验教训\n\n6. 知识沉淀\n- 记录改进过程和结果\n- 更新最佳实践文档\n- 团队内部分享\n\n常用方法：\n- PDCA循环\n- 根因分析（5Why、鱼骨图）\n- TMMi成熟度评估\n- 敏捷回顾会议",
        },
    ],
}
