import re

with open('generate_lp15_18.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace problematic inner quotes with single quotes
replacements = [
    ('"微服务架构"', "'微服务架构'"),
    ('"单体架构"', "'单体架构'"),
    ('"前后端分离"', "'前后端分离'"),
    ('"已管理级"', "'已管理级'"),
    ('"已定义级"', "'已定义级'"),
    ('"已测量级"', "'已测量级'"),
    ('"优化级"', "'优化级'"),
    ('"冰淇淋锥"', "'冰淇淋锥'"),
    ('"倒三角"', "'倒三角'"),
    ('"测试左移"', "'测试左移'"),
    ('"模型漂移"', "'模型漂移'"),
    ('"Self-Healing"', "'Self-Healing'"),
    ('"忽略区域"', "'忽略区域'"),
    ('"基线截图"', "'基线截图'"),
    ('"DFT"', "'DFT'"),
    ('"五个为什么"', "'五个为什么'"),
    ('"契约测试"', "'契约测试'"),
    ('"服务虚拟化"', "'服务虚拟化'"),
    ('"质量门禁"', "'质量门禁'"),
    ('"金丝雀发布"', "'金丝雀发布'"),
    ('"蓝绿部署"', "'蓝绿部署'"),
    ('"A/B测试"', "'A/B测试'"),
    ('"任务队列"', "'任务队列'"),
    ('"执行引擎"', "'执行引擎'"),
    ('"定时器"', "'定时器'"),
    ('"Timer"', "'Timer'"),
    ('"Proxy"', "'Proxy'"),
    ('"Intruder"', "'Intruder'"),
    ('"假阳性"', "'假阳性'"),
    ('"False Positive"', "'False Positive'"),
    ('"Desired Capabilities"', "'Desired Capabilities'"),
    ('"Accessibility ID"', "'Accessibility ID'"),
    ('"TouchAction"', "'TouchAction'"),
    ('"throttle"', "'throttle'"),
    ('"ignore-crashes"', "'ignore-crashes'"),
    ('"HTTP Cookie管理器"', "'HTTP Cookie管理器'"),
    ('"吞吐量控制器"', "'吞吐量控制器'"),
    ('"Debug Sampler"', "'Debug Sampler'"),
    ('"Cache"', "'Cache'"),
    ('"Artifacts"', "'Artifacts'"),
    ('"Runner"', "'Runner'"),
    ('"Jenkinsfile"', "'Jenkinsfile'"),
    ('"stage"', "'stage'"),
    ('"agent"', "'agent'"),
    ('"FROM"', "'FROM'"),
    ('"COPY"', "'COPY'"),
    ('"ADD"', "'ADD'"),
    ('"声明式Pipeline"', "'声明式Pipeline'"),
    ('"脚本式Pipeline"', "'脚本式Pipeline'"),
    ('"rebase"', "'rebase'"),
    ('"merge"', "'merge'"),
    ('"cherry-pick"', "'cherry-pick'"),
    ('"feature"', "'feature'"),
    ('"release"', "'release'"),
    ('"hotfix"', "'hotfix'"),
    ('"main"', "'main'"),
    ('"develop"', "'develop'"),
    ('"v-model"', "'v-model'"),
    ('"离线模式"', "'离线模式'"),
    ('"后台运行"', "'后台运行'"),
    ('"权限测试"', "'权限测试'"),
    ('"推送通知"', "'推送通知'"),
    ('"安装/卸载/升级"', "'安装/卸载/升级'"),
    ('"中断测试"', "'中断测试'"),
    ('"横竖屏切换"', "'横竖屏切换'"),
    ('"深色模式"', "'深色模式'"),
    ('"电量测试"', "'电量测试'"),
    ('"冷启动"', "'冷启动'"),
    ('"热启动"', "'热启动'"),
    ('"内存泄漏"', "'内存泄漏'"),
    ('"手势操作"', "'手势操作'"),
    ('"信息泄露"', "'信息泄露'"),
    ('"自愈自动化测试"', "'自愈自动化测试'"),
    ('"使用情况的测试"', "'使用情况的测试'"),
    ('"倒三角"', "'倒三角'"),
    ('"冰淇淋锥"', "'冰淇淋锥'"),
    ('"测试左移"', "'测试左移'"),
    ('"模型漂移"', "'模型漂移'"),
]

for old, new in replacements:
    content = content.replace(old, new)

with open('generate_lp15_18.py', 'w', encoding='utf-8') as f:
    f.write(content)

print('Inner quotes fixed')
