"""
重新生成 LP12-LP14 高质量习题
根据课程内容精心设计每道题，确保选项有实质内容
"""
import sqlite3
from datetime import datetime

import os

def get_db():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return sqlite3.connect(os.path.join(base_dir, 'instance', 'testmaster.db'))

def insert_exercise(cursor, title, description, solution, exercise_type, difficulty, learning_path_id, category, lang="中文"):
    cursor.execute("""
        INSERT INTO exercises
        (title, description, solution, exercise_type, difficulty,
         learning_path_id, category, is_public, language,
         created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, datetime('now'), datetime('now'))
    """, (title, description, solution, exercise_type, difficulty, learning_path_id, category, lang))

# ========== LP12: 移动端测试基础 (50题) ==========
LP12_EXERCISES = [
    # 移动端测试概述 (8题)
    ("Android和iOS平台在应用发布审核机制上的主要区别是什么？",
     "Android和iOS平台在应用发布审核机制上的主要区别是什么？\n\nA. Android应用无需审核即可直接发布到Google Play，iOS应用需要经过Apple严格的审核流程\nB. iOS应用通常审核周期为1-2天，Android应用审核周期为3-7天\nC. 两个平台都采用完全相同的自动化审核机制，没有人工介入\nD. Android和iOS的审核标准和流程完全一致，主要检查内容是否合规",
     "A", "single_choice", "medium", "移动端测试概述"),
    ("以下哪项不是移动端测试相较于Web端测试的特殊挑战？",
     "以下哪项不是移动端测试相较于Web端测试的特殊挑战？\n\nA. 设备碎片化，需要适配多种屏幕尺寸和分辨率\nB. 网络环境复杂，需要处理弱网、断网、网络切换等场景\nC. 浏览器兼容性问题，需要适配Chrome、Firefox、Safari等\nD. 系统资源有限，需要关注内存、电量、CPU等性能指标",
     "C", "single_choice", "easy", "移动端测试概述"),
    ("移动端应用的'安装包大小'优化主要考虑哪些因素？",
     "移动端应用的'安装包大小'优化主要考虑哪些因素？\n\nA. 主要考虑代码行数，代码越少包越小\nB. 需要考虑图片资源压缩、代码混淆、无用资源移除、so库过滤等多个方面\nC. 只需要压缩图片资源即可，其他因素影响不大\nD. 安装包大小对用户体验没有影响，不需要优化",
     "B", "single_choice", "medium", "移动端测试概述"),
    ("关于移动端应用的生命周期测试，以下说法正确的是？",
     "关于移动端应用的生命周期测试，以下说法正确的是？\n\nA. 只需要测试应用启动和退出两个状态\nB. 需要测试启动、前台运行、后台运行、挂起、恢复、终止等多种状态的转换\nC. 应用生命周期测试只在iOS上需要，Android不需要\nD. 生命周期测试是开发人员的职责，与测试人员无关",
     "B", "single_choice", "medium", "移动端测试概述"),
    ("以下哪些是移动端测试需要覆盖的典型场景？",
     "以下哪些是移动端测试需要覆盖的典型场景？（多选）\n\nA. 横竖屏切换\nB. 来电/短信中断\nC. 低电量模式\nD. 夜间模式切换",
     "A,B,C,D", "multiple_choice", "easy", "移动端测试概述"),
    ("Android碎片化问题主要体现在哪些方面？",
     "Android碎片化问题主要体现在哪些方面？（多选）\n\nA. 操作系统版本众多（Android 8/9/10/11/12/13/14等）\nB. 设备厂商众多，每个厂商都有定制UI\nC. 屏幕尺寸和分辨率差异巨大\nD. 硬件配置差异（内存、CPU、摄像头等）",
     "A,B,C,D", "multiple_choice", "easy", "移动端测试概述"),
    ("Android和iOS的推送通知机制完全相同，都使用APNs服务。",
     "Android和iOS的推送通知机制完全相同，都使用APNs服务。\n\nA. 正确\nB. 错误",
     "B", "true_false", "easy", "移动端测试概述"),
    ("以下关于移动端测试和Web端测试区别的描述，正确的是？",
     "以下关于移动端测试和Web端测试区别的描述，正确的是？\n\nA. 移动端测试和Web端测试完全相同，没有区别\nB. 移动端测试需要考虑更多设备和环境因素，如电量、信号、传感器等\nC. Web端测试比移动端测试更复杂\nD. 移动端不需要进行功能测试，只需要做兼容性测试",
     "B", "single_choice", "easy", "移动端测试概述"),

    # 移动端功能测试 (10题)
    ("移动端功能测试中，'手势操作'测试主要包括哪些内容？",
     "移动端功能测试中，'手势操作'测试主要包括哪些内容？\n\nA. 仅测试点击操作\nB. 包括点击、长按、滑动、捏合、拖拽、双击等多种手势\nC. 手势操作不需要专门测试，与Web端点击相同\nD. 只需要测试Android系统的手势，iOS不需要",
     "B", "single_choice", "easy", "移动端功能测试"),
    ("移动端应用的'权限测试'需要关注哪些方面？",
     "移动端应用的'权限测试'需要关注哪些方面？\n\nA. 只需要测试应用启动时申请的权限\nB. 需要测试权限申请时机、权限拒绝后的处理、权限动态变化、系统设置中修改权限后的行为等\nC. 权限测试是iOS独有的，Android不需要\nD. 权限测试只需要验证一次，不需要反复测试",
     "B", "single_choice", "medium", "移动端功能测试"),
    ("关于移动端'推送通知'测试，以下说法错误的是？",
     "关于移动端'推送通知'测试，以下说法错误的是？\n\nA. 需要测试通知的到达率、显示内容、点击跳转逻辑\nB. 需要测试通知在锁屏、通知栏、应用内等不同场景下的表现\nC. 推送通知测试只需要在WiFi环境下进行即可\nD. 需要测试通知的静音模式、免打扰模式下的行为",
     "C", "single_choice", "easy", "移动端功能测试"),
    ("移动端'安装/卸载/升级'测试需要验证哪些场景？",
     "移动端'安装/卸载/升级'测试需要验证哪些场景？（多选）\n\nA. 首次安装和覆盖安装\nB. 应用卸载后数据是否清除干净\nC. 低版本升级到新版本的兼容性\nD. 安装过程中来电中断的处理",
     "A,B,C,D", "multiple_choice", "medium", "移动端功能测试"),
    ("移动端'后台运行'测试主要关注什么？",
     "移动端'后台运行'测试主要关注什么？\n\nA. 应用在后台时是否继续占用大量CPU\nB. 应用在后台一段时间后再次打开是否需要重新登录\nC. 应用在后台时推送通知是否还能正常接收\nD. 以上所有选项都是后台运行测试需要关注的",
     "D", "single_choice", "medium", "移动端功能测试"),
    ("移动端测试中，'中断测试'主要测试什么场景？",
     "移动端测试中，'中断测试'主要测试什么场景？\n\nA. 应用运行过程中被来电、短信、通知、闹钟等打断后的表现\nB. 网络中断后的恢复能力\nC. 服务器中断后的容错处理\nD. 用户操作中断的响应速度",
     "A", "single_choice", "easy", "移动端功能测试"),
    ("以下哪个不是常见的移动端专项测试类型？",
     "以下哪个不是常见的移动端专项测试类型？\n\nA. 安装/卸载/升级测试\nB. 权限测试\nC. 数据库性能测试\nD. 推送通知测试",
     "C", "single_choice", "easy", "移动端功能测试"),
    ("移动端应用不需要进行权限测试，因为权限管理完全由操作系统负责。",
     "移动端应用不需要进行权限测试，因为权限管理完全由操作系统负责。\n\nA. 正确\nB. 错误",
     "B", "true_false", "easy", "移动端功能测试"),
    ("移动端测试中的'用户体验测试'包含哪些维度？",
     "移动端测试中的'用户体验测试'包含哪些维度？（多选）\n\nA. 界面美观度\nB. 交互流畅度\nC. 操作反馈及时性\nD. 错误提示友好度",
     "A,B,C,D", "multiple_choice", "easy", "移动端功能测试"),
    ("在进行移动端'横竖屏切换'测试时，应该关注什么？",
     "在进行移动端'横竖屏切换'测试时，应该关注什么？\n\nA. 界面布局是否正确适配，数据是否丢失，状态是否保持\nB. 只需要测试从竖屏切到横屏\nC. 横竖屏切换不需要测试，用户很少用\nD. 只需要检查界面是否旋转即可",
     "A", "single_choice", "medium", "移动端功能测试"),

    # 兼容性测试 (8题)
    ("移动端兼容性测试中，'屏幕适配'测试需要关注哪些内容？",
     "移动端兼容性测试中，'屏幕适配'测试需要关注哪些内容？\n\nA. 只需要在大屏手机上测试即可\nB. 需要在不同分辨率、不同屏幕比例、不同DPI的设备上测试UI显示\nC. 屏幕适配只需要测试竖屏，横屏不需要测试\nD. 屏幕适配是设计师的职责，测试不需要关注",
     "B", "single_choice", "medium", "兼容性测试"),
    ("iOS应用的兼容性测试相比Android的优势在于？",
     "iOS应用的兼容性测试相比Android的优势在于？\n\nA. iOS设备型号更多，测试覆盖面更广\nB. iOS系统版本和机型相对集中，碎片化程度较低\nC. iOS不需要兼容性测试，所有设备表现一致\nD. iOS应用只能在最新系统上运行",
     "B", "single_choice", "easy", "兼容性测试"),
    ("移动端兼容性测试时，以下哪款工具可以用于远程真机测试？",
     "移动端兼容性测试时，以下哪款工具可以用于远程真机测试？\n\nA. Postman\nB. JMeter\nC. BrowserStack 或 Sauce Labs\nD. Charles",
     "C", "single_choice", "easy", "兼容性测试"),
    ("在进行移动端兼容性测试时，以下哪项不属于必须测试的内容？",
     "在进行移动端兼容性测试时，以下哪项不属于必须测试的内容？\n\nA. 不同操作系统版本上的功能表现\nB. 不同品牌设备上的UI显示\nC. 应用代码的圈复杂度\nD. 不同网络环境下的表现",
     "C", "single_choice", "easy", "兼容性测试"),
    ("Android碎片化问题比iOS更严重，因为Android设备和系统版本更多样化。",
     "Android碎片化问题比iOS更严重，因为Android设备和系统版本更多样化。\n\nA. 正确\nB. 错误",
     "A", "true_false", "easy", "兼容性测试"),
    ("在移动端UI测试中，为什么需要测试'深色模式'？",
     "在移动端UI测试中，为什么需要测试'深色模式'？\n\nA. 深色模式只是视觉效果，不需要测试\nB. 需要确保文字对比度、图标显示、图片适配等在深色模式下正常\nC. 只有iOS支持深色模式，Android不需要测试\nD. 深色模式是系统功能，应用不需要适配",
     "B", "single_choice", "medium", "兼容性测试"),
    ("以下哪个不是移动端兼容性测试的常用设备选择策略？",
     "以下哪个不是移动端兼容性测试的常用设备选择策略？\n\nA. 选择市场占有率最高的Top 10设备\nB. 选择不同品牌、不同分辨率、不同系统版本的设备组合\nC. 只在开发者自己的手机上测试\nD. 使用云测平台的设备矩阵进行覆盖",
     "C", "single_choice", "easy", "兼容性测试"),
    ("移动端'系统版本兼容性'测试应该覆盖哪些版本？",
     "移动端'系统版本兼容性'测试应该覆盖哪些版本？\n\nA. 只需要测试最新版本\nB. 需要覆盖主流版本，通常包括最新2-3个版本和市场占有率较高的旧版本\nC. 只需要测试最低支持版本\nD. 需要测试从系统发布以来的所有版本",
     "B", "single_choice", "medium", "兼容性测试"),

    # 弱网测试 (7题)
    ("弱网测试中常用的网络模拟工具包括哪些？",
     "弱网测试中常用的网络模拟工具包括哪些？（多选）\n\nA. Charles Proxy\nB. Fiddler\nC. Chrome DevTools Network Throttling\nD. Xcode Network Link Conditioner",
     "A,B,C,D", "multiple_choice", "medium", "弱网测试"),
    ("移动端应用在网络从WiFi切换到4G时，应该具备什么能力？",
     "移动端应用在网络从WiFi切换到4G时，应该具备什么能力？\n\nA. 直接闪退，提醒用户切换网络\nB. 自动检测网络变化并恢复数据传输，不需要用户重新操作\nC. 提示用户重启应用\nD. 没有任何提示，直接断开所有连接",
     "B", "single_choice", "easy", "弱网测试"),
    ("在2G网络环境下测试移动端应用，主要关注什么？",
     "在2G网络环境下测试移动端应用，主要关注什么？\n\nA. 应用的启动速度是否够快\nB. 超时处理是否合理，是否有友好的加载提示\nC. 高清图片的显示效果\nD. 视频播放的流畅度",
     "B", "single_choice", "medium", "弱网测试"),
    ("移动端'离线模式'测试需要验证哪些功能？",
     "移动端'离线模式'测试需要验证哪些功能？\n\nA. 应用在无网络时是否直接崩溃\nB. 应用在无网络时是否能展示缓存数据，操作是否有合适的提示\nC. 离线模式不需要测试，现代应用都必须联网\nD. 只需要测试WiFi断开的情况，不需要测试蜂窝网络",
     "B", "single_choice", "medium", "弱网测试"),
    ("弱网测试中，'超时'和'重试'机制的设计原则是什么？",
     "弱网测试中，'超时'和'重试'机制的设计原则是什么？\n\nA. 超时时间越长越好，避免频繁重试\nB. 设置合理的超时时间（如10-30秒），并实现指数退避重试策略\nC. 不需要设置超时，等待网络恢复即可\nD. 每次失败后立即重试，不需要间隔",
     "B", "single_choice", "medium", "弱网测试"),
    ("Charles Proxy只能用于Web调试，不能用于移动端弱网模拟。",
     "Charles Proxy只能用于Web调试，不能用于移动端弱网模拟。\n\nA. 正确\nB. 错误",
     "B", "true_false", "easy", "弱网测试"),
    ("移动端应用在网络恢复后，应该具备什么行为？",
     "移动端应用在网络恢复后，应该具备什么行为？\n\nA. 等待用户手动刷新页面\nB. 自动检测网络恢复并重新加载失败的数据\nC. 显示网络已恢复的提示，不做任何操作\nD. 强制用户重新登录",
     "B", "single_choice", "easy", "弱网测试"),

    # Appium自动化 (9题)
    ("Appium支持哪些编程语言编写测试脚本？",
     "Appium支持哪些编程语言编写测试脚本？（多选）\n\nA. Java\nB. Python\nC. JavaScript\nD. Ruby",
     "A,B,C,D", "multiple_choice", "easy", "Appium自动化"),
    ("Appium的底层使用的是哪种协议与设备进行通信？",
     "Appium的底层使用的是哪种协议与设备进行通信？\n\nA. HTTP协议\nB. WebDriver协议\nC. WebSocket协议\nD. gRPC协议",
     "B", "single_choice", "medium", "Appium自动化"),
    ("在Appium中，'Accessibility ID'是什么定位方式？",
     "在Appium中，'Accessibility ID'是什么定位方式？\n\nA. 通过元素的CSS类名定位\nB. 通过元素的内容描述（content-desc）或accessibilityLabel定位\nC. 通过元素的坐标位置定位\nD. 通过元素的文本内容定位",
     "B", "single_choice", "medium", "Appium自动化"),
    ("Appium测试中，'Desired Capabilities'的作用是什么？",
     "Appium测试中，'Desired Capabilities'的作用是什么？\n\nA. 用于断言测试结果\nB. 用于配置测试会话的环境参数，如平台名称、设备名称、应用路径等\nC. 用于生成测试报告\nD. 用于管理测试数据",
     "B", "single_choice", "easy", "Appium自动化"),
    ("以下哪种手势操作在Appium中需要使用TouchAction类实现？",
     "以下哪种手势操作在Appium中需要使用TouchAction类实现？\n\nA. 点击（Click）\nB. 滑动（Swipe）\nC. 输入文本（Send Keys）\nD. 获取元素文本（Get Text）",
     "B", "single_choice", "medium", "Appium自动化"),
    ("Appium可以同时支持Android和iOS平台的自动化测试。",
     "Appium可以同时支持Android和iOS平台的自动化测试。\n\nA. 正确\nB. 错误",
     "A", "true_false", "easy", "Appium自动化"),
    ("在Appium测试中，遇到'元素定位不到'的问题，以下哪些方法可以尝试解决？",
     "在Appium测试中，遇到'元素定位不到'的问题，以下哪些方法可以尝试解决？（多选）\n\nA. 添加显式等待（Explicit Wait）\nB. 切换不同的定位策略（XPath、ID、Accessibility ID等）\nC. 检查元素是否在WebView中，需要切换上下文\nD. 直接增加固定的sleep等待",
     "A,B,C", "multiple_choice", "medium", "Appium自动化"),
    ("Appium测试Android应用时，以下哪个定位方式通常最稳定？",
     "Appium测试Android应用时，以下哪个定位方式通常最稳定？\n\nA. XPath定位\nB. Accessibility ID定位\nC. 坐标定位\nD. 图片匹配定位",
     "B", "single_choice", "medium", "Appium自动化"),
    ("以下关于Appium和UI Automator的描述，正确的是？",
     "以下关于Appium和UI Automator的描述，正确的是？\n\nA. Appium是iOS专用框架，UI Automator是Android专用框架\nB. Appium底层在Android上可以使用UI Automator2驱动\nC. UI Automator可以测试Web应用\nD. Appium和UI Automator没有任何关系",
     "B", "single_choice", "medium", "Appium自动化"),

    # 性能测试 (8题)
    ("移动端性能测试中，'冷启动'和'热启动'的区别是什么？",
     "移动端性能测试中，'冷启动'和'热启动'的区别是什么？\n\nA. 冷启动是从桌面点击图标启动，热启动是从后台恢复到前台\nB. 冷启动和热启动没有任何区别\nC. 冷启动是第一次安装后的启动，热启动是更新后的启动\nD. 冷启动需要联网，热启动不需要联网",
     "A", "single_choice", "easy", "性能测试"),
    ("Android Monkey测试工具的主要作用是什么？",
     "Android Monkey测试工具的主要作用是什么？\n\nA. 自动化执行功能测试用例\nB. 向系统发送伪随机的用户事件流（点击、触摸、手势等），用于稳定性测试\nC. 测试应用的网络性能\nD. 生成测试报告",
     "B", "single_choice", "easy", "性能测试"),
    ("以下哪些是移动端性能测试需要关注的指标？",
     "以下哪些是移动端性能测试需要关注的指标？（多选）\n\nA. 启动时间\nB. 内存占用\nC. CPU使用率\nD. 电量消耗",
     "A,B,C,D", "multiple_choice", "easy", "性能测试"),
    ("使用Monkey进行稳定性测试时，以下哪个参数可以设置事件发送的时间间隔？",
     "使用Monkey进行稳定性测试时，以下哪个参数可以设置事件发送的时间间隔？\n\nA. --throttle\nB. --count\nC. --seed\nD. --ignore-crashes",
     "A", "single_choice", "medium", "性能测试"),
    ("移动端'内存泄漏'测试通常使用什么工具进行？",
     "移动端'内存泄漏'测试通常使用什么工具进行？\n\nA. Postman\nB. Android Profiler（Android）和 Instruments（iOS）\nC. Charles\nD. Selenium",
     "B", "single_choice", "medium", "性能测试"),
    ("Monkey测试中的'--ignore-crashes'参数的作用是什么？",
     "Monkey测试中的'--ignore-crashes'参数的作用是什么？\n\nA. 忽略所有异常，继续发送事件\nB. 遇到应用崩溃时不停止测试，继续发送事件\nC. 忽略ANR错误\nD. 不生成崩溃日志",
     "B", "single_choice", "medium", "性能测试"),
    ("以下哪个命令可以启动Android Monkey测试，发送1000个随机事件？",
     "以下哪个命令可以启动Android Monkey测试，发送1000个随机事件？\n\nA. adb shell monkey -p com.example.app 1000\nB. adb shell monkey com.example.app 1000\nC. monkey -p com.example.app 1000\nD. adb monkey -p com.example.app 1000",
     "A", "single_choice", "easy", "性能测试"),
    ("移动端'电量测试'主要关注什么？",
     "移动端'电量测试'主要关注什么？\n\nA. 应用在不同使用场景下的电量消耗情况\nB. 充电速度\nC. 电池容量大小\nD. 充电器功率",
     "A", "single_choice", "medium", "性能测试"),
]


# ========== LP13: 性能测试 - JMeter与Locust (50题) ==========
LP13_EXERCISES = [
    # 性能测试核心指标 (8题)
    ("性能测试中，'TPS'指的是什么？",
     "性能测试中，'TPS'指的是什么？\n\nA. 每秒传输的数据量（Transfer Per Second）\nB. 每秒事务数（Transactions Per Second）\nC. 总处理时间（Total Processing Time）\nD. 线程池大小（Thread Pool Size）",
     "B", "single_choice", "easy", "性能测试核心指标"),
    ("以下哪个指标表示系统处理请求的平均时间？",
     "以下哪个指标表示系统处理请求的平均时间？\n\nA. TPS\nB. RT（Response Time）\nC. QPS\nD. 并发数",
     "B", "single_choice", "easy", "性能测试核心指标"),
    ("性能测试中，'并发用户数'和'TPS'之间的关系是？",
     "性能测试中，'并发用户数'和'TPS'之间的关系是？\n\nA. 并发用户数越多，TPS一定越高\nB. TPS达到峰值后，再增加并发用户数，TPS可能下降\nC. 并发用户数和TPS之间没有关系\nD. TPS总是等于并发用户数",
     "B", "single_choice", "medium", "性能测试核心指标"),
    ("以下哪些是性能测试的核心指标？",
     "以下哪些是性能测试的核心指标？（多选）\n\nA. TPS/QPS\nB. 响应时间（RT）\nC. 并发用户数\nD. 错误率",
     "A,B,C,D", "multiple_choice", "easy", "性能测试核心指标"),
    ("性能测试中的'90%响应时间'是什么意思？",
     "性能测试中的'90%响应时间'是什么意思？\n\nA. 90%的请求都在该时间内完成\nB. 平均响应时间的90%\nC. 最快响应时间的90%\nD. 90%的用户同时在线的时间",
     "A", "single_choice", "medium", "性能测试核心指标"),
    ("QPS和TPS的主要区别是什么？",
     "QPS和TPS的主要区别是什么？\n\nA. QPS是每秒查询数，TPS是每秒事务数；一个事务可能包含多个查询\nB. QPS和TPS完全等同，没有区别\nC. QPS用于数据库，TPS用于Web应用\nD. QPS总是大于TPS",
     "A", "single_choice", "medium", "性能测试核心指标"),
    ("性能测试中，'吞吐量'通常用什么指标表示？",
     "性能测试中，'吞吐量'通常用什么指标表示？\n\nA. 仅使用TPS\nB. 可以使用TPS、QPS或每秒处理的数据量等多种指标\nC. 仅使用并发数\nD. 仅使用响应时间",
     "B", "single_choice", "easy", "性能测试核心指标"),
    ("在进行性能测试时，'基线测试'的目的是什么？",
     "在进行性能测试时，'基线测试'的目的是什么？\n\nA. 找出系统的最大承载能力\nB. 建立系统在正常负载下的性能基准，用于后续对比\nC. 测试系统在极端条件下的表现\nD. 验证系统的功能正确性",
     "B", "single_choice", "medium", "性能测试核心指标"),

    # JMeter基础 (8题)
    ("JMeter是一款基于什么语言开发的性能测试工具？",
     "JMeter是一款基于什么语言开发的性能测试工具？\n\nA. Python\nB. Java\nC. C++\nD. Go",
     "B", "single_choice", "easy", "JMeter基础"),
    ("JMeter中，'线程组'（Thread Group）的作用是什么？",
     "JMeter中，'线程组'（Thread Group）的作用是什么？\n\nA. 用于生成测试报告\nB. 定义虚拟用户的数量、启动方式和执行次数\nC. 用于配置数据库连接\nD. 用于管理测试计划中的元件",
     "B", "single_choice", "easy", "JMeter基础"),
    ("以下哪个不是JMeter的核心组件？",
     "以下哪个不是JMeter的核心组件？\n\nA. 取样器（Sampler）\nB. 监听器（Listener）\nC. 断言（Assertion）\nD. 编译器（Compiler）",
     "D", "single_choice", "easy", "JMeter基础"),
    ("JMeter中的'HTTP请求'取样器主要用于测试什么？",
     "JMeter中的'HTTP请求'取样器主要用于测试什么？\n\nA. 数据库性能\nB. Web接口性能\nC. 文件传输性能\nD. 邮件服务器性能",
     "B", "single_choice", "easy", "JMeter基础"),
    ("JMeter的'聚合报告'（Aggregate Report）中包含哪些统计信息？",
     "JMeter的'聚合报告'（Aggregate Report）中包含哪些统计信息？（多选）\n\nA. 平均响应时间\nB. 吞吐量\nC. 错误率\nD. 最小/最大响应时间",
     "A,B,C,D", "multiple_choice", "easy", "JMeter基础"),
    ("JMeter中，'断言'（Assertion）的作用是什么？",
     "JMeter中，'断言'（Assertion）的作用是什么？\n\nA. 用于验证响应结果是否符合预期\nB. 用于生成随机数据\nC. 用于控制线程的执行顺序\nD. 用于配置代理服务器",
     "A", "single_choice", "easy", "JMeter基础"),
    ("JMeter支持通过命令行模式运行测试计划，这种模式适合什么场景？",
     "JMeter支持通过命令行模式运行测试计划，这种模式适合什么场景？\n\nA. 适合调试脚本\nB. 适合在CI/CD流水线中自动化执行性能测试\nC. 适合查看实时结果\nD. 适合手动配置测试计划",
     "B", "single_choice", "medium", "JMeter基础"),
    ("在JMeter中，'前置处理器'（Pre Processor）和'后置处理器'（Post Processor）的区别是什么？",
     "在JMeter中，'前置处理器'（Pre Processor）和'后置处理器'（Post Processor）的区别是什么？\n\nA. 前置处理器在请求发送前执行，后置处理器在请求响应后执行\nB. 前置处理器用于断言，后置处理器用于提取数据\nC. 两者功能完全相同，只是名称不同\nD. 前置处理器只用于HTTP请求，后置处理器只用于数据库请求",
     "A", "single_choice", "medium", "JMeter基础"),

    # JMeter脚本开发 (7题)
    ("JMeter中实现'参数化'测试的常用方法有哪些？",
     "JMeter中实现'参数化'测试的常用方法有哪些？（多选）\n\nA. CSV Data Set Config\nB. 用户定义的变量\nC. 函数助手（如__Random、__UUID等）\nD. JSON Extractor",
     "A,B,C", "multiple_choice", "medium", "JMeter脚本开发"),
    ("JMeter中的'关联'（Correlation）通常使用什么元件实现？",
     "JMeter中的'关联'（Correlation）通常使用什么元件实现？\n\nA. 断言\nB. 正则表达式提取器或JSON提取器\nC. 定时器\nD. 配置元件",
     "B", "single_choice", "medium", "JMeter脚本开发"),
    ("在JMeter中，如何模拟真实的用户思考时间？",
     "在JMeter中，如何模拟真实的用户思考时间？\n\nA. 使用固定定时器设置固定的等待时间\nB. 使用高斯随机定时器设置随机的思考时间\nC. 不需要模拟思考时间\nD. 使用断言来实现",
     "B", "single_choice", "easy", "JMeter脚本开发"),
    ("JMeter的'HTTP Cookie管理器'的作用是什么？",
     "JMeter的'HTTP Cookie管理器'的作用是什么？\n\nA. 用于清理浏览器的Cookie\nB. 用于自动处理请求和响应中的Cookie，维持会话状态\nC. 用于修改HTTP请求头\nD. 用于加密Cookie数据",
     "B", "single_choice", "medium", "JMeter脚本开发"),
    ("JMeter中，'吞吐量控制器'（Throughput Controller）的作用是什么？",
     "JMeter中，'吞吐量控制器'（Throughput Controller）的作用是什么？\n\nA. 限制每秒发送的请求数\nB. 控制其子元件的执行次数或执行比例\nC. 限制并发用户数\nD. 控制测试计划的执行时间",
     "B", "single_choice", "medium", "JMeter脚本开发"),
    ("在JMeter中，如果要测试数据库性能，应该使用哪种取样器？",
     "在JMeter中，如果要测试数据库性能，应该使用哪种取样器？\n\nA. HTTP请求取样器\nB. JDBC请求取样器\nC. FTP请求取样器\nD. JMS请求取样器",
     "B", "single_choice", "easy", "JMeter脚本开发"),
    ("JMeter脚本中的'Debug Sampler'有什么作用？",
     "JMeter脚本中的'Debug Sampler'有什么作用？\n\nA. 用于生成测试负载\nB. 用于查看变量值，方便调试脚本\nC. 用于发送HTTP请求\nD. 用于配置数据库连接",
     "B", "single_choice", "easy", "JMeter脚本开发"),

    # JMeter分布式压测 (7题)
    ("JMeter分布式压测时，'控制机'和'执行机'分别是什么角色？",
     "JMeter分布式压测时，'控制机'和'执行机'分别是什么角色？\n\nA. 控制机负责分发脚本和收集结果，执行机负责实际发送请求\nB. 控制机负责发送请求，执行机负责生成报告\nC. 两者角色完全相同，没有区别\nD. 控制机只用于Windows，执行机只用于Linux",
     "A", "single_choice", "medium", "JMeter分布式"),
    ("单台JMeter机器通常最多能模拟多少并发用户？",
     "单台JMeter机器通常最多能模拟多少并发用户？\n\nA. 10-50\nB. 500-1000\nC. 10000以上\nD. 没有上限，取决于内存大小",
     "B", "single_choice", "easy", "JMeter分布式"),
    ("JMeter分布式测试中，执行机（Slave）需要启动什么服务？",
     "JMeter分布式测试中，执行机（Slave）需要启动什么服务？\n\nA. jmeter-server\nB. jmeter-master\nC. jmeter-proxy\nD. jmeter-agent",
     "A", "single_choice", "medium", "JMeter分布式"),
    ("JMeter分布式压测时，控制机和执行机之间的通信使用什么端口？",
     "JMeter分布式压测时，控制机和执行机之间的通信使用什么端口？\n\nA. 80端口\nB. 1099端口（RMI默认端口）\nC. 8080端口\nD. 443端口",
     "B", "single_choice", "medium", "JMeter分布式"),
    ("以下关于JMeter分布式压测的说法，正确的是？",
     "以下关于JMeter分布式压测的说法，正确的是？\n\nA. 分布式压测时，每台执行机都运行完整的测试计划\nB. 控制机不参与发送请求，只负责协调和收集结果\nC. 分布式压测时，结果文件分散保存在各执行机上\nD. 分布式压测的配置与单机测试完全相同，不需要额外配置",
     "B", "single_choice", "medium", "JMeter分布式"),
    ("在进行大规模分布式压测时，以下哪项不是需要注意的事项？",
     "在进行大规模分布式压测时，以下哪项不是需要注意的事项？\n\nA. 确保所有执行机的JMeter版本一致\nB. 确保控制机和执行机之间网络互通\nC. 确保测试数据文件在所有执行机上路径一致\nD. 确保所有执行机使用不同的操作系统",
     "D", "single_choice", "easy", "JMeter分布式"),
    ("JMeter分布式测试中，如果某台执行机出现故障，测试会如何处理？",
     "JMeter分布式测试中，如果某台执行机出现故障，测试会如何处理？\n\nA. 整个测试立即停止\nB. 其他正常的执行机继续执行，但结果可能不完整\nC. 自动重新启动故障的执行机\nD. 控制机会接管故障执行机的工作",
     "B", "single_choice", "medium", "JMeter分布式"),

    # Locust开发 (6题)
    ("Locust是一款基于什么编程语言的性能测试工具？",
     "Locust是一款基于什么编程语言的性能测试工具？\n\nA. Java\nB. Python\nC. Go\nD. JavaScript",
     "B", "single_choice", "easy", "Locust开发"),
    ("Locust的核心并发模型是什么？",
     "Locust的核心并发模型是什么？\n\nA. 多线程\nB. 多进程\nC. 协程（基于gevent）\nD. 异步IO（基于asyncio）",
     "C", "single_choice", "medium", "Locust开发"),
    ("在Locust中，定义用户行为的类需要继承自哪个基类？",
     "在Locust中，定义用户行为的类需要继承自哪个基类？\n\nA. User\nB. HttpUser\nC. TaskSet\nD. Locust",
     "B", "single_choice", "easy", "Locust开发"),
    ("Locust中的'@task'装饰器的作用是什么？",
     "Locust中的'@task'装饰器的作用是什么？\n\nA. 定义任务之间的依赖关系\nB. 标记一个方法为Locust任务，并可以设置权重\nC. 配置HTTP请求头\nD. 设置任务执行的超时时间",
     "B", "single_choice", "easy", "Locust开发"),
    ("Locust的Web界面默认运行在哪个端口？",
     "Locust的Web界面默认运行在哪个端口？\n\nA. 5000\nB. 8089\nC. 3000\nD. 8000",
     "B", "single_choice", "easy", "Locust开发"),
    ("Locust和JMeter相比，主要优势是什么？",
     "Locust和JMeter相比，主要优势是什么？\n\nA. Locust的GUI界面更友好\nB. Locust使用代码定义测试场景，更灵活，且单机可模拟更多并发\nC. Locust支持的协议更多\nD. Locust的历史更悠久，社区更大",
     "B", "single_choice", "medium", "Locust开发"),

    # 性能监控 (7题)
    ("以下哪个不是常用的性能监控指标？",
     "以下哪个不是常用的性能监控指标？\n\nA. CPU使用率\nB. 内存使用率\nC. 磁盘I/O\nD. 代码行数",
     "D", "single_choice", "easy", "性能监控"),
    ("Prometheus是一个什么类型的工具？",
     "Prometheus是一个什么类型的工具？\n\nA. 性能测试工具\nB. 时序数据库和监控系统\nC. 日志收集工具\nD. 配置管理工具",
     "B", "single_choice", "easy", "性能监控"),
    ("Grafana在性能监控体系中主要承担什么角色？",
     "Grafana在性能监控体系中主要承担什么角色？\n\nA. 数据采集\nB. 数据存储\nC. 数据可视化和仪表盘展示\nD. 告警通知",
     "C", "single_choice", "easy", "性能监控"),
    ("以下哪些是服务器性能监控需要关注的资源？",
     "以下哪些是服务器性能监控需要关注的资源？（多选）\n\nA. CPU\nB. 内存\nC. 磁盘\nD. 网络带宽",
     "A,B,C,D", "multiple_choice", "easy", "性能监控"),
    ("Nginx访问日志可以用于分析哪些性能指标？",
     "Nginx访问日志可以用于分析哪些性能指标？\n\nA. 请求的响应时间\nB. 请求的URL分布\nC. HTTP状态码分布\nD. 以上所有",
     "D", "single_choice", "easy", "性能监控"),
    ("以下哪个工具可以用于数据库性能监控？",
     "以下哪个工具可以用于数据库性能监控？\n\nA. Prometheus + mysqld_exporter\nB. JMeter\nC. Postman\nD. Charles",
     "A", "single_choice", "medium", "性能监控"),
    ("在性能测试中，'全链路监控'的意义是什么？",
     "在性能测试中，'全链路监控'的意义是什么？\n\nA. 只监控应用服务器的性能\nB. 从前端到网关、应用服务、数据库、缓存等全链条追踪请求，定位瓶颈\nC. 只监控数据库的性能\nD. 只监控网络带宽",
     "B", "single_choice", "medium", "性能监控"),

    # 性能调优 (6题)
    ("性能瓶颈分析的第一步通常是什么？",
     "性能瓶颈分析的第一步通常是什么？\n\nA. 直接修改代码优化\nB. 收集监控数据，定位资源使用率最高的组件\nC. 增加服务器数量\nD. 重启服务器",
     "B", "single_choice", "easy", "性能调优"),
    ("当数据库成为性能瓶颈时，以下哪些是常见的优化手段？",
     "当数据库成为性能瓶颈时，以下哪些是常见的优化手段？（多选）\n\nA. 添加合适的索引\nB. 优化慢查询SQL\nC. 读写分离\nD. 分库分表",
     "A,B,C,D", "multiple_choice", "medium", "性能调优"),
    ("应用服务器CPU使用率过高，可能的原因有哪些？",
     "应用服务器CPU使用率过高，可能的原因有哪些？（多选）\n\nA. 代码中存在死循环\nB. 频繁的垃圾回收（GC）\nC. 复杂的计算逻辑\nD. 数据库连接池过小",
     "A,B,C", "multiple_choice", "medium", "性能调优"),
    ("以下哪个不是常见的性能调优策略？",
     "以下哪个不是常见的性能调优策略？\n\nA. 缓存优化（Redis/Memcached）\nB. 异步处理（消息队列）\nC. 增加日志输出级别\nD. 数据库优化（索引/SQL优化）",
     "C", "single_choice", "easy", "性能调优"),
    ("在进行性能调优时，'压测-分析-优化-验证'的循环原则是指什么？",
     "在进行性能调优时，'压测-分析-优化-验证'的循环原则是指什么？\n\nA. 每次只做一个优化改动，然后重新压测验证效果\nB. 一次性做多个优化改动，然后验证\nC. 只做一次优化就不需要再测试了\nD. 先优化再压测，顺序不重要",
     "A", "single_choice", "medium", "性能调优"),
    ("内存泄漏的典型表现是什么？",
     "内存泄漏的典型表现是什么？\n\nA. 应用启动速度变慢\nB. 应用运行时间越长，内存占用持续增长，最终可能导致OOM\nC. CPU使用率持续升高\nD. 网络延迟增加",
     "B", "single_choice", "easy", "性能调优"),
]


# ========== LP14: 安全测试基础 (50题) ==========
LP14_EXERCISES = [
    # Web安全概述 (8题)
    ("OWASP Top 10 2021中，排名第一的安全风险是什么？",
     "OWASP Top 10 2021中，排名第一的安全风险是什么？\n\nA. 注入（Injection）\nB. 失效的访问控制（Broken Access Control）\nC. 敏感数据暴露（Cryptographic Failures）\nD. 跨站脚本（XSS）",
     "B", "single_choice", "easy", "Web安全概述"),
    ("以下哪些属于OWASP Top 10 2021列出的安全风险？",
     "以下哪些属于OWASP Top 10 2021列出的安全风险？（多选）\n\nA. 失效的访问控制\nB. 注入\nC. 不安全设计\nD. 服务器端请求伪造（SSRF）",
     "A,B,C,D", "multiple_choice", "easy", "Web安全概述"),
    ("安全测试的主要目标是什么？",
     "安全测试的主要目标是什么？\n\nA. 验证系统功能是否正确\nB. 发现系统的安全漏洞和弱点，确保数据和系统安全\nC. 测试系统的性能表现\nD. 验证系统的兼容性",
     "B", "single_choice", "easy", "Web安全概述"),
    ("以下哪个不是常见的Web应用安全漏洞类型？",
     "以下哪个不是常见的Web应用安全漏洞类型？\n\nA. SQL注入\nB. XSS\nC. 缓冲区溢出\nD. 性能瓶颈",
     "D", "single_choice", "easy", "Web安全概述"),
    ("安全测试应该在软件开发的哪个阶段开始？",
     "安全测试应该在软件开发的哪个阶段开始？\n\nA. 只在上线前进行\nB. 从需求分析阶段就开始，贯穿整个软件生命周期\nC. 只在开发完成后进行\nD. 只在发现安全事件后进行",
     "B", "single_choice", "medium", "Web安全概述"),
    ("OWASP是一个什么组织？",
     "OWASP是一个什么组织？\n\nA. 一个商业安全软件公司\nB. 一个开放的Web应用安全项目组织，致力于提高软件安全性\nC. 一个政府网络安全机构\nD. 一个编程语言开发组织",
     "B", "single_choice", "easy", "Web安全概述"),
    ("以下哪些是安全测试的常见类型？",
     "以下哪些是安全测试的常见类型？（多选）\n\nA. 漏洞扫描\nB. 渗透测试\nC. 代码审计\nD. 配置审查",
     "A,B,C,D", "multiple_choice", "easy", "Web安全概述"),
    ("安全测试和功能测试可以完全互相替代。",
     "安全测试和功能测试可以完全互相替代。\n\nA. 正确\nB. 错误",
     "B", "true_false", "easy", "Web安全概述"),

    # SQL注入 (8题)
    ("SQL注入攻击的原理是什么？",
     "SQL注入攻击的原理是什么？\n\nA. 通过恶意SQL语句，利用应用程序未对用户输入进行充分验证的漏洞\nB. 通过暴力破解数据库密码\nC. 通过DDoS攻击数据库服务器\nD. 通过社会工程学获取数据库凭证",
     "A", "single_choice", "easy", "SQL注入"),
    ("以下哪个代码片段存在SQL注入漏洞？",
     "以下哪个代码片段存在SQL注入漏洞？\n\nA. cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))\nB. query = f\"SELECT * FROM users WHERE id = '{user_id}'\"; cursor.execute(query)\nC. cursor.execute('SELECT * FROM users WHERE id = ?', [user_id])\nD. 使用ORM框架的查询API",
     "B", "single_choice", "medium", "SQL注入"),
    ("防止SQL注入的最佳实践是什么？",
     "防止SQL注入的最佳实践是什么？\n\nA. 在前端验证用户输入\nB. 使用参数化查询（Prepared Statements）或ORM框架\nC. 在后端过滤所有特殊字符\nD. 关闭数据库的错误信息显示",
     "B", "single_choice", "medium", "SQL注入"),
    ("以下哪些是SQL注入的常见类型？",
     "以下哪些是SQL注入的常见类型？（多选）\n\nA. 基于错误的SQL注入\nB. 基于布尔的盲注\nC. 基于时间的盲注\nD. 联合查询注入",
     "A,B,C,D", "multiple_choice", "medium", "SQL注入"),
    ("SQLMap是一款什么工具？",
     "SQLMap是一款什么工具？\n\nA. 数据库管理工具\nB. 自动化SQL注入检测和利用工具\nC. SQL性能优化工具\nD. 数据库备份工具",
     "B", "single_choice", "easy", "SQL注入"),
    ("以下哪种方法可以有效防御SQL注入？",
     "以下哪种方法可以有效防御SQL注入？\n\nA. 对用户输入进行严格验证和过滤\nB. 使用存储过程并参数化调用\nC. 最小权限原则，限制数据库账户权限\nD. 以上所有方法",
     "D", "single_choice", "medium", "SQL注入"),
    ("在SQL注入测试中，'1=1'常用于什么目的？",
     "在SQL注入测试中，'1=1'常用于什么目的？\n\nA. 测试数据库连接是否正常\nB. 构造永真条件，绕过认证或改变查询逻辑\nC. 测试数据库的版本信息\nD. 测试表名是否正确",
     "B", "single_choice", "medium", "SQL注入"),
    ("参数化查询（Prepared Statements）为什么能防止SQL注入？",
     "参数化查询（Prepared Statements）为什么能防止SQL注入？\n\nA. 因为参数化查询会自动加密用户输入\nB. 因为参数化查询将SQL语句和数据分离，数据库不会将参数当作SQL代码执行\nC. 因为参数化查询会拒绝所有特殊字符\nD. 因为参数化查询使用了更强的密码",
     "B", "single_choice", "medium", "SQL注入"),

    # XSS攻击 (7题)
    ("XSS（跨站脚本攻击）的主要危害是什么？",
     "XSS（跨站脚本攻击）的主要危害是什么？\n\nA. 导致数据库损坏\nB. 在用户浏览器中执行恶意脚本，窃取用户Cookie或会话信息\nC. 导致服务器CPU过载\nD. 删除服务器上的文件",
     "B", "single_choice", "easy", "XSS攻击"),
    ("以下哪种属于存储型XSS（Stored XSS）？",
     "以下哪种属于存储型XSS（Stored XSS）？\n\nA. 恶意脚本通过URL参数传递，不存储在服务器上\nB. 恶意脚本被存储在服务器数据库中，当其他用户浏览时触发\nC. 恶意脚本只影响攻击者自己的浏览器\nD. 恶意脚本通过邮件附件传播",
     "B", "single_choice", "medium", "XSS攻击"),
    ("以下哪些是防御XSS攻击的有效方法？",
     "以下哪些是防御XSS攻击的有效方法？（多选）\n\nA. 对用户输入进行HTML实体编码\nB. 使用内容安全策略（CSP）\nC. 对输出到页面的数据进行过滤和转义\nD. 设置HttpOnly Cookie属性",
     "A,B,C,D", "multiple_choice", "medium", "XSS攻击"),
    ("反射型XSS和存储型XSS的主要区别是什么？",
     "反射型XSS和存储型XSS的主要区别是什么？\n\nA. 反射型XSS危害更大\nB. 反射型XSS的恶意脚本不存储在服务器上，需要通过URL诱导用户点击；存储型XSS的脚本存储在服务器上\nC. 存储型XSS只能攻击管理员\nD. 两者没有本质区别",
     "B", "single_choice", "medium", "XSS攻击"),
    ("DOM型XSS与其他XSS类型的主要区别是什么？",
     "DOM型XSS与其他XSS类型的主要区别是什么？\n\nA. DOM型XSS只影响静态网页\nB. DOM型XSS的攻击发生在客户端JavaScript处理数据时，不经过服务器端处理\nC. DOM型XSS的危害最小\nD. DOM型XSS只能攻击IE浏览器",
     "B", "single_choice", "medium", "XSS攻击"),
    ("以下哪个HTTP响应头可以有效缓解XSS攻击？",
     "以下哪个HTTP响应头可以有效缓解XSS攻击？\n\nA. X-Frame-Options\nB. Content-Security-Policy\nC. Strict-Transport-Security\nD. X-Content-Type-Options",
     "B", "single_choice", "medium", "XSS攻击"),
    ("对富文本编辑器的内容进行XSS过滤时，以下哪种策略更安全？",
     "对富文本编辑器的内容进行XSS过滤时，以下哪种策略更安全？\n\nA. 直接删除所有HTML标签\nB. 使用白名单策略，只允许特定的安全标签和属性\nC. 使用黑名单策略，只过滤已知的危险标签\nD. 不对富文本内容进行任何过滤",
     "B", "single_choice", "medium", "XSS攻击"),

    # CSRF/SSRF (7题)
    ("CSRF（跨站请求伪造）攻击的原理是什么？",
     "CSRF（跨站请求伪造）攻击的原理是什么？\n\nA. 在目标网站上执行恶意脚本\nB. 诱导已登录用户在不知情的情况下向目标网站发送恶意请求\nC. 直接破解用户的密码\nD. 通过DDoS攻击使网站瘫痪",
     "B", "single_choice", "easy", "CSRF/SSRF"),
    ("以下哪个是防御CSRF攻击的有效方法？",
     "以下哪个是防御CSRF攻击的有效方法？\n\nA. 验证HTTP Referer头\nB. 使用CSRF Token\nC. 对敏感操作添加验证码或二次确认\nD. 以上所有方法",
     "D", "single_choice", "medium", "CSRF/SSRF"),
    ("SSRF（服务器端请求伪造）与CSRF的主要区别是什么？",
     "SSRF（服务器端请求伪造）与CSRF的主要区别是什么？\n\nA. SSRF是服务器发起请求，CSRF是客户端发起请求\nB. SSRF和CSRF完全相同\nC. SSRF只影响内网，CSRF只影响外网\nD. SSRF不需要用户交互，CSRF需要用户点击链接",
     "A", "single_choice", "medium", "CSRF/SSRF"),
    ("SSRF攻击通常利用什么功能点？",
     "SSRF攻击通常利用什么功能点？\n\nA. 用户登录功能\nB. 服务器端发起HTTP请求的功能（如图片下载、URL访问等）\nC. 用户注册功能\nD. 密码找回功能",
     "B", "single_choice", "medium", "CSRF/SSRF"),
    ("以下哪些措施可以防御SSRF攻击？",
     "以下哪些措施可以防御SSRF攻击？（多选）\n\nA. 限制服务器可以访问的URL白名单\nB. 禁用不必要的协议（如file://、gopher://等）\nC. 统一错误处理，避免信息泄露\nD. 对内网地址进行过滤",
     "A,B,C,D", "multiple_choice", "medium", "CSRF/SSRF"),
    ("SameSite Cookie属性的作用是什么？",
     "SameSite Cookie属性的作用是什么？\n\nA. 限制Cookie在跨站请求中的发送行为，帮助防御CSRF\nB. 加密Cookie内容\nC. 设置Cookie的过期时间\nD. 限制Cookie的大小",
     "A", "single_choice", "medium", "CSRF/SSRF"),
    ("CSRF攻击可以窃取用户的Cookie信息。",
     "CSRF攻击可以窃取用户的Cookie信息。\n\nA. 正确\nB. 错误",
     "B", "true_false", "medium", "CSRF/SSRF"),

    # 文件上传漏洞 (6题)
    ("文件上传漏洞的主要危害是什么？",
     "文件上传漏洞的主要危害是什么？\n\nA. 只能上传病毒文件\nB. 攻击者可能上传恶意脚本文件（如PHP、JSP）并在服务器上执行\nC. 只能占用服务器磁盘空间\nD. 只能窃取用户数据",
     "B", "single_choice", "easy", "文件上传漏洞"),
    ("以下哪些是防御文件上传漏洞的有效措施？",
     "以下哪些是防御文件上传漏洞的有效措施？（多选）\n\nA. 限制上传文件的类型（白名单）\nB. 重命名上传的文件，避免执行\nC. 将上传文件存储在非Web目录\nD. 对上传的文件进行病毒扫描",
     "A,B,C,D", "multiple_choice", "medium", "文件上传漏洞"),
    ("以下哪种文件类型上传最危险？",
     "以下哪种文件类型上传最危险？\n\nA. .jpg图片文件\nB. .txt文本文件\nC. .php可执行脚本文件\nD. .pdf文档文件",
     "C", "single_choice", "easy", "文件上传漏洞"),
    ("文件上传时，仅检查文件的扩展名是否足够安全？",
     "文件上传时，仅检查文件的扩展名是否足够安全？\n\nA. 足够，扩展名是可靠的判断依据\nB. 不够，攻击者可以通过修改扩展名或使用双扩展名绕过检测\nC. 足够，服务器会自动识别真实文件类型\nD. 不够，但加上文件大小检查就足够了",
     "B", "single_choice", "medium", "文件上传漏洞"),
    ("以下哪种方式可以更准确地判断文件的真实类型？",
     "以下哪种方式可以更准确地判断文件的真实类型？\n\nA. 仅检查文件名\nB. 检查文件的Magic Number（文件头）\nC. 仅检查文件扩展名\nD. 仅依赖前端JavaScript验证",
     "B", "single_choice", "medium", "文件上传漏洞"),
    ("对于图片文件上传，以下哪种处理可以增加安全性？",
     "对于图片文件上传，以下哪种处理可以增加安全性？\n\nA. 直接保存原始文件\nB. 对图片进行重新压缩/缩放处理，去除可能的恶意代码\nC. 只检查文件扩展名\nD. 将图片存储在Web根目录下",
     "B", "single_choice", "medium", "文件上传漏洞"),

    # 认证授权安全 (6题)
    ("JWT（JSON Web Token）由哪三部分组成？",
     "JWT（JSON Web Token）由哪三部分组成？\n\nA. Header、Payload、Signature\nB. Username、Password、Token\nC. Key、Value、Expire\nD. Request、Response、Cookie",
     "A", "single_choice", "easy", "认证授权安全"),
    ("以下哪个是JWT相对于Session认证的优势？",
     "以下哪个是JWT相对于Session认证的优势？\n\nA. JWT需要服务器存储会话信息\nB. JWT是无状态的，适合分布式系统\nC. JWT不能跨域使用\nD. JWT更安全，永远不会被伪造",
     "B", "single_choice", "easy", "认证授权安全"),
    ("以下哪些是安全的密码存储方式？",
     "以下哪些是安全的密码存储方式？（多选）\n\nA. MD5哈希\nB. SHA256加盐哈希\nC. bcrypt\nD. 明文存储",
     "B,C", "multiple_choice", "medium", "认证授权安全"),
    ("以下关于Session安全的说法，正确的是？",
     "以下关于Session安全的说法，正确的是？\n\nA. Session ID可以放在URL参数中传递\nB. 应该使用HttpOnly和Secure属性保护Cookie中的Session ID\nC. Session永远不会过期，不需要设置超时时间\nD. 同一个Session ID可以在多个设备上同时使用，不需要限制",
     "B", "single_choice", "medium", "认证授权安全"),
    ("水平权限漏洞和垂直权限漏洞的区别是什么？",
     "水平权限漏洞和垂直权限漏洞的区别是什么？\n\nA. 水平权限漏洞是同级用户之间的未授权访问，垂直权限漏洞是普通用户访问管理员功能\nB. 两者完全相同\nC. 水平权限漏洞更严重\nD. 垂直权限漏洞只存在于Web应用中",
     "A", "single_choice", "medium", "认证授权安全"),
    ("JWT的Payload部分如果包含敏感信息，应该怎么做？",
     "JWT的Payload部分如果包含敏感信息，应该怎么做？\n\nA. 没关系，Payload是加密的\nB. 避免在Payload中存放敏感信息，因为Payload只是Base64编码，可以被解码\nC. 使用HTTP而不是HTTPS传输\nD. 增加JWT的过期时间",
     "B", "single_choice", "medium", "认证授权安全"),
]


def insert_lp_exercises(cursor, exercises, lp_id):
    for ex in exercises:
        insert_exercise(cursor, ex[0], ex[1], ex[2], ex[3], ex[4], lp_id, ex[5])


if __name__ == '__main__':
    print("=" * 60)
    print("重新生成 LP12-LP14 高质量习题")
    print("=" * 60)

    conn = get_db()
    cursor = conn.cursor()

    # LP12
    print(f"\n--- LP12: 移动端测试基础 ---")
    insert_lp_exercises(cursor, LP12_EXERCISES, 12)
    print(f"LP12: 成功插入 {len(LP12_EXERCISES)} 道习题")

    # LP13
    print(f"\n--- LP13: 性能测试 - JMeter与Locust ---")
    insert_lp_exercises(cursor, LP13_EXERCISES, 13)
    print(f"LP13: 成功插入 {len(LP13_EXERCISES)} 道习题")

    # LP14
    print(f"\n--- LP14: 安全测试基础 ---")
    insert_lp_exercises(cursor, LP14_EXERCISES, 14)
    print(f"LP14: 成功插入 {len(LP14_EXERCISES)} 道习题")

    conn.commit()
    conn.close()

    print("\n" + "=" * 60)
    print("✅ LP12-LP14 全部完成！")
    print("=" * 60)
