"""
测试工程师成长平台 - 知识体系数据填充脚本
填充5个阶段的学习路径和配套习题
"""
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import datetime
from sqlalchemy import select
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

from fastapi_backend.core.config import settings
from fastapi_backend.models.models import Base, Exercise, LearningPath

DATABASE_URL = settings.DATABASE_URL

engine = create_async_engine(DATABASE_URL, echo=False)
async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


LEARNING_PATHS_DATA = [
    {
        "title": "软件测试基础理论",
        "description": "系统学习软件测试的基本概念、原则、分类和流程，建立正确的测试思维。掌握V模型、W模型、敏捷测试等开发模型，理解黑盒测试与白盒测试的核心区别。",
        "learning_objectives": "理解软件测试的定义和目的；掌握测试的5大原则；熟悉测试分类体系；理解缺陷的生命周期；掌握测试用例的基本要素",
        "knowledge_outline": "1.软件测试概述 2.测试原则与误区 3.测试分类(按阶段/按方法/按方向) 4.软件开发生命周期 5.缺陷管理 6.测试用例基础",
        "supporting_resources": "《软件测试的艺术》第1-3章；ISTQB基础级大纲",
        "prerequisites": "无",
        "language": "中文",
        "difficulty": "beginner",
        "stage": 1,
        "estimated_hours": 20,
        "exercises": [
            {
                "title": "软件测试的定义与目的",
                "description": "理解软件测试的核心定义，区分验证(Verification)和确认(Validation)的概念，掌握测试的终极目标。",
                "instructions": "请回答以下关于软件测试基础概念的问题",
                "solution": "B",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "test_theory",
                "stage": 1,
                "knowledge_point": "测试基础理论",
                "time_estimate": 5,
                "exercise_type": "choice",
                "test_cases": None,
                "code_template": None,
                "expected_output": None,
            },
            {
                "title": "测试原则 - 杀虫剂悖论",
                "description": "杀虫剂悖论是软件测试的重要原则之一：如果反复使用相同的测试用例集，最终将无法发现新的缺陷。请问以下哪种做法最能应对杀虫剂悖论？",
                "instructions": "选择最能应对杀虫剂悖论的测试策略",
                "solution": "B",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "test_theory",
                "stage": 1,
                "knowledge_point": "测试原则",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "黑盒测试与白盒测试的区别",
                "description": "黑盒测试和白盒测试是两种基本的测试方法。黑盒测试关注输入和输出，不考虑内部结构；白盒测试关注程序内部逻辑结构。以下关于两者的说法，哪个是正确的？",
                "instructions": "判断关于黑盒测试和白盒测试的说法是否正确",
                "solution": "A",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "test_theory",
                "stage": 1,
                "knowledge_point": "测试方法分类",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "缺陷的严重程度与优先级",
                "description": "缺陷管理中，严重程度(Severity)和优先级(Priority)是两个重要概念。一个导致系统崩溃的偶发缺陷，严重程度应该是什么级别？",
                "instructions": "根据缺陷描述判断严重程度级别",
                "solution": "A",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "test_theory",
                "stage": 1,
                "knowledge_point": "缺陷管理",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "V模型中的测试阶段",
                "description": "V模型是经典的软件开发模型，它将测试活动与开发活动对应起来。在V模型中，系统测试对应哪个开发阶段？",
                "instructions": "选择V模型中系统测试对应的开发阶段",
                "solution": "C",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "test_theory",
                "stage": 1,
                "knowledge_point": "开发模型",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "SQL数据库基础",
        "description": "掌握SQL语言的核心操作，包括数据查询(SELECT)、数据操作(INSERT/UPDATE/DELETE)、表操作(CREATE/ALTER/DROP)，以及多表连接查询和子查询。这是测试工程师验证数据正确性的必备技能。",
        "learning_objectives": "掌握SQL基本查询语法；熟练使用WHERE、ORDER BY、GROUP BY、HAVING；掌握多表JOIN查询；理解子查询和聚合函数；能编写SQL验证测试数据",
        "knowledge_outline": "1.SQL基础语法 2.SELECT查询 3.WHERE条件过滤 4.聚合函数与分组 5.多表JOIN 6.子查询 7.数据操作DML 8.表操作DDL",
        "supporting_resources": "《SQL必知必会》；MySQL官方文档",
        "prerequisites": "无",
        "language": "SQL",
        "difficulty": "beginner",
        "stage": 1,
        "estimated_hours": 30,
        "exercises": [
            {
                "title": "基础SELECT查询",
                "description": "有一个学生表students(id, name, age, grade)，请编写SQL查询所有年龄大于18岁的学生姓名和年龄。",
                "instructions": "编写SQL查询语句，从students表中查询age > 18的记录，返回name和age字段",
                "solution": "SELECT name, age FROM students WHERE age > 18;",
                "difficulty": "beginner",
                "language": "SQL",
                "module": "normal",
                "category": "database",
                "stage": 1,
                "knowledge_point": "SQL基础查询",
                "time_estimate": 5,
                "exercise_type": "sql",
                "test_cases": "[{\"input\": \"CREATE TABLE students(id INT, name VARCHAR(50), age INT, grade VARCHAR(10)); INSERT INTO students VALUES(1,'张三',20,'A'),(2,'李四',17,'B'),(3,'王五',19,'A');\", \"expected_output\": \"张三|20\\n王五|19\"}]",
                "code_template": "-- 请编写SQL查询\nSELECT",
                "expected_output": "张三|20\n王五|19",
            },
            {
                "title": "GROUP BY与聚合函数",
                "description": "有订单表orders(id, customer_id, amount, order_date)，请编写SQL查询每个客户的订单总数和总金额。",
                "instructions": "使用GROUP BY和聚合函数COUNT、SUM，按customer_id分组统计",
                "solution": "SELECT customer_id, COUNT(*) as order_count, SUM(amount) as total_amount FROM orders GROUP BY customer_id;",
                "difficulty": "beginner",
                "language": "SQL",
                "module": "normal",
                "category": "database",
                "stage": 1,
                "knowledge_point": "SQL聚合函数",
                "time_estimate": 8,
                "exercise_type": "sql",
                "code_template": "-- 请编写SQL查询\nSELECT",
            },
            {
                "title": "多表JOIN查询",
                "description": "有用户表users(id, name, dept_id)和部门表departments(id, dept_name)，请查询每个用户及其所属部门名称，包括没有部门的用户。",
                "instructions": "使用LEFT JOIN连接users和departments表",
                "solution": "SELECT u.name, d.dept_name FROM users u LEFT JOIN departments d ON u.dept_id = d.id;",
                "difficulty": "intermediate",
                "language": "SQL",
                "module": "normal",
                "category": "database",
                "stage": 1,
                "knowledge_point": "SQL多表查询",
                "time_estimate": 10,
                "exercise_type": "sql",
                "code_template": "-- 请编写SQL查询\nSELECT",
            },
            {
                "title": "子查询实战",
                "description": "有员工表employees(id, name, salary, dept_id)，请查询薪资高于其所在部门平均薪资的员工姓名和薪资。",
                "instructions": "使用子查询先计算每个部门的平均薪资，再筛选高于平均的员工",
                "solution": "SELECT name, salary FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE dept_id = e.dept_id);",
                "difficulty": "intermediate",
                "language": "SQL",
                "module": "normal",
                "category": "database",
                "stage": 1,
                "knowledge_point": "SQL子查询",
                "time_estimate": 12,
                "exercise_type": "sql",
                "code_template": "-- 请编写SQL查询\nSELECT",
            },
        ],
    },
    {
        "title": "计算机基础与网络知识",
        "description": "测试工程师需要具备基本的计算机和网络知识，包括HTTP协议、TCP/IP、操作系统基础、数据结构等，这些是理解系统行为和定位问题的基础。",
        "learning_objectives": "理解HTTP请求响应模型；掌握常见HTTP状态码；理解TCP/IP分层模型；了解Linux基本命令；理解进程与线程的区别",
        "knowledge_outline": "1.HTTP协议基础 2.HTTP状态码 3.TCP/IP模型 4.DNS解析 5.Linux基础命令 6.进程与线程",
        "supporting_resources": "《计算机网络：自顶向下方法》；《图解HTTP》",
        "prerequisites": "无",
        "language": "中文",
        "difficulty": "beginner",
        "stage": 1,
        "estimated_hours": 25,
        "exercises": [
            {
                "title": "HTTP状态码识别",
                "description": "HTTP状态码是Web测试中最常见的概念。当服务器返回404状态码时，表示什么含义？",
                "instructions": "选择404状态码的正确含义",
                "solution": "B",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "test_theory",
                "stage": 1,
                "knowledge_point": "HTTP协议",
                "time_estimate": 3,
                "exercise_type": "choice",
            },
            {
                "title": "GET与POST请求的区别",
                "description": "GET和POST是HTTP最常用的两种请求方法。以下关于GET和POST的说法，哪个是错误的？",
                "instructions": "选择关于GET和POST的错误说法",
                "solution": "D",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "api_test",
                "stage": 1,
                "knowledge_point": "HTTP方法",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "TCP三次握手",
                "description": "TCP建立连接需要三次握手。请描述三次握手的过程：第一次握手客户端发送什么标志位的报文？",
                "instructions": "选择第一次握手客户端发送的TCP标志位",
                "solution": "A",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "test_theory",
                "stage": 1,
                "knowledge_point": "TCP/IP",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "Linux基础命令",
        "description": "掌握Linux常用命令是测试工程师查看日志、部署环境、排查问题的必备技能。本路径覆盖文件操作、文本处理、进程管理、权限管理等核心命令。",
        "learning_objectives": "熟练使用ls/cd/cp/mv/rm等文件命令；掌握grep/sed/awk文本处理；理解文件权限chmod/chown；掌握ps/top/kill进程管理；能使用tail查看日志",
        "knowledge_outline": "1.文件与目录操作 2.文件内容查看与编辑 3.文本处理三剑客(grep/sed/awk) 4.文件权限管理 5.进程管理 6.网络命令 7.日志查看",
        "supporting_resources": "《鸟哥的Linux私房菜》；Linux命令行大全",
        "prerequisites": "计算机基础",
        "language": "Shell",
        "difficulty": "beginner",
        "stage": 1,
        "estimated_hours": 25,
        "exercises": [
            {
                "title": "文件权限chmod命令",
                "description": "在Linux中，chmod 755 file.txt 命令将文件权限设置为什么？请解释755各数字的含义。",
                "instructions": "选择chmod 755的正确权限解释",
                "solution": "A",
                "difficulty": "beginner",
                "language": "Shell",
                "module": "normal",
                "category": "linux",
                "stage": 1,
                "knowledge_point": "Linux权限管理",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "grep命令查找日志",
                "description": "在日志文件app.log中查找包含ERROR关键字的所有行，并显示行号，应该使用什么命令？",
                "instructions": "编写正确的grep命令",
                "solution": "grep -n 'ERROR' app.log",
                "difficulty": "beginner",
                "language": "Shell",
                "module": "normal",
                "category": "linux",
                "stage": 1,
                "knowledge_point": "Linux文本处理",
                "time_estimate": 5,
                "exercise_type": "code",
                "code_template": "# 编写grep命令查找ERROR\n",
            },
            {
                "title": "tail命令实时查看日志",
                "description": "需要实时监控服务器上的error.log文件，查看最新追加的内容，应该使用什么命令？",
                "instructions": "编写tail命令实时查看日志",
                "solution": "tail -f error.log",
                "difficulty": "beginner",
                "language": "Shell",
                "module": "normal",
                "category": "linux",
                "stage": 1,
                "knowledge_point": "Linux日志查看",
                "time_estimate": 3,
                "exercise_type": "code",
                "code_template": "# 编写tail命令\n",
            },
        ],
    },
    {
        "title": "测试用例设计方法",
        "description": "掌握等价类划分、边界值分析、因果图、正交实验、场景法等核心测试用例设计方法，能针对不同类型的功能设计出高质量的测试用例。",
        "learning_objectives": "掌握等价类划分法；熟练使用边界值分析；理解因果图法；掌握场景法设计用例；能综合运用多种方法设计完整测试方案",
        "knowledge_outline": "1.等价类划分法 2.边界值分析法 3.因果图法 4.判定表驱动 5.正交实验法 6.场景法 7.错误推测法 8.综合策略",
        "supporting_resources": "《软件测试技术基础》；ISTQB高级大纲",
        "prerequisites": "测试基础理论",
        "language": "中文",
        "difficulty": "intermediate",
        "stage": 2,
        "estimated_hours": 30,
        "exercises": [
            {
                "title": "等价类划分法实战",
                "description": "某系统要求用户输入年龄，有效范围是18-60岁。请使用等价类划分法，划分出有效等价类和无效等价类。",
                "instructions": "根据等价类划分原则，选择正确的划分方案",
                "solution": "B",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "functional_test",
                "stage": 2,
                "knowledge_point": "等价类划分",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
            {
                "title": "边界值分析法",
                "description": "一个文本框允许输入1-100之间的整数。使用边界值分析法，应该测试哪些边界值？",
                "instructions": "选择正确的边界值测试数据集",
                "solution": "C",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "functional_test",
                "stage": 2,
                "knowledge_point": "边界值分析",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
            {
                "title": "场景法设计测试用例",
                "description": "电商下单流程：用户登录→浏览商品→加入购物车→填写地址→选择支付方式→确认支付。请使用场景法设计测试场景，以下哪个是异常场景？",
                "instructions": "选择属于异常场景的选项",
                "solution": "D",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "functional_test",
                "stage": 2,
                "knowledge_point": "场景法",
                "time_estimate": 10,
                "exercise_type": "choice",
            },
            {
                "title": "因果图法应用",
                "description": "某注册页面有如下规则：①用户名不能为空 ②密码长度6-16位 ③确认密码必须与密码一致 ④手机号必须是11位数字。请使用因果图法分析，以下哪个测试用例覆盖了'密码长度不足6位且手机号格式错误'的组合？",
                "instructions": "选择正确覆盖指定条件的测试用例",
                "solution": "B",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "functional_test",
                "stage": 2,
                "knowledge_point": "因果图法",
                "time_estimate": 12,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "测试计划编写与项目管理",
        "description": "学习如何编写专业的测试计划文档，掌握测试范围界定、资源估算、风险评估、进度安排等核心能力，能独立负责项目的测试工作。",
        "learning_objectives": "掌握测试计划的核心要素；能编写测试范围和策略；理解测试里程碑和进度管理；掌握风险评估方法；能输出测试总结报告",
        "knowledge_outline": "1.测试计划概述 2.测试范围界定 3.测试策略制定 4.资源与进度安排 5.风险评估与应对 6.测试执行管理 7.测试报告编写",
        "supporting_resources": "IEEE 829测试文档标准；ISTQB高级测试管理",
        "prerequisites": "测试基础理论、测试用例设计",
        "language": "中文",
        "difficulty": "intermediate",
        "stage": 2,
        "estimated_hours": 25,
        "exercises": [
            {
                "title": "测试计划核心要素",
                "description": "一份完整的测试计划文档应包含哪些核心要素？以下哪个不属于测试计划的必要组成部分？",
                "instructions": "选择不属于测试计划必要组成部分的选项",
                "solution": "D",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "functional_test",
                "stage": 2,
                "knowledge_point": "测试计划",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "测试风险评估",
                "description": "在项目测试过程中，以下哪种风险属于项目风险（而非产品风险）？",
                "instructions": "选择属于项目风险的选项",
                "solution": "B",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "functional_test",
                "stage": 2,
                "knowledge_point": "风险评估",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "接口测试基础",
        "description": "系统学习接口测试的核心概念和方法，掌握HTTP接口测试流程、Postman工具使用、接口文档解读、参数化测试、断言验证等实战技能。",
        "learning_objectives": "理解接口测试的概念和意义；掌握HTTP接口测试流程；熟练使用Postman发送请求；掌握接口参数化和断言；理解RESTful API设计规范",
        "knowledge_outline": "1.接口测试概述 2.HTTP协议深入 3.RESTful API规范 4.Postman使用 5.接口参数化 6.接口断言与验证 7.接口安全测试基础 8.接口自动化入门",
        "supporting_resources": "《接口测试自动化实战》；Postman官方文档",
        "prerequisites": "HTTP协议基础、SQL基础",
        "language": "中文",
        "difficulty": "intermediate",
        "stage": 3,
        "estimated_hours": 35,
        "exercises": [
            {
                "title": "RESTful API设计规范",
                "description": "RESTful API遵循特定的设计规范。以下哪个URL设计符合RESTful规范，用于获取ID为123的用户信息？",
                "instructions": "选择符合RESTful规范的API URL",
                "solution": "A",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "api_test",
                "stage": 3,
                "knowledge_point": "RESTful规范",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "接口测试用例设计",
                "description": "对一个登录接口 POST /api/login (参数: username, password) 进行测试，以下哪个不属于必须测试的场景？",
                "instructions": "选择不属于必须测试的场景",
                "solution": "D",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "api_test",
                "stage": 3,
                "knowledge_point": "接口测试设计",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
            {
                "title": "Postman环境变量",
                "description": "在Postman中，如何在请求URL中使用环境变量base_url？请写出正确的语法。",
                "instructions": "编写Postman中引用环境变量的语法",
                "solution": "{{base_url}}",
                "difficulty": "beginner",
                "language": "中文",
                "module": "normal",
                "category": "api_test",
                "stage": 3,
                "knowledge_point": "Postman使用",
                "time_estimate": 3,
                "exercise_type": "code",
                "code_template": "# 写出Postman引用环境变量的语法\n",
            },
            {
                "title": "接口鉴权Token测试",
                "description": "某API使用Bearer Token进行鉴权。在请求头中添加Authorization字段时，正确的格式是什么？",
                "instructions": "编写Bearer Token鉴权的请求头格式",
                "solution": "Bearer <token>",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "api_test",
                "stage": 3,
                "knowledge_point": "接口鉴权",
                "time_estimate": 5,
                "exercise_type": "code",
                "code_template": "# 编写Authorization请求头格式\n",
            },
        ],
    },
    {
        "title": "Python编程基础",
        "description": "从零开始学习Python编程，掌握变量、数据类型、控制流、函数、面向对象、文件操作、异常处理等核心语法，为自动化测试打下坚实的编程基础。",
        "learning_objectives": "掌握Python基本语法和数据类型；熟练使用列表/字典/元组/集合；掌握函数定义和参数传递；理解面向对象编程；掌握文件读写和异常处理",
        "knowledge_outline": "1.Python环境搭建 2.变量与数据类型 3.运算符与表达式 4.条件判断与循环 5.列表/字典/元组/集合 6.函数与模块 7.面向对象编程 8.文件操作 9.异常处理 10.常用标准库",
        "supporting_resources": "《Python编程：从入门到实践》；《流畅的Python》",
        "prerequisites": "无",
        "language": "Python",
        "difficulty": "beginner",
        "stage": 3,
        "estimated_hours": 40,
        "exercises": [
            {
                "title": "Python列表操作",
                "description": "编写一个Python函数，接收一个整数列表，返回其中所有偶数的平方组成的列表。例如输入[1,2,3,4,5]返回[4,16]。",
                "instructions": "使用列表推导式或循环实现",
                "solution": "def even_squares(lst):\n    return [x**2 for x in lst if x % 2 == 0]",
                "difficulty": "beginner",
                "language": "Python",
                "module": "normal",
                "category": "programming",
                "stage": 3,
                "knowledge_point": "Python列表",
                "time_estimate": 10,
                "exercise_type": "code",
                "test_cases": "[{\"input\": \"[1,2,3,4,5]\", \"expected_output\": \"[4, 16]\"}, {\"input\": \"[1,3,5]\", \"expected_output\": \"[]\"}]",
                "code_template": "def even_squares(lst):\n    # 请在此处编写代码\n    pass",
                "expected_output": "[4, 16]",
            },
            {
                "title": "Python字典操作",
                "description": "编写一个Python函数，统计字符串中每个字符出现的次数，返回一个字典。例如输入'hello'返回{'h':1,'e':1,'l':2,'o':1}。",
                "instructions": "使用字典实现字符计数",
                "solution": "def char_count(s):\n    result = {}\n    for c in s:\n        result[c] = result.get(c, 0) + 1\n    return result",
                "difficulty": "beginner",
                "language": "Python",
                "module": "normal",
                "category": "programming",
                "stage": 3,
                "knowledge_point": "Python字典",
                "time_estimate": 10,
                "exercise_type": "code",
                "code_template": "def char_count(s):\n    # 请在此处编写代码\n    pass",
            },
            {
                "title": "Python面向对象",
                "description": "创建一个TestCase类，包含属性name(用例名称)、status(执行状态)，以及方法mark_pass()和mark_fail()用于设置状态。mark_pass()设置status为'passed'，mark_fail()设置status为'failed'。",
                "instructions": "编写完整的TestCase类",
                "solution": "class TestCase:\n    def __init__(self, name):\n        self.name = name\n        self.status = 'pending'\n    def mark_pass(self):\n        self.status = 'passed'\n    def mark_fail(self):\n        self.status = 'failed'",
                "difficulty": "intermediate",
                "language": "Python",
                "module": "normal",
                "category": "programming",
                "stage": 3,
                "knowledge_point": "Python面向对象",
                "time_estimate": 15,
                "exercise_type": "code",
                "code_template": "class TestCase:\n    # 请在此处编写代码\n    pass",
            },
            {
                "title": "Python文件读取与解析",
                "description": "编写一个函数read_csv(filename)，读取CSV文件并返回列表的列表。假设CSV文件没有表头，字段用逗号分隔。例如文件内容'a,b\\nc,d'返回[['a','b'],['c','d']]。",
                "instructions": "使用open()和字符串split()方法实现",
                "solution": "def read_csv(filename):\n    result = []\n    with open(filename, 'r') as f:\n        for line in f:\n            result.append(line.strip().split(','))\n    return result",
                "difficulty": "intermediate",
                "language": "Python",
                "module": "normal",
                "category": "programming",
                "stage": 3,
                "knowledge_point": "Python文件操作",
                "time_estimate": 15,
                "exercise_type": "code",
                "code_template": "def read_csv(filename):\n    # 请在此处编写代码\n    pass",
            },
            {
                "title": "Python异常处理",
                "description": "编写一个函数safe_divide(a, b)，实现安全除法。当b为0时返回None而不是抛出异常，当参数不是数字时返回None。",
                "instructions": "使用try-except实现异常处理",
                "solution": "def safe_divide(a, b):\n    try:\n        return a / b\n    except (ZeroDivisionError, TypeError):\n        return None",
                "difficulty": "beginner",
                "language": "Python",
                "module": "normal",
                "category": "programming",
                "stage": 3,
                "knowledge_point": "Python异常处理",
                "time_estimate": 8,
                "exercise_type": "code",
                "code_template": "def safe_divide(a, b):\n    # 请在此处编写代码\n    pass",
            },
        ],
    },
    {
        "title": "UI自动化测试 - Selenium",
        "description": "系统学习Selenium WebDriver进行Web UI自动化测试，掌握元素定位、浏览器操作、等待机制、页面对象模式(POM)、数据驱动测试等核心技能。",
        "learning_objectives": "掌握Selenium环境搭建；熟练使用8种元素定位方式；掌握显式等待和隐式等待；理解POM设计模式；掌握数据驱动测试；能编写完整的UI自动化测试框架",
        "knowledge_outline": "1.Selenium环境搭建 2.浏览器驱动配置 3.元素定位8种方式 4.浏览器操作API 5.等待机制 6.iframe与窗口切换 7.POM设计模式 8.数据驱动测试 9.截图与日志 10.测试报告",
        "supporting_resources": "Selenium官方文档；《Selenium自动化测试实战》",
        "prerequisites": "Python编程基础",
        "language": "Python",
        "difficulty": "advanced",
        "stage": 4,
        "estimated_hours": 45,
        "exercises": [
            {
                "title": "Selenium元素定位",
                "description": "在Selenium中，以下哪种定位方式是最推荐的，因为它最稳定且性能最好？",
                "instructions": "选择最推荐的元素定位方式",
                "solution": "A",
                "difficulty": "intermediate",
                "language": "Python",
                "module": "normal",
                "category": "automation_test",
                "stage": 4,
                "knowledge_point": "元素定位",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "显式等待与隐式等待",
                "description": "Selenium中有两种等待机制。以下关于显式等待(WebDriverWait)和隐式等待(implicitly_wait)的说法，哪个是正确的？",
                "instructions": "选择关于两种等待机制的正确说法",
                "solution": "C",
                "difficulty": "intermediate",
                "language": "Python",
                "module": "normal",
                "category": "automation_test",
                "stage": 4,
                "knowledge_point": "等待机制",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
            {
                "title": "编写Selenium登录测试",
                "description": "使用Selenium编写一个登录测试脚本：打开登录页面，输入用户名'admin'和密码'123456'，点击登录按钮，验证是否跳转到首页。",
                "instructions": "编写完整的Selenium登录测试代码",
                "solution": "from selenium import webdriver\nfrom selenium.webdriver.common.by import By\nfrom selenium.webdriver.support.ui import WebDriverWait\nfrom selenium.webdriver.support import expected_conditions as EC\n\ndef test_login():\n    driver = webdriver.Chrome()\n    driver.get('https://example.com/login')\n    driver.find_element(By.ID, 'username').send_keys('admin')\n    driver.find_element(By.ID, 'password').send_keys('123456')\n    driver.find_element(By.ID, 'login-btn').click()\n    WebDriverWait(driver, 10).until(\n        EC.url_contains('home')\n    )\n    assert 'home' in driver.current_url\n    driver.quit()",
                "difficulty": "advanced",
                "language": "Python",
                "module": "normal",
                "category": "automation_test",
                "stage": 4,
                "knowledge_point": "Selenium实战",
                "time_estimate": 20,
                "exercise_type": "code",
                "code_template": "from selenium import webdriver\nfrom selenium.webdriver.common.by import By\n\n# 请编写登录测试代码\n",
            },
            {
                "title": "POM设计模式",
                "description": "页面对象模型(POM)是UI自动化测试的最佳实践。以下关于POM的说法，哪个是错误的？",
                "instructions": "选择关于POM的错误说法",
                "solution": "D",
                "difficulty": "advanced",
                "language": "Python",
                "module": "normal",
                "category": "automation_test",
                "stage": 4,
                "knowledge_point": "POM模式",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "接口自动化测试 - Requests+Pytest",
        "description": "使用Python Requests库+Pytest框架构建接口自动化测试体系，掌握接口自动化框架设计、数据驱动、Allure报告、CI集成等企业级实践。",
        "learning_objectives": "熟练使用Requests库发送HTTP请求；掌握Pytest测试框架；理解接口自动化框架设计；掌握数据驱动测试；掌握Allure测试报告；理解CI/CD集成",
        "knowledge_outline": "1.Requests库基础 2.Pytest框架入门 3.接口自动化框架设计 4.数据驱动测试 5.接口签名与加密 6.文件上传下载测试 7.Allure测试报告 8.持续集成CI/CD",
        "supporting_resources": "Requests官方文档；Pytest官方文档；《接口自动化测试实战》",
        "prerequisites": "Python编程基础、接口测试基础",
        "language": "Python",
        "difficulty": "advanced",
        "stage": 4,
        "estimated_hours": 45,
        "exercises": [
            {
                "title": "Requests发送POST请求",
                "description": "使用Python Requests库发送一个POST请求到 https://api.example.com/login，传递JSON数据{\"username\": \"admin\", \"password\": \"123456\"}，并获取响应的JSON数据。",
                "instructions": "编写使用Requests发送POST请求的代码",
                "solution": "import requests\n\nresponse = requests.post(\n    'https://api.example.com/login',\n    json={'username': 'admin', 'password': '123456'}\n)\ndata = response.json()",
                "difficulty": "intermediate",
                "language": "Python",
                "module": "normal",
                "category": "automation_test",
                "stage": 4,
                "knowledge_point": "Requests库",
                "time_estimate": 10,
                "exercise_type": "code",
                "code_template": "import requests\n\n# 请编写POST请求代码\n",
            },
            {
                "title": "Pytest参数化测试",
                "description": "使用Pytest的@pytest.mark.parametrize装饰器，对登录接口进行参数化测试。测试数据：正确账号密码、空用户名、空密码、错误密码。",
                "instructions": "编写Pytest参数化测试代码",
                "solution": "import pytest\n\n@pytest.mark.parametrize('username,password,expected', [\n    ('admin', '123456', 200),\n    ('', '123456', 400),\n    ('admin', '', 400),\n    ('admin', 'wrong', 401),\n])\ndef test_login(username, password, expected):\n    response = requests.post(url, json={'username': username, 'password': password})\n    assert response.status_code == expected",
                "difficulty": "advanced",
                "language": "Python",
                "module": "normal",
                "category": "automation_test",
                "stage": 4,
                "knowledge_point": "Pytest参数化",
                "time_estimate": 15,
                "exercise_type": "code",
                "code_template": "import pytest\n\n# 请编写参数化测试代码\n",
            },
            {
                "title": "接口自动化框架分层",
                "description": "企业级接口自动化框架通常采用分层设计。以下哪个不属于标准的框架分层？",
                "instructions": "选择不属于标准框架分层的选项",
                "solution": "D",
                "difficulty": "advanced",
                "language": "Python",
                "module": "normal",
                "category": "automation_test",
                "stage": 4,
                "knowledge_point": "框架设计",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "性能测试 - JMeter与Locust",
        "description": "系统学习性能测试理论和方法，掌握JMeter和Locust两大性能测试工具，能独立完成性能测试方案设计、脚本编写、场景执行和结果分析。",
        "learning_objectives": "理解性能测试核心指标(QPS/TPS/RT/并发数)；掌握JMeter测试计划编写；掌握Locust脚本开发；能设计性能测试场景；掌握性能瓶颈分析方法",
        "knowledge_outline": "1.性能测试概述 2.核心指标与术语 3.JMeter基础 4.JMeter高级组件 5.Locust入门 6.Locust高级用法 7.性能测试场景设计 8.性能瓶颈分析 9.性能测试报告",
        "supporting_resources": "JMeter官方文档；Locust官方文档；《性能测试实战》",
        "prerequisites": "接口测试基础、Python编程基础",
        "language": "Python",
        "difficulty": "advanced",
        "stage": 4,
        "estimated_hours": 40,
        "exercises": [
            {
                "title": "性能测试核心指标",
                "description": "性能测试中，TPS(Transactions Per Second)和QPS(Queries Per Second)是两个重要指标。以下关于它们的说法，哪个是正确的？",
                "instructions": "选择关于TPS和QPS的正确说法",
                "solution": "B",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "performance_test",
                "stage": 4,
                "knowledge_point": "性能指标",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "Locust基础脚本",
                "description": "编写一个Locust性能测试脚本，模拟用户访问首页(HttpUser)，设置wait_time为1-3秒，定义一个task访问'/'路径。",
                "instructions": "编写Locust性能测试脚本",
                "solution": "from locust import HttpUser, task, between\n\nclass WebUser(HttpUser):\n    wait_time = between(1, 3)\n\n    @task\n    def visit_home(self):\n        self.client.get('/')",
                "difficulty": "advanced",
                "language": "Python",
                "module": "normal",
                "category": "performance_test",
                "stage": 4,
                "knowledge_point": "Locust脚本",
                "time_estimate": 15,
                "exercise_type": "code",
                "code_template": "from locust import HttpUser, task, between\n\n# 请编写Locust脚本\n",
            },
        ],
    },
    {
        "title": "安全测试基础",
        "description": "学习Web安全测试的核心知识，掌握OWASP Top 10安全漏洞的测试方法，包括SQL注入、XSS、CSRF、越权访问等常见安全风险的发现与验证。",
        "learning_objectives": "理解OWASP Top 10安全风险；掌握SQL注入测试方法；掌握XSS攻击测试；理解CSRF防护机制；掌握越权漏洞测试；能使用Burp Suite辅助测试",
        "knowledge_outline": "1.安全测试概述 2.OWASP Top 10 3.SQL注入 4.XSS跨站脚本 5.CSRF跨站请求伪造 6.越权访问 7.文件上传漏洞 8.信息泄露 9.Burp Suite使用 10.安全测试报告",
        "supporting_resources": "OWASP官方文档；《Web安全攻防》",
        "prerequisites": "接口测试基础、SQL基础",
        "language": "中文",
        "difficulty": "advanced",
        "stage": 5,
        "estimated_hours": 35,
        "exercises": [
            {
                "title": "SQL注入识别",
                "description": "以下哪个输入最可能是SQL注入攻击的尝试？",
                "instructions": "选择SQL注入攻击的典型输入",
                "solution": "C",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "security_test",
                "stage": 5,
                "knowledge_point": "SQL注入",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "XSS攻击类型",
                "description": "XSS(跨站脚本)攻击分为存储型、反射型和DOM型三种。以下关于三种类型的说法，哪个是正确的？",
                "instructions": "选择关于XSS类型的正确说法",
                "solution": "A",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "security_test",
                "stage": 5,
                "knowledge_point": "XSS攻击",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
            {
                "title": "CSRF防护机制",
                "description": "CSRF(跨站请求伪造)是一种常见的Web安全漏洞。以下哪种方式是最常用的CSRF防护手段？",
                "instructions": "选择最常用的CSRF防护方式",
                "solution": "B",
                "difficulty": "intermediate",
                "language": "中文",
                "module": "normal",
                "category": "security_test",
                "stage": 5,
                "knowledge_point": "CSRF防护",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "AI测试与智能化",
        "description": "探索AI在软件测试领域的应用，包括AI辅助测试用例生成、智能缺陷预测、视觉回归测试、NLP驱动的接口测试等前沿技术方向。",
        "learning_objectives": "理解AI测试的发展趋势；掌握AI辅助用例生成方法；了解智能缺陷预测模型；掌握视觉回归测试工具；理解NLP在测试中的应用",
        "knowledge_outline": "1.AI测试概述 2.AI辅助用例生成 3.智能缺陷预测 4.视觉回归测试 5.NLP驱动测试 6.测试大模型应用 7.AI测试工具链 8.未来趋势",
        "supporting_resources": "《AI赋能软件测试》；Google AI Testing博客",
        "prerequisites": "自动化测试基础、Python编程",
        "language": "中文",
        "difficulty": "advanced",
        "stage": 5,
        "estimated_hours": 30,
        "exercises": [
            {
                "title": "AI测试应用场景",
                "description": "AI在软件测试中有多种应用场景。以下哪个不是目前AI在测试领域的主要应用方向？",
                "instructions": "选择不属于AI测试主要应用方向的选项",
                "solution": "D",
                "difficulty": "advanced",
                "language": "中文",
                "module": "normal",
                "category": "ai_test",
                "stage": 5,
                "knowledge_point": "AI测试概述",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "视觉回归测试原理",
                "description": "视觉回归测试(Visual Regression Testing)通过对比截图来发现UI变化。以下关于视觉回归测试的说法，哪个是正确的？",
                "instructions": "选择关于视觉回归测试的正确说法",
                "solution": "B",
                "difficulty": "advanced",
                "language": "中文",
                "module": "normal",
                "category": "ai_test",
                "stage": 5,
                "knowledge_point": "视觉回归测试",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
        ],
    },
    {
        "title": "测试平台开发与DevOps",
        "description": "学习测试平台的设计与开发，掌握Docker容器化、Jenkins CI/CD、质量度量体系等DevOps实践，向测试架构师方向发展。",
        "learning_objectives": "掌握测试平台架构设计；理解Docker容器化部署；掌握Jenkins Pipeline；理解质量度量体系；掌握测试数据管理策略",
        "knowledge_outline": "1.测试平台架构设计 2.Django/FastAPI开发 3.Docker容器化 4.Jenkins CI/CD 5.质量度量体系 6.测试数据管理 7.测试环境治理 8.持续测试实践",
        "supporting_resources": "《测试架构师》；Docker官方文档；Jenkins官方文档",
        "prerequisites": "Python编程、自动化测试、接口测试",
        "language": "Python",
        "difficulty": "advanced",
        "stage": 5,
        "estimated_hours": 50,
        "exercises": [
            {
                "title": "Docker基础命令",
                "description": "Docker是容器化部署的核心工具。以下哪个命令用于构建Docker镜像？",
                "instructions": "选择构建Docker镜像的命令",
                "solution": "A",
                "difficulty": "intermediate",
                "language": "Shell",
                "module": "normal",
                "category": "devops",
                "stage": 5,
                "knowledge_point": "Docker基础",
                "time_estimate": 5,
                "exercise_type": "choice",
            },
            {
                "title": "Jenkins Pipeline语法",
                "description": "Jenkins Pipeline使用Groovy DSL定义流水线。以下哪个是声明式Pipeline的正确结构？",
                "instructions": "选择正确的声明式Pipeline结构",
                "solution": "B",
                "difficulty": "advanced",
                "language": "Shell",
                "module": "normal",
                "category": "devops",
                "stage": 5,
                "knowledge_point": "Jenkins CI/CD",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
            {
                "title": "质量度量指标设计",
                "description": "构建质量度量体系是测试架构师的核心能力。以下哪个指标最适合衡量代码质量？",
                "instructions": "选择衡量代码质量的最佳指标",
                "solution": "C",
                "difficulty": "advanced",
                "language": "中文",
                "module": "normal",
                "category": "devops",
                "stage": 5,
                "knowledge_point": "质量度量",
                "time_estimate": 8,
                "exercise_type": "choice",
            },
        ],
    },
]


async def seed_data():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        total_paths = 0
        total_exercises = 0

        for path_data in LEARNING_PATHS_DATA:
            exercises_data = path_data.pop("exercises")

            stmt = select(LearningPath).where(LearningPath.title == path_data["title"])
            result = await session.execute(stmt)
            existing = result.scalar_one_or_none()

            if existing:
                print(f"  [SKIP] Already exists: {path_data['title']}")
                continue

            path = LearningPath(**path_data, exercise_count=len(exercises_data))
            session.add(path)
            await session.flush()

            for ex_data in exercises_data:
                exercise = Exercise(**ex_data, learning_path_id=path.id, is_public=True)
                session.add(exercise)

            total_paths += 1
            total_exercises += len(exercises_data)
            print(f"  [OK] Created path: {path_data['title']} ({len(exercises_data)} exercises)")

        await session.commit()
        print(f"\n[DONE] Created {total_paths} learning paths, {total_exercises} exercises")


if __name__ == "__main__":
    print("=" * 60)
    print("[START] Seeding test engineer knowledge data...")
    print("=" * 60)
    asyncio.run(seed_data())
