"""
TestMaster 习题扩充脚本
重点补充软件测试基础、Python、MySQL 三大方向的习题
"""
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

from fastapi_backend.core.config import settings
from fastapi_backend.models.models import Base, Exercise, LearningPath

DATABASE_URL = settings.DATABASE_URL
engine = create_async_engine(DATABASE_URL, echo=False)
async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

# ================================================================
# 习题数据定义（按学习路径分组）
# ================================================================

NEW_EXERCISES = {
    # ============================================================
    # 软件测试基础理论 (原本5题 → 新增11题 = 合计16题)
    # ============================================================
    "软件测试基础理论": [
        {
            "title": "静态测试与动态测试的区别",
            "description": "静态测试和动态测试是两种不同的测试方式。静态测试不需要执行程序，通过人工审查或工具扫描代码；动态测试需要实际运行程序来发现缺陷。以下哪个活动属于静态测试？",
            "instructions": "选择属于静态测试的活动",
            "solution": "C",
            "difficulty": "beginner",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "静态测试",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "测试级别：单元测试",
            "description": "软件测试分为单元测试、集成测试、系统测试、验收测试四个级别。以下关于单元测试的说法，哪个是正确的？",
            "instructions": "选择关于单元测试的正确说法",
            "solution": "B",
            "difficulty": "beginner",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "测试级别",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "冒烟测试与回归测试的区别",
            "description": "冒烟测试(Smoke Test)和回归测试(Regression Test)是两种常见的测试类型。冒烟测试主要用于验证软件的基本功能是否正常，通常在每次构建后进行；回归测试则验证修改后原有功能是否受影响。以下哪种场景最适合做冒烟测试？",
            "instructions": "选择最适合冒烟测试的场景",
            "solution": "A",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "冒烟测试",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "测试驱动开发(TDD)的基本流程",
            "description": "测试驱动开发(TDD)遵循\'红-绿-重构\'的循环。以下哪个是TDD的正确流程？",
            "instructions": "选择TDD的正确流程顺序",
            "solution": "C",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "TDD",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "敏捷测试的特点",
            "description": "敏捷测试与传统瀑布模型中的测试有很大不同。以下关于敏捷测试的说法，哪个是正确的？",
            "instructions": "选择关于敏捷测试的正确说法",
            "solution": "D",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "敏捷测试",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "测试用例的八大要素",
            "description": "一个完整的测试用例应包含多个要素。以下哪个不属于测试用例的必要要素？",
            "instructions": "选择不属于测试用例必要要素的选项",
            "solution": "D",
            "difficulty": "beginner",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "测试用例要素",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "缺陷的生命周期状态转换",
            "description": "缺陷从发现到关闭经历了多个状态。典型的缺陷生命周期包括：New→Open→Fixed→Verified→Closed。以下哪个状态转换是正确的？",
            "instructions": "选择正确的缺陷状态转换",
            "solution": "B",
            "difficulty": "beginner",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "缺陷生命周期",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "测试的七大原则 - 穷尽测试是不可能的",
            "description": "ISTQB定义了软件测试的七大原则。\'穷尽测试是不可能的\'是其中一条。以下哪种做法最能体现这一原则？",
            "instructions": "选择最能体现此原则的做法",
            "solution": "C",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "测试七大原则",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "探索性测试与脚本化测试",
            "description": "探索性测试强调测试人员的创造性和直觉，而脚本化测试则依赖预先设计的测试用例。以下关于两者的说法，哪个是正确的？",
            "instructions": "选择关于探索性测试和脚本化测试的正确说法",
            "solution": "A",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "探索性测试",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "验收测试包含哪些类型",
            "description": "验收测试是软件交付前的最后一道测试关卡，包括Alpha测试和Beta测试等。以下关于Alpha测试和Beta测试的说法，哪个是正确的？",
            "instructions": "选择关于Alpha和Beta测试的正确说法",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "验收测试",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "测试覆盖率的作用与局限",
            "description": "测试覆盖率是衡量测试完整性的重要指标。以下关于测试覆盖率的说法，哪个是正确的？",
            "instructions": "选择关于测试覆盖率的正确理解",
            "solution": "D",
            "difficulty": "advanced",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "测试覆盖率",
            "time_estimate": 10,
            "exercise_type": "choice",
        },
    ],

    # ============================================================
    # SQL数据库基础 (原本4题 → 新增12题 = 合计16题)
    # ============================================================
    "SQL数据库基础": [
        {
            "title": "CREATE TABLE创建表",
            "description": "需要创建一个用户表users，包含id(主键自增)、username(不为空)、email(唯一)、age(整数)、created_at(默认当前时间)。请编写正确的CREATE TABLE语句。",
            "instructions": "编写完整的CREATE TABLE语句",
            "solution": "CREATE TABLE users (\n    id INT PRIMARY KEY AUTO_INCREMENT,\n    username VARCHAR(50) NOT NULL,\n    email VARCHAR(100) UNIQUE,\n    age INT,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);",
            "difficulty": "beginner",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "DDL建表",
            "time_estimate": 10,
            "exercise_type": "sql",
            "code_template": "-- 编写CREATE TABLE语句\n",
            "test_cases": None,
        },
        {
            "title": "INSERT插入数据",
            "description": "向users表中插入一条新用户记录：username为'tom'，email为'tom@test.com'，age为25。请编写INSERT语句。",
            "instructions": "编写INSERT语句插入一条记录",
            "solution": "INSERT INTO users (username, email, age) VALUES ('tom', 'tom@test.com', 25);",
            "difficulty": "beginner",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "DML插入",
            "time_estimate": 5,
            "exercise_type": "sql",
            "code_template": "-- 编写INSERT语句\n",
            "test_cases": None,
        },
        {
            "title": "UPDATE更新数据",
            "description": "将users表中所有age小于18的用户的status字段更新为'minor'。请编写UPDATE语句。",
            "instructions": "编写UPDATE语句更新符合条件的数据",
            "solution": "UPDATE users SET status = 'minor' WHERE age < 18;",
            "difficulty": "beginner",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "DML更新",
            "time_estimate": 5,
            "exercise_type": "sql",
            "code_template": "-- 编写UPDATE语句\n",
            "test_cases": None,
        },
        {
            "title": "DELETE删除数据",
            "description": "删除orders表中所有状态为'cancelled'且创建时间超过30天的订单。请编写DELETE语句。",
            "instructions": "编写DELETE语句删除符合条件的记录",
            "solution": "DELETE FROM orders WHERE status = 'cancelled' AND created_at < DATE_SUB(NOW(), INTERVAL 30 DAY);",
            "difficulty": "intermediate",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "DML删除",
            "time_estimate": 8,
            "exercise_type": "sql",
            "code_template": "-- 编写DELETE语句\n",
            "test_cases": None,
        },
        {
            "title": "ORDER BY与LIMIT分页查询",
            "description": "查询products表中价格最高的前5件商品，显示商品名称和价格。请编写SQL语句。",
            "instructions": "使用ORDER BY和LIMIT实现分页查询",
            "solution": "SELECT name, price FROM products ORDER BY price DESC LIMIT 5;",
            "difficulty": "beginner",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "排序与分页",
            "time_estimate": 5,
            "exercise_type": "sql",
            "code_template": "-- 编写SQL查询\nSELECT",
            "test_cases": None,
        },
        {
            "title": "HAVING过滤分组结果",
            "description": "查询订单表中每个客户的订单总金额，只显示总金额超过1000的客户ID和总金额。请编写SQL语句。",
            "instructions": "使用GROUP BY和HAVING子句",
            "solution": "SELECT customer_id, SUM(amount) as total FROM orders GROUP BY customer_id HAVING SUM(amount) > 1000;",
            "difficulty": "intermediate",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "HAVING子句",
            "time_estimate": 8,
            "exercise_type": "sql",
            "code_template": "-- 编写SQL查询\nSELECT",
            "test_cases": None,
        },
        {
            "title": "COUNT/AVG/MAX/MIN聚合函数综合",
            "description": "查询employees表中各部门(department_id)的员工人数、平均薪资、最高薪资、最低薪资。请编写SQL语句。",
            "instructions": "使用多种聚合函数分组统计",
            "solution": "SELECT department_id, COUNT(*) as emp_count, AVG(salary) as avg_salary, MAX(salary) as max_salary, MIN(salary) as min_salary FROM employees GROUP BY department_id;",
            "difficulty": "intermediate",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "聚合函数",
            "time_estimate": 10,
            "exercise_type": "sql",
            "code_template": "-- 编写SQL查询\nSELECT",
            "test_cases": None,
        },
        {
            "title": "RIGHT JOIN与全连接的概念",
            "description": "有部门表departments和员工表employees，需要查询所有部门及其员工人数（包括没有员工的部门）。请编写SQL语句。",
            "instructions": "使用LEFT JOIN或RIGHT JOIN实现",
            "solution": "SELECT d.name, COUNT(e.id) as emp_count FROM departments d LEFT JOIN employees e ON d.id = e.dept_id GROUP BY d.id, d.name;",
            "difficulty": "intermediate",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "外连接",
            "time_estimate": 12,
            "exercise_type": "sql",
            "code_template": "-- 编写SQL查询\nSELECT",
            "test_cases": None,
        },
        {
            "title": "UNION合并查询结果",
            "description": "有两张表active_users和inactive_users，结构相同。请编写SQL查询所有用户（去重）的用户名和邮箱。",
            "instructions": "使用UNION合并两个查询结果",
            "solution": "SELECT username, email FROM active_users UNION SELECT username, email FROM inactive_users;",
            "difficulty": "intermediate",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "UNION查询",
            "time_estimate": 8,
            "exercise_type": "sql",
            "code_template": "-- 编写SQL查询\nSELECT",
            "test_cases": None,
        },
        {
            "title": "索引的作用与创建",
            "description": "create index idx_email on users(email) 这条语句创建了什么类型的索引？主要作用是什么？",
            "instructions": "选择关于索引的正确说法",
            "solution": "A",
            "difficulty": "intermediate",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "索引",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "事务的ACID特性",
            "description": "数据库事务具有ACID特性。以下哪个选项正确描述了ACID四个特性的含义？",
            "instructions": "选择ACID特性的正确描述",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "database",
            "knowledge_point": "事务ACID",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "SELECT DISTINCT去重查询",
            "description": "查询orders表中所有不同的客户ID（去重），并按ID升序排列。请编写SQL语句。",
            "instructions": "使用DISTINCT关键字去重",
            "solution": "SELECT DISTINCT customer_id FROM orders ORDER BY customer_id;",
            "difficulty": "beginner",
            "language": "SQL",
            "module": "normal",
            "category": "database",
            "knowledge_point": "DISTINCT去重",
            "time_estimate": 5,
            "exercise_type": "sql",
            "code_template": "-- 编写SQL查询\nSELECT",
            "test_cases": None,
        },
    ],

    # ============================================================
    # Python编程基础 (原本5题 → 新增11题 = 合计16题)
    # ============================================================
    "Python编程基础": [
        {
            "title": "Python字符串切片操作",
            "description": "编写一个Python函数reverse_string(s)，接收一个字符串，返回其反转后的字符串。例如输入'hello'返回'olleh'。",
            "instructions": "使用字符串切片实现反转",
            "solution": "def reverse_string(s):\n    return s[::-1]",
            "difficulty": "beginner",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "字符串操作",
            "time_estimate": 8,
            "exercise_type": "code",
            "code_template": "def reverse_string(s):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python字符串常用方法",
            "description": "编写一个函数clean_text(text)，接收一个字符串，去除首尾空格，将所有字符转为小写，并将多个连续空格替换为单个空格。",
            "instructions": "使用strip()、lower()和split()/join()方法",
            "solution": "def clean_text(text):\n    return ' '.join(text.strip().lower().split())",
            "difficulty": "beginner",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "字符串方法",
            "time_estimate": 10,
            "exercise_type": "code",
            "code_template": "def clean_text(text):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python集合(Set)操作",
            "description": "编写一个函数find_common(list1, list2)，接收两个列表，返回它们共同元素的列表（去重）。例如输入[1,2,3]和[2,3,4]返回[2,3]。",
            "instructions": "使用集合的交集操作",
            "solution": "def find_common(list1, list2):\n    return list(set(list1) & set(list2))",
            "difficulty": "beginner",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "集合操作",
            "time_estimate": 8,
            "exercise_type": "code",
            "code_template": "def find_common(list1, list2):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python列表推导式进阶",
            "description": "编写一个函数filter_and_transform(numbers)，接收一个整数列表，使用列表推导式返回所有大于10的数的平方，结果按降序排列。",
            "instructions": "一行列表推导式 + sorted实现",
            "solution": "def filter_and_transform(numbers):\n    return sorted([x**2 for x in numbers if x > 10], reverse=True)",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "列表推导式",
            "time_estimate": 10,
            "exercise_type": "code",
            "code_template": "def filter_and_transform(numbers):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python函数默认参数与可变参数",
            "description": "编写一个函数create_report(title, *sections, author='Anonymous')，可以接收可变数量的章节名和一个可选作者名。函数返回一个格式化的报告字符串。调用create_report('周报', '测试情况', 'Bug统计', author='张三')应返回'周报\\n作者: 张三\\n1.测试情况\\n2.Bug统计'。",
            "instructions": "使用*args和默认参数",
            "solution": "def create_report(title, *sections, author='Anonymous'):\n    lines = [title, f'作者: {author}']\n    for i, s in enumerate(sections, 1):\n        lines.append(f'{i}.{s}')\n    return '\\n'.join(lines)",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "函数参数",
            "time_estimate": 15,
            "exercise_type": "code",
            "code_template": "def create_report(title, *sections, author='Anonymous'):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python列表去重并保持顺序",
            "description": "编写一个函数unique_ordered(lst)，接收一个列表，去除重复元素但保持原有顺序。例如输入[3,1,2,1,3,4]返回[3,1,2,4]。不能使用set直接转换。",
            "instructions": "使用字典或循环实现有序去重",
            "solution": "def unique_ordered(lst):\n    seen = set()\n    result = []\n    for item in lst:\n        if item not in seen:\n            seen.add(item)\n            result.append(item)\n    return result",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "列表去重",
            "time_estimate": 12,
            "exercise_type": "code",
            "code_template": "def unique_ordered(lst):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python装饰器实现计时器",
            "description": "编写一个装饰器timer，用于测量被装饰函数的执行时间（秒），并打印出来。装饰器的作用是在不修改原函数的情况下给函数增加计时功能。",
            "instructions": "使用functools.wraps和time模块实现装饰器",
            "solution": "import time\nfrom functools import wraps\n\ndef timer(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        end = time.time()\n        print(f'{func.__name__} took {end - start:.4f}s')\n        return result\n    return wrapper",
            "difficulty": "advanced",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "装饰器",
            "time_estimate": 20,
            "exercise_type": "code",
            "code_template": "import time\nfrom functools import wraps\n\ndef timer(func):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python生成器函数",
            "description": "编写一个生成器函数fibonacci(n)，生成前n个斐波那契数列的值。斐波那契数列：0, 1, 1, 2, 3, 5, 8, 13...",
            "instructions": "使用yield关键字实现生成器",
            "solution": "def fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b",
            "difficulty": "advanced",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "生成器",
            "time_estimate": 15,
            "exercise_type": "code",
            "code_template": "def fibonacci(n):\n    # 请在此处编写代码\n    yield",
        },
        {
            "title": "Python JSON数据处理",
            "description": "编写一个函数merge_json_data(file_path)，读取一个JSON文件，文件中是一个列表，每个元素是一个包含name和score的字典。返回按score降序排列的前3名的名字列表。",
            "instructions": "使用json模块和sorted函数",
            "solution": "import json\n\ndef merge_json_data(file_path):\n    with open(file_path, 'r') as f:\n        data = json.load(f)\n    sorted_data = sorted(data, key=lambda x: x['score'], reverse=True)\n    return [item['name'] for item in sorted_data[:3]]",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "JSON处理",
            "time_estimate": 15,
            "exercise_type": "code",
            "code_template": "import json\n\ndef merge_json_data(file_path):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python日期时间处理",
            "description": "编写一个函数days_between(date1, date2)，接收两个日期字符串（格式'YYYY-MM-DD'），返回它们之间相隔的天数。例如days_between('2024-01-01', '2024-01-10')返回9。",
            "instructions": "使用datetime模块进行日期计算",
            "solution": "from datetime import datetime\n\ndef days_between(date1, date2):\n    d1 = datetime.strptime(date1, '%Y-%m-%d')\n    d2 = datetime.strptime(date2, '%Y-%m-%d')\n    return abs((d2 - d1).days)",
            "difficulty": "beginner",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "日期处理",
            "time_estimate": 10,
            "exercise_type": "code",
            "code_template": "from datetime import datetime\n\ndef days_between(date1, date2):\n    # 请在此处编写代码\n    pass",
        },
        {
            "title": "Python map/filter/reduce函数式编程",
            "description": "编写一个函数process_numbers(numbers)，接收一个整数列表，使用filter过滤出偶数，使用map将每个偶数乘以3，最后使用reduce求和。返回最终结果。例如输入[1,2,3,4,5]返回18(因为2*3+4*3=18)。",
            "instructions": "使用filter、map和functools.reduce",
            "solution": "from functools import reduce\n\ndef process_numbers(numbers):\n    evens = filter(lambda x: x % 2 == 0, numbers)\n    tripled = map(lambda x: x * 3, evens)\n    return reduce(lambda a, b: a + b, tripled)",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "programming",
            "knowledge_point": "函数式编程",
            "time_estimate": 15,
            "exercise_type": "code",
            "code_template": "from functools import reduce\n\ndef process_numbers(numbers):\n    # 请在此处编写代码\n    pass",
        },
    ],

    # ============================================================
    # Linux基础命令 (原本3题 → 新增5题 = 合计8题)
    # ============================================================
    "Linux基础命令": [
        {
            "title": "find命令查找文件",
            "description": "在Linux中，要在当前目录及子目录下查找所有扩展名为.log且大于10MB的文件，应该使用什么命令？",
            "instructions": "选择正确的find命令",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "Shell",
            "module": "normal",
            "category": "linux",
            "knowledge_point": "find命令",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "sed命令文本替换",
            "description": "使用sed命令将文件config.txt中所有的'localhost'替换为'192.168.1.100'，并保存到新文件config_new.txt中。",
            "instructions": "编写sed替换命令",
            "solution": "sed 's/localhost/192.168.1.100/g' config.txt > config_new.txt",
            "difficulty": "intermediate",
            "language": "Shell",
            "module": "normal",
            "category": "linux",
            "knowledge_point": "sed命令",
            "time_estimate": 8,
            "exercise_type": "code",
            "code_template": "# 编写sed命令\n",
        },
        {
            "title": "ps与kill进程管理",
            "description": "如何查看所有正在运行的Python进程，并强制结束PID为12345的进程？",
            "instructions": "编写ps和kill命令",
            "solution": "ps aux | grep python\nkill -9 12345",
            "difficulty": "beginner",
            "language": "Shell",
            "module": "normal",
            "category": "linux",
            "knowledge_point": "进程管理",
            "time_estimate": 5,
            "exercise_type": "code",
            "code_template": "# 编写进程管理命令\n",
        },
        {
            "title": "awk命令数据提取",
            "description": "有一个access.log日志文件，每行格式为：IP 时间 请求URL 状态码。使用awk命令统计每个状态码的出现次数。",
            "instructions": "编写awk统计命令",
            "solution": "awk '{print $4}' access.log | sort | uniq -c | sort -rn",
            "difficulty": "advanced",
            "language": "Shell",
            "module": "normal",
            "category": "linux",
            "knowledge_point": "awk命令",
            "time_estimate": 12,
            "exercise_type": "code",
            "code_template": "# 编写awk命令\n",
        },
        {
            "title": "磁盘空间与内存查看",
            "description": "以下哪个命令用于查看Linux系统的磁盘使用情况和剩余空间？",
            "instructions": "选择正确的磁盘查看命令",
            "solution": "C",
            "difficulty": "beginner",
            "language": "Shell",
            "module": "normal",
            "category": "linux",
            "knowledge_point": "系统信息",
            "time_estimate": 3,
            "exercise_type": "choice",
        },
    ],

    # ============================================================
    # 计算机基础与网络知识 (原本3题 → 新增5题 = 合计8题)
    # ============================================================
    "计算机基础与网络知识": [
        {
            "title": "DNS解析过程",
            "description": "当在浏览器中输入www.example.com并回车时，DNS解析是第一步。以下关于DNS解析过程的说法，哪个是正确的？",
            "instructions": "选择关于DNS解析的正确说法",
            "solution": "A",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "DNS解析",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "进程与线程的区别",
            "description": "在多任务操作系统中，以下关于进程和线程的说法哪个是正确的？",
            "instructions": "选择关于进程与线程的正确说法",
            "solution": "D",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "进程与线程",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "TCP与UDP协议对比",
            "description": "TCP和UDP是传输层最重要的两个协议。以下关于它们的说法，哪个是正确的？",
            "instructions": "选择关于TCP和UDP的正确说法",
            "solution": "C",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "TCP/UDP",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "HTTPS与HTTP的区别",
            "description": "HTTPS在HTTP的基础上增加了SSL/TLS加密层。以下关于HTTPS的说法，哪个是正确的？",
            "instructions": "选择关于HTTPS的正确说法",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "HTTPS",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "Cookie与Session的区别",
            "description": "Cookie和Session都是Web开发中维持用户状态的技术。以下关于它们的说法哪个是正确的？",
            "instructions": "选择关于Cookie和Session的正确说法",
            "solution": "A",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "test_theory",
            "knowledge_point": "Cookie/Session",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
    ],

    # ============================================================
    # 接口测试基础 (原本4题 → 新增4题 = 合计8题)
    # ============================================================
    "接口测试基础": [
        {
            "title": "HTTP状态码5XX系列",
            "description": "HTTP 5XX系列状态码表示服务器端错误。以下哪个状态码表示服务不可用(Service Unavailable)？",
            "instructions": "选择正确的5XX状态码",
            "solution": "C",
            "difficulty": "beginner",
            "language": "中文",
            "module": "normal",
            "category": "api_test",
            "knowledge_point": "HTTP状态码",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "接口文档Swagger/OpenAPI",
            "description": "Swagger/OpenAPI是现代API开发的文档标准。以下关于Swagger的说法，哪个是正确的？",
            "instructions": "选择关于Swagger的正确说法",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "api_test",
            "knowledge_point": "API文档",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "接口测试数据驱动",
            "description": "使用Pytest对登录接口进行参数化测试，测试数据包括：(admin,123456,200)、(admin,'',400)、('',123456,400)、(admin,wrong,401)。请编写完整的参数化测试函数。",
            "instructions": "使用@pytest.mark.parametrize实现",
            "solution": "import pytest\n\n@pytest.mark.parametrize('username,password,expected_status', [\n    ('admin', '123456', 200),\n    ('admin', '', 400),\n    ('', '123456', 400),\n    ('admin', 'wrong', 401),\n])\ndef test_login(username, password, expected_status):\n    response = requests.post('/api/login', json={'username': username, 'password': password})\n    assert response.status_code == expected_status",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "api_test",
            "knowledge_point": "数据驱动测试",
            "time_estimate": 15,
            "exercise_type": "code",
            "code_template": "import pytest\n\n# 请编写参数化测试代码\n",
        },
        {
            "title": "接口响应时间测试",
            "description": "接口性能测试中，对同一接口进行多次请求，计算平均响应时间。以下Python代码实现了这个功能，其中response.elapsed.total_seconds()返回的是？",
            "instructions": "选择response.elapsed.total_seconds()的正确含义",
            "solution": "A",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "api_test",
            "knowledge_point": "响应时间",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
    ],

    # ============================================================
    # 测试用例设计方法 (原本4题 → 新增4题 = 合计8题)
    # ============================================================
    "测试用例设计方法": [
        {
            "title": "正交实验法实战",
            "description": "某系统有3个参数：浏览器(Chrome/Firefox/Edge)、操作系统(Windows/Mac/Linux)、语言(中文/英文)。使用正交实验法，至少需要多少个测试用例？",
            "instructions": "选择正交实验法的最少用例数",
            "solution": "D",
            "difficulty": "advanced",
            "language": "中文",
            "module": "normal",
            "category": "functional_test",
            "knowledge_point": "正交实验法",
            "time_estimate": 10,
            "exercise_type": "choice",
        },
        {
            "title": "判定表驱动法",
            "description": "一个登录功能有3个条件：用户名正确(Y/N)、密码正确(Y/N)、验证码正确(Y/N)。使用判定表驱动法，完整的判定表应该有多少条规则？",
            "instructions": "选择判定表的规则数量",
            "solution": "C",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "functional_test",
            "knowledge_point": "判定表",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "错误推测法的应用",
            "description": "错误推测法基于测试人员的经验和直觉。以下哪个测试场景最适合使用错误推测法？",
            "instructions": "选择最适合错误推测法的场景",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "functional_test",
            "knowledge_point": "错误推测法",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "综合运用：为计算器设计测试用例",
            "description": "为一个简单的四则运算计算器（支持+,-,*,/）设计测试用例。以下哪个测试场景覆盖了除数为零的边界条件？",
            "instructions": "选择覆盖除数为零的测试用例",
            "solution": "D",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "functional_test",
            "knowledge_point": "综合运用",
            "time_estimate": 10,
            "exercise_type": "choice",
        },
    ],

    # ============================================================
    # 其他路径各补充2-3题
    # ============================================================
    "测试计划编写与项目管理": [
        {
            "title": "测试策略与测试方法的选择",
            "description": "一个电商项目需要在2周内完成测试，以下哪种测试策略最合理？",
            "instructions": "选择最合理的测试策略",
            "solution": "B",
            "difficulty": "advanced",
            "language": "中文",
            "module": "normal",
            "category": "functional_test",
            "knowledge_point": "测试策略",
            "time_estimate": 10,
            "exercise_type": "choice",
        },
        {
            "title": "测试报告的核心指标",
            "description": "测试总结报告中，以下哪个指标最能反映版本的稳定性？",
            "instructions": "选择最能反映版本稳定性的指标",
            "solution": "C",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "functional_test",
            "knowledge_point": "测试报告",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
    ],

    "UI自动化测试 - Selenium": [
        {
            "title": "Selenium处理Alert弹窗",
            "description": "在Selenium中，以下哪个方法用于接受（点击确定）JavaScript Alert弹窗？",
            "instructions": "选择处理Alert的正确方法",
            "solution": "A",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "automation_test",
            "knowledge_point": "Alert处理",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "Selenium截图功能",
            "description": "使用Selenium对当前页面进行截图并保存为screenshot.png，应该使用什么方法？",
            "instructions": "编写Selenium截图代码",
            "solution": "driver.save_screenshot('screenshot.png')",
            "difficulty": "beginner",
            "language": "Python",
            "module": "normal",
            "category": "automation_test",
            "knowledge_point": "截图功能",
            "time_estimate": 5,
            "exercise_type": "code",
            "code_template": "# 编写Selenium截图代码\ndriver.",
        },
        {
            "title": "Selenium执行JavaScript",
            "description": "在Selenium中，使用execute_script执行JavaScript滚动到页面底部的代码是什么？",
            "instructions": "编写JS滚动代码",
            "solution": "driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "automation_test",
            "knowledge_point": "JS执行",
            "time_estimate": 8,
            "exercise_type": "code",
            "code_template": "# 编写JS滚动代码\ndriver.",
        },
    ],

    "接口自动化测试 - Requests+Pytest": [
        {
            "title": "Pytest conftest.py共享fixture",
            "description": "在Pytest中，conftest.py文件的作用是什么？",
            "instructions": "选择conftest.py的正确作用",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "automation_test",
            "knowledge_point": "conftest.py",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
        {
            "title": "Requests库Session保持登录状态",
            "description": "编写Python代码使用requests.Session()保持会话，先登录获取cookie，再使用同一session访问需要登录的接口。",
            "instructions": "使用Session保持登录状态",
            "solution": "import requests\n\nsession = requests.Session()\nsession.post('https://api.example.com/login', json={'username': 'admin', 'password': '123456'})\nresponse = session.get('https://api.example.com/user/profile')\nprint(response.json())",
            "difficulty": "intermediate",
            "language": "Python",
            "module": "normal",
            "category": "automation_test",
            "knowledge_point": "Session管理",
            "time_estimate": 12,
            "exercise_type": "code",
            "code_template": "import requests\n\n# 请编写代码\n",
        },
        {
            "title": "Pytest断言异常处理",
            "description": "编写一个Pytest测试函数，验证调用某个接口时如果网络超时会正确抛出requests.exceptions.Timeout异常。",
            "instructions": "使用pytest.raises断言异常",
            "solution": "import pytest\nimport requests\n\ndef test_timeout():\n    with pytest.raises(requests.exceptions.Timeout):\n        requests.get('https://api.example.com/slow', timeout=0.001)",
            "difficulty": "advanced",
            "language": "Python",
            "module": "normal",
            "category": "automation_test",
            "knowledge_point": "异常断言",
            "time_estimate": 12,
            "exercise_type": "code",
            "code_template": "import pytest\nimport requests\n\ndef test_timeout():\n    # 请编写代码\n    pass",
        },
    ],

    "性能测试 - JMeter与Locust": [
        {
            "title": "性能测试中的瓶颈分析方法",
            "description": "性能测试发现TPS不达标后，以下哪种分析顺序最合理？",
            "instructions": "选择最合理的瓶颈分析顺序",
            "solution": "C",
            "difficulty": "advanced",
            "language": "中文",
            "module": "normal",
            "category": "performance_test",
            "knowledge_point": "瓶颈分析",
            "time_estimate": 10,
            "exercise_type": "choice",
        },
        {
            "title": "JMeter中定时器的作用",
            "description": "在JMeter中，Constant Timer和Uniform Random Timer的作用是什么？",
            "instructions": "选择关于JMeter定时器的正确说法",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "performance_test",
            "knowledge_point": "JMeter定时器",
            "time_estimate": 5,
            "exercise_type": "choice",
        },
    ],

    "安全测试基础": [
        {
            "title": "文件上传漏洞测试",
            "description": "测试一个文件上传功能时，以下哪种测试方法最可能发现安全漏洞？",
            "instructions": "选择最佳的文件上传安全测试方法",
            "solution": "D",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "security_test",
            "knowledge_point": "文件上传安全",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
        {
            "title": "越权访问漏洞测试",
            "description": "水平越权和垂直越权是常见的Web安全漏洞。以下哪个场景属于垂直越权？",
            "instructions": "选择属于垂直越权的场景",
            "solution": "B",
            "difficulty": "intermediate",
            "language": "中文",
            "module": "normal",
            "category": "security_test",
            "knowledge_point": "越权漏洞",
            "time_estimate": 8,
            "exercise_type": "choice",
        },
    ],
}

# ================================================================
# 扩充主逻辑
# ================================================================


async def enrich_exercises():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        total_added = 0
        stats = {}

        for path_title, exercises_data in NEW_EXERCISES.items():
            stmt = select(LearningPath).where(LearningPath.title == path_title)
            result = await session.execute(stmt)
            path = result.scalar_one_or_none()

            if not path:
                print(f"  [SKIP] Learning path not found: {path_title}")
                continue

            added = 0
            for ex_data in exercises_data:
                ex_stmt = select(Exercise).where(
                    Exercise.title == ex_data["title"],
                    Exercise.learning_path_id == path.id
                )
                ex_result = await session.execute(ex_stmt)
                if ex_result.scalar_one_or_none():
                    continue
                exercise = Exercise(**ex_data, learning_path_id=path.id, is_public=True)
                session.add(exercise)
                added += 1

            if added > 0:
                path.exercise_count += added

            stats[path_title] = added
            total_added += added
            print(f"  [OK] '{path_title}': +{added} exercises (total now: {path.exercise_count})")

        await session.commit()

        print("\n" + "=" * 60)
        print(f"[DONE] Added {total_added} exercises across {len(stats)} learning paths")
        print("=" * 60)
        print("\nSummary by path:")
        for title, count in stats.items():
            print(f"  {title}: +{count}")


if __name__ == "__main__":
    print("=" * 60)
    print("[START] Enriching TestMaster exercises...")
    print("=" * 60)
    asyncio.run(enrich_exercises())