# -*- coding: utf-8 -*-
"""
持续集成与DevOps - 学习路径 ID=15
知识点: CI/CD概念、Jenkins配置与流水线、Docker容器化、Dockerfile编写、Kubernetes基础、
       Git工作流、GitHub Actions、自动化部署、基础设施即代码、监控与告警
题目数量: 80题 (选择题30 + 编程题25 + 简答题25)
难度分布: easy 30% + medium 50% + hard 20%
"""

EXERCISES = {
    "持续集成与DevOps": [
        # ==================== 选择题 (30题) ====================
        # --- CI/CD概念 (easy) ---
        {
            "title": "CI/CD中的CI代表什么？",
            "description": "CI/CD中的CI代表什么？\nA. Continuous Integration\nB. Continuous Improvement\nC. Central Intelligence\nD. Common Interface",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "CI/CD概念",
            "knowledge_point": "CI/CD基本概念",
            "solution": "A",
        },
        {
            "title": "持续集成的核心实践是：",
            "description": "持续集成的核心实践是：\nA. 每月合并一次代码\nB. 开发人员频繁地将代码集成到共享主干\nC. 只在发布时集成代码\nD. 每个开发者独立开发不合并",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "CI/CD概念",
            "knowledge_point": "持续集成原则",
            "solution": "B",
        },
        {
            "title": "以下哪项不是DevOps的核心价值观(CALMS)？",
            "description": "以下哪项不是DevOps的核心价值观(CALMS)？\nA. Culture（文化）\nB. Automation（自动化）\nC. Lean（精益）\nD. Documentation（文档）",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "CI/CD概念",
            "knowledge_point": "DevOps价值观",
            "solution": "D",
        },
        {
            "title": "持续交付(Continuous Delivery)和持续部署(Continuous Deployment)的区别是：",
            "description": "持续交付和持续部署的区别是：\nA. 没有区别\nB. 持续交付需要手动批准才能部署到生产环境，持续部署自动部署\nC. 持续部署需要手动批准，持续交付自动部署\nD. 持续交付只部署到测试环境",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "CI/CD概念",
            "knowledge_point": "持续交付vs持续部署",
            "solution": "B",
        },
        {
            "title": "DevOps中的\"左移\"(Shift Left)是指：",
            "description": "DevOps中的左移是指：\nA. 将测试和质量保障活动尽早融入开发流程\nB. 将所有工作移到左侧看板\nC. 减少开发人员数量\nD. 将部署推迟到后期",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "CI/CD概念",
            "knowledge_point": "DevOps左移",
            "solution": "A",
        },
        # --- Jenkins配置与流水线 (medium) ---
        {
            "title": "Jenkins中Pipeline脚本的两种语法是：",
            "description": "Jenkins中Pipeline脚本的两种语法是：\nA. Groovy和Java\nB. Scripted Pipeline和Declarative Pipeline\nC. XML和JSON\nD. YAML和TOML",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Jenkins配置与流水线",
            "knowledge_point": "Jenkins Pipeline语法",
            "solution": "B",
        },
        {
            "title": "Jenkins Declarative Pipeline中，哪个指令用于定义流水线的整体结构？",
            "description": "Jenkins Declarative Pipeline中，哪个指令用于定义流水线的整体结构？\nA. job\nB. pipeline\nC. workflow\nD. build",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Jenkins配置与流水线",
            "knowledge_point": "Declarative Pipeline",
            "solution": "B",
        },
        {
            "title": "Jenkins中用于定时触发构建的触发器是：",
            "description": "Jenkins中用于定时触发构建的触发器是：\nA. webhook\nB. pollSCM\nC. cron\nD. trigger",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Jenkins配置与流水线",
            "knowledge_point": "Jenkins触发器",
            "solution": "C",
        },
        {
            "title": "Jenkins Pipeline中，post部分的always块的作用是：",
            "description": "Jenkins Pipeline中post部分的always块的作用是：\nA. 只在成功时执行\nB. 只在失败时执行\nC. 无论构建结果如何都会执行\nD. 只在取消时执行",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Jenkins配置与流水线",
            "knowledge_point": "Jenkins post指令",
            "solution": "C",
        },
        {
            "title": "Jenkinsfile应该放在项目的什么位置？",
            "description": "Jenkinsfile应该放在项目的什么位置？\nA. 项目根目录\nB. src目录\nC. docs目录\nD. 可以放在任意位置，通过配置指定",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Jenkins配置与流水线",
            "knowledge_point": "Jenkinsfile位置",
            "solution": "A",
        },
        # --- Docker容器化 (medium) ---
        {
            "title": "Docker容器和虚拟机的主要区别是：",
            "description": "Docker容器和虚拟机的主要区别是：\nA. 没有区别\nB. 容器共享宿主机内核，虚拟机有独立的操作系统\nC. 虚拟机更轻量\nD. 容器需要完整的操作系统",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Docker容器化",
            "knowledge_point": "容器vs虚拟机",
            "solution": "B",
        },
        {
            "title": "Docker镜像的分层存储(layer)的好处是：",
            "description": "Docker镜像的分层存储的好处是：\nA. 增加安全性\nB. 提高网络速度\nC. 共享公共层，节省存储空间和加速构建\nD. 减少CPU使用",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Docker容器化",
            "knowledge_point": "Docker镜像分层",
            "solution": "C",
        },
        {
            "title": "docker-compose.yml的主要作用是：",
            "description": "docker-compose.yml的主要作用是：\nA. 构建单个镜像\nB. 定义和运行多容器Docker应用\nC. 管理Docker网络\nD. 监控容器性能",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Docker容器化",
            "knowledge_point": "Docker Compose",
            "solution": "B",
        },
        {
            "title": "以下哪个Docker命令用于查看运行中的容器？",
            "description": "以下哪个Docker命令用于查看运行中的容器？\nA. docker images\nB. docker ps\nC. docker logs\nD. docker inspect",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Docker容器化",
            "knowledge_point": "Docker基本命令",
            "solution": "B",
        },
        # --- Dockerfile编写 (hard) ---
        {
            "title": "Dockerfile中CMD和ENTRYPOINT的区别是：",
            "description": "Dockerfile中CMD和ENTRYPOINT的区别是：\nA. 没有区别\nB. CMD可被docker run参数覆盖，ENTRYPOINT不会被轻易覆盖\nC. ENTRYPOINT可被覆盖，CMD不会\nD. CMD用于Linux，ENTRYPOINT用于Windows",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "Dockerfile编写",
            "knowledge_point": "CMD vs ENTRYPOINT",
            "solution": "B",
        },
        {
            "title": "Dockerfile中使用多阶段构建(multi-stage build)的主要目的是：",
            "description": "Dockerfile中使用多阶段构建的主要目的是：\nA. 增加构建速度\nB. 减小最终镜像体积\nC. 提高安全性\nD. 增加功能",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "Dockerfile编写",
            "knowledge_point": "多阶段构建",
            "solution": "B",
        },
        {
            "title": "Dockerfile中COPY和ADD指令的区别是：",
            "description": "Dockerfile中COPY和ADD指令的区别是：\nA. 没有区别\nB. ADD支持URL和自动解压tar文件，COPY只做简单的文件复制\nC. COPY功能更强\nD. ADD已被弃用",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Dockerfile编写",
            "knowledge_point": "COPY vs ADD",
            "solution": "B",
        },
        # --- Kubernetes基础 (hard) ---
        {
            "title": "Kubernetes中最小的部署单元是：",
            "description": "Kubernetes中最小的部署单元是：\nA. Container\nB. Pod\nC. Service\nD. Node",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Kubernetes基础",
            "knowledge_point": "K8s核心概念",
            "solution": "B",
        },
        {
            "title": "Kubernetes中Service的作用是：",
            "description": "Kubernetes中Service的作用是：\nA. 存储数据\nB. 为Pod提供稳定的网络访问入口\nC. 管理容器镜像\nD. 监控集群状态",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Kubernetes基础",
            "knowledge_point": "K8s Service",
            "solution": "B",
        },
        {
            "title": "Kubernetes中Deployment和ReplicaSet的关系是：",
            "description": "Kubernetes中Deployment和ReplicaSet的关系是：\nA. 没有关系\nB. Deployment管理ReplicaSet，ReplicaSet管理Pod\nC. ReplicaSet管理Deployment\nD. 两者功能完全相同",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "Kubernetes基础",
            "knowledge_point": "Deployment与ReplicaSet",
            "solution": "B",
        },
        # --- Git工作流 (medium) ---
        {
            "title": "Git Flow工作流中，feature分支通常从哪个分支创建？",
            "description": "Git Flow工作流中，feature分支通常从哪个分支创建？\nA. main\nB. develop\nC. release\nD. hotfix",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Git工作流",
            "knowledge_point": "Git Flow",
            "solution": "B",
        },
        {
            "title": "Trunk-Based Development的核心思想是：",
            "description": "Trunk-Based Development的核心思想是：\nA. 使用多个长期分支\nB. 所有开发者在同一个主干分支上频繁提交小的变更\nC. 每个功能一个独立分支\nD. 不使用版本控制",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "Git工作流",
            "knowledge_point": "主干开发",
            "solution": "B",
        },
        # --- GitHub Actions (medium) ---
        {
            "title": "GitHub Actions的配置文件存放在项目的哪个目录？",
            "description": "GitHub Actions的配置文件存放在项目的哪个目录？\nA. .github/workflows/\nB. .actions/\nC. .ci/\nD. .pipelines/",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "GitHub Actions",
            "knowledge_point": "GitHub Actions配置",
            "solution": "A",
        },
        {
            "title": "GitHub Actions中，workflow的触发事件关键字是：",
            "description": "GitHub Actions中，workflow的触发事件关键字是：\nA. trigger\nB. on\nC. when\nD. event",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "GitHub Actions",
            "knowledge_point": "GitHub Actions触发",
            "solution": "B",
        },
        # --- 基础设施即代码 (hard) ---
        {
            "title": "Terraform属于哪种类型的IaC工具？",
            "description": "Terraform属于哪种类型的IaC工具？\nA. 配置管理工具\nB. 基础设施编排工具\nC. 容器编排工具\nD. 监控工具",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "基础设施即代码",
            "knowledge_point": "IaC工具分类",
            "solution": "B",
        },
        {
            "title": "Infrastructure as Code(IaC)的核心优势是：",
            "description": "Infrastructure as Code的核心优势是：\nA. 不需要网络\nB. 基础设施可版本化、可重复、可审计\nC. 降低硬件成本\nD. 不需要运维人员",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "基础设施即代码",
            "knowledge_point": "IaC优势",
            "solution": "B",
        },
        # --- 监控与告警 (medium) ---
        {
            "title": "Prometheus监控系统的数据采集模型是：",
            "description": "Prometheus监控系统的数据采集模型是：\nA. Push模型\nB. Pull模型\nC. 事件驱动模型\nD. 批处理模型",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "Prometheus架构",
            "solution": "B",
        },
        {
            "title": "以下哪个工具常用于日志聚合和分析？",
            "description": "以下哪个工具常用于日志聚合和分析？\nA. Grafana\nB. ELK Stack (Elasticsearch + Logstash + Kibana)\nC. Ansible\nD. Nagios",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "日志管理",
            "solution": "B",
        },
        {
            "title": "告警风暴(Alert Storm)的最佳应对策略是：",
            "description": "告警风暴的最佳应对策略是：\nA. 关闭所有告警\nB. 设置告警聚合、抑制和分级策略\nC. 增加更多告警规则\nD. 只保留紧急告警",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "监控与告警",
            "knowledge_point": "告警管理",
            "solution": "B",
        },
        {
            "title": "可观测性(Observability)的三大支柱是：",
            "description": "可观测性的三大支柱是：\nA. CPU、内存、磁盘\nB. Metrics(指标)、Logs(日志)、Traces(链路追踪)\nC. 开发、测试、运维\nD. 网络、存储、计算",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "可观测性",
            "solution": "B",
        },

        # ==================== 编程题 (25题) ====================
        # --- CI/CD脚本 (easy) ---
        {
            "title": "编写函数解析Jenkins构建状态",
            "description": "编写Python函数parse_jenkins_status(status_code)，将Jenkins构建状态码转换为可读状态。\n\n状态码映射：\n- 0: SUCCESS\n- 1: UNSTABLE\n- 2: FAILURE\n- 3: NOT_BUILT\n- 4: ABORTED\n\n其他状态码返回 UNKNOWN",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "CI/CD脚本",
            "knowledge_point": "Jenkins状态解析",
            "code_template": "def parse_jenkins_status(status_code):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "0", "expected": "SUCCESS"}, {"input": "2", "expected": "FAILURE"}, {"input": "99", "expected": "UNKNOWN"}]',
            "solution": "def parse_jenkins_status(status_code):\n    mapping = {0: 'SUCCESS', 1: 'UNSTABLE', 2: 'FAILURE', 3: 'NOT_BUILT', 4: 'ABORTED'}\n    return mapping.get(status_code, 'UNKNOWN')",
            "hint": "使用字典映射状态码",
        },
        {
            "title": "编写函数生成Jenkins Pipeline stage",
            "description": "编写Python函数generate_pipeline_stage(name, steps)，生成Jenkins Declarative Pipeline的stage配置字符串。\n\n参数：\n- name: stage名称\n- steps: 步骤列表\n\n返回格式化的stage字符串",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "CI/CD脚本",
            "knowledge_point": "Pipeline生成",
            "code_template": "def generate_pipeline_stage(name, steps):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"Build\", [\"echo Building...\", \"make all\"]", "expected": "包含stage(Build)和steps的字符串"}]',
            "solution": "def generate_pipeline_stage(name, steps):\n    lines = [f\"stage('{name}') {{\"]\n    lines.append(\"    steps {\")\n    for step in steps:\n        lines.append(f\"        sh '{step}'\")\n    lines.append(\"    }\")\n    lines.append(\"}\")\n    return '\\n'.join(lines)",
            "hint": "使用字符串拼接生成Pipeline配置",
        },
        # --- Docker相关 (medium) ---
        {
            "title": "编写函数解析Docker镜像标签",
            "description": "编写Python函数parse_docker_image(image_str)，解析Docker镜像字符串。\n\n格式: registry/repository:tag\n\n返回字典：\n- registry: 仓库地址（默认docker.io）\n- repository: 仓库名\n- tag: 标签（默认latest）\n\n示例:\n- nginx -> {registry: docker.io, repository: nginx, tag: latest}\n- myregistry.com/myapp:v1.0 -> {registry: myregistry.com, repository: myapp, tag: v1.0}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Docker脚本",
            "knowledge_point": "Docker镜像标签解析",
            "code_template": "def parse_docker_image(image_str):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"nginx\"", "expected": "{registry: docker.io, repository: nginx, tag: latest}"}, {"input": "\"myregistry.com/myapp:v1.0\"", "expected": "{registry: myregistry.com, repository: myapp, tag: v1.0}"}]',
            "solution": "def parse_docker_image(image_str):\n    result = {'registry': 'docker.io', 'repository': '', 'tag': 'latest'}\n    parts = image_str.split('/')\n    if len(parts) > 1 and ('.' in parts[0] or ':' in parts[0]):\n        result['registry'] = parts[0]\n        image_str = '/'.join(parts[1:])\n    if ':' in image_str:\n        repo, tag = image_str.rsplit(':', 1)\n        result['repository'] = repo\n        result['tag'] = tag\n    else:\n        result['repository'] = image_str\n    return result",
            "hint": "注意处理不同格式的镜像字符串，使用rsplit分割tag",
        },
        {
            "title": "编写函数验证Docker Compose配置",
            "description": "编写Python函数validate_compose_config(config)，验证Docker Compose配置的基本字段。\n\nconfig为字典，检查：\n- version字段存在且为字符串\n- services字段存在且为字典\n- 每个service必须有image或build字段\n\n返回(is_valid, errors)元组",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Docker脚本",
            "knowledge_point": "Docker Compose验证",
            "code_template": "def validate_compose_config(config):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"version\": \"3\", \"services\": {\"web\": {\"image\": \"nginx\"}}}", "expected": "(True, [])"}]',
            "solution": "def validate_compose_config(config):\n    errors = []\n    if 'version' not in config:\n        errors.append('missing version')\n    elif not isinstance(config['version'], str):\n        errors.append('version must be string')\n    if 'services' not in config:\n        errors.append('missing services')\n    elif not isinstance(config['services'], dict):\n        errors.append('services must be dict')\n    else:\n        for name, svc in config['services'].items():\n            if not isinstance(svc, dict):\n                errors.append(f'service {name} must be dict')\n            elif 'image' not in svc and 'build' not in svc:\n                errors.append(f'service {name} must have image or build')\n    return (len(errors) == 0, errors)",
            "hint": "逐层检查配置结构",
        },
        {
            "title": "编写函数生成Dockerfile",
            "description": "编写Python函数generate_dockerfile(base_image, workdir, copy_files, run_commands, expose_port, cmd)，\n生成Dockerfile内容字符串。\n\n所有参数都有默认值，返回完整的Dockerfile字符串",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Dockerfile编写",
            "knowledge_point": "Dockerfile生成",
            "code_template": "def generate_dockerfile(base_image, workdir, copy_files, run_commands, expose_port, cmd):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"python:3.9\", \"/app\", [\"requirements.txt\", \".\"], [\"pip install -r requirements.txt\"], 8000, \"python app.py\"", "expected": "包含FROM、WORKDIR、COPY、RUN、EXPOSE、CMD的Dockerfile字符串"}]',
            "solution": "def generate_dockerfile(base_image, workdir, copy_files, run_commands, expose_port, cmd):\n    lines = [f'FROM {base_image}']\n    if workdir:\n        lines.append(f'WORKDIR {workdir}')\n    for f in copy_files:\n        lines.append(f'COPY {f} .')\n    for cmd_item in run_commands:\n        lines.append(f'RUN {cmd_item}')\n    if expose_port:\n        lines.append(f'EXPOSE {expose_port}')\n    if cmd:\n        lines.append(f'CMD [\"{cmd}\"]')\n    return '\\n'.join(lines)",
            "hint": "按Dockerfile指令顺序拼接字符串",
        },
        {
            "title": "编写函数解析Docker容器资源使用",
            "description": "编写Python函数parse_container_stats(stats_str)，解析docker stats输出的资源使用信息。\n\nstats_str格式: \"container_name cpu:5.2% memory:256MB/1GB\"\n\n返回字典：\n- name: 容器名\n- cpu_percent: CPU使用率(浮点数)\n- memory_used: 内存使用量(字符串)\n- memory_limit: 内存限制(字符串)",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Docker脚本",
            "knowledge_point": "Docker资源监控",
            "code_template": "def parse_container_stats(stats_str):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"web-server cpu:5.2% memory:256MB/1GB\"", "expected": "{name: web-server, cpu_percent: 5.2, memory_used: 256MB, memory_limit: 1GB}"}]',
            "solution": "def parse_container_stats(stats_str):\n    parts = stats_str.split()\n    name = parts[0]\n    cpu_str = parts[1].replace('cpu:', '').replace('%', '')\n    mem_parts = parts[2].replace('memory:', '').split('/')\n    return {\n        'name': name,\n        'cpu_percent': float(cpu_str),\n        'memory_used': mem_parts[0],\n        'memory_limit': mem_parts[1]\n    }",
            "hint": "使用split和replace解析固定格式的字符串",
        },
        # --- Kubernetes相关 (hard) ---
        {
            "title": "编写函数解析Kubernetes资源YAML",
            "description": "编写Python函数parse_k8s_resource(yaml_dict)，解析简化的K8s资源配置字典。\n\nyaml_dict包含kind, metadata.name, metadata.namespace等字段\n\n返回字典：\n- kind: 资源类型\n- name: 资源名称\n- namespace: 命名空间（默认default）\n- full_name: namespace/name格式",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "Kubernetes脚本",
            "knowledge_point": "K8s资源解析",
            "code_template": "def parse_k8s_resource(yaml_dict):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"kind\": \"Deployment\", \"metadata\": {\"name\": \"nginx\", \"namespace\": \"prod\"}}", "expected": "{kind: Deployment, name: nginx, namespace: prod, full_name: prod/nginx}"}]',
            "solution": "def parse_k8s_resource(yaml_dict):\n    kind = yaml_dict.get('kind', 'Unknown')\n    metadata = yaml_dict.get('metadata', {})\n    name = metadata.get('name', '')\n    namespace = metadata.get('namespace', 'default')\n    return {\n        'kind': kind,\n        'name': name,\n        'namespace': namespace,\n        'full_name': f'{namespace}/{name}'\n    }",
            "hint": "使用get方法安全访问嵌套字典",
        },
        {
            "title": "编写函数生成K8s Deployment配置",
            "description": "编写Python函数generate_deployment(name, image, replicas, port, env_vars)，\n生成简化的K8s Deployment配置字典。\n\nenv_vars为字典，键值对作为环境变量\n返回嵌套字典结构",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "Kubernetes脚本",
            "knowledge_point": "K8s配置生成",
            "code_template": "def generate_deployment(name, image, replicas, port, env_vars):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"nginx\", \"nginx:latest\", 3, 80, {\"ENV\": \"prod\"}\"", "expected": "包含apiVersion、kind、metadata、spec的完整Deployment配置"}]',
            "solution": "def generate_deployment(name, image, replicas, port, env_vars):\n    env_list = [{'name': k, 'value': v} for k, v in env_vars.items()]\n    return {\n        'apiVersion': 'apps/v1',\n        'kind': 'Deployment',\n        'metadata': {'name': name},\n        'spec': {\n            'replicas': replicas,\n            'selector': {'matchLabels': {'app': name}},\n            'template': {\n                'metadata': {'labels': {'app': name}},\n                'spec': {\n                    'containers': [{\n                        'name': name,\n                        'image': image,\n                        'ports': [{'containerPort': port}],\n                        'env': env_list\n                    }]\n                }\n            }\n        }\n    }",
            "hint": "按K8s Deployment的YAML结构构建嵌套字典",
        },
        # --- GitHub Actions相关 (medium) ---
        {
            "title": "编写函数生成GitHub Actions workflow",
            "description": "编写Python函数generate_workflow(name, trigger, jobs)，\n生成简化的GitHub Actions workflow配置字典。\n\n- name: workflow名称\n- trigger: 触发事件（如push, pull_request）\n- jobs: 字典，每个job包含runs_on和steps列表\n\n返回字典",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "GitHub Actions",
            "knowledge_point": "Workflow生成",
            "code_template": "def generate_workflow(name, trigger, jobs):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"CI\", \"push\", {\"build\": {\"runs_on\": \"ubuntu-latest\", \"steps\": [\"checkout\", \"test\"]}}", "expected": "包含name、on、jobs的workflow配置字典"}]',
            "solution": "def generate_workflow(name, trigger, jobs):\n    workflow = {'name': name, 'on': trigger, 'jobs': {}}\n    for job_name, job_config in jobs.items():\n        steps = [{'run': s} if isinstance(s, str) else s for s in job_config.get('steps', [])]\n        workflow['jobs'][job_name] = {\n            'runs-on': job_config.get('runs_on', 'ubuntu-latest'),\n            'steps': steps\n        }\n    return workflow",
            "hint": "构建嵌套字典结构，注意runs-on的连字符格式",
        },
        {
            "title": "编写函数解析GitHub Actions日志",
            "description": "编写Python函数parse_actions_log(log_text)，解析GitHub Actions的执行日志。\n\nlog_text格式示例：\n\"::group::Build\\nBuilding...\\n::endgroup::\\n::group::Test\\nTesting...\\n::endgroup::\"\n\n返回字典列表，每个包含group名和内容",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "GitHub Actions",
            "knowledge_point": "Actions日志解析",
            "code_template": "def parse_actions_log(log_text):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"::group::Build\\nBuilding...\\n::endgroup::\"", "expected": "[{group: Build, content: Building...}]"}]',
            "solution": "def parse_actions_log(log_text):\n    result = []\n    current_group = None\n    current_content = []\n    for line in log_text.split('\\n'):\n        if line.startswith('::group::'):\n            current_group = line.replace('::group::', '')\n            current_content = []\n        elif line == '::endgroup::':\n            if current_group:\n                result.append({'group': current_group, 'content': '\\n'.join(current_content)})\n                current_group = None\n        elif current_group is not None:\n            current_content.append(line)\n    return result",
            "hint": "按行解析，使用状态标记当前是否在group内",
        },
        # --- 基础设施即代码 (hard) ---
        {
            "title": "编写函数解析Terraform变量",
            "description": "编写Python函数parse_terraform_vars(vars_dict)，解析Terraform变量定义。\n\nvars_dict中每个键值对代表一个变量\n返回字典列表，每个包含name, type(推断), default_value\n\n类型推断规则：\n- str -> string\n- int -> number\n- bool -> bool\n- list -> list\n- dict -> map",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "基础设施即代码",
            "knowledge_point": "Terraform变量解析",
            "code_template": "def parse_terraform_vars(vars_dict):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"region\": \"us-east-1\", \"instance_count\": 3, \"enable_ssl\": true}", "expected": "包含3个变量定义的列表，类型分别为string, number, bool"}]',
            "solution": "def parse_terraform_vars(vars_dict):\n    type_map = {str: 'string', int: 'number', float: 'number', bool: 'bool', list: 'list', dict: 'map'}\n    result = []\n    for name, value in vars_dict.items():\n        var_type = type_map.get(type(value), 'string')\n        result.append({'name': name, 'type': var_type, 'default_value': value})\n    return result",
            "hint": "使用type()函数和类型映射字典",
        },
        {
            "title": "编写函数验证Ansible Playbook",
            "description": "编写Python函数validate_playbook(playbook)，验证Ansible Playbook配置。\n\nplaybook为字典列表，每个字典必须有：\n- hosts字段（字符串）\n- tasks字段（列表）\n每个task必须有name字段\n\n返回(is_valid, errors)元组",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "基础设施即代码",
            "knowledge_point": "Ansible验证",
            "code_template": "def validate_playbook(playbook):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"hosts\": \"webservers\", \"tasks\": [{\"name\": \"Install nginx\", \"apt\": {\"name\": \"nginx\"}}]}]", "expected": "(True, [])"}]',
            "solution": "def validate_playbook(playbook):\n    errors = []\n    if not isinstance(playbook, list):\n        return (False, ['playbook must be a list'])\n    for i, play in enumerate(playbook):\n        if not isinstance(play, dict):\n            errors.append(f'play {i} must be dict')\n            continue\n        if 'hosts' not in play:\n            errors.append(f'play {i} missing hosts')\n        if 'tasks' not in play:\n            errors.append(f'play {i} missing tasks')\n        elif isinstance(play['tasks'], list):\n            for j, task in enumerate(play['tasks']):\n                if not isinstance(task, dict) or 'name' not in task:\n                    errors.append(f'play {i} task {j} missing name')\n    return (len(errors) == 0, errors)",
            "hint": "逐层验证嵌套结构",
        },
        # --- 监控与告警 (medium) ---
        {
            "title": "编写函数解析Prometheus指标",
            "description": "编写Python函数parse_prometheus_metric(metric_text)，解析Prometheus格式的指标文本。\n\nmetric_text格式示例：\n\"http_requests_total{method=GET,status=200} 1234\"\n\n返回字典：\n- name: 指标名\n- labels: 标签字典\n- value: 数值",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "Prometheus指标解析",
            "code_template": "def parse_prometheus_metric(metric_text):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"http_requests_total{method=GET,status=200} 1234\"", "expected": "{name: http_requests_total, labels: {method: GET, status: 200}, value: 1234}"}]',
            "solution": "def parse_prometheus_metric(metric_text):\n    name_part, value_part = metric_text.rsplit(' ', 1)\n    value = float(value_part)\n    if '{' in name_part:\n        name, labels_str = name_part.split('{', 1)\n        labels_str = labels_str.rstrip('}')\n        labels = {}\n        for pair in labels_str.split(','):\n            k, v = pair.split('=')\n            labels[k.strip()] = v.strip()\n    else:\n        name = name_part\n        labels = {}\n    return {'name': name, 'labels': labels, 'value': value}",
            "hint": "先分割名称和值，再解析标签部分",
        },
        {
            "title": "编写函数生成告警规则",
            "description": "编写Python函数generate_alert_rule(name, metric, threshold, duration, severity)，\n生成Prometheus告警规则字典。\n\n参数：\n- name: 告警名称\n- metric: 指标名\n- threshold: 阈值\n- duration: 持续时间（如5m）\n- severity: 严重级别\n\n返回告警规则字典",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "Prometheus告警规则",
            "code_template": "def generate_alert_rule(name, metric, threshold, duration, severity):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"HighCPU\", \"cpu_usage\", 90, \"5m\", \"critical\"", "expected": "包含alert、for、labels、annotations的告警规则字典"}]',
            "solution": "def generate_alert_rule(name, metric, threshold, duration, severity):\n    return {\n        'alert': name,\n        'expr': f'{metric} > {threshold}',\n        'for': duration,\n        'labels': {'severity': severity},\n        'annotations': {\n            'summary': f'{name} alert triggered',\n            'description': f'{metric} exceeds {threshold} for {duration}'\n        }\n    }",
            "hint": "按Prometheus告警规则格式构建字典",
        },
        {
            "title": "编写函数计算服务SLA",
            "description": "编写Python函数calculate_sla(total_minutes, downtime_minutes)，计算服务可用性SLA。\n\n返回字典：\n- sla_percent: SLA百分比（保留4位小数）\n- downtime_per_year: 年度允许宕机时间（天、小时、分钟）\n- tier: SLA等级（99.99%以上为premium，99.9%以上为standard，其他为basic）",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "SLA计算",
            "code_template": "def calculate_sla(total_minutes, downtime_minutes):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "525600, 52", "expected": "sla_percent约99.99%, tier=premium"}]',
            "solution": "def calculate_sla(total_minutes, downtime_minutes):\n    sla = round((1 - downtime_minutes / total_minutes) * 100, 4)\n    minutes_per_year = 525600\n    allowed_downtime = minutes_per_year * (1 - sla / 100)\n    days = int(allowed_downtime // 1440)\n    hours = int((allowed_downtime % 1440) // 60)\n    mins = round(allowed_downtime % 60)\n    if sla >= 99.99:\n        tier = 'premium'\n    elif sla >= 99.9:\n        tier = 'standard'\n    else:\n        tier = 'basic'\n    return {\n        'sla_percent': sla,\n        'downtime_per_year': f'{days}d {hours}h {mins}m',\n        'tier': tier\n    }",
            "hint": "使用数学运算计算SLA百分比和对应等级",
        },
        # --- Git与版本控制 (easy) ---
        {
            "title": "编写函数比较两个版本号",
            "description": "编写Python函数compare_versions(v1, v2)，比较两个语义化版本号。\n\n版本号格式: major.minor.patch\n返回值：\n- 1: v1 > v2\n- -1: v1 < v2\n- 0: v1 == v2\n\n示例:\n- compare_versions(1.2.3, 1.2.4) -> -1\n- compare_versions(2.0.0, 1.9.9) -> 1\n- compare_versions(1.0.0, 1.0.0) -> 0",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "Git工作流",
            "knowledge_point": "版本号比较",
            "code_template": "def compare_versions(v1, v2):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"1.2.3\", \"1.2.4\"", "expected": "-1"}, {"input": "\"2.0.0\", \"1.9.9\"", "expected": "1"}, {"input": "\"1.0.0\", \"1.0.0\"", "expected": "0"}]',
            "solution": "def compare_versions(v1, v2):\n    parts1 = [int(x) for x in v1.split('.')]\n    parts2 = [int(x) for x in v2.split('.')]\n    for a, b in zip(parts1, parts2):\n        if a > b:\n            return 1\n        elif a < b:\n            return -1\n    return 0",
            "hint": "将版本号分割为数字列表，逐段比较",
        },
        {
            "title": "编写函数解析Git commit信息",
            "description": "编写Python函数parse_git_log(log_line)，解析一行git log输出。\n\n格式: hash|author|date|message\n示例: abc1234|John|2024-01-15|feat: add login\n\n返回字典包含hash, author, date, message, type(feat/fix/docs等)",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "Git工作流",
            "knowledge_point": "Git log解析",
            "code_template": "def parse_git_log(log_line):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"abc1234|John|2024-01-15|feat: add login\"", "expected": "{hash: abc1234, author: John, type: feat, message: feat: add login}"}]',
            "solution": "def parse_git_log(log_line):\n    parts = log_line.split('|')\n    message = parts[3]\n    commit_type = message.split(':')[0] if ':' in message else 'other'\n    return {\n        'hash': parts[0],\n        'author': parts[1],\n        'date': parts[2],\n        'message': message,\n        'type': commit_type\n    }",
            "hint": "使用split分割字段，从message中提取type",
        },
        {
            "title": "编写函数验证分支命名规范",
            "description": "编写Python函数validate_branch_name(branch_name)，验证Git分支命名是否符合规范。\n\n规范：\n- 以feature/、bugfix/、hotfix/、release/开头\n- 名称只包含小写字母、数字、连字符\n- 不以连字符开头或结尾\n\n返回(is_valid, reason)元组",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "Git工作流",
            "knowledge_point": "分支命名规范",
            "code_template": "def validate_branch_name(branch_name):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"feature/user-login\"", "expected": "(True, valid)"}, {"input": "\"dev-feature\"", "expected": "(False, invalid prefix)"}]',
            "solution": "def validate_branch_name(branch_name):\n    import re\n    valid_prefixes = ('feature/', 'bugfix/', 'hotfix/', 'release/')\n    if not branch_name.startswith(valid_prefixes):\n        return (False, 'invalid prefix')\n    name = branch_name.split('/', 1)[1]\n    if not name:\n        return (False, 'empty name after prefix')\n    if name.startswith('-') or name.endswith('-'):\n        return (False, 'cannot start or end with hyphen')\n    if not re.match(r'^[a-z0-9-]+$', name):\n        return (False, 'contains invalid characters')\n    return (True, 'valid')",
            "hint": "使用正则表达式验证命名规则",
        },
        # --- 自动化部署 (medium) ---
        {
            "title": "编写函数生成部署配置",
            "description": "编写Python函数generate_deploy_config(app_name, env, version, replicas, port)，\n生成部署配置字典。\n\nenv支持: development, staging, production\n不同环境有不同的默认配置\n\n返回配置字典",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "自动化部署",
            "knowledge_point": "部署配置生成",
            "code_template": "def generate_deploy_config(app_name, env, version, replicas, port):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"myapp\", \"production\", \"v1.0.0\", 3, 8080\"", "expected": "包含app名称、环境、版本、副本数等的配置字典"}]',
            "solution": "def generate_deploy_config(app_name, env, version, replicas, port):\n    env_defaults = {\n        'development': {'debug': True, 'log_level': 'debug'},\n        'staging': {'debug': False, 'log_level': 'info'},\n        'production': {'debug': False, 'log_level': 'warning'}\n    }\n    defaults = env_defaults.get(env, env_defaults['development'])\n    return {\n        'app_name': app_name,\n        'environment': env,\n        'version': version,\n        'replicas': replicas,\n        'port': port,\n        'debug': defaults['debug'],\n        'log_level': defaults['log_level'],\n        'health_check': f'http://localhost:{port}/health'\n    }",
            "hint": "使用字典存储不同环境的默认配置",
        },
        {
            "title": "编写函数实现蓝绿部署状态检查",
            "description": "编写Python函数check_blue_green_status(blue_status, green_status, active)，\n检查蓝绿部署状态。\n\n参数：\n- blue_status: blue环境状态(healthy/unhealthy)\n- green_status: green环境状态\n- active: 当前活跃环境(blue/green)\n\n返回字典包含current, standby, can_switch, recommendation",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "自动化部署",
            "knowledge_point": "蓝绿部署",
            "code_template": "def check_blue_green_status(blue_status, green_status, active):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"healthy\", \"healthy\", \"blue\"", "expected": "{current: blue, can_switch: true, recommendation: safe to switch}"}]',
            "solution": "def check_blue_green_status(blue_status, green_status, active):\n    standby = 'green' if active == 'blue' else 'blue'\n    standby_status = green_status if active == 'blue' else blue_status\n    can_switch = standby_status == 'healthy'\n    if can_switch:\n        recommendation = 'safe to switch'\n    else:\n        recommendation = f'fix {standby} environment first'\n    return {\n        'current': active,\n        'standby': standby,\n        'can_switch': can_switch,\n        'recommendation': recommendation\n    }",
            "hint": "根据当前活跃环境判断待机环境和切换条件",
        },
        # --- 自动化部署补充 (medium) ---
        {
            "title": "编写函数解析健康检查响应",
            "description": "编写Python函数parse_health_check(response)，解析应用健康检查的返回结果。\n\nresponse为字典，包含：\n- status: UP/DOWN\n- components: 各组件状态字典\n- uptime: 运行时间(秒)\n\n返回字典：\n- healthy: 是否健康(bool)\n- components_count: 组件总数\n- unhealthy_components: 不健康组件列表\n- uptime_hours: 运行时间(小时，保留1位小数)",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "自动化部署",
            "knowledge_point": "健康检查解析",
            "code_template": "def parse_health_check(response):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"status\": \"UP\", \"components\": {\"db\": \"UP\", \"cache\": \"DOWN\"}, \"uptime\": 3600}", "expected": "{healthy: True, unhealthy_components: [cache], uptime_hours: 1.0}"}]',
            "solution": "def parse_health_check(response):\n    components = response.get('components', {})\n    unhealthy = [k for k, v in components.items() if v != 'UP']\n    return {\n        'healthy': response.get('status') == 'UP' and len(unhealthy) == 0,\n        'components_count': len(components),\n        'unhealthy_components': unhealthy,\n        'uptime_hours': round(response.get('uptime', 0) / 3600, 1)\n    }",
            "hint": "使用列表推导式筛选不健康组件",
        },
        {
            "title": "编写函数生成环境变量配置",
            "description": "编写Python函数generate_env_config(app_name, env, custom_vars)，\n生成应用的环境变量配置字典。\n\n自动包含的变量：\n- APP_NAME\n- APP_ENV\n- LOG_LEVEL(debug=DEBUG, staging=INFO, production=WARNING)\n- NODE_ENV(development/production)\n\ncustom_vars会合并覆盖自动变量\n返回完整配置字典",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "自动化部署",
            "knowledge_point": "环境变量配置",
            "code_template": "def generate_env_config(app_name, env, custom_vars):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "\"myapp\", \"production\", {\"DB_HOST\": \"db.example.com\"}", "expected": "包含APP_NAME、APP_ENV、LOG_LEVEL和DB_HOST的配置字典"}]',
            "solution": "def generate_env_config(app_name, env, custom_vars):\n    log_map = {'development': 'DEBUG', 'staging': 'INFO', 'production': 'WARNING'}\n    node_map = {'development': 'development', 'staging': 'production', 'production': 'production'}\n    config = {\n        'APP_NAME': app_name,\n        'APP_ENV': env,\n        'LOG_LEVEL': log_map.get(env, 'INFO'),\n        'NODE_ENV': node_map.get(env, 'development')\n    }\n    config.update(custom_vars)\n    return config",
            "hint": "使用字典映射环境到日志级别，然后update合并",
        },
        {
            "title": "编写函数解析Docker日志格式",
            "description": "编写Python函数parse_docker_log(log_line)，解析Docker JSON格式日志。\n\nlog_line格式: {\"log\":\"message text\\n\",\"stream\":\"stdout\",\"time\":\"2024-01-15T10:30:00Z\"}\n\n返回字典：\n- message: 日志内容(去除换行)\n- stream: 日志流(stdout/stderr)\n- timestamp: 时间戳\n- level: 根据stream推断(INFO for stdout, ERROR for stderr)",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Docker脚本",
            "knowledge_point": "Docker日志解析",
            "code_template": "def parse_docker_log(log_line):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"log\":\"started server\\n\",\"stream\":\"stdout\",\"time\":\"2024-01-15T10:30:00Z\"}", "expected": "{message: started server, stream: stdout, level: INFO}"}]',
            "solution": "def parse_docker_log(log_line):\n    import json\n    data = json.loads(log_line) if isinstance(log_line, str) else log_line\n    message = data.get('log', '').strip()\n    stream = data.get('stream', 'stdout')\n    return {\n        'message': message,\n        'stream': stream,\n        'timestamp': data.get('time', ''),\n        'level': 'ERROR' if stream == 'stderr' else 'INFO'\n    }",
            "hint": "使用json.loads解析，根据stream字段判断日志级别",
        },
        {
            "title": "编写函数检查K8s Pod状态",
            "description": "编写Python函数check_pod_readiness(pod_status)，检查K8s Pod是否就绪。\n\npod_status为字典，包含：\n- phase: Running/Pending/Succeeded/Failed\n- conditions: 列表，每个包含type和status\n- container_statuses: 列表，每个包含ready(bool)\n\n返回字典：\n- ready: 是否全部就绪\n- phase: 当前阶段\n- all_containers_ready: 所有容器是否就绪\n- conditions_met: 所有条件是否满足",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "Kubernetes脚本",
            "knowledge_point": "Pod状态检查",
            "code_template": "def check_pod_readiness(pod_status):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "{\"phase\": \"Running\", \"conditions\": [{\"type\": \"Ready\", \"status\": \"True\"}], \"container_statuses\": [{\"ready\": true}]}", "expected": "{ready: true, phase: Running, all_containers_ready: true}"}]',
            "solution": "def check_pod_readiness(pod_status):\n    phase = pod_status.get('phase', 'Unknown')\n    conditions = pod_status.get('conditions', [])\n    container_statuses = pod_status.get('container_statuses', [])\n    all_containers_ready = all(c.get('ready', False) for c in container_statuses)\n    conditions_met = all(\n        c.get('status') == 'True' for c in conditions if c.get('type') == 'Ready'\n    ) if conditions else False\n    ready = phase == 'Running' and all_containers_ready and conditions_met\n    return {\n        'ready': ready,\n        'phase': phase,\n        'all_containers_ready': all_containers_ready,\n        'conditions_met': conditions_met\n    }",
            "hint": "分别检查phase、conditions和container_statuses，用all()判断整体状态",
        },
        # --- 综合实践 (hard) ---
        {
            "title": "编写函数模拟CI/CD流水线执行",
            "description": "编写Python函数simulate_pipeline(stages, env)，模拟CI/CD流水线执行。\n\nstages: 阶段列表，每个阶段包含name和duration(秒)\nenv: 环境(development/staging/production)\n\n返回执行报告字典：\n- stages: 各阶段执行结果\n- total_duration: 总耗时\n- status: 整体状态(success/failed)\n- environment: 执行环境",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "CI/CD脚本",
            "knowledge_point": "流水线模拟",
            "code_template": "def simulate_pipeline(stages, env):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"name\": \"build\", \"duration\": 30}, {\"name\": \"test\", \"duration\": 60}], \"staging\"", "expected": "包含stages结果列表和total_duration的字典"}]',
            "solution": "def simulate_pipeline(stages, env):\n    results = []\n    total_duration = 0\n    all_passed = True\n    for stage in stages:\n        stage_result = {\n            'name': stage['name'],\n            'duration': stage['duration'],\n            'status': 'success'\n        }\n        results.append(stage_result)\n        total_duration += stage['duration']\n    return {\n        'stages': results,\n        'total_duration': total_duration,\n        'status': 'success' if all_passed else 'failed',\n        'environment': env\n    }",
            "hint": "遍历阶段列表，累加耗时，检查状态",
        },

        # ==================== 简答题 (25题) ====================
        # --- CI/CD概念 (easy) ---
        {
            "title": "请解释持续集成(CI)的定义和核心实践",
            "description": "请详细解释：\n1. 什么是持续集成？\n2. CI的核心实践有哪些？\n3. CI能带来什么价值？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "CI/CD概念",
            "knowledge_point": "持续集成",
            "solution": "持续集成(CI)是一种开发实践，要求开发人员频繁地将代码集成到共享主干，每次集成都通过自动化构建和测试来验证。\n\n核心实践：\n1. 频繁提交代码（至少每天一次）\n2. 每次提交触发自动化构建\n3. 每次构建都运行自动化测试\n4. 构建失败后优先修复\n5. 保持快速的构建过程\n\n价值：\n- 尽早发现集成问题\n- 减少手动测试工作量\n- 提高代码质量\n- 加速开发反馈循环\n- 降低发布风险",
        },
        {
            "title": "请解释持续交付和持续部署的区别",
            "description": "请详细解释持续交付(Continuous Delivery)和持续部署(Continuous Deployment)的区别、联系和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "CI/CD概念",
            "knowledge_point": "持续交付vs部署",
            "solution": "持续交付(Continuous Delivery)：\n- 定义：代码随时可以部署到生产环境\n- 特点：需要手动批准才能部署\n- 适用：需要人工审核的场景\n\n持续部署(Continuous Deployment)：\n- 定义：代码变更自动部署到生产环境\n- 特点：全自动，无需人工干预\n- 适用：高度自动化的团队\n\n联系：\n- 都基于持续集成\n- 都需要完善的自动化测试\n- 持续部署是持续交付的更进一步\n\n选择建议：\n- 初期团队建议从持续交付开始\n- 测试覆盖率高时可考虑持续部署",
        },
        {
            "title": "请解释DevOps文化的核心要素",
            "description": "请详细解释DevOps文化的核心要素，以及如何在团队中推行DevOps文化。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "CI/CD概念",
            "knowledge_point": "DevOps文化",
            "solution": "DevOps文化核心要素(CALMS)：\n\n1. Culture（文化）：\n- 打破开发和运维的壁垒\n- 强调协作和共享责任\n- 鼓励试错和学习\n\n2. Automation（自动化）：\n- 自动化构建、测试、部署\n- 减少手动操作，降低错误\n\n3. Lean（精益）：\n- 消除浪费\n- 持续改进\n- 小批量快速交付\n\n4. Measurement（度量）：\n- 度量关键指标\n- 数据驱动决策\n\n5. Sharing（分享）：\n- 知识共享\n- 工具和最佳实践分享\n\n推行建议：\n- 领导层支持\n- 从小范围试点开始\n- 建立跨职能团队\n- 持续培训和学习",
        },
        # --- Jenkins (medium) ---
        {
            "title": "请解释Jenkins Pipeline的两种语法及其区别",
            "description": "请详细解释Jenkins Pipeline的Scripted Pipeline和Declarative Pipeline的区别、优缺点和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "Jenkins配置与流水线",
            "knowledge_point": "Pipeline语法",
            "solution": "Scripted Pipeline：\n- 语法：基于Groovy的完整编程语言\n- 特点：灵活，支持复杂逻辑\n- 优点：功能强大，可定制性高\n- 缺点：学习曲线陡，不易维护\n\nDeclarative Pipeline：\n- 语法：声明式，结构化配置\n- 特点：简洁，易于理解\n- 优点：易于学习和维护，有更好的IDE支持\n- 缺点：灵活性较低\n\n适用场景：\n- 简单流水线：Declarative\n- 复杂逻辑：Scripted\n- 团队协作：Declarative（更易理解）\n\n最佳实践：\n- 优先使用Declarative\n- 需要复杂逻辑时嵌入Scripted块",
        },
        {
            "title": "请解释Jenkins共享库(Shared Library)的概念和用途",
            "description": "请解释什么是Jenkins共享库，为什么需要共享库，以及如何组织共享库代码。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "Jenkins配置与流水线",
            "knowledge_point": "共享库",
            "solution": "共享库定义：\n- 可复用的Pipeline代码集合\n- 独立于Jenkinsfile存储\n- 多个项目可以共享\n\n为什么需要：\n- 避免Pipeline代码重复\n- 统一构建流程\n- 集中管理共享逻辑\n- 便于维护和更新\n\n目录结构：\nsrc/ - Groovy源代码\nvars/ - 全局变量和函数\nresources/ - 非Groovy文件\n\n使用方式：\n1. 在Jenkins中配置共享库\n2. 在Jenkinsfile中引用\n3. 调用共享库中的函数\n\n最佳实践：\n- 版本化管理\n- 单一职责原则\n- 编写文档和示例",
        },
        # --- Docker (medium) ---
        {
            "title": "请解释Docker容器的基本概念和架构",
            "description": "请详细解释Docker的镜像、容器、仓库的概念，以及Docker的分层存储机制。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "Docker容器化",
            "knowledge_point": "Docker核心概念",
            "solution": "核心概念：\n\n1. 镜像(Image)：\n- 只读模板\n- 包含运行应用所需的一切\n- 分层存储\n\n2. 容器(Container)：\n- 镜像的运行实例\n- 可写层 + 只读层\n- 相互隔离\n\n3. 仓库(Registry)：\n- 存储和分发镜像\n- Docker Hub是最大的公共仓库\n\n分层存储：\n- 每个Dockerfile指令创建一层\n- 层可以共享和复用\n- 节省存储空间\n- 加速构建和传输\n\n架构：\n- Docker Client：命令行工具\n- Docker Daemon：后台服务\n- Docker Registry：镜像仓库",
        },
        {
            "title": "请解释Dockerfile最佳实践",
            "description": "请列出编写Dockerfile的最佳实践，并解释为什么这些实践很重要。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "Dockerfile编写",
            "knowledge_point": "Dockerfile最佳实践",
            "solution": "Dockerfile最佳实践：\n\n1. 使用小的基础镜像：\n- 减小镜像体积\n- 减少攻击面\n\n2. 合理利用构建缓存：\n- 将不常变化的指令放在前面\n- COPY依赖文件先于COPY源代码\n\n3. 减少镜像层数：\n- 合并RUN指令\n- 清理临时文件\n\n4. 使用多阶段构建：\n- 分离构建环境和运行环境\n- 大幅减小最终镜像体积\n\n5. 使用.dockerignore：\n- 排除不需要的文件\n- 加速构建\n\n6. 避免以root运行：\n- 创建专用用户\n- 提高安全性\n\n7. 使用COPY而非ADD：\n- COPY行为明确\n- ADD有隐式解压\n\n8. 设置合理的ENTRYPOINT和CMD：\n- ENTRYPOINT定义主命令\n- CMD提供默认参数",
        },
        # --- Kubernetes (hard) ---
        {
            "title": "请解释Kubernetes的核心概念和架构",
            "description": "请详细解释Kubernetes的核心概念（Pod、Service、Deployment、Namespace等）和整体架构。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "Kubernetes基础",
            "knowledge_point": "K8s架构",
            "solution": "Kubernetes核心概念：\n\n1. Pod：\n- 最小部署单元\n- 一个或多个容器\n- 共享网络和存储\n\n2. Service：\n- 为Pod提供稳定访问入口\n- 负载均衡\n- ClusterIP、NodePort、LoadBalancer类型\n\n3. Deployment：\n- 声明式更新\n- 管理ReplicaSet\n- 支持滚动更新和回滚\n\n4. Namespace：\n- 逻辑隔离\n- 资源配额管理\n\n架构：\n\nControl Plane（主节点）：\n- API Server：集群入口\n- Scheduler：Pod调度\n- Controller Manager：状态管理\n- etcd：数据存储\n\nWorker Node（工作节点）：\n- Kubelet：节点代理\n- Kube-proxy：网络代理\n- Container Runtime：容器运行时",
        },
        {
            "title": "请解释Kubernetes的Service类型及其适用场景",
            "description": "请详细解释ClusterIP、NodePort、LoadBalancer和ExternalName四种Service类型的区别和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "Kubernetes基础",
            "knowledge_point": "K8s Service类型",
            "solution": "Service类型：\n\n1. ClusterIP（默认）：\n- 仅集群内部访问\n- 分配集群内部IP\n- 适用：内部服务通信\n\n2. NodePort：\n- 在每个节点上开放端口\n- 范围：30000-32767\n- 适用：开发测试环境\n\n3. LoadBalancer：\n- 使用云厂商负载均衡器\n- 自动创建外部IP\n- 适用：生产环境对外服务\n\n4. ExternalName：\n- 映射到外部DNS名\n- 不代理，只做CNAME\n- 适用：访问外部服务\n\n选择建议：\n- 内部服务：ClusterIP\n- 需要外部访问：LoadBalancer\n- 临时测试：NodePort\n- 外部依赖：ExternalName",
        },
        # --- Git工作流 (easy) ---
        {
            "title": "请解释常见的Git分支策略",
            "description": "请解释Git Flow、GitHub Flow和Trunk-Based Development三种分支策略的区别和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "Git工作流",
            "knowledge_point": "Git分支策略",
            "solution": "Git Flow：\n- 分支：main, develop, feature, release, hotfix\n- 特点：严格的分支模型\n- 适用：有固定发布周期的项目\n- 优点：清晰的分支职责\n- 缺点：复杂，合并频繁\n\nGitHub Flow：\n- 分支：main + feature分支\n- 特点：简单，基于PR\n- 适用：持续部署的项目\n- 优点：简单易懂\n- 缺点：不适合复杂发布流程\n\nTrunk-Based Development：\n- 分支：主干 + 短生命周期分支\n- 特点：频繁集成，小批量提交\n- 适用：CI/CD成熟的团队\n- 优点：减少合并冲突\n- 缺点：需要完善的自动化测试\n\n选择建议：\n- 传统项目：Git Flow\n- SaaS产品：GitHub Flow\n- 高成熟度团队：Trunk-Based",
        },
        # --- GitHub Actions (medium) ---
        {
            "title": "请解释GitHub Actions的核心概念",
            "description": "请详细解释GitHub Actions的workflow、job、step、action等核心概念，以及它们之间的关系。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "GitHub Actions",
            "knowledge_point": "GitHub Actions概念",
            "solution": "核心概念：\n\n1. Workflow（工作流）：\n- 自动化流程的集合\n- 由事件触发\n- 存放在.github/workflows/\n\n2. Job（作业）：\n- 一组步骤的集合\n- 在同一个运行器上执行\n- 默认并行执行，可设置依赖\n\n3. Step（步骤）：\n- Job中的单个任务\n- 可以是action或shell命令\n- 按顺序执行\n\n4. Action（动作）：\n- 可复用的工作单元\n- 可以是JavaScript或Docker\n- 从Marketplace获取或自定义\n\n5. Runner（运行器）：\n- 执行Job的服务器\n- GitHub托管或自托管\n\n关系：\nWorkflow -> Job -> Step -> Action",
        },
        # --- 基础设施即代码 (hard) ---
        {
            "title": "请解释Infrastructure as Code(IaC)的概念和工具",
            "description": "请详细解释IaC的概念、优势，以及Terraform和Ansible的区别。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "基础设施即代码",
            "knowledge_point": "IaC概念与工具",
            "solution": "IaC概念：\n- 用代码定义和管理基础设施\n- 版本化、可重复、可审计\n- 自动化基础设施变更\n\n优势：\n- 一致性：消除环境差异\n- 速度：快速创建和销毁环境\n- 版本控制：追踪变更历史\n- 协作：团队共享基础设施定义\n- 文档化：代码即文档\n\nTerraform vs Ansible：\n\nTerraform：\n- 类型：基础设施编排工具\n- 特点：声明式，状态管理\n- 适用：创建云资源（VM、网络、存储）\n- 工作方式：计划 -> 应用 -> 状态\n\nAnsible：\n- 类型：配置管理工具\n- 特点：过程式，无代理\n- 适用：软件安装、配置管理\n- 工作方式：Playbook -> 执行\n\n最佳实践：\n- 两者结合使用\n- Terraform创建基础设施\n- Ansible配置和部署应用",
        },
        {
            "title": "请解释不可变基础设施(Immutable Infrastructure)的概念",
            "description": "请详细解释不可变基础设施的概念、与可变基础设施的区别，以及实现方式。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "基础设施即代码",
            "knowledge_point": "不可变基础设施",
            "solution": "不可变基础设施：\n- 定义：基础设施部署后不再修改\n- 变更方式：替换而非修改\n\n可变基础设施：\n- 传统方式：SSH登录修改配置\n- 问题：配置漂移、雪花服务器\n\n区别：\n- 可变：原地修改，状态不可控\n- 不可变：整体替换，状态一致\n\n实现方式：\n1. 构建不可变镜像（Docker、AMI）\n2. 使用IaC工具管理\n3. 蓝绿部署或金丝雀发布\n4. 自动化CI/CD流水线\n\n优势：\n- 可预测性：每次部署一致\n- 可回滚：快速切换版本\n- 安全性：减少配置篡改\n- 简化运维：无需追踪变更",
        },
        # --- 监控与告警 (medium) ---
        {
            "title": "请解释监控系统的三大支柱",
            "description": "请详细解释可观测性(Observability)的三大支柱：Metrics、Logs、Traces的概念和作用。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "可观测性三支柱",
            "solution": "三大支柱：\n\n1. Metrics（指标）：\n- 定义：数值型时间序列数据\n- 示例：CPU使用率、请求QPS、响应时间\n- 工具：Prometheus、Grafana\n- 用途：趋势分析、告警触发\n\n2. Logs（日志）：\n- 定义：事件记录\n- 示例：错误日志、访问日志、应用日志\n- 工具：ELK Stack、Loki\n- 用途：问题排查、审计\n\n3. Traces（链路追踪）：\n- 定义：请求在分布式系统中的完整路径\n- 示例：一次API调用经过的所有服务\n- 工具：Jaeger、Zipkin\n- 用途：性能优化、依赖分析\n\n三者关系：\n- Metrics发现问题\n- Traces定位问题\n- Logs分析问题\n\n最佳实践：\n- 三者结合使用\n- 统一日志格式\n- 设置合理的采样率",
        },
        {
            "title": "请解释告警管理的最佳实践",
            "description": "请详细解释如何设计有效的告警策略，避免告警疲劳。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "监控与告警",
            "knowledge_point": "告警管理",
            "solution": "告警管理最佳实践：\n\n1. 告警分级：\n- P0/紧急：服务不可用，立即响应\n- P1/重要：功能受损，1小时内响应\n- P2/警告：性能下降，工作时间响应\n- P3/信息：需关注，定期处理\n\n2. 避免告警疲劳：\n- 减少无效告警\n- 设置合理的阈值\n- 使用告警聚合\n- 设置静默规则\n\n3. 告警设计原则：\n- 可操作：每条告警都应有明确的处理步骤\n- 可理解：告警信息清晰明确\n- 及时性：告警应在问题发生后尽快触发\n\n4. 告警流程：\n- 告警 -> 通知 -> 响应 -> 处理 -> 复盘\n\n5. 持续改进：\n- 定期审查告警规则\n- 分析告警数据\n- 优化阈值和规则",
        },
        {
            "title": "请解释什么是SLA、SLO和SLI",
            "description": "请详细解释SLA、SLO和SLI的定义、关系和如何制定。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "监控与告警",
            "knowledge_point": "SLA/SLO/SLI",
            "solution": "SLI（Service Level Indicator）：\n- 定义：服务级别指标\n- 示例：可用性99.9%、延迟<200ms\n- 特点：可度量的服务质量指标\n\nSLO（Service Level Objective）：\n- 定义：服务级别目标\n- 内容：SLI的目标值\n- 示例：可用性SLO为99.95%\n- 用途：内部质量目标\n\nSLA（Service Level Agreement）：\n- 定义：服务级别协议\n- 内容：对客户的承诺\n- 包含：SLO、违约责任、补偿\n- 用途：商业合同\n\n关系：\nSLI度量 -> SLO目标 -> SLA承诺\n\n制定建议：\n1. 选择关键SLI\n2. 设定合理SLO（留有余量）\n3. SLA略低于SLO\n4. 持续监控和调整",
        },
        # --- 自动化部署 (medium) ---
        {
            "title": "请解释Docker网络模式及其适用场景",
            "description": "请详细解释Docker的bridge、host、none和overlay四种网络模式的区别和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "Docker容器化",
            "knowledge_point": "Docker网络模式",
            "solution": "Docker网络模式：\n\n1. Bridge（桥接模式，默认）：\n- 特点：容器有独立的网络命名空间\n- 通信：通过docker0网桥互联\n- 适用：大多数单机容器场景\n\n2. Host（主机模式）：\n- 特点：容器直接使用宿主机网络\n- 优势：网络性能最佳\n- 缺点：端口冲突风险\n- 适用：对网络性能要求高的场景\n\n3. None（无网络模式）：\n- 特点：容器没有网络接口\n- 适用：安全隔离场景、批量计算\n\n4. Overlay（覆盖网络）：\n- 特点：跨主机容器通信\n- 实现：基于VXLAN\n- 适用：Docker Swarm或K8s集群\n\n选择建议：\n- 开发测试：bridge\n- 高性能需求：host\n- 集群环境：overlay",
        },
        {
            "title": "请解释CI/CD中的制品管理",
            "description": "请详细解释CI/CD中制品(Artifact)的概念、管理策略和最佳实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "CI/CD概念",
            "knowledge_point": "制品管理",
            "solution": "制品概念：\n- CI/CD流水线生成的可部署产物\n- 例：Docker镜像、JAR包、npm包、二进制文件\n\n管理策略：\n\n1. 版本化：\n- 语义化版本(semantic versioning)\n- Git commit hash作为标签\n- 构建号作为唯一标识\n\n2. 制品仓库：\n- Docker镜像：Harbor、Docker Registry\n- 通用制品：Nexus、JFrog Artifactory\n- 包管理：npm registry、PyPI\n\n3. 生命周期管理：\n- 保留策略：保留最近N个版本\n- 清理策略：删除过期制品\n- 签名验证：确保制品完整性\n\n最佳实践：\n- 制品不可变：一次构建，多环境部署\n- 制品与代码关联：可追溯到源码\n- 安全扫描：部署前进行漏洞扫描\n- 自动化发布：流水线自动推送制品",
        },
        {
            "title": "请解释如何进行有效的容量规划",
            "description": "请详细解释在DevOps实践中如何进行容量规划，包括指标监控、预测方法和扩展策略。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "监控与告警",
            "knowledge_point": "容量规划",
            "solution": "容量规划步骤：\n\n1. 基线建立：\n- 收集历史性能数据\n- 确定关键指标：CPU、内存、磁盘IO、网络带宽\n- 建立正常负载基线\n\n2. 负载预测：\n- 分析业务增长趋势\n- 预测峰值场景（促销、节假日）\n- 留有余量（通常30-50%缓冲）\n\n3. 监控指标：\n- 资源使用率：CPU<70%、内存<80%\n- 响应时间：P95/P99延迟\n- 错误率：5xx错误比例\n- 队列积压：消息队列长度\n\n4. 扩展策略：\n- 垂直扩展(Scale Up)：增加单机资源\n- 水平扩展(Scale Out)：增加实例数量\n- 自动扩展(HPA)：基于指标自动调整\n\n5. 工具：\n- 监控：Prometheus + Grafana\n- 告警：设置阈值告警\n- 预测：基于历史数据的趋势分析\n\n最佳实践：\n- 定期review容量\n- 压力测试验证容量\n- 建立扩缩容预案\n- 成本优化和资源利用率平衡",
        },
        {
            "title": "请解释常见的部署策略",
            "description": "请详细解释蓝绿部署、滚动更新、金丝雀发布和A/B测试的区别和适用场景。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "自动化部署",
            "knowledge_point": "部署策略",
            "solution": "蓝绿部署：\n- 方式：维护两套完整环境\n- 切换：一次性切换流量\n- 优点：快速回滚，零停机\n- 缺点：需要双倍资源\n- 适用：关键服务\n\n滚动更新：\n- 方式：逐步替换旧版本实例\n- 特点：始终有部分实例服务\n- 优点：资源利用率高\n- 缺点：回滚较慢\n- 适用：K8s默认策略\n\n金丝雀发布：\n- 方式：先向少量用户发布新版本\n- 特点：逐步扩大范围\n- 优点：风险可控\n- 缺点：部署周期长\n- 适用：风险较高的更新\n\nA/B测试：\n- 方式：按条件分流到不同版本\n- 特点：功能级测试\n- 优点：数据驱动决策\n- 缺点：需要功能开关\n- 适用：产品功能验证",
        },
        {
            "title": "请解释GitOps的概念和实践",
            "description": "请详细解释GitOps的定义、原则、工作流程和优势。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "自动化部署",
            "knowledge_point": "GitOps",
            "solution": "GitOps定义：\n- 以Git仓库为唯一可信源\n- 通过Git变更驱动基础设施和应用部署\n- 声明式配置管理\n\n核心原则：\n1. 声明式：所有配置都是声明式的\n2. 版本化：Git是唯一可信源\n3. 自动化：变更自动应用\n4. 自愈性：持续调和实际状态和期望状态\n\n工作流程：\n1. 开发者提交代码变更\n2. CI构建镜像\n3. 更新Git仓库中的配置\n4. GitOps工具检测变更\n5. 自动部署到集群\n\n优势：\n- 审计追踪：所有变更都有记录\n- 快速回滚：恢复到任意Git版本\n- 一致性：声明式保证环境一致\n- 安全性：Git权限控制部署权限\n\n工具：ArgoCD、Flux、Jenkins X",
        },
        # --- 综合实践 (hard) ---
        {
            "title": "请解释如何设计一个完整的CI/CD流水线",
            "description": "请详细解释如何为一个Web应用设计完整的CI/CD流水线，包括各阶段、工具选择和最佳实践。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "CI/CD概念",
            "knowledge_point": "CI/CD流水线设计",
            "solution": "完整CI/CD流水线设计：\n\n阶段1：代码提交\n- 触发：Git push/PR\n- 操作：代码规范检查、pre-commit hooks\n\n阶段2：构建(Build)\n- 操作：编译、打包\n- 产物：Docker镜像、二进制文件\n\n阶段3：测试(Test)\n- 单元测试：快速反馈\n- 集成测试：验证交互\n- 安全扫描：漏洞检测\n- 代码质量：SonarQube\n\n阶段4：发布(Release)\n- 镜像推送到Registry\n- 版本号管理\n- 生成发布说明\n\n阶段5：部署(Deploy)\n- 环境：dev -> staging -> prod\n- 策略：蓝绿/金丝雀\n- 验证：冒烟测试、健康检查\n\n阶段6：监控(Monitor)\n- 部署状态监控\n- 性能指标监控\n- 告警通知\n\n工具选择：\n- CI：Jenkins/GitHub Actions/GitLab CI\n- 容器：Docker\n- 编排：Kubernetes\n- 配置：Helm/Kustomize\n- 监控：Prometheus + Grafana",
        },
        {
            "title": "请解释如何实现应用的零停机部署",
            "description": "请详细解释实现零停机部署(Zero-Downtime Deployment)的技术方案和注意事项。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "自动化部署",
            "knowledge_point": "零停机部署",
            "solution": "零停机部署方案：\n\n1. 蓝绿部署：\n- 维护两套环境\n- 一次性切换流量\n- 快速回滚\n\n2. 滚动更新：\n- 逐步替换实例\n- 保持最小可用实例数\n- 健康检查确保新实例就绪\n\n3. 金丝雀发布：\n- 先发布到少量实例\n- 监控指标正常后扩大\n\n关键技术：\n- 负载均衡器：Nginx、HAProxy、云LB\n- 健康检查：就绪探针、存活探针\n- 优雅关闭：处理完当前请求再关闭\n- 数据库迁移：向后兼容\n\n注意事项：\n1. 数据库Schema变更要向后兼容\n2. 会话管理：共享存储或无状态\n3. 静态资源：CDN缓存更新\n4. API版本：保持向后兼容\n5. 监控：部署过程中的指标监控",
        },
        {
            "title": "请解释容器编排的必要性和Kubernetes的优势",
            "description": "请详细解释为什么需要容器编排，以及Kubernetes相比其他编排工具的优势。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "Kubernetes基础",
            "knowledge_point": "容器编排",
            "solution": "为什么需要容器编排：\n\n1. 容器数量增长：\n- 手动管理不现实\n- 需要自动化调度\n\n2. 服务发现和负载均衡：\n- 容器动态创建销毁\n- 需要自动注册和流量分配\n\n3. 高可用：\n- 容器故障自动恢复\n- 跨节点调度\n\n4. 资源管理：\n- 合理分配CPU、内存\n- 提高资源利用率\n\nKubernetes优势：\n\n1. 声明式配置：\n- 定义期望状态\n- 系统自动调和\n\n2. 自愈能力：\n- 自动重启失败容器\n- 自动替换不健康节点\n\n3. 水平扩展：\n- 自动扩缩容\n- 基于指标的弹性伸缩\n\n4. 服务发现和负载均衡：\n- 内置DNS\n- 自动负载均衡\n\n5. 滚动更新和回滚：\n- 零停机更新\n- 快速回滚\n\n6. 生态系统：\n- 丰富的插件和工具\n- 活跃的社区",
        },
        {
            "title": "请解释DevSecOps的概念和实践",
            "description": "请详细解释DevSecOps的概念、安全左移的实践，以及如何在CI/CD中集成安全检查。",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "CI/CD概念",
            "knowledge_point": "DevSecOps",
            "solution": "DevSecOps概念：\n- 将安全融入DevOps流程\n- 安全是每个人的责任\n- 自动化安全检查\n\n安全左移：\n- 传统：安全检查在最后\n- 左移：安全检查尽早融入开发\n- 优势：早期发现漏洞，降低修复成本\n\nCI/CD中的安全集成：\n\n1. 代码阶段：\n- 静态代码分析(SAST)\n- 依赖漏洞扫描\n- 密钥检测\n\n2. 构建阶段：\n- 镜像漏洞扫描(Trivy)\n- 合规性检查\n- 签名验证\n\n3. 部署阶段：\n- 动态安全测试(DAST)\n- 配置合规检查\n- 运行时安全\n\n4. 运行阶段：\n- 入侵检测\n- 日志审计\n- 安全监控\n\n工具链：\n- SAST：SonarQube、Semgrep\n- DAST：OWASP ZAP\n- 依赖扫描：Dependabot、Snyk\n- 镜像扫描：Trivy、Clair\n- 密钥检测：GitLeaks",
        },
    ]
}
