# -*- coding: utf-8 -*-
"""
测试平台开发 - 学习路径 ID=16
知识点: FastAPI框架、Flask基础、RESTful API设计、SQLAlchemy ORM、数据库设计、前端Vue.js基础、测试平台架构设计、任务调度、日志系统、权限管理
题目数量: 80题 (选择题30 + 编程题25 + 简答题25)
难度分布: easy 30% + medium 50% + hard 20%
"""

EXERCISES = {
    "测试平台开发": [
        # ==================== 选择题 (30题) ====================
        # --- FastAPI框架 (easy) ---
        {
            "title": "FastAPI框架的核心特点不包括以下哪项？",
            "description": "FastAPI框架的核心特点不包括以下哪项？\nA. 自动生成API文档\nB. 基于Python类型提示\nC. 内置ORM框架\nD. 支持异步请求处理",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "FastAPI框架",
            "knowledge_point": "FastAPI核心特点",
            "solution": "C",
        },
        {
            "title": "FastAPI中用于定义路径参数的方式是？",
            "description": "FastAPI中用于定义路径参数的方式是？\nA. 使用@query装饰器\nB. 在路径中使用{参数名}并声明在函数参数中\nC. 使用request.body获取\nD. 使用配置文件定义",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "FastAPI框架",
            "knowledge_point": "路径参数",
            "solution": "B",
        },
        {
            "title": "FastAPI自动生成的交互式API文档默认路径是？",
            "description": "FastAPI自动生成的交互式API文档默认路径是？\nA. /api/docs\nB. /docs\nC. /swagger\nD. /api-docs",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "FastAPI框架",
            "knowledge_point": "API文档",
            "solution": "B",
        },
        # --- Flask基础 (easy) ---
        {
            "title": "Flask框架被称为微框架，主要是因为？",
            "description": "Flask框架被称为微框架，主要是因为？\nA. 代码量很少\nB. 核心功能精简，通过扩展增强功能\nC. 只能开发小型应用\nD. 不支持数据库",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Flask基础",
            "knowledge_point": "Flask微框架",
            "solution": "B",
        },
        {
            "title": "Flask中用于将URL映射到函数的装饰器是？",
            "description": "Flask中用于将URL映射到函数的装饰器是？\nA. @app.view\nB. @app.route\nC. @app.url\nD. @app.map",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "Flask基础",
            "knowledge_point": "Flask路由",
            "solution": "B",
        },
        # --- RESTful API设计 (medium) ---
        {
            "title": "RESTful API中，获取资源列表应使用的HTTP方法是？",
            "description": "RESTful API中，获取资源列表应使用的HTTP方法是？\nA. POST\nB. PUT\nC. GET\nD. DELETE",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "RESTful API设计",
            "knowledge_point": "HTTP方法",
            "solution": "C",
        },
        {
            "title": "RESTful API中，更新资源的部分字段应使用的HTTP方法是？",
            "description": "RESTful API中，更新资源的部分字段应使用的HTTP方法是？\nA. POST\nB. PUT\nC. PATCH\nD. DELETE",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "RESTful API设计",
            "knowledge_point": "PUT与PATCH区别",
            "solution": "C",
        },
        {
            "title": "RESTful API中HTTP状态码201表示？",
            "description": "RESTful API中HTTP状态码201表示？\nA. 请求成功\nB. 资源创建成功\nC. 请求被拒绝\nD. 服务器内部错误",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "RESTful API设计",
            "knowledge_point": "HTTP状态码",
            "solution": "B",
        },
        {
            "title": "RESTful API中，资源的URL命名最佳实践是？",
            "description": "RESTful API中，资源的URL命名最佳实践是？\nA. 使用动词，如/getUsers\nB. 使用名词复数，如/users\nC. 使用大写字母\nD. 使用下划线分隔",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "RESTful API设计",
            "knowledge_point": "URL命名规范",
            "solution": "B",
        },
        # --- SQLAlchemy ORM (medium) ---
        {
            "title": "SQLAlchemy中，定义模型类需要继承的基类是？",
            "description": "SQLAlchemy中，定义模型类需要继承的基类是？\nA. db.Model\nB. Base\nC. Model\nD. SQLAlchemy.Model",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "模型定义",
            "solution": "B",
        },
        {
            "title": "SQLAlchemy中，一对多关系使用的关键字是？",
            "description": "SQLAlchemy中，一对多关系使用的关键字是？\nA. ForeignKey\nB. relationship\nC. backref\nD. join",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "关系定义",
            "solution": "B",
        },
        {
            "title": "SQLAlchemy中，查询所有记录的方法是？",
            "description": "SQLAlchemy中，查询所有记录的方法是？\nA. session.query(Model).all()\nB. session.find(Model)\nC. Model.select_all()\nD. Model.findall()",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "基本查询",
            "solution": "A",
        },
        # --- 数据库设计 (medium) ---
        {
            "title": "数据库设计中第三范式(3NF)要求？",
            "description": "数据库设计中第三范式(3NF)要求？\nA. 每个字段不可再分\nB. 非主键字段完全依赖于主键\nC. 非主键字段不传递依赖于主键\nD. 允许数据冗余",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "数据库设计",
            "knowledge_point": "数据库范式",
            "solution": "C",
        },
        {
            "title": "测试平台中测试用例与测试结果的关系通常是？",
            "description": "测试平台中测试用例与测试结果的关系通常是？\nA. 一对一\nB. 一对多\nC. 多对多\nD. 没有关系",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "数据库设计",
            "knowledge_point": "实体关系",
            "solution": "B",
        },
        {
            "title": "数据库索引的主要作用是？",
            "description": "数据库索引的主要作用是？\nA. 保证数据完整性\nB. 提高查询速度\nC. 减少存储空间\nD. 加密数据",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "数据库设计",
            "knowledge_point": "索引",
            "solution": "B",
        },
        # --- 前端Vue.js基础 (medium) ---
        {
            "title": "Vue.js中用于双向数据绑定的指令是？",
            "description": "Vue.js中用于双向数据绑定的指令是？\nA. v-bind\nB. v-model\nC. v-on\nD. v-show",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "前端Vue.js基础",
            "knowledge_point": "双向绑定",
            "solution": "B",
        },
        {
            "title": "Vue.js中v-if和v-show的区别是？",
            "description": "Vue.js中v-if和v-show的区别是？\nA. 没有区别\nB. v-if销毁DOM元素，v-show使用CSS隐藏\nC. v-if更快\nD. v-show销毁DOM元素",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "前端Vue.js基础",
            "knowledge_point": "条件渲染",
            "solution": "B",
        },
        {
            "title": "Vue 3中用于管理全局状态的推荐方案是？",
            "description": "Vue 3中用于管理全局状态的推荐方案是？\nA. Vuex\nB. Pinia\nC. Redux\nD. MobX",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "前端Vue.js基础",
            "knowledge_point": "状态管理",
            "solution": "B",
        },
        # --- 测试平台架构设计 (medium/hard) ---
        {
            "title": "测试平台前后端分离架构中，前端通过什么方式与后端通信？",
            "description": "测试平台前后端分离架构中，前端通过什么方式与后端通信？\nA. 直接访问数据库\nB. 通过API接口\nC. 共享内存\nD. 文件传输",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "测试平台架构设计",
            "knowledge_point": "前后端分离",
            "solution": "B",
        },
        {
            "title": "测试平台中，测试执行引擎通常采用什么架构模式？",
            "description": "测试平台中，测试执行引擎通常采用什么架构模式？\nA. 同步阻塞执行\nB. 异步任务队列\nC. 定时轮询\nD. 手动触发",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "测试平台架构设计",
            "knowledge_point": "执行引擎架构",
            "solution": "B",
        },
        {
            "title": "微服务架构下测试平台的服务拆分原则是？",
            "description": "微服务架构下测试平台的服务拆分原则是？\nA. 按技术栈拆分\nB. 按业务领域拆分\nC. 按团队人数拆分\nD. 不需要拆分",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "测试平台架构设计",
            "knowledge_point": "微服务拆分",
            "solution": "B",
        },
        # --- 任务调度 (medium) ---
        {
            "title": "Python中常用的定时任务调度库是？",
            "description": "Python中常用的定时任务调度库是？\nA. Celery\nB. APScheduler\nC. Schedule\nD. 以上都是",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "任务调度",
            "knowledge_point": "调度库",
            "solution": "D",
        },
        {
            "title": "Celery任务队列中，用于存储任务结果的组件是？",
            "description": "Celery任务队列中，用于存储任务结果的组件是？\nA. Broker\nB. Backend\nC. Worker\nD. Beat",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "任务调度",
            "knowledge_point": "Celery组件",
            "solution": "B",
        },
        {
            "title": "测试任务调度中，Cron表达式 0 8 * * 1-5 表示？",
            "description": "测试任务调度中，Cron表达式 0 8 * * 1-5 表示？\nA. 每天8点执行\nB. 工作日8点执行\nC. 每周一8点执行\nD. 每月1-5号8点执行",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "任务调度",
            "knowledge_point": "Cron表达式",
            "solution": "B",
        },
        # --- 日志系统 (medium/hard) ---
        {
            "title": "Python标准日志模块中，严重程度最高的级别是？",
            "description": "Python标准日志模块中，严重程度最高的级别是？\nA. ERROR\nB. WARNING\nC. CRITICAL\nD. INFO",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "easy",
            "category": "日志系统",
            "knowledge_point": "日志级别",
            "solution": "C",
        },
        {
            "title": "测试平台中日志聚合分析常用的开源方案是？",
            "description": "测试平台中日志聚合分析常用的开源方案是？\nA. ELK Stack\nB. LAMP Stack\nC. MEAN Stack\nD. Django Stack",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "日志系统",
            "knowledge_point": "日志聚合",
            "solution": "A",
        },
        {
            "title": "结构化日志相比普通文本日志的优势是？",
            "description": "结构化日志相比普通文本日志的优势是？\nA. 占用更少存储空间\nB. 便于机器解析和检索\nC. 不需要日志框架\nD. 输出更美观",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "日志系统",
            "knowledge_point": "结构化日志",
            "solution": "B",
        },
        # --- 权限管理 (medium/hard) ---
        {
            "title": "RBAC权限模型中，用户和权限之间通过什么关联？",
            "description": "RBAC权限模型中，用户和权限之间通过什么关联？\nA. 直接关联\nB. 通过角色关联\nC. 通过部门关联\nD. 通过资源关联",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "权限管理",
            "knowledge_point": "RBAC模型",
            "solution": "B",
        },
        {
            "title": "JWT令牌由哪三部分组成？",
            "description": "JWT令牌由哪三部分组成？\nA. 用户名、密码、时间戳\nB. Header、Payload、Signature\nC. Token、Secret、Expiry\nD. Public Key、Private Key、Data",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "medium",
            "category": "权限管理",
            "knowledge_point": "JWT结构",
            "solution": "B",
        },
        {
            "title": "测试平台中，API接口的权限验证最佳实践是？",
            "description": "测试平台中，API接口的权限验证最佳实践是？\nA. 在每个接口中手动检查\nB. 使用中间件统一验证\nC. 只在前端验证\nD. 不需要验证",
            "instructions": "请选择正确答案",
            "exercise_type": "single_choice",
            "difficulty": "hard",
            "category": "权限管理",
            "knowledge_point": "权限验证实践",
            "solution": "B",
        },

        # ==================== 编程题 (25题) ====================
        # --- FastAPI框架 (easy) ---
        {
            "title": "编写FastAPI基础应用",
            "description": "编写一个FastAPI应用，包含根路径/返回欢迎信息。\n\n要求：\n- 创建FastAPI实例\n- 定义GET / 返回 {\"message\": \"Welcome to TestPlatform\"}\n\n示例：\n- GET / -> {\"message\": \"Welcome to TestPlatform\"}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "FastAPI框架",
            "knowledge_point": "FastAPI基础",
            "code_template": "from fastapi import FastAPI\n\napp = FastAPI()\n\n# 请在此处编写路由",
            "test_cases": '[{"input": "GET /", "expected": "{\"message\": \"Welcome to TestPlatform\"}"}]',
            "solution": "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/\")\nasync def root():\n    return {\"message\": \"Welcome to TestPlatform\"}",
            "hint": "使用@app.get装饰器定义GET路由",
        },
        {
            "title": "编写FastAPI路径参数接口",
            "description": "编写FastAPI接口，通过路径参数获取测试用例详情。\n\n要求：\n- GET /cases/{case_id} 返回 {\"case_id\": case_id, \"status\": \"active\"}\n- case_id为整数类型\n\n示例：\n- GET /cases/1 -> {\"case_id\": 1, \"status\": \"active\"}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "FastAPI框架",
            "knowledge_point": "路径参数",
            "code_template": "from fastapi import FastAPI\n\napp = FastAPI()\n\n# 请在此处编写路由",
            "test_cases": '[{"input": "GET /cases/1", "expected": "{\"case_id\": 1, \"status\": \"active\"}"}]',
            "solution": "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/cases/{case_id}\")\nasync def get_case(case_id: int):\n    return {\"case_id\": case_id, \"status\": \"active\"}",
            "hint": "在函数参数中声明类型即可自动校验",
        },
        {
            "title": "编写FastAPI查询参数接口",
            "description": "编写FastAPI接口，支持分页查询测试用例列表。\n\n要求：\n- GET /cases?skip=0&limit=10\n- 返回 {\"skip\": skip, \"limit\": limit, \"total\": 100}\n- skip默认0，limit默认10\n\n示例：\n- GET /cases?skip=5&limit=20 -> {\"skip\": 5, \"limit\": 20, \"total\": 100}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "FastAPI框架",
            "knowledge_point": "查询参数",
            "code_template": "from fastapi import FastAPI\n\napp = FastAPI()\n\n# 请在此处编写路由",
            "test_cases": '[{"input": "GET /cases?skip=5&limit=20", "expected": "{\"skip\": 5, \"limit\": 20, \"total\": 100}"}]',
            "solution": "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/cases\")\nasync def list_cases(skip: int = 0, limit: int = 10):\n    return {\"skip\": skip, \"limit\": limit, \"total\": 100}",
            "hint": "函数参数中设置默认值即可作为查询参数",
        },
        # --- Flask基础 (easy/medium) ---
        {
            "title": "编写Flask基础应用",
            "description": "编写一个Flask应用，包含健康检查接口。\n\n要求：\n- 创建Flask实例\n- GET /health 返回 {\"status\": \"ok\"}\n\n示例：\n- GET /health -> {\"status\": \"ok\"}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "easy",
            "category": "Flask基础",
            "knowledge_point": "Flask基础",
            "code_template": "from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n# 请在此处编写路由",
            "test_cases": '[{"input": "GET /health", "expected": "{\"status\": \"ok\"}"}]',
            "solution": "from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n@app.route(\"/health\")\ndef health():\n    return jsonify({\"status\": \"ok\"})",
            "hint": "使用@app.route装饰器和jsonify返回JSON",
        },
        {
            "title": "编写Flask错误处理",
            "description": "编写Flask应用的全局错误处理函数。\n\n要求：\n- 捕获404错误，返回 {\"error\": \"Not Found\", \"code\": 404}\n- 捕获500错误，返回 {\"error\": \"Internal Server Error\", \"code\": 500}\n\n示例：\n- 访问不存在的路径 -> {\"error\": \"Not Found\", \"code\": 404}",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "Flask基础",
            "knowledge_point": "错误处理",
            "code_template": "from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n# 请在此处编写错误处理",
            "test_cases": '[{"input": "GET /not_exist", "expected": "{\"error\": \"Not Found\", \"code\": 404}"}]',
            "solution": "from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n@app.errorhandler(404)\ndef not_found(e):\n    return jsonify({\"error\": \"Not Found\", \"code\": 404}), 404\n\n@app.errorhandler(500)\ndef internal_error(e):\n    return jsonify({\"error\": \"Internal Server Error\", \"code\": 500}), 500",
            "hint": "使用@app.errorhandler装饰器注册错误处理函数",
        },
        # --- RESTful API设计 (medium) ---
        {
            "title": "编写RESTful CRUD接口",
            "description": "使用FastAPI编写测试项目的CRUD接口。\n\n要求：\n- POST /projects 创建项目\n- GET /projects/{id} 获取项目\n- PUT /projects/{id} 更新项目\n- DELETE /projects/{id} 删除项目\n- 使用内存字典存储数据",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "RESTful API设计",
            "knowledge_point": "CRUD接口",
            "code_template": "from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\ndb = {}\ncounter = 0\n\nclass ProjectCreate(BaseModel):\n    name: str\n    description: str = \"\"\n\n# 请在此处编写四个接口",
            "test_cases": '[{"input": "POST /projects {\"name\": \"TestProject\"}", "expected": "返回包含id的项目信息"}]',
            "solution": "from fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\n\napp = FastAPI()\ndb = {}\ncounter = 0\n\nclass ProjectCreate(BaseModel):\n    name: str\n    description: str = \"\"\n\n@app.post(\"/projects\")\nasync def create_project(project: ProjectCreate):\n    global counter\n    counter += 1\n    db[counter] = {\"id\": counter, **project.model_dump()}\n    return db[counter]\n\n@app.get(\"/projects/{project_id}\")\nasync def get_project(project_id: int):\n    if project_id not in db:\n        raise HTTPException(status_code=404, detail=\"Project not found\")\n    return db[project_id]\n\n@app.put(\"/projects/{project_id}\")\nasync def update_project(project_id: int, project: ProjectCreate):\n    if project_id not in db:\n        raise HTTPException(status_code=404, detail=\"Project not found\")\n    db[project_id] = {\"id\": project_id, **project.model_dump()}\n    return db[project_id]\n\n@app.delete(\"/projects/{project_id}\")\nasync def delete_project(project_id: int):\n    if project_id not in db:\n        raise HTTPException(status_code=404, detail=\"Project not found\")\n    del db[project_id]\n    return {\"message\": \"Deleted\"}",
            "hint": "使用HTTPException处理资源不存在的情况",
        },
        {
            "title": "编写API响应格式封装函数",
            "description": "编写一个通用的API响应格式封装函数。\n\n要求：\n- 成功响应: {\"code\": 0, \"message\": \"success\", \"data\": data}\n- 失败响应: {\"code\": code, \"message\": msg, \"data\": null}\n- 提供success()和error()两个函数",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "RESTful API设计",
            "knowledge_point": "响应格式封装",
            "code_template": "def success(data=None):\n    # 请在此处编写代码\n    pass\n\ndef error(code=-1, message=\"error\"):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "success({\"id\": 1})", "expected": "{\"code\": 0, \"message\": \"success\", \"data\": {\"id\": 1}}"}]',
            "solution": "def success(data=None):\n    return {\"code\": 0, \"message\": \"success\", \"data\": data}\n\ndef error(code=-1, message=\"error\"):\n    return {\"code\": code, \"message\": message, \"data\": None}",
            "hint": "直接返回字典即可",
        },
        # --- SQLAlchemy ORM (medium/hard) ---
        {
            "title": "编写SQLAlchemy模型定义",
            "description": "使用SQLAlchemy定义测试用例(TestCase)和测试结果(TestResult)模型。\n\n要求：\n- TestCase: id, name, description, priority, created_at\n- TestResult: id, case_id(外键), status(pass/fail/error), executed_at\n- 定义一对多关系",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "模型定义",
            "code_template": "from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, create_engine\nfrom sqlalchemy.orm import relationship, declarative_base\nfrom datetime import datetime\n\nBase = declarative_base()\n\n# 请在此处定义模型",
            "test_cases": '[{"input": "创建TestCase和TestResult表", "expected": "模型定义正确，包含外键关系"}]',
            "solution": "from sqlalchemy import Column, Integer, String, DateTime, ForeignKey\nfrom sqlalchemy.orm import relationship, declarative_base\nfrom datetime import datetime\n\nBase = declarative_base()\n\nclass TestCase(Base):\n    __tablename__ = \"test_cases\"\n    id = Column(Integer, primary_key=True, autoincrement=True)\n    name = Column(String(200), nullable=False)\n    description = Column(String(500), default=\"\")\n    priority = Column(String(20), default=\"medium\")\n    created_at = Column(DateTime, default=datetime.utcnow)\n    results = relationship(\"TestResult\", back_populates=\"case\")\n\nclass TestResult(Base):\n    __tablename__ = \"test_results\"\n    id = Column(Integer, primary_key=True, autoincrement=True)\n    case_id = Column(Integer, ForeignKey(\"test_cases.id\"), nullable=False)\n    status = Column(String(20), nullable=False)\n    executed_at = Column(DateTime, default=datetime.utcnow)\n    case = relationship(\"TestCase\", back_populates=\"results\")",
            "hint": "使用ForeignKey定义外键，relationship定义关系",
        },
        {
            "title": "编写SQLAlchemy查询函数",
            "description": "编写一个函数，使用SQLAlchemy查询指定项目下所有失败的测试结果。\n\n要求：\n- 函数名: get_failed_results(session, project_id)\n- 返回包含用例名称和失败信息的列表",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "复杂查询",
            "code_template": "from sqlalchemy.orm import Session\n\ndef get_failed_results(session: Session, project_id: int):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "session和project_id=1", "expected": "返回失败的测试结果列表"}]',
            "solution": "from sqlalchemy.orm import Session\n\ndef get_failed_results(session: Session, project_id: int):\n    results = session.query(TestResult).join(TestCase).filter(\n        TestCase.project_id == project_id,\n        TestResult.status == \"fail\"\n    ).all()\n    return [{\"case_name\": r.case.name, \"status\": r.status, \"executed_at\": r.executed_at} for r in results]",
            "hint": "使用join关联查询，filter添加条件",
        },
        {
            "title": "编写数据库迁移脚本",
            "description": "编写一个函数，为现有表添加新字段。\n\n要求：\n- 函数名: add_column(engine, table_name, column_name, column_type)\n- 使用原生SQL执行ALTER TABLE语句\n- 兼容SQLite和PostgreSQL",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "数据库迁移",
            "code_template": "from sqlalchemy import create_engine, text\n\ndef add_column(engine, table_name, column_name, column_type):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "add_column(engine, \"users\", \"email\", \"VARCHAR(200)\")", "expected": "成功添加列"}]',
            "solution": "from sqlalchemy import create_engine, text\n\ndef add_column(engine, table_name, column_name, column_type):\n    with engine.connect() as conn:\n        sql = f\"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_type}\"\n        conn.execute(text(sql))\n        conn.commit()",
            "hint": "使用text()执行原生SQL字符串",
        },
        # --- 数据库设计 (medium/hard) ---
        {
            "title": "编写数据库初始化脚本",
            "description": "编写函数创建测试平台所需的数据表。\n\n要求：\n- 创建projects、test_cases、test_suites、test_results四张表\n- 使用原始SQL的CREATE TABLE IF NOT EXISTS\n- 定义合理的字段和主外键关系",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "数据库设计",
            "knowledge_point": "建表脚本",
            "code_template": "import sqlite3\n\ndef init_database(db_path):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "init_database(\"test.db\")", "expected": "成功创建四张表"}]',
            "solution": "import sqlite3\n\ndef init_database(db_path):\n    conn = sqlite3.connect(db_path)\n    cursor = conn.cursor()\n    cursor.executescript(\"\"\"\n        CREATE TABLE IF NOT EXISTS projects (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            name TEXT NOT NULL,\n            description TEXT DEFAULT \",\n            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n        );\n        CREATE TABLE IF NOT EXISTS test_cases (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            project_id INTEGER NOT NULL,\n            name TEXT NOT NULL,\n            description TEXT DEFAULT \",\n            priority TEXT DEFAULT \"medium\",\n            FOREIGN KEY (project_id) REFERENCES projects(id)\n        );\n        CREATE TABLE IF NOT EXISTS test_suites (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            project_id INTEGER NOT NULL,\n            name TEXT NOT NULL,\n            FOREIGN KEY (project_id) REFERENCES projects(id)\n        );\n        CREATE TABLE IF NOT EXISTS test_results (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            case_id INTEGER NOT NULL,\n            status TEXT NOT NULL,\n            executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n            FOREIGN KEY (case_id) REFERENCES test_cases(id)\n        );\n    \"\"\")\n    conn.commit()\n    conn.close()",
            "hint": "使用executescript执行多条SQL语句",
        },
        {
            "title": "编写数据统计查询函数",
            "description": "编写函数统计每个项目的测试通过率。\n\n要求：\n- 函数名: get_pass_rate(conn, project_id)\n- 返回 {\"total\": 总数, \"passed\": 通过数, \"rate\": 通过率}\n- 通过率保留两位小数",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "数据库设计",
            "knowledge_point": "统计查询",
            "code_template": "import sqlite3\n\ndef get_pass_rate(conn, project_id):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "conn和project_id=1", "expected": "{\"total\": 10, \"passed\": 8, \"rate\": 0.8}"}]',
            "solution": "import sqlite3\n\ndef get_pass_rate(conn, project_id):\n    cursor = conn.cursor()\n    cursor.execute(\"\"\"\n        SELECT COUNT(*) as total,\n               SUM(CASE WHEN status = \"pass\" THEN 1 ELSE 0 END) as passed\n        FROM test_results tr\n        JOIN test_cases tc ON tr.case_id = tc.id\n        WHERE tc.project_id = ?\n    \"\"\", (project_id,))\n    row = cursor.fetchone()\n    total = row[0] or 0\n    passed = row[1] or 0\n    rate = round(passed / total, 2) if total > 0 else 0\n    return {\"total\": total, \"passed\": passed, \"rate\": rate}",
            "hint": "使用CASE WHEN进行条件统计",
        },
        # --- 前端Vue.js基础 (medium) ---
        {
            "title": "编写Vue.js测试用例列表组件",
            "description": "编写一个Vue 3组件，展示测试用例列表。\n\n要求：\n- 使用setup语法\n- 从API获取数据并展示\n- 包含加载状态显示",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "前端Vue.js基础",
            "knowledge_point": "Vue组件",
            "code_template": "// 请编写Vue 3组件代码",
            "test_cases": '[{"input": "组件渲染", "expected": "正确显示用例列表"}]',
            "solution": "<template>\n  <div>\n    <div v-if=\"loading\">Loading...</div>\n    <table v-else>\n      <thead>\n        <tr><th>ID</th><th>Name</th><th>Priority</th></tr>\n      </thead>\n      <tbody>\n        <tr v-for=\"item in cases\" :key=\"item.id\">\n          <td>{{ item.id }}</td>\n          <td>{{ item.name }}</td>\n          <td>{{ item.priority }}</td>\n        </tr>\n      </tbody>\n    </table>\n  </div>\n</template>\n\n<script setup>\nimport { ref, onMounted } from \"vue\"\n\nconst cases = ref([])\nconst loading = ref(true)\n\nonMounted(async () => {\n  try {\n    const res = await fetch(\"/api/cases\")\n    cases.value = await res.json()\n  } finally {\n    loading.value = false\n  }\n})\n</script>",
            "hint": "使用ref定义响应式数据，onMounted发送请求",
        },
        {
            "title": "编写Vue.js表单提交组件",
            "description": "编写一个Vue 3组件，实现测试用例创建表单。\n\n要求：\n- 包含name、description、priority三个字段\n- 提交到POST /api/cases\n- 提交成功后清空表单",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "前端Vue.js基础",
            "knowledge_point": "表单处理",
            "code_template": "// 请编写Vue 3组件代码",
            "test_cases": '[{"input": "填写并提交表单", "expected": "成功创建用例并清空表单"}]',
            "solution": "<template>\n  <form @submit.prevent=\"submitForm\">\n    <input v-model=\"form.name\" placeholder=\"Case Name\" required />\n    <textarea v-model=\"form.description\" placeholder=\"Description\"></textarea>\n    <select v-model=\"form.priority\">\n      <option value=\"low\">Low</option>\n      <option value=\"medium\">Medium</option>\n      <option value=\"high\">High</option>\n    </select>\n    <button type=\"submit\">Create</button>\n  </form>\n</template>\n\n<script setup>\nimport { reactive } from \"vue\"\n\nconst form = reactive({ name: \"\", description: \"\", priority: \"medium\" })\n\nasync function submitForm() {\n  await fetch(\"/api/cases\", {\n    method: \"POST\",\n    headers: { \"Content-Type\": \"application/json\" },\n    body: JSON.stringify(form)\n  })\n  form.name = \"\"\n  form.description = \"\"\n  form.priority = \"medium\"\n}\n</script>",
            "hint": "使用reactive定义表单数据，@submit.prevent阻止默认提交",
        },
        # --- 测试平台架构设计 (hard) ---
        {
            "title": "编写插件化测试执行器",
            "description": "编写一个支持插件的测试执行器框架。\n\n要求：\n- 支持注册不同类型的测试执行器\n- 统一的执行接口 run(test_config)\n- 支持按类型查找并执行",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "测试平台架构设计",
            "knowledge_point": "插件化架构",
            "code_template": "class TestRunner:\n    def __init__(self):\n        self.runners = {}\n\n    def register(self, runner_type, runner_func):\n        # 请在此处编写代码\n        pass\n\n    def execute(self, test_type, test_config):\n        # 请在此处编写代码\n        pass",
            "test_cases": '[{"input": "注册并执行api类型测试", "expected": "成功调用对应的runner"}]',
            "solution": "class TestRunner:\n    def __init__(self):\n        self.runners = {}\n\n    def register(self, runner_type, runner_func):\n        self.runners[runner_type] = runner_func\n\n    def execute(self, test_type, test_config):\n        if test_type not in self.runners:\n            raise ValueError(f\"Unknown test type: {test_type}\")\n        return self.runners[test_type](test_config)",
            "hint": "使用字典存储类型和对应的执行函数",
        },
        {
            "title": "编写中间件请求日志记录器",
            "description": "编写FastAPI中间件，记录每个请求的方法、路径和耗时。\n\n要求：\n- 记录请求方法和路径\n- 计算请求处理耗时(ms)\n- 使用logging模块输出",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "测试平台架构设计",
            "knowledge_point": "中间件设计",
            "code_template": "from fastapi import Request\nimport time\nimport logging\n\nlogger = logging.getLogger(__name__)\n\nasync def log_middleware(request: Request, call_next):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "任意HTTP请求", "expected": "日志输出请求方法、路径和耗时"}]',
            "solution": "from fastapi import Request\nimport time\nimport logging\n\nlogger = logging.getLogger(__name__)\n\nasync def log_middleware(request: Request, call_next):\n    start_time = time.time()\n    response = await call_next(request)\n    duration = round((time.time() - start_time) * 1000, 2)\n    logger.info(f\"{request.method} {request.url.path} - {duration}ms - {response.status_code}\")\n    return response",
            "hint": "在call_next前后分别记录时间和计算差值",
        },
        # --- 任务调度 (medium/hard) ---
        {
            "title": "编写简单任务调度器",
            "description": "编写一个简单的任务调度器，支持定时执行任务。\n\n要求：\n- 支持添加任务(add_task)\n- 支持按间隔时间执行(run)\n- 任务到时间时自动调用",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "任务调度",
            "knowledge_point": "任务调度基础",
            "code_template": "import time\nfrom datetime import datetime\n\nclass SimpleScheduler:\n    def __init__(self):\n        self.tasks = []\n\n    def add_task(self, func, interval_seconds):\n        # 请在此处编写代码\n        pass\n\n    def run_once(self):\n        # 检查并执行到期任务\n        # 请在此处编写代码\n        pass",
            "test_cases": '[{"input": "添加间隔60秒的任务", "expected": "任务被正确添加到列表"}]',
            "solution": "import time\nfrom datetime import datetime\n\nclass SimpleScheduler:\n    def __init__(self):\n        self.tasks = []\n\n    def add_task(self, func, interval_seconds):\n        self.tasks.append({\n            \"func\": func,\n            \"interval\": interval_seconds,\n            \"last_run\": 0\n        })\n\n    def run_once(self):\n        now = time.time()\n        for task in self.tasks:\n            if now - task[\"last_run\"] >= task[\"interval\"]:\n                task[\"func\"]()\n                task[\"last_run\"] = now",
            "hint": "使用时间戳记录上次执行时间",
        },
        {
            "title": "编写异步任务执行器",
            "description": "编写一个异步任务执行器，支持并发执行多个测试任务。\n\n要求：\n- 使用asyncio\n- 支持最大并发数限制\n- 返回所有任务的执行结果",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "任务调度",
            "knowledge_point": "异步任务",
            "code_template": "import asyncio\n\nasync def run_tasks(tasks, max_concurrent=5):\n    # tasks: list of coroutines\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "5个异步任务，最大并发3", "expected": "所有任务完成，返回结果列表"}]',
            "solution": "import asyncio\n\nasync def run_tasks(tasks, max_concurrent=5):\n    semaphore = asyncio.Semaphore(max_concurrent)\n\n    async def limited_task(task):\n        async with semaphore:\n            return await task\n\n    results = await asyncio.gather(*[limited_task(t) for t in tasks])\n    return list(results)",
            "hint": "使用asyncio.Semaphore限制并发数",
        },
        # --- 日志系统 (medium) ---
        {
            "title": "编写日志记录工具类",
            "description": "编写一个日志记录工具类，支持不同级别的日志输出。\n\n要求：\n- 支持info、warning、error三个级别\n- 日志格式包含时间戳、级别、消息\n- 支持同时输出到控制台和文件",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "日志系统",
            "knowledge_point": "日志工具类",
            "code_template": "import logging\n\nclass LoggerUtil:\n    def __init__(self, name, log_file=None):\n        # 请在此处编写代码\n        pass",
            "test_cases": '[{"input": "创建logger并输出info日志", "expected": "日志包含时间戳和消息"}]',
            "solution": "import logging\n\nclass LoggerUtil:\n    def __init__(self, name, log_file=None):\n        self.logger = logging.getLogger(name)\n        self.logger.setLevel(logging.DEBUG)\n        formatter = logging.Formatter(\"%(asctime)s - %(levelname)s - %(message)s\")\n\n        console_handler = logging.StreamHandler()\n        console_handler.setFormatter(formatter)\n        self.logger.addHandler(console_handler)\n\n        if log_file:\n            file_handler = logging.FileHandler(log_file)\n            file_handler.setFormatter(formatter)\n            self.logger.addHandler(file_handler)\n\n    def info(self, msg):\n        self.logger.info(msg)\n\n    def warning(self, msg):\n        self.logger.warning(msg)\n\n    def error(self, msg):\n        self.logger.error(msg)",
            "hint": "使用Formatter设置格式，Handler设置输出目标",
        },
        {
            "title": "编写测试报告生成函数",
            "description": "编写函数生成HTML格式的测试报告。\n\n要求：\n- 输入: 测试结果列表[{name, status, duration}]\n- 输出: HTML字符串\n- 包含通过/失败/总数统计",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "日志系统",
            "knowledge_point": "测试报告",
            "code_template": "def generate_report(results):\n    # results: list of dict with name, status, duration\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"name\": \"test1\", \"status\": \"pass\", \"duration\": 0.5}]", "expected": "包含统计信息的HTML字符串"}]',
            "solution": "def generate_report(results):\n    total = len(results)\n    passed = sum(1 for r in results if r[\"status\"] == \"pass\")\n    failed = total - passed\n\n    html = f\"<html><body>\"\n    html += f\"<h1>Test Report</h1>\"\n    html += f\"<p>Total: {total} | Passed: {passed} | Failed: {failed}</p>\"\n    html += \"<table border=1><tr><th>Name</th><th>Status</th><th>Duration</th></tr>\"\n    for r in results:\n        color = \"green\" if r[\"status\"] == \"pass\" else \"red\"\n        html += f\"<tr><td>{r['name']}</td><td style='color:{color}'>{r['status']}</td><td>{r['duration']}s</td></tr>\"\n    html += \"</table></body></html>\"\n    return html",
            "hint": "使用字符串拼接生成HTML，用颜色区分通过和失败",
        },
        # --- 权限管理 (medium/hard) ---
        {
            "title": "编写JWT令牌生成和验证函数",
            "description": "编写JWT令牌的生成和验证函数。\n\n要求：\n- generate_token(user_id, secret_key, expire_hours=24)\n- verify_token(token, secret_key)\n- 返回解码后的payload或None",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "权限管理",
            "knowledge_point": "JWT实现",
            "code_template": "import jwt\nfrom datetime import datetime, timedelta\n\ndef generate_token(user_id, secret_key, expire_hours=24):\n    # 请在此处编写代码\n    pass\n\ndef verify_token(token, secret_key):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "generate_token(1, \"secret\")", "expected": "返回有效的JWT字符串"}]',
            "solution": "import jwt\nfrom datetime import datetime, timedelta\n\ndef generate_token(user_id, secret_key, expire_hours=24):\n    payload = {\n        \"user_id\": user_id,\n        \"exp\": datetime.utcnow() + timedelta(hours=expire_hours),\n        \"iat\": datetime.utcnow()\n    }\n    return jwt.encode(payload, secret_key, algorithm=\"HS256\")\n\ndef verify_token(token, secret_key):\n    try:\n        payload = jwt.decode(token, secret_key, algorithms=[\"HS256\"])\n        return payload\n    except jwt.ExpiredSignatureError:\n        return None\n    except jwt.InvalidTokenError:\n        return None",
            "hint": "使用PyJWT库，注意捕获token过期和无效异常",
        },
        {
            "title": "编写RBAC权限检查函数",
            "description": "编写基于RBAC模型的权限检查函数。\n\n要求：\n- check_permission(user_roles, required_permission)\n- user_roles: 用户角色列表，每个角色包含permissions列表\n- required_permission: 需要的权限字符串\n- 返回True或False",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "权限管理",
            "knowledge_point": "RBAC权限检查",
            "code_template": "def check_permission(user_roles, required_permission):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "user_roles=[{\"name\": \"admin\", \"permissions\": [\"read\", \"write\"]}], required_permission=\"write\"", "expected": "True"}]',
            "solution": "def check_permission(user_roles, required_permission):\n    for role in user_roles:\n        if required_permission in role.get(\"permissions\", []):\n            return True\n        if \"*\" in role.get(\"permissions\", []):\n            return True\n    return False",
            "hint": "遍历用户角色，检查权限列表中是否包含所需权限",
        },
        {
            "title": "编写FastAPI权限装饰器",
            "description": "编写FastAPI的权限验证依赖项。\n\n要求：\n- 从请求头获取token\n- 解析token获取用户信息\n- 检查用户是否具有所需权限",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "权限管理",
            "knowledge_point": "权限依赖注入",
            "code_template": "from fastapi import Depends, HTTPException, Header\n\ndef require_permission(permission: str):\n    async def checker(authorization: str = Header(...)):\n        # 请在此处编写代码\n        pass\n    return checker",
            "test_cases": '[{"input": "有效token且有权限", "expected": "返回用户信息"}]',
            "solution": "from fastapi import Depends, HTTPException, Header\nimport jwt\n\ndef require_permission(permission: str):\n    async def checker(authorization: str = Header(...)):\n        if not authorization.startswith(\"Bearer \"):\n            raise HTTPException(status_code=401, detail=\"Invalid token format\")\n        token = authorization.split(\" \")[1]\n        try:\n            payload = jwt.decode(token, \"secret\", algorithms=[\"HS256\"])\n        except jwt.InvalidTokenError:\n            raise HTTPException(status_code=401, detail=\"Invalid token\")\n        user_permissions = payload.get(\"permissions\", [])\n        if permission not in user_permissions and \"*\" not in user_permissions:\n            raise HTTPException(status_code=403, detail=\"Permission denied\")\n        return payload\n    return checker",
            "hint": "返回一个依赖函数，使用Header获取Authorization",
        },
        {
            "title": "编写数据导出CSV函数",
            "description": "编写函数将测试结果导出为CSV格式字符串。\n\n要求：\n- 输入: 结果列表[{name, status, duration, error_msg}]\n- 输出: CSV格式字符串\n- 第一行为表头",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "medium",
            "category": "数据库设计",
            "knowledge_point": "数据导出",
            "code_template": "import csv\nfrom io import StringIO\n\ndef export_to_csv(results):\n    # 请在此处编写代码\n    pass",
            "test_cases": '[{"input": "[{\"name\": \"test_login\", \"status\": \"pass\", \"duration\": 1.2, \"error_msg\": \"\"}]", "expected": "包含表头和数据行的CSV字符串"}]',
            "solution": "import csv\nfrom io import StringIO\n\ndef export_to_csv(results):\n    output = StringIO()\n    writer = csv.DictWriter(output, fieldnames=[\"name\", \"status\", \"duration\", \"error_msg\"])\n    writer.writeheader()\n    writer.writerows(results)\n    return output.getvalue()",
            "hint": "使用csv.DictWriter写入字典列表",
        },
        {
            "title": "编写API请求封装类",
            "description": "编写一个API请求封装类，支持GET/POST/PUT/DELETE方法。\n\n要求：\n- 封装requests库\n- 自动处理JSON响应\n- 支持统一的错误处理",
            "instructions": "请编写代码实现以下功能",
            "exercise_type": "code",
            "difficulty": "hard",
            "category": "RESTful API设计",
            "knowledge_point": "API客户端封装",
            "code_template": "import requests\n\nclass APIClient:\n    def __init__(self, base_url, token=None):\n        # 请在此处编写代码\n        pass\n\n    def get(self, path, params=None):\n        # 请在此处编写代码\n        pass\n\n    def post(self, path, data=None):\n        # 请在此处编写代码\n        pass",
            "test_cases": '[{"input": "client.get(\"/cases\")", "expected": "返回解析后的JSON数据"}]',
            "solution": "import requests\n\nclass APIClient:\n    def __init__(self, base_url, token=None):\n        self.base_url = base_url.rstrip(\"/\")\n        self.session = requests.Session()\n        if token:\n            self.session.headers[\"Authorization\"] = f\"Bearer {token}\"\n\n    def _request(self, method, path, **kwargs):\n        url = f\"{self.base_url}{path}\"\n        response = self.session.request(method, url, **kwargs)\n        response.raise_for_status()\n        if response.headers.get(\"content-type\", \"\").startswith(\"application/json\"):\n            return response.json()\n        return response.text\n\n    def get(self, path, params=None):\n        return self._request(\"GET\", path, params=params)\n\n    def post(self, path, data=None):\n        return self._request(\"POST\", path, json=data)\n\n    def put(self, path, data=None):\n        return self._request(\"PUT\", path, json=data)\n\n    def delete(self, path):\n        return self._request(\"DELETE\", path)",
            "hint": "使用requests.Session复用连接，_request统一处理请求",
        },

        # ==================== 简答题 (25题) ====================
        # --- FastAPI框架 (easy/medium) ---
        {
            "title": "请解释FastAPI相比Flask的优势",
            "description": "请详细解释：\n1. FastAPI相比Flask有哪些核心优势？\n2. 自动文档生成是如何实现的？\n3. 类型提示在FastAPI中起什么作用？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "FastAPI框架",
            "knowledge_point": "FastAPI优势",
            "solution": "FastAPI相比Flask的核心优势：\n1. 性能：基于Starlette和Pydantic，性能接近Node.js和Go\n2. 自动文档：基于OpenAPI标准自动生成Swagger UI和ReDoc\n3. 类型安全：利用Python类型提示进行数据验证和序列化\n4. 异步支持：原生支持async/await\n5. 依赖注入：内置强大的依赖注入系统\n\n自动文档生成：FastAPI读取路径函数的类型提示和文档字符串，自动生成OpenAPI schema，然后渲染为Swagger UI。\n\n类型提示的作用：\n- 自动数据验证：请求参数自动校验类型\n- 自动序列化：响应数据自动转为JSON\n- 编辑器支持：代码补全和类型检查\n- 文档生成：自动生成API文档",
        },
        {
            "title": "请解释FastAPI的依赖注入系统",
            "description": "请详细解释：\n1. 什么是依赖注入？\n2. FastAPI中如何使用Depends？\n3. 依赖注入在测试平台中有哪些应用场景？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "FastAPI框架",
            "knowledge_point": "依赖注入",
            "solution": "依赖注入(DI)是一种设计模式，对象的依赖由外部提供而非自己创建。\n\nFastAPI中使用Depends：\n1. 定义依赖函数，返回所需值\n2. 在路径函数参数中使用Depends(依赖函数)声明\n3. FastAPI自动解析并注入依赖\n\n示例：\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()\n\n@app.get(\"/cases\")\ndef get_cases(db = Depends(get_db)):\n    return db.query(Case).all()\n\n测试平台应用场景：\n- 数据库连接管理\n- 用户认证和权限验证\n- 请求参数解析\n- 日志记录\n- 分页参数复用",
        },
        # --- Flask基础 (easy/medium) ---
        {
            "title": "请解释Flask的核心组件",
            "description": "请详细解释：\n1. Flask的核心组件有哪些？\n2. Flask的请求上下文和应用上下文是什么？\n3. Flask蓝图(Blueprint)的作用是什么？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "Flask基础",
            "knowledge_point": "Flask核心组件",
            "solution": "Flask核心组件：\n1. Werkzeug：WSGI工具库，处理HTTP请求和响应\n2. Jinja2：模板引擎，用于渲染HTML\n3. 路由系统：URL到函数的映射\n4. 请求/响应对象：封装HTTP数据\n5. 扩展系统：通过Flask-SQLAlchemy等扩展功能\n\n请求上下文：封装一次请求的所有信息(request, session)，请求开始时推入栈，结束时弹出。\n\n应用上下文：封装应用相关信息(current_app, g)，应用启动时创建。\n\n蓝图(Blueprint)的作用：\n- 模块化组织路由和视图\n- 支持URL前缀\n- 便于大型应用的代码组织\n- 测试平台中可按功能模块划分蓝图",
        },
        # --- RESTful API设计 (medium) ---
        {
            "title": "请解释RESTful API设计的最佳实践",
            "description": "请详细解释：\n1. REST的核心约束有哪些？\n2. API版本管理有哪些方案？\n3. 如何设计测试平台的API接口规范？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "RESTful API设计",
            "knowledge_point": "REST最佳实践",
            "solution": "REST核心约束：\n1. 客户端-服务器分离\n2. 无状态：每个请求包含所有信息\n3. 可缓存\n4. 统一接口：使用标准HTTP方法\n5. 分层系统\n6. 按需代码（可选）\n\nAPI版本管理方案：\n1. URL路径：/api/v1/users\n2. 请求头：Accept: application/vnd.api.v1+json\n3. 查询参数：/api/users?version=1\n\n测试平台API规范：\n- 使用名词复数：/api/cases, /api/projects\n- HTTP方法语义：GET查询、POST创建、PUT全量更新、PATCH部分更新、DELETE删除\n- 状态码：200成功、201创建、400参数错误、401未认证、403无权限、404不存在、500服务器错误\n- 分页：?page=1&page_size=20\n- 统一响应格式：{code, message, data}",
        },
        {
            "title": "请解释API接口的认证与鉴权方案",
            "description": "请详细解释：\n1. 认证(Authentication)和鉴权(Authorization)的区别？\n2. 常见的API认证方案有哪些？\n3. OAuth2.0的基本流程是什么？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "RESTful API设计",
            "knowledge_point": "认证鉴权",
            "solution": "认证vs鉴权：\n- 认证：验证用户身份（你是谁）\n- 鉴权：验证用户权限（你能做什么）\n\n常见API认证方案：\n1. API Key：简单，适合服务间调用\n2. Basic Auth：用户名密码Base64编码\n3. JWT：无状态令牌，适合分布式系统\n4. OAuth2.0：第三方授权\n5. Session/Cookie：传统Web应用\n\nOAuth2.0基本流程：\n1. 用户点击授权链接跳转到授权服务器\n2. 用户登录并授权\n3. 授权服务器返回authorization_code\n4. 客户端用code换取access_token\n5. 使用access_token访问资源",
        },
        # --- SQLAlchemy ORM (medium/hard) ---
        {
            "title": "请解释SQLAlchemy的会话管理",
            "description": "请详细解释：\n1. SQLAlchemy的Session是什么？\n2. 会话的生命周期是怎样的？\n3. 在Web应用中如何管理会话？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "会话管理",
            "solution": "Session是SQLAlchemy与数据库交互的中介：\n1. 维护对象的标识映射（Identity Map）\n2. 跟踪对象的变更（脏检查）\n3. 管理事务\n\n会话生命周期：\n1. 创建Session实例\n2. 通过session.query()查询或add()添加对象\n3. 修改对象属性（自动跟踪）\n4. session.commit()提交事务\n5. session.rollback()回滚（出错时）\n6. session.close()关闭会话\n\nWeb应用中的会话管理：\n- 每个请求创建一个Session\n- 请求结束时关闭Session\n- 使用依赖注入管理Session生命周期\n- FastAPI中通常使用yield依赖：\n\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()",
        },
        {
            "title": "请解释SQLAlchemy的N+1查询问题及解决方案",
            "description": "请详细解释：\n1. 什么是N+1查询问题？\n2. 在SQLAlchemy中如何复现这个问题？\n3. 有哪些解决方案？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "SQLAlchemy ORM",
            "knowledge_point": "N+1查询",
            "solution": "N+1查询问题：\n查询N条记录时，额外发出N条SQL查询关联数据，总共N+1条查询。\n\n复现：\ncases = session.query(TestCase).all()  # 1条查询\nfor case in cases:\n    print(case.results)  # 每次循环触发1条查询，共N条\n\n解决方案：\n1. 预加载(Eager Loading)：\n   - joinedload：JOIN查询\n     session.query(TestCase).options(joinedload(TestCase.results)).all()\n   - subload：子查询\n     session.query(TestCase).options(subqueryload(TestCase.results)).all()\n\n2. 手动JOIN：\n   session.query(TestCase).join(TestResult).all()\n\n3. 使用IN查询：\n   case_ids = [c.id for c in cases]\n   results = session.query(TestResult).filter(TestResult.case_id.in_(case_ids)).all()",
        },
        # --- 数据库设计 (medium) ---
        {
            "title": "请解释测试平台的数据库设计方案",
            "description": "请详细解释：\n1. 测试平台需要哪些核心数据表？\n2. 表之间的关系如何设计？\n3. 如何处理测试数据的版本管理？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "数据库设计",
            "knowledge_point": "数据库设计方案",
            "solution": "核心数据表：\n1. users：用户表\n2. projects：项目表\n3. test_cases：测试用例表\n4. test_suites：测试套件表\n5. test_results：测试结果表\n6. test_plans：测试计划表\n7. environments：环境配置表\n\n表关系：\n- projects 1:N test_cases\n- projects 1:N test_suites\n- test_suites N:M test_cases（通过suite_cases关联表）\n- test_cases 1:N test_results\n- test_plans 1:N test_results\n\n测试数据版本管理：\n1. 乐观锁：增加version字段，更新时检查版本号\n2. 审计日志：记录所有变更历史\n3. 快照：保存测试用例的副本\n4. Git集成：将测试用例存储在Git仓库中",
        },
        # --- 前端Vue.js基础 (easy/medium) ---
        {
            "title": "请解释Vue.js的响应式原理",
            "description": "请详细解释：\n1. Vue 2和Vue 3的响应式实现有何不同？\n2. ref和reactive有什么区别？\n3. 响应式在测试平台前端开发中如何应用？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "前端Vue.js基础",
            "knowledge_point": "响应式原理",
            "solution": "Vue 2 vs Vue 3响应式：\n- Vue 2：使用Object.defineProperty，只能监听已有属性，无法监听新增/删除属性\n- Vue 3：使用Proxy，可以监听所有操作，性能更好\n\nref vs reactive：\n- ref：用于基本类型，通过.value访问，模板中自动解包\n- reactive：用于对象类型，直接访问属性，不能用于基本类型\n\n测试平台前端应用：\n1. 测试数据展示：使用ref/reactive绑定数据，自动更新UI\n2. 表单输入：v-model双向绑定\n3. 状态管理：Pinia使用reactive存储全局状态\n4. 列表渲染：v-for配合响应式数据\n5. 条件渲染：v-if/v-show根据响应式数据切换",
        },
        {
            "title": "请解释Vue 3的Composition API",
            "description": "请详细解释：\n1. Composition API解决了什么问题？\n2. setup函数的作用是什么？\n3. 常用的Composition API有哪些？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "前端Vue.js基础",
            "knowledge_point": "Composition API",
            "solution": "Composition API解决的问题：\n1. 逻辑复用：Mixins命名冲突和来源不清晰\n2. 代码组织：Options API相关代码分散在不同选项中\n3. 类型推断：更好的TypeScript支持\n\nsetup函数：\n- 组件创建前执行\n- 返回模板需要的数据和方法\n- 替代beforeCreate和created\n\n常用Composition API：\n1. ref()：创建响应式基本类型\n2. reactive()：创建响应式对象\n3. computed()：计算属性\n4. watch()/watchEffect()：侦听器\n5. onMounted()/onUnmounted()：生命周期钩子\n6. provide()/inject()：依赖注入\n7. toRef()/toRefs()：解构响应式对象",
        },
        # --- 测试平台架构设计 (medium/hard) ---
        {
            "title": "请解释测试平台的整体架构设计",
            "description": "请详细解释：\n1. 测试平台应采用什么架构模式？\n2. 前后端如何分工？\n3. 如何设计可扩展的测试执行引擎？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试平台架构设计",
            "knowledge_point": "架构设计",
            "solution": "架构模式：\n采用前后端分离的分层架构：\n- 前端层：Vue 3 + Element Plus\n- API层：FastAPI RESTful接口\n- 业务层：Service层处理业务逻辑\n- 数据层：SQLAlchemy ORM + 数据库\n\n前后端分工：\n- 前端：UI展示、表单验证、路由管理、状态管理\n- 后端：业务逻辑、数据处理、权限验证、任务调度\n\n可扩展的测试执行引擎：\n1. 插件化设计：定义统一的Runner接口\n2. 消息队列：使用Celery进行异步任务分发\n3. 执行器池：支持多种测试类型（API、UI、性能）\n4. 结果收集：统一的结果格式和存储\n5. 回调机制：测试完成后通知前端更新",
        },
        {
            "title": "请解释测试平台的微服务拆分策略",
            "description": "请详细解释：\n1. 测试平台何时需要拆分为微服务？\n2. 如何进行服务拆分？\n3. 微服务间如何通信？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试平台架构设计",
            "knowledge_point": "微服务拆分",
            "solution": "何时需要微服务：\n- 团队规模增长，单体应用难以维护\n- 不同模块有不同的扩展需求\n- 需要独立部署和发布\n- 性能瓶颈需要独立扩展\n\n服务拆分方式：\n1. 用户服务：认证、授权、用户管理\n2. 项目服务：项目、套件、用例管理\n3. 执行服务：测试调度和执行\n4. 报告服务：结果收集和报告生成\n5. 通知服务：消息推送和告警\n\n微服务间通信：\n1. 同步通信：REST API、gRPC\n2. 异步通信：消息队列（RabbitMQ、Kafka）\n3. 服务发现：Consul、Nacos\n4. API网关：统一入口、路由、限流",
        },
        # --- 任务调度 (medium) ---
        {
            "title": "请解释测试任务调度的设计方案",
            "description": "请详细解释：\n1. 测试任务调度有哪些常见模式？\n2. 如何实现定时执行测试？\n3. 如何处理任务失败和重试？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "任务调度",
            "knowledge_point": "任务调度设计",
            "solution": "常见调度模式：\n1. 定时调度：Cron表达式定义执行时间\n2. 事件触发：代码提交、部署完成时触发\n3. 手动触发：用户手动点击执行\n4. 依赖触发：前置任务完成后触发\n\n定时执行实现：\n1. Celery Beat：Celery的定时任务组件\n2. APScheduler：Python定时任务库\n3. 系统Cron：Linux系统级定时任务\n4. Kubernetes CronJob：容器化环境\n\n任务失败和重试：\n1. 重试策略：指数退避、最大重试次数\n2. 死信队列：多次失败后转入死信队列\n3. 告警通知：失败后发送告警\n4. 状态记录：记录任务状态和错误信息\n5. 手动重试：支持用户手动重新执行",
        },
        # --- 日志系统 (medium/hard) ---
        {
            "title": "请解释测试平台的日志系统设计",
            "description": "请详细解释：\n1. 日志系统应包含哪些组件？\n2. 如何实现日志的收集和分析？\n3. 测试日志与应用日志有何不同？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "日志系统",
            "knowledge_point": "日志系统设计",
            "solution": "日志系统组件：\n1. 日志采集：应用日志、系统日志、测试日志\n2. 日志传输：Fluentd、Logstash、Filebeat\n3. 日志存储：Elasticsearch、ClickHouse\n4. 日志展示：Kibana、Grafana\n5. 日志告警：基于规则的告警\n\n日志收集和分析：\n1. 结构化日志：JSON格式便于解析\n2. 统一日志格式：时间戳、级别、模块、消息、trace_id\n3. 链路追踪：跨服务的日志关联\n4. 实时分析：流式处理日志数据\n5. 日志聚合：按时间、级别、模块聚合\n\n测试日志vs应用日志：\n- 测试日志：关注测试步骤、断言结果、执行时间\n- 应用日志：关注业务逻辑、错误堆栈、性能指标\n- 测试日志需要与测试用例关联\n- 测试日志需要支持附件（截图、视频）",
        },
        {
            "title": "请解释结构化日志的设计和实现",
            "description": "请详细解释：\n1. 什么是结构化日志？\n2. 结构化日志有哪些格式？\n3. 如何在Python中实现结构化日志？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "日志系统",
            "knowledge_point": "结构化日志",
            "solution": "结构化日志：\n以机器可解析的格式记录日志，通常使用JSON格式，便于检索和分析。\n\n常见格式：\n1. JSON：{\"timestamp\": \"...\", \"level\": \"INFO\", \"message\": \"...\"}\n2. Logfmt：key=value格式\n3. CSV：表格格式\n\nPython实现：\n1. 使用python-json-logger：\n   from pythonjsonlogger import jsonlogger\n   handler = logging.StreamHandler()\n   formatter = jsonlogger.JsonFormatter()\n   handler.setFormatter(formatter)\n\n2. 自定义Formatter：\n   class StructuredFormatter(logging.Formatter):\n       def format(self, record):\n           return json.dumps({\n               \"timestamp\": self.formatTime(record),\n               \"level\": record.levelname,\n               \"message\": record.getMessage(),\n               \"module\": record.module\n           })\n\n3. 使用structlog库：功能更强大的结构化日志库",
        },
        # --- 权限管理 (medium/hard) ---
        {
            "title": "请解释RBAC权限模型的设计",
            "description": "请详细解释：\n1. RBAC模型的核心概念有哪些？\n2. 如何设计测试平台的权限体系？\n3. 如何实现数据权限控制？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "权限管理",
            "knowledge_point": "RBAC设计",
            "solution": "RBAC核心概念：\n1. 用户(User)：系统的使用者\n2. 角色(Role)：权限的集合\n3. 权限(Permission)：对资源的操作许可\n4. 资源(Resource)：被保护的对象\n\n关系：用户->角色->权限->资源\n\n测试平台权限体系：\n角色设计：\n- 超级管理员：全部权限\n- 项目管理员：项目内全部权限\n- 测试工程师：执行测试、查看结果\n- 访客：只读权限\n\n权限粒度：\n- 功能权限：能否访问某功能\n- 数据权限：能否查看某项目的数据\n- 操作权限：能否执行某操作\n\n数据权限实现：\n1. 在查询时自动添加数据范围过滤\n2. 使用中间件注入数据权限条件\n3. 基于项目ID进行数据隔离",
        },
        {
            "title": "请解释JWT认证的实现原理和安全考虑",
            "description": "请详细解释：\n1. JWT的三个部分分别包含什么？\n2. JWT的签发和验证流程？\n3. 使用JWT有哪些安全注意事项？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "权限管理",
            "knowledge_point": "JWT安全",
            "solution": "JWT三个部分：\n1. Header：{\"alg\": \"HS256\", \"typ\": \"JWT\"}\n2. Payload：{\"user_id\": 1, \"exp\": 1234567890, \"iat\": 1234567800}\n3. Signature：HMACSHA256(base64(header) + \".\" + base64(payload), secret)\n\n签发流程：\n1. 用户登录成功\n2. 构建Payload（用户信息+过期时间）\n3. 使用密钥签名\n4. 返回token给客户端\n\n验证流程：\n1. 从请求头获取token\n2. 验证签名是否正确\n3. 检查是否过期\n4. 提取用户信息\n\n安全注意事项：\n1. 使用HTTPS传输\n2. 设置合理的过期时间\n3. 密钥足够复杂且安全存储\n4. 不在Payload中存储敏感信息\n5. 实现token刷新机制\n6. 支持token黑名单（登出）\n7. 防止重放攻击",
        },
        {
            "title": "请解释测试平台中的接口鉴权中间件设计",
            "description": "请详细解释：\n1. 为什么需要鉴权中间件？\n2. 中间件的处理流程是什么？\n3. 如何处理跨域和预检请求？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "权限管理",
            "knowledge_point": "鉴权中间件",
            "solution": "为什么需要鉴权中间件：\n1. 统一处理认证逻辑，避免每个接口重复代码\n2. 集中管理权限策略\n3. 便于维护和修改\n4. 关注点分离\n\n处理流程：\n1. 拦截请求\n2. 检查是否需要认证（白名单路由跳过）\n3. 从请求头提取token\n4. 验证token有效性\n5. 查询用户信息和权限\n6. 检查是否有接口访问权限\n7. 将用户信息注入请求上下文\n8. 转发到目标接口\n\n跨域和预检请求处理：\n1. OPTIONS预检请求直接放行\n2. 设置CORS响应头：\n   - Access-Control-Allow-Origin\n   - Access-Control-Allow-Methods\n   - Access-Control-Allow-Headers\n   - Access-Control-Allow-Credentials\n3. FastAPI使用CORSMiddleware中间件",
        },
        # --- 综合题 (medium/hard) ---
        {
            "title": "请解释测试平台中如何实现测试用例管理",
            "description": "请详细解释：\n1. 测试用例的数据模型如何设计？\n2. 用例的增删改查接口如何设计？\n3. 如何支持用例的导入导出？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试平台架构设计",
            "knowledge_point": "用例管理",
            "solution": "数据模型设计：\nTestCase表：\n- id：主键\n- project_id：所属项目\n- suite_id：所属套件（可选）\n- name：用例名称\n- description：用例描述\n- preconditions：前置条件\n- steps：测试步骤（JSON格式）\n- expected_result：预期结果\n- priority：优先级（P0-P3）\n- status：状态（draft/ready/deprecated）\n- tags：标签\n- creator_id：创建者\n- created_at/updated_at：时间戳\n\n接口设计：\n- POST /api/cases：创建用例\n- GET /api/cases：查询用例列表（支持筛选、分页）\n- GET /api/cases/{id}：获取用例详情\n- PUT /api/cases/{id}：更新用例\n- DELETE /api/cases/{id}：删除用例\n- POST /api/cases/batch：批量操作\n\n导入导出：\n1. 导出：支持Excel、CSV、JSON格式\n2. 导入：解析文件、数据校验、批量插入\n3. 模板下载：提供标准导入模板",
        },
        {
            "title": "请解释测试平台中如何实现测试执行引擎",
            "description": "请详细解释：\n1. 测试执行引擎的核心组件有哪些？\n2. 如何支持多种测试类型（API、UI、性能）？\n3. 如何收集和存储测试结果？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试平台架构设计",
            "knowledge_point": "执行引擎",
            "solution": "核心组件：\n1. 任务调度器：接收执行请求，分配到执行队列\n2. 执行队列：Celery/RabbitMQ消息队列\n3. 执行器Worker：实际执行测试的进程\n4. 结果收集器：收集和存储测试结果\n5. 报告生成器：生成可视化报告\n\n支持多种测试类型：\n1. 插件化架构：定义统一的Runner接口\n2. API测试Runner：基于requests/httpx\n3. UI测试Runner：基于Selenium/Playwright\n4. 性能测试Runner：基于Locust/JMeter\n5. 配置化工厂：根据类型创建对应Runner\n\n结果收集和存储：\n1. 实时推送：WebSocket推送执行状态\n2. 结果存储：\n   - 测试结果表：status、duration、error_message\n   - 步骤结果表：每个步骤的详细结果\n   - 附件表：截图、日志文件\n3. 结果分析：\n   - 通过率统计\n   - 失败趋势分析\n   - 耗时分析",
        },
        # --- 补充简答题 ---
        {
            "title": "请解释前后端分离架构的优缺点",
            "description": "请详细解释：\n1. 前后端分离架构的核心思想是什么？\n2. 与传统MVC架构相比有哪些优势？\n3. 存在哪些挑战和解决方案？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "测试平台架构设计",
            "knowledge_point": "前后端分离",
            "solution": "核心思想：\n前端负责UI展示和交互逻辑，后端负责数据处理和业务逻辑，通过API接口通信。\n\n相比MVC的优势：\n1. 开发效率：前后端并行开发，互不阻塞\n2. 技术选型灵活：前端可用Vue/React，后端可用任意语言\n3. 部署独立：前端可部署到CDN，后端独立扩展\n4. 多端复用：同一API支持Web、App、小程序\n\n挑战和解决方案：\n1. 接口联调：使用Swagger/OpenAPI文档自动化\n2. 跨域问题：后端配置CORS\n3. SEO问题：使用SSR（服务端渲染）\n4. 首屏性能：代码分割、懒加载、CDN加速\n5. 认证状态：使用JWT无状态认证",
        },
        {
            "title": "请解释测试平台中的环境管理方案",
            "description": "请详细解释：\n1. 测试环境管理面临哪些问题？\n2. 如何设计环境配置的数据模型？\n3. 如何实现环境变量的动态切换？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "easy",
            "category": "数据库设计",
            "knowledge_point": "环境管理",
            "solution": "环境管理面临的问题：\n1. 多套环境（开发/测试/预发/生产）配置不同\n2. 数据库连接、API地址等配置需动态切换\n3. 不同环境的测试数据不同\n4. 环境配置容易泄露\n\n数据模型设计：\nEnvironment表：id, name, description, base_url, db_url\nEnvironmentVariable表：id, env_id, key, value, is_secret\n\n动态切换方案：\n1. 配置中心：使用Nacos/Apollo集中管理配置\n2. 环境变量：通过.env文件或环境变量注入\n3. 前端选择：用户在页面选择环境，API请求携带环境标识\n4. 后端拦截：中间件根据环境标识加载对应配置\n5. 敏感信息加密：密码等敏感配置加密存储",
        },
        {
            "title": "请解释如何实现测试平台的WebSocket实时通知",
            "description": "请详细解释：\n1. 为什么测试平台需要WebSocket？\n2. FastAPI中如何实现WebSocket？\n3. 如何实现向指定用户推送消息？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "FastAPI框架",
            "knowledge_point": "WebSocket通知",
            "solution": "为什么需要WebSocket：\n1. 测试执行进度实时更新\n2. 测试完成即时通知\n3. 多人协作时的状态同步\n4. 减少前端轮询的资源消耗\n\nFastAPI实现WebSocket：\nfrom fastapi import FastAPI, WebSocket\n\n@app.websocket(\"/ws\")\nasync def websocket_endpoint(websocket: WebSocket):\n    await websocket.accept()\n    while True:\n        data = await websocket.receive_text()\n        await websocket.send_text(f\"Echo: {data}\")\n\n向指定用户推送：\n1. 连接管理：维护 user_id -> WebSocket连接 的映射\n2. 认证：连接时通过token验证用户身份\n3. 消息路由：根据user_id查找对应连接发送消息\n4. 广播：遍历所有连接发送消息\n5. 心跳检测：定期检查连接是否存活",
        },
        {
            "title": "请解释如何设计测试平台的缓存策略",
            "description": "请详细解释：\n1. 测试平台中哪些数据适合缓存？\n2. 常见的缓存策略有哪些？\n3. 如何处理缓存一致性问题？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "medium",
            "category": "测试平台架构设计",
            "knowledge_point": "缓存策略",
            "solution": "适合缓存的数据：\n1. 用户信息和权限数据\n2. 项目配置和环境变量\n3. 测试用例列表（高频查询）\n4. 统计报表数据\n5. 字典数据和下拉选项\n\n常见缓存策略：\n1. Cache-Aside：先查缓存，未命中查数据库并更新缓存\n2. Write-Through：写入时同时更新缓存和数据库\n3. Write-Behind：先写缓存，异步写数据库\n4. TTL过期：设置缓存过期时间\n\n缓存一致性方案：\n1. 更新数据库时删除缓存（Cache-Aside）\n2. 延迟双删：删除缓存->更新数据库->延迟再删缓存\n3. 消息队列：数据库变更时发送消息更新缓存\n4. 版本号：缓存数据携带版本号，更新时检查版本",
        },
        {
            "title": "请解释如何实现测试平台的CI/CD集成",
            "description": "请详细解释：\n1. 测试平台与CI/CD集成的意义是什么？\n2. 如何设计触发测试执行的接口？\n3. 如何将测试结果反馈到CI/CD流水线？",
            "instructions": "请详细回答以下问题",
            "exercise_type": "text",
            "difficulty": "hard",
            "category": "测试平台架构设计",
            "knowledge_point": "CI/CD集成",
            "solution": "集成意义：\n1. 代码提交自动触发测试，尽早发现问题\n2. 测试结果作为发布门禁\n3. 自动化回归测试保障质量\n4. 减少人工干预，提高效率\n\n触发接口设计：\n1. Webhook接口：POST /api/webhook/trigger\n   - 接收CI系统的回调请求\n   - 验证请求签名\n   - 创建测试执行任务\n2. API触发：POST /api/executions\n   - 接收测试计划ID和参数\n   - 支持指定环境和分支\n3. 定时触发：与CI系统配合定时执行\n\n结果反馈方案：\n1. 回调CI系统：测试完成后POST结果到CI回调URL\n2. 状态码：通过/失败返回不同状态码\n3. 测试报告：生成JUnit XML格式报告供CI解析\n4. 质量门禁：设置通过率阈值，低于阈值则流水线失败\n5. 通知集成：Slack/钉钉/邮件通知测试结果",
        },
    ],
}
