<template>
  <div class="traffic-workbench page-shell">
    <section class="page-header">
      <div><h2>流量工作台</h2><p>检查已脱敏流量、定位异常、在目标环境中确认回放结果，再沉淀为接口用例。</p></div>
      <div class="header-actions"><el-button :icon="Refresh" :loading="loading" @click="loadSessions">刷新会话</el-button><el-upload :show-file-list="false" accept=".har,application/json" :http-request="importHar"><el-button :icon="Upload">导入 HAR</el-button></el-upload><el-button type="primary" :icon="Connection" @click="openImport">导入流量</el-button></div>
    </section>
    <el-alert title="当前版本采集 TestMaster 录制浏览器中的 XHR、Fetch 与页面加载失败。移动 App、小程序或其他浏览器请从合规代理工具导出 HAR 后导入；证书固定应用需由应用提供测试开关，工具不会绕过其安全保护。" type="info" :closable="false" show-icon />

    <section class="work-grid">
      <aside class="content-band sessions"><div class="section-title"><h3>抓包会话</h3><span>{{ sessions.length }} 个</span></div><el-empty v-if="!sessions.length && !loading" description="暂无抓包会话" /><el-menu v-else :default-active="selectedId" @select="selectSession"><el-menu-item v-for="item in sessions" :key="item.id" :index="item.id"><div class="session-row"><strong>{{ item.source_url || '未命名抓包' }}</strong><span>{{ sourceLabel(item.origin) }} · {{ statusLabel(item.status) }}</span><small>{{ formatTime(item.started_at) }}</small></div></el-menu-item></el-menu></aside>

      <main class="content-band detail" v-loading="loadingDetail">
        <template v-if="session">
          <div class="detail-head"><div><h3>{{ session.source_url || '未命名抓包' }}</h3><p>{{ session.total }} 条已脱敏流量 · {{ sourceLabel(session.origin) }}</p></div><div class="header-actions"><el-button :icon="Download" @click="exportHar">导出 HAR</el-button><el-button type="primary" :disabled="!convertibleCount" @click="openImport">转接口 / 场景</el-button></div></div>
          <div class="metrics"><div><strong>{{ analysis.total || 0 }}</strong><span>请求</span></div><div><strong>{{ analysis.failed_exchanges?.length || 0 }}</strong><span>失败</span></div><div><strong>{{ analysis.duplicate_count || 0 }}</strong><span>相同指纹</span></div><div><strong>{{ analysis.p95_timing_ms ?? '-' }}<small v-if="analysis.p95_timing_ms != null"> ms</small></strong><span>P95 耗时</span></div></div>
          <el-alert v-for="tip in analysis.suggestions || []" :key="tip.title" :title="tip.title" :description="tip.detail" :type="tip.type === 'failure' ? 'warning' : 'info'" :closable="false" show-icon class="suggestion" />
          <div class="filter-row"><el-input v-model="filters.keyword" clearable placeholder="URL、方法或接口名称" /><el-select v-model="filters.method" clearable placeholder="方法"><el-option v-for="value in methods" :key="value" :label="value" :value="value" /></el-select><el-select v-model="filters.type" clearable placeholder="类型"><el-option v-for="value in resourceTypes" :key="value" :label="typeLabel(value)" :value="value" /></el-select><el-select v-model="filters.status" clearable placeholder="状态"><el-option label="4xx / 5xx / 网络失败" value="failed" /><el-option label="2xx / 3xx" value="passed" /></el-select><el-input-number v-model="filters.minDuration" :min="0" :max="600000" controls-position="right" placeholder="最小耗时 ms" /><el-switch v-model="filters.convertibleOnly" active-text="仅可转接口" /></div>
          <el-table :data="pagedExchanges" max-height="390" highlight-current-row row-key="id" empty-text="没有匹配的流量" @current-change="selectExchange"><el-table-column prop="sequence" label="#" width="58" /><el-table-column prop="method" label="方法" width="82"><template #default="{ row }"><el-tag size="small" effect="plain">{{ row.method }}</el-tag></template></el-table-column><el-table-column label="类型" width="88"><template #default="{ row }"><el-tag size="small" :type="row.convertible ? 'success' : 'info'">{{ typeLabel(row.resource_type) }}</el-tag></template></el-table-column><el-table-column prop="name" label="接口" min-width="160" /><el-table-column prop="url" label="URL" min-width="280" show-overflow-tooltip /><el-table-column label="状态" width="88"><template #default="{ row }"><el-tag :type="statusType(row)" size="small">{{ statusText(row) }}</el-tag></template></el-table-column><el-table-column prop="timing_ms" label="耗时" width="95"><template #default="{ row }">{{ row.timing_ms == null ? '-' : `${row.timing_ms} ms` }}</template></el-table-column></el-table>
          <div class="pager"><span>匹配 {{ filteredExchanges.length }} 条</span><el-pagination v-model:current-page="page" :page-size="pageSize" layout="prev, pager, next" :total="filteredExchanges.length" small /></div>

          <section v-if="exchange" class="inspector" v-loading="loadingExchange"><div class="inspector-head"><div><h3>流量详情 #{{ exchange.sequence }}</h3><span>{{ exchange.method }} {{ exchange.url }}</span></div><div class="header-actions"><el-tag v-if="!exchange.convertible" type="info">仅供诊断，不可回放</el-tag><el-button v-else type="primary" :icon="VideoPlay" @click="openReplay">回放并对比</el-button></div></div><el-tabs v-model="detailTab"><el-tab-pane label="请求" name="request"><el-descriptions :column="2" border size="small"><el-descriptions-item label="方法">{{ exchange.method }}</el-descriptions-item><el-descriptions-item label="请求体">{{ exchange.request?.body_type || 'none' }}</el-descriptions-item><el-descriptions-item label="参数"><pre>{{ pretty(exchange.request?.params) }}</pre></el-descriptions-item><el-descriptions-item label="请求头"><pre>{{ pretty(exchange.request?.headers) }}</pre></el-descriptions-item></el-descriptions><pre class="payload">{{ pretty(exchange.request?.body) }}</pre></el-tab-pane><el-tab-pane label="响应" name="response"><el-descriptions :column="2" border size="small"><el-descriptions-item label="状态">{{ exchange.response?.status || '网络失败' }}</el-descriptions-item><el-descriptions-item label="耗时">{{ exchange.timing_ms == null ? '-' : `${exchange.timing_ms} ms` }}</el-descriptions-item><el-descriptions-item label="响应头" :span="2"><pre>{{ pretty(exchange.response?.headers) }}</pre></el-descriptions-item></el-descriptions><pre class="payload">{{ pretty(exchange.response?.body) }}</pre><el-alert v-if="exchange.failure_reason" type="error" :title="exchange.failure_reason" :closable="false" /></el-tab-pane></el-tabs></section>
        </template>
        <el-empty v-else description="选择左侧抓包会话查看流量详情" />
      </main>
    </section>

    <el-dialog v-model="replayVisible" title="回放已捕获请求" width="680px" destroy-on-close><el-alert title="回放会向目标地址发送真实请求，可能产生下单、写入或删除等副作用。请只在可控测试环境执行。" type="warning" :closable="false" show-icon /><el-form label-position="top" class="replay-form"><el-form-item label="目标环境"><el-select v-model="replayEnvironmentId" clearable placeholder="不选择时只使用请求中已有的脱敏模板"><el-option v-for="env in environments" :key="env.id" :label="env.name || env.env_name" :value="env.id" /></el-select></el-form-item><el-form-item label="覆盖 URL（可选）"><el-input v-model="replayUrl" placeholder="保留为空则使用录制地址" /></el-form-item><el-form-item label="临时变量（JSON，可选）"><el-input v-model="replayVariables" type="textarea" :rows="4" placeholder='例如 {"ORDER_ID":"10001"}' /></el-form-item></el-form><template #footer><el-button @click="replayVisible = false">取消</el-button><el-button type="danger" :loading="replaying" @click="runReplay">确认发送并对比</el-button></template></el-dialog>
    <el-dialog v-model="replayResultVisible" title="回放对比结果" width="760px"><template v-if="replayResult"><el-descriptions :column="3" border><el-descriptions-item label="回放状态">{{ replayResult.replay.status ?? '失败' }}</el-descriptions-item><el-descriptions-item label="状态码一致"><el-tag :type="replayResult.comparison.status_matches ? 'success' : 'danger'">{{ replayResult.comparison.status_matches ? '一致' : '不一致' }}</el-tag></el-descriptions-item><el-descriptions-item label="耗时变化">{{ replayResult.comparison.timing_delta_ms == null ? '-' : `${replayResult.comparison.timing_delta_ms} ms` }}</el-descriptions-item></el-descriptions><el-alert v-if="replayResult.replay.error" :title="replayResult.replay.error" type="error" :closable="false" class="result-gap" /><h4>响应差异（{{ replayResult.comparison.body_differences?.length || 0 }}）</h4><el-table :data="replayResult.comparison.body_differences || []" max-height="240" empty-text="未发现可比较的响应差异"><el-table-column prop="path" label="位置" min-width="220" /><el-table-column prop="kind" label="类型" width="100" /><el-table-column prop="expected" label="录制值" min-width="160" /><el-table-column prop="actual" label="回放值" min-width="160" /></el-table><h4>回放响应</h4><pre class="payload">{{ pretty(replayResult.replay.body) }}</pre></template></el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { Connection, Download, Refresh, Upload, VideoPlay } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import autoTestRequest from '@/utils/autoTestRequest'

const router = useRouter()
const sessions = ref([]); const session = ref(null); const analysis = ref({}); const selectedId = ref(''); const loading = ref(false); const loadingDetail = ref(false); const loadingExchange = ref(false)
const exchange = ref(null); const detailTab = ref('request'); const page = ref(1); const pageSize = 100
const filters = ref({ keyword: '', method: '', type: '', status: '', minDuration: undefined, convertibleOnly: false })
const environments = ref([]); const replayVisible = ref(false); const replaying = ref(false); const replayEnvironmentId = ref(null); const replayUrl = ref(''); const replayVariables = ref(''); const replayResult = ref(null); const replayResultVisible = ref(false)
const methods = computed(() => [...new Set((session.value?.candidates || []).map(item => item.method))].sort())
const resourceTypes = computed(() => [...new Set((session.value?.candidates || []).map(item => item.resource_type).filter(Boolean))].sort())
const convertibleCount = computed(() => (session.value?.candidates || []).filter(item => item.convertible).length)
const filteredExchanges = computed(() => (session.value?.candidates || []).filter(row => { const text = `${row.method} ${row.name} ${row.url}`.toLowerCase(); const status = Number(row.response_status || 0); return (!filters.value.keyword || text.includes(filters.value.keyword.toLowerCase())) && (!filters.value.method || row.method === filters.value.method) && (!filters.value.type || row.resource_type === filters.value.type) && (!filters.value.status || (filters.value.status === 'failed' ? status >= 400 || !status || row.failure_reason : status >= 200 && status < 400)) && (!filters.value.minDuration || Number(row.timing_ms || 0) >= filters.value.minDuration) && (!filters.value.convertibleOnly || row.convertible) }))
const pagedExchanges = computed(() => filteredExchanges.value.slice((page.value - 1) * pageSize, page.value * pageSize))
watch(filters, () => { page.value = 1 }, { deep: true })
watch(filteredExchanges, rows => { if ((page.value - 1) * pageSize >= rows.length) page.value = 1 })
const sourceLabel = value => ({ desktop_browser: '桌面浏览器录制', har_import: 'HAR 导入' })[value] || value
const statusLabel = value => ({ capturing: '采集中', paused: '已暂停', completed: '已完成', cancelled: '已取消' })[value] || value
const typeLabel = value => ({ xhr: 'XHR', fetch: 'Fetch', document: '页面' })[value] || value || '未知'
const statusType = row => row.failure_reason || !Number(row.response_status) || Number(row.response_status) >= 400 ? 'danger' : 'success'
const statusText = row => row.failure_reason || !Number(row.response_status) ? '失败' : row.response_status
const formatTime = value => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '-'
const pretty = value => value == null ? '无内容' : typeof value === 'string' ? value : JSON.stringify(value, null, 2)
async function loadSessions () { loading.value = true; try { const res = await autoTestRequest.get('/auto-test/import/captures?limit=100'); sessions.value = res.captures || []; const next = selectedId.value || sessions.value[0]?.id; if (next) await selectSession(next) } catch (error) { ElMessage.error(error.response?.data?.detail || '加载抓包会话失败') } finally { loading.value = false } }
async function selectSession (id) { selectedId.value = id; exchange.value = null; loadingDetail.value = true; try { const [detail, report] = await Promise.all([autoTestRequest.get(`/auto-test/import/captures/${id}`), autoTestRequest.get(`/auto-test/import/captures/${id}/analysis`)]); session.value = detail; analysis.value = report; page.value = 1 } catch (error) { ElMessage.error(error.response?.data?.detail || '加载流量详情失败') } finally { loadingDetail.value = false } }
async function selectExchange (row) { if (!row || !selectedId.value) return; loadingExchange.value = true; try { exchange.value = await autoTestRequest.get(`/auto-test/import/captures/${selectedId.value}/exchanges/${row.id}`); detailTab.value = 'request' } catch (error) { ElMessage.error(error.response?.data?.detail || '加载请求详情失败') } finally { loadingExchange.value = false } }
function openImport () { router.push({ path: '/import-center', query: selectedId.value ? { captureId: selectedId.value } : {} }) }
async function exportHar () { try { const blob = await autoTestRequest.get(`/auto-test/import/captures/${selectedId.value}/export`, { responseType: 'blob' }); const href = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = href; link.download = `capture-${selectedId.value}.har`; link.click(); window.setTimeout(() => URL.revokeObjectURL(href), 1000); ElMessage.success('已导出脱敏 HAR') } catch (error) { ElMessage.error(error.response?.data?.detail || '导出 HAR 失败') } }
async function importHar (options) { const form = new FormData(); form.append('file', options.file); try { const created = await autoTestRequest.post('/auto-test/import/captures/har', form); await loadSessions(); await selectSession(created.id); ElMessage.success(`HAR 已导入工作台，共 ${created.imported_exchanges} 条流量`); return created } catch (error) { ElMessage.error(error.response?.data?.detail || 'HAR 导入失败'); throw error } }
async function openReplay () { try { const data = await autoTestRequest.get('/auto-test/environments'); environments.value = Array.isArray(data) ? data : []; replayEnvironmentId.value = environments.value.find(item => item.is_default)?.id || null; replayUrl.value = ''; replayVariables.value = ''; replayVisible.value = true } catch (error) { ElMessage.error(error.response?.data?.detail || '加载环境失败') } }
async function runReplay () { let variables = {}; try { variables = replayVariables.value.trim() ? JSON.parse(replayVariables.value) : {}; if (!variables || Array.isArray(variables) || typeof variables !== 'object') throw new Error('变量必须是 JSON 对象') } catch (error) { ElMessage.error(error.message || '临时变量格式不正确'); return } replaying.value = true; try { replayResult.value = await autoTestRequest.post(`/auto-test/import/captures/${selectedId.value}/exchanges/${exchange.value.id}/replay`, { confirm_replay: true, environment_id: replayEnvironmentId.value, variables, overrides: replayUrl.value.trim() ? { url: replayUrl.value.trim() } : {} }); replayVisible.value = false; replayResultVisible.value = true } catch (error) { ElMessage.error(error.response?.data?.detail || '回放失败') } finally { replaying.value = false } }
onMounted(loadSessions)
</script>

<style scoped>
.page-shell{display:grid;gap:16px}.page-header,.content-band{background:var(--tm-surface,#fff);border:1px solid var(--tm-border,#e5e7eb);padding:20px}.page-header,.detail-head,.section-title,.header-actions,.filter-row,.inspector-head,.pager{display:flex;justify-content:space-between;align-items:center;gap:12px}.page-header h2,.detail-head h3,.section-title h3,.inspector-head h3{margin:0;color:var(--tm-text,#1f2937)}.page-header p,.detail-head p,.section-title span,.inspector-head span{margin:6px 0 0;color:var(--tm-text-secondary,#667085);font-size:13px}.work-grid{display:grid;grid-template-columns:minmax(240px,.25fr) minmax(0,.75fr);gap:16px}.sessions{padding:12px;min-width:0}.session-row{display:grid;min-width:0;gap:3px}.session-row strong,.session-row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.session-row span,.session-row small{color:var(--tm-text-secondary,#667085);font-size:12px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.metrics>div{border:1px solid var(--tm-border,#e5e7eb);padding:14px;display:grid;gap:4px}.metrics strong{font-size:22px;color:var(--tm-text,#1f2937)}.metrics span{font-size:12px;color:var(--tm-text-secondary,#667085)}.suggestion{margin:8px 0}.filter-row{align-items:flex-end;flex-wrap:wrap;margin:16px 0}.filter-row .el-input{width:260px}.filter-row .el-select{width:135px}.filter-row .el-input-number{width:150px}.pager{margin-top:10px;color:var(--tm-text-secondary,#667085);font-size:13px}.inspector{margin-top:16px;border-top:1px solid var(--tm-border,#e5e7eb);padding-top:16px}.inspector-head{align-items:flex-start}.inspector-head span{display:block;max-width:560px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.payload,pre{margin:10px 0 0;max-height:220px;overflow:auto;background:var(--tm-code-bg,#f6f8fa);color:var(--tm-text,#1f2937);padding:10px;white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.55 Consolas,Monaco,monospace}.replay-form{margin-top:16px}.result-gap{margin-top:12px}@media(max-width:1050px){.work-grid{grid-template-columns:1fr}.page-header,.detail-head{align-items:flex-start;flex-direction:column}.filter-row{align-items:stretch}.filter-row .el-input,.filter-row .el-select,.filter-row .el-input-number{width:100%}.metrics{grid-template-columns:repeat(2,1fr)}}
</style>
